### ISSUE TITLE
fontFamily customization & html tag

### ISSUE THREAD

**Issue by TigersWay** [tailwindcss/tailwindcss#1000]
Hi,
I was trying different customization (v1.0.4):
```
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: colors.purple,
        secondary: colors.pink,
      },
      fontFamily: {
        sans: ['Muli'].concat(fontFamily.sans)
      }
    }
  },
  variants: {},
  plugins: []
}
```
font-sans is changed, but html is still with the default.
Not sure it's a bug, the wrong way to do it or the expected/intended outcome.
Thanks

**Comment by AlexVipond** [comment]
@TigersWay That's the expected outcome. Tailwind's base styles are designed to reset `font-family` to a safe stack of sans fonts, but those fonts are hard-coded and are not pulled from your config file.

To use your new sans font as the default, just add the `font-sans` class to an element at the top of the tree, e.g. `body`.

Or, you can override `html` styles using your `tailwind.css` entry file:

```
// tailwind.css
@tailwind base;

html {
  @apply font-sans;
}

@tailwind components;

@tailwind utilities;
```

**Comment by TigersWay** [comment]
I had doubt... But that's perfectly logical :-)
Thanks
