### ISSUE TITLE
`@apply` cannot be used with `.text-md`

### ISSUE THREAD

**Issue by hakhsin** [tailwindcss/tailwindcss#1006]
Hi, I got an error when I try `@apply .text-md`. 
```
`@apply` cannot be used with `.text-md` because `.text-md` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc.
```
How can I fix it?

![Untitled](https://user-images.githubusercontent.com/39958174/60730504-8fcd9a00-9f5a-11e9-9bc9-bf46709ebd30.png)
![Untitled](https://user-images.githubusercontent.com/39958174/60730809-3e71da80-9f5b-11e9-8f5e-a5c91f793827.png)

[https://stackoverflow.com/questions/56900926/apply-cannot-be-used-with-text-md](url)

**Comment by devcircus** [comment]
Did you add text-md? That's not a valid option. See https://tailwindcss.com/docs/font-size/#app

**Comment by adamwathan** [comment]
Yeah there is no text-md class by default.

**Comment by hakhsin** [comment]
@devcircus and @adamwathan  thank you for your response. I am new in tailwindcss. I didn't knew it very well or know it now very well. Anyway I اhad see a code that used that utility. but he defined it herself.
