### ISSUE TITLE
Importing tailwind directives after Vue components causes normalize css to be applied after components.

### ISSUE THREAD

**Issue by BinarySpike** [tailwindcss/tailwindcss#1019]
As I'm fairly new to npm/webpack/postcss/etc., I'm not sure if this is something that can be fixed or just needs to be clearly documented:

Importing a Vue Single File Component (.vue) before your tailwindcss directives causes normalize to be placed after your vue component styling.  Thus, the css reset takes precedence on simple selectors like `h1` etc.

```
import Vue from 'vue'
import App from './App.vue'

import './tailwind.css' // causes issues because it's placed after App.vue

new Vue({
    el: '#app',
    render: h => h(App),
})
```

The proper way to do it is:
```
import './tailwind.css' // works as expected

import Vue from 'vue'
import App from './App.vue'

new Vue({
    el: '#app',
    render: h => h(App),
})
```

Scoped styles work because the selectors become more specific, making them take precedence.

**Comment by adamwathan** [comment]
Yeah this is a Vue "issue" really more than a Tailwind thing. Vue (and React, and others) sort of make it difficult to have fine-grained control over the order in which your CSS is loaded.

Thanks for sharing your solution so others can benefit from it if they run into the same problem 👍
