### ISSUE TITLE
[Docs] Having a way to choose the version of the docs like you can with Laravel

### ISSUE THREAD

**Issue by MichaelDeBoey** [tailwindcss/tailwindcss#103]
Hi @adamwathan, @reinink & @davidhemphill!

Really enjoying Tailwind already and hoping to help you guys as much as I can. 🙂

My suggestion is that we can choose the version of the docs, like you can on the Laravel docs site (with a `<select>`).
Let it redirect automatically to the latest version, but also have a `master` option, where we can see the latest changes.
<img width="103" src="https://user-images.githubusercontent.com/6643991/32416622-77581f78-c24c-11e7-92bd-af6157e9b267.png">

This would make things easier when referring to the docs in issues for example. 🙂
Right now we always see `master`, which can be confusing sometimes.
Definitely when the first major release will come and Tailwind will be used in multiple versions I think.

Keep up the good work guys! 🙂

**Comment by adamwathan** [comment]
We'll definitely tackle this eventually, but probably not until there's a meaningful difference between versions (ie. 0.x vs 1.0) and things have stabilized a little bit more.

Going to close this as it's definitely planned 👍

**Comment by MichaelDeBoey** [comment]
No problem 🙂

Happy to hear it's on the (probably long) list 🙂
