### ISSUE TITLE
word-spacing

### ISSUE THREAD

**Issue by sandro-git** [tailwindcss/tailwindcss#1030]
hello, have you plan to add word-spacing ?

**Comment by adamwathan** [comment]
No concrete plans to add this at the moment but we have a lot of documentation around adding your own utilities:

https://tailwindcss.com/docs/adding-new-utilities

**Comment by nestarz** [comment]
Hello @adamwathan , any reason why not adding this utility ? It seems useful, as useful as letter spacing for example.
