### ISSUE TITLE
[Feature proposal] Tailwind Modals - trigger a modal without a button

### ISSUE THREAD

**Issue by breeze88** [tailwindcss/tailwindcss#1037]
Implementing something similiar to https://getbootstrap.com/docs/4.0/components/modal/#modalshow  .

Other libraries solved it this way: https://stackoverflow.com/questions/27011026/nifty-modal-how-to-trigger-a-modal-without-a-button

**Comment by AlexVipond** [comment]
@breeze88 Tailwind is a postcss plugin that generates CSS classes—without HTML and without JS. Dynamic modals require HTML and JS to work, so they are outside Tailwind's current scope
