### ISSUE TITLE
[Feature Request] Max Content

### ISSUE THREAD

**Issue by mitchbne** [tailwindcss/tailwindcss#1042]
👋 Hey, I'd be very keen to add six new classes to Tailwind:

```width: max-content;```, which would be written in Tailwind as ```w-content```
```min-width: max-content;```, which would be written in Tailwind as ```min-w-content```
```max-width: max-content;```, which would be written in Tailwind as ```max-w-content```
```height: max-content;```, which would be written in Tailwind as ```h-content```
```min-height: max-content;```, which would be written in Tailwind as ```min-h-content```
```max-height: max-content;```, which would be written in Tailwind as ```max-h-content```

Very keen to get my hands a bit dirty and add this myself, but curious on people's thoughts as to whether or not the general consensus is for or against these additions.

**Comment by brasilikum** [comment]
Hey, if I am not totally lost you can just add this to your configuration, as max-width is already there.

```js
// tailwind.config.js
module.exports = {
  theme: {
    maxWidth: {
      ...,
      "content": "max-content"
    }
  }
}
```

**Comment by mitchbne** [comment]
Yeah, that's fair enough. I've already done something very similar for personal projects, just thought it might be a nice addition to Tailwind is all.

**Comment by imannms** [comment]
yeah, I need this functionality.
this feature should be added out of the box into vanilla tailwind css.

**Comment by mitchbne** [comment]
> yeah, I need this functionality.
> this feature should be added out of the box into vanilla tailwind css.

Thanks, @imannms. If this gets more traction I'll look into doing this

**Comment by adamwathan** [comment]
We don't include this by default because it has no Edge or IE support, but you can add it to your config file if you need it 👍🏻

Closing for now, can revisit in the future if there's a lot of demand for it as a default.

**Comment by rightaway** [comment]
@adamwathan Can we reopen this? It's a useful and standard part of CSS with full support in all browsers except only IE https://developer.mozilla.org/en-US/docs/Web/CSS/width#Browser_compatibility

**Comment by adamwathan** [comment]
Yep I actually have it on my to-do list to add max-content and min-content soon 👍

**Comment by Zac-Zajdel** [comment]
Anyone progress been made on this? Ran into this not being included out of the box as well unless I missed it. Implemented it within the config file but still would be nice not having to do as such.

**Comment by deadcoder0904** [comment]
Not sure when it was added but it's supported now. See https://tailwindcss.com/docs/max-width 💯 

```css
.max-w-min → max-width: min-content;
.max-w-max → max-width: max-content;
```

**Comment by kudak3** [comment]
may the feature also be extended to the height

**Comment by AgainPsychoX** [comment]
Seems its supported widely now:  https://caniuse.com/?search=max-content

Can we get it finally in Tailwind without user configuration?

**Comment by RobinMalfait** [comment]
@AgainPsychoX we have this natively in Tailwind since October of 2021. Checkout the relevant do apges:

- https://tailwindcss.com/docs/min-width
- https://tailwindcss.com/docs/max-width

**Comment by annxiesun** [comment]
Bumping again still no `width: max-content` ;-;

**Comment by 4nche** [comment]
@annxiesun https://tailwindcss.com/docs/width

"w-max"

**Comment by pezy4303676** [comment]
careb.vercel.app
