### ISSUE TITLE
Can't customize max-width

### ISSUE THREAD

**Issue by creativiii** [tailwindcss/tailwindcss#1045]
I'm not entirely sure if this is a bug, although I doubt I'm doing something wrong since it's so simple.

```
module.exports = {
  theme: {
    maxWidth: {
     'max-w-7xl': '80rem',
    }
  }
}
```

This is the same example given on [this page ](https://tailwindcss.com/docs/max-width/#app)
I know my `tailwind.config.js` works because I successfully already added breakpoints. 

Is this my mistake or is this a bug?

**Comment by CvX** [comment]
You shouldn't prefix width's name:

```js
maxWidth: {
  '7xl': '80rem',
}
```

**Comment by creativiii** [comment]
Ah oops, sorry about that.
Thank you for the help.
