### ISSUE TITLE
Pointer Events Classname Too Long

### ISSUE THREAD

**Issue by pxwee5** [tailwindcss/tailwindcss#1046]
Can we have `pointer` instead of `pointer-events` for pointerEvents class names? 

`pointer-events-none` is quite long imo.

**Comment by AlexVipond** [comment]
@pxwee5 it's always possible to write your own plugin to use custom names. Note that changing the class name would be a breaking change, so it would have to wait at least until the next major release

**Comment by adamwathan** [comment]
Yeah unfortunately since it's a breaking change I don't really want to change this. Agree it's long one :/ But since it's not used super commonly (compared to padding or margin for example) hopefully it's not too big of an issue.
