### ISSUE TITLE
postcss-import does not compile CSS

### ISSUE THREAD

**Issue by andrewcroce** [tailwindcss/tailwindcss#1049]
I am attempting to use the `@import` method of using Tailwind as described in the docs. I am using Parcel Bundler to compile my assets.

My `postcss.config.js`:
```
module.exports = {
  plugins: [
    require("postcss-import"),
    require("tailwindcss"),
    require("autoprefixer"),
  ],
}
``` 

My CSS file:
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

The resulting compiled CSS file:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Looks like the `@imports` are inlining the contents of those tailwind source files, but the `@tailwind` directive isn't compiling out the actual CSS.

**Comment by adamwathan** [comment]
This is unfortunately a problem with Parcel:

https://github.com/parcel-bundler/parcel/issues/1165

**Comment by andrewcroce** [comment]
Sigh. Thanks for the reference.

**Comment by Steffi3rd** [comment]
Hello guys, is there a solution for this? 
Still have the same problem in 2020 🙁

**Comment by bholtbholt** [comment]
Found a counterintuitive/weird fix for this while working with Parcel.
### Don't include `postcss-import` in your package, use `@tailwind` for tailwind, and `@import` for custom files



#### Here's what worked for me:

My `postcss.config.js`:
```javascript
module.exports = {
  plugins: ['tailwindcss', 'postcss-nested', 'autoprefixer'], // I'm using nested styles in one of my imports
};
```

My CSS entry: `css/index.css`:
```css
@import './variables';
@tailwind base;
@tailwind components;
@import './button';
@import './loading-dots';
@tailwind utilities;
```

My output CSS:
```javascript
// variables
// button
// loading-dots
// tailwind base
// tailwind components
// tailwind utilities
```

So Parcel doesn't seem to care about your import order, and automatically shifts imports to the top.

**Comment by murtazasultani** [comment]
still, have the issue is there any solution?
