### ISSUE TITLE
List reset overrides other (padding, margin) utilites

### ISSUE THREAD

**Issue by jake-dohm** [tailwindcss/tailwindcss#105]
Hey guys, first of all, I appreciate all of your great work on Tailwind!

Down to business: When I use the `list-reset` utility class, it is overriding any padding/margin utilities that I want to add. I obviously haven't thought through this as much as y'all, but I would think it would be best for any override/reset utilities to be automatically overwritten by other Tailwind utilities. I doubt anyone putting `list-reset` and `p-top-4` on a list element is expecting anything other than an element with no styling except some top padding.

Again, great work, and let me know if I'm just thinking wrong about this!

**Comment by jake-dohm** [comment]
Also, if this makes sense to you, and you agree that the `list-reset` utility should come first in the CSS file so the cascade will take care of this issue for us, then I'd be glad to submit a PR. Just let me know!

**Comment by adamwathan** [comment]
Hey great catch, it definitely should earlier in the list of generators,
would love a PR 👍🏻 I’d say put it at the very beginning with the forms
module!

**Comment by jake-dohm** [comment]
Submitted PR #110 to (hopefully) address this issue!

**Comment by adamwathan** [comment]
Fixed, thanks @jake-dohm!
