### ISSUE TITLE
Allow passing multiple styles to hover:, etc

### ISSUE THREAD

**Issue by alexleeelkins** [tailwindcss/tailwindcss#1068]
Allow users to pass multiple styles to a given class, example:

<div class="hover:bg-orange-500|text-blue-500"></div>

Ideally using some commonly used delimiter, like a pipe.

**Comment by ryanpurcella** [comment]
Something like  class="hover:bg-orange-500|text-blue-500". It would just clean up the syntax significantly when you have to add a lot of classes to hover, focus, etc. Obviously you can just use @apply when needed, but this would make it easier to play with the design before creating further abstractions.

**Comment by adamwathan** [comment]
This isn't really feasible because we'd have to pre-generate every possible combination which would literally lead to millions of CSS classes.

**Comment by alexleeelkins** [comment]
Is it possible to use JS to parse the separated data and apply the styles that way?

**Comment by adamwathan** [comment]
Probably not in any sort of efficient way :/ If you're comfortable with that sort of solution though you might be interested in exploring CSS-in-JS libraries like [Theme UI](https://theme-ui.com) or [Emotion](https://emotion.sh).

**Comment by anburocky3** [comment]
Developers would love these features. Quite organised.

**Comment by JoshuaPelealu** [comment]
I'm just bouncing ideas about this topic, because this would indeed be such a useful feature, couldn't this feature be implemented using the attribute selectors?
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

Just bouncing some ideas, I know this thread is old

**Comment by arye-eidelman** [comment]
> This isn't really feasible because we'd have to pre-generate every possible combination which would literally lead to millions of CSS classes.

Can this be revisited now that Tailwind 3 fully transitioned to jit mode?

it should create about as much css as creating a class and applying the styles there
`.hover\:bg-orange-500\|text-blue-500 { @apply hover:bg-orange-500 hover:text-blue-500; }`
vs 
`.my-hover-affect { @apply hover:bg-orange-500 hover:text-blue-500; }`

Maybe if the classes after the hover prefix are wrapped in parentheses it would be simplar for the compilar? `hover:(bg-orange-500|text-blue-500)`

**Comment by prs-wjy** [comment]
Just wondering if there is info if this will be revisited? I hope we can have this soon, I think this feature could save a lot of development time and improve the code readability.

**Comment by aquaductape** [comment]
it would be sick if you could could group utilities like twind https://twind.dev/handbook/grouping-syntax.html#variant-grouping. Tailwind increases development time once you add dark mode, because you have to duplicate everything.

**Comment by nickyhajal** [comment]
This does seem like it would be a big help!

**Comment by istarkov** [comment]
Having supports of arbitrary variants this looks like must have feature, as for example

```
[&:not(:focus):not(:placeholder-shown):invalid]:(border-white outline-none ring-2 ring-offset-2 ring-offset-red-500 ring-white)
```

Looks much nicier vs expanding this.

Not a big issue as custom plugin 
```
({ addVariant }) => {
  addVariant('invalid', '&:not(:focus):not(:placeholder-shown):invalid');
}
```
shortify example above BTW its really cool feature.

**Comment by knpwrs** [comment]
This is also supported by windi: https://windicss.org/features/variant-groups.html

**Comment by TheDefinitionist** [comment]
> This is also supported by windi: https://windicss.org/features/variant-groups.html
Yeah idk why every other tw extension has it by now but not tailwind itself

**Comment by TheDefinitionist** [comment]
> This is also supported by windi: https://windicss.org/features/variant-groups.html
> Yeah idk why every other tw extension has it by now but not tailwind itself

Yeah idk why every other tw extension has it by now but Tailwind itself.

**Comment by linorabolini** [comment]
hmm I think we should revisit this, 

Wouldn't it be just syntax sugar ? it would be really helpful to group some sort of state

instead of 
`disabled:bg-gray-200 disabled:text-gray-400 disabed:pointer-events-none`

we could write the following
`disabled:(bg-gray-200 text-gray-400 pointer-events-none)`

**Comment by dizzyjaguar** [comment]
is there any update on this?

**Comment by cawa-93** [comment]
UnoCSS also do this 🤷🏻‍♂️
https://www.npmjs.com/package/@unocss/transformer-variant-group

**Comment by morganfeeney** [comment]
I came looking for this issue.

Having so many instances of selectors detracts from the usefulness / efficiency of Tailwind, this is always the point where I want to throw my toys out of my pram and use `@apply`, obviously that is an option, but one of the core principles is not having to leave HTML.

```jsx
const CodeBlockVariants = cva(
  "codeFigure relative [&_figcaption]:absolute [&_figcaption]:top-0 [&_figcaption]:text-white [&_figcaption]:text-sm [&_figcaption]:font-bold [&_figcaption]:px-2 [&_figcaption]:py-1 [&_figcaption]:-rotate-12 [&_figcaption]:-left-2",
  {
    variants: {
      variant: {
        default:
          "[&>pre]:drop-shadow-[12px_12px_0_#5200FF] [&_figcaption]:bg-[#5200FF]",
        secondary: "[&>pre]:drop-shadow-[12px_12px_0_#FF5C5C]",
        tertiary: "[&>pre]:drop-shadow-[12px_12px_0_#65ABFE]",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

interface CodeBlockProps extends VariantProps<typeof CodeBlockVariants> {
  code: string;
  title: string;
}

const CodeBlock: FC<CodeBlockProps> = ({ code, title, variant }) => {
  return (
    <figure className={cn(CodeBlockVariants({ variant }))}>
      <pre className="bg-black overflow-auto text-white text-xl rounded-lg p-6">
        <code>{code}</code>
      </pre>
      <figcaption>{title}</figcaption>
    </figure>
  );
};
```

**Comment by koakuma-chan** [comment]
> This isn't really feasible because we'd have to pre-generate every possible combination which would literally lead to millions of CSS classes.

I have the following code:
```astro
---
import Layout from "../Layout.astro";
---

<Layout>
  <form class="space-y-4">
    <h1 class="text-2xl font-semibold">
      Upload
    </h1>

    <input
      class="p-4 [&::file-selector-button]:cursor-pointer [&::file-selector-button]:bg-transparent [&::file-selector-button]:border-none [&::file-selector-button]:h-[48px] [&::file-selector-button]:mr-4 [&::file-selector-button]:text-zinc-800 [&::file-selector-button]:px-8"
      type="file"
      accept="audio/*,video/*"
      multiple
    />
  </form>
</Layout>
```

If you look at the `input` element, you will be able to see that there are ten classes.

Now, with this in mind, if pseudo-class grouping was a thing, the code could be rewritten as:

```astro
---
import Layout from "../Layout.astro";
---

<Layout>
  <form class="space-y-4">
    <h1 class="text-2xl font-semibold">
      Upload
    </h1>

    <input
      class="p-4 [&::file-selector-button]:(cursor-pointer bg-transparent border-none h-[48px] mr-4 text-zinc-800 px-8)"
      type="file"
      accept="audio/*,video/*"
      multiple
    />
  </form>
</Layout>
```

As far as my understanding goes, this would reduce the number of classes on the `input` element from ten to two and therefore, not only would the code become readable, the amount of generated CSS would probably also become lower.
