### ISSUE TITLE
List reset in base

### ISSUE THREAD

**Issue by missmatsuko** [tailwindcss/tailwindcss#1076]
I don't think *all* lists (ol, ul) should be unstyled in the base styles.

For example, if we have lists coming from a rich text editor and want each nested level of list to have different bullet styles (like browser defaults), I don't think there's a reliable way to do that.

Example:
https://jsfiddle.net/zapju3n0/1/

Also, the list-reset utility class isn't very useful if all the lists start off unstyled anyways?

**Comment by florianbouvot** [comment]
I wrap every rich text editor with a `cms-content` classes so I can easily style list, link, ...

**Comment by adamwathan** [comment]
Only the first three levels of list styles have different bullet types by default:

![image](https://user-images.githubusercontent.com/4323180/62939552-917f4e80-bd9f-11e9-94f1-fe39ef87c655.png)

So you could bring that back with your own base styles without a ton of difficulty.

Here's the original discussion around resetting list styles:

https://github.com/tailwindcss/tailwindcss/pull/761

It would be a big breaking change to change this and when we ran an informal vote the majority wanted unstyled so no plans to revert this change.

> Also, the list-reset utility class isn't very useful if all the lists start off unstyled anyways?

We actually removed that utility in 1.0 for this reason, so it doesn't exist anymore 👍

**Comment by missmatsuko** [comment]
Oh weird, I must've ended up in the old docs through search and saw that list-reset class.

I still think it's a lot easier to add a list-reset class on a list whose markup I can directly control, than adding browser default-esque styled back into a list whose markup I don't control. Especially if you have a multilingual site. Maybe something to consider for the next version, or make it possible to opt-out of the list reset styles in base.

**Comment by adamwathan** [comment]
Going to close this since no plans to change this by default, but you can always disable `preflight` in your `corePlugins` if you'd like to provide your own base styles instead 👍

**Comment by florianbouvot** [comment]
@MiruiWang2021 I do this kind of things to restore list style. And I also include style for paragraphs, headings, links, ...

```
.c-cms-content {
  ...
  
  /* Lists */
  ol,
  ul {
    padding-left: theme('spacing.10');
  }

  ol {
    list-style-type: decimal;
  }

  ul {
    list-style-type: disc;
  }

  ...
}
```

But you can also look at [Tailwind typography official plugin](https://tailwindcss.com/docs/typography-plugin)

**Comment by MiruiWang2021** [comment]
@florianbouvot thank you for share the detail, this solve my issue, appreciate.

**Comment by vincerubinetti** [comment]
For anyone stumbling on this, the way to undo the list reset is with `list-[revert]`:

```
  ul,
  ol {
    @apply list-[revert];
  }
```

<img height="100" alt="Image" src="https://github.com/user-attachments/assets/cab938c9-1500-4070-8422-7a8b9d806a6f" />

And then to prevent the extra marker when nesting the lists, you might also want to do this:

```
  li:has(ul, ol) {
    @apply list-none;
  }
```
