### ISSUE TITLE
.font-sans missing sans-serif

### ISSUE THREAD

**Issue by tlgreg** [tailwindcss/tailwindcss#108]
So the defaultConfig `.font-sans` font stack doesn't have `sans-serif` as the last fallback.
Although be unlikely that every font is missing, but if so the font stack actually falls back to Times New Roman on Chrome and Firefox (and most likely others).

ps.: Actually the only windows default in the list is Segoe UI.

**Comment by reinink** [comment]
Yeah, good point @tlgreg. I'll add that.
