### ISSUE TITLE
Custom config not considered when compiling

### ISSUE THREAD

**Issue by ack202** [tailwindcss/tailwindcss#1080]
Environment: Laravel 5.8

Any changes made to tailwind.js are not considered when compiling the assets via npm run dev

webpack.mix.js 

```
require('laravel-mix-tailwind');
require('laravel-mix-purgecss');

mix.js('resources/js/app.js', 'public/js')
   .postCss('resources/css/app.css', 'public/css')
   .tailwind('./tailwind.js')
   .purgeCss();
```

Someone else ran also into this?

**Comment by adamwathan** [comment]
Can you share a whole project? Looks like you might be combining information from tailwind 0.x and 1.0 since the file is no longer called tailwind.js, so I’m guessing some thing are configured the old way.

**Comment by ack202** [comment]
The moment I created a fresh install to provide it as an example here it worked :)
