### ISSUE TITLE
Default border styles causing issues with default select

### ISSUE THREAD

**Issue by RedHatter** [tailwindcss/tailwindcss#1092]
Setting borders for all elements causes select elements to display in an ugly flat look instead of with the default browser appearance. Even after setting border width, style, and color to initial the problem persists. This is fine when I want to apply a custom style but in some cases the browser defaults are desired.

**Comment by adamwathan** [comment]
No plans change this by default, but you can opt-out of our default styles by disabling the `preflight` core plugin:

https://tailwindcss.com/docs/preflight#disabling-preflight

There's also the official (although still under development) [Tailwind Custom Forms](https://tailwindcss-custom-forms.netlify.com) plugin you can use to easily add nicer cross-browser form styles to a project.
