### ISSUE TITLE
Custom max-width for container

### ISSUE THREAD

**Issue by Jonarod** [tailwindcss/tailwindcss#1102]
I need to tweak max-width for each `.container` breakpoints. 

In fact, I would prefer to use these:

Class | Breakpoint | Properties
-- | -- | --
|.container | None | width: 100%;
||sm (640px) | max-width: 600px;
||md (768px) | max-width: 700px;
||lg (1024px) | max-width: 800px;
||xl (1280px) | max-width: 900px;

But I couldn't find a way to achieve that using `tailwind.config.js`.

**Comment by Jonarod** [comment]
Nice ! I was about to rewrite all my components using some `md:max-w-lg mx-auto ...` logic.
Thank you !

**Comment by Flothus** [comment]
Why not allow to overwrite maxWidth values in the config instead?
I thought this feels kind of like the tailwind way?
 
```js
container: 
  center: true,
  maxWidth: {
    'md': '700px'
}
```

**Comment by bugproof** [comment]
container doesn't work with max-width breakpoints, it's 100% all the time, no way to change that behaviour https://tailwindcss.com/docs/breakpoints/#max-width-breakpoints

**Comment by Flothus** [comment]
@bugproof 

well, the tailwind container could just come with the max-widths by default, then you don't have to pollute the config with a custom plugin for something that I guess most people would need anyway. 
But maybe I'm overestimating the usefulness.

**Comment by adamwathan** [comment]
I'd be open to a PR that added support for this, but I personally think matching breakpoints + some horizontal padding is all you really need for most situations. I find that to be a cleaner solution than settings a max-width of 1240px on 1280px screens for example.

The main use-case for customizing it in my opinion is sidebar layouts, where you might want a container just for your content area so you need to subtract the width of the sidebar from your breakpoints.

**Comment by codemonkeynorth** [comment]
the reason for needing this is I have some elements that are eg `xl:w-6\12` but they're too narrow at around ~1200px screen width. there's quite a big difference between 1200 and 1920! but `xl` only covers up to 1200, so I added an `xxl` @ 1440px so I had a bit more control (eg `xl:w-8/12  xxl:w-6/12`)

however it didn't mean i want my `container` to be any wider than the actual 1200px it is by default (for `xl`)

think of `1200px` as "max site width" in this case (for contained sections at least)

for now i've just thrown this in though

```
@media (min-width: 1440px) {
  .container {
    max-width: 1200px;  
  }
}
```

thanks

**Comment by RomainMazB** [comment]
Just to add another use case: I'm currently migrating a website from a CMS to another for a client and he want me to make a perfect copy of its webdesign which uses a 1200px width design.

TailwindCSS is friendly for customization with near from every components,
I was surprised to see .container is not part of them.

**Comment by BjornLuG** [comment]
Just to add, [v1.3.0](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.3.0) now supports breakpoint-specific padding for containers and can be used to indirectly set the max-width. Not the best workflow but it's currently the best option without resulting to writing a plugin.

**Comment by jorher** [comment]
Hey there, I found this solution

```
container: {
  screens: {
     sm: "100%",
     md: "100%",
     lg: "1024px",
     xl: "1280px"
  }
},
```

with this you don't have to create a new container.
Hope it helps :)

**Comment by webcoderkz** [comment]
@adamwathan how about @jorher approach? Is it fine?

**Comment by isramv** [comment]
> Hey there, I found this solution
> 
> ```
> module.exports = {
>   theme: {
>     container: {
>       screens: {
>          sm: "100%",
>          md: "100%",
>          lg: "1024px",
>          xl: "1280px"
>       }
>     }
>   }
> }
> ```
> 
> with this you don't have to create a new container.
> Hope it helps :)

This should be added to the documentation :tada:

**Comment by 8bu** [comment]
> 
> 
> Hey there, I found this solution
> 
> ```
> module.exports = {
>   theme: {
>     container: {
>       screens: {
>          sm: "100%",
>          md: "100%",
>          lg: "1024px",
>          xl: "1280px"
>       }
>     }
>   }
> }
> ```
> 
> with this you don't have to create a new container.
> Hope it helps :)

how's it still not in the document?

**Comment by stoplion** [comment]
☝🏼 that doesn't work for me

**Comment by PSoltes** [comment]
> > Hey there, I found this solution
> > ```
> > module.exports = {
> >   theme: {
> >     container: {
> >       screens: {
> >          sm: "100%",
> >          md: "100%",
> >          lg: "1024px",
> >          xl: "1280px"
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > with this you don't have to create a new container.
> > Hope it helps :)
> 
> This should be added to the documentation

This also sets the breakpoint to the value you want the container to be, also you can't set None width

**Comment by NicoHood** [comment]
Can we have a clear answer about this container thing? It is completely missing in the docs. I guess that is a common usecase to set a global website container width.

**Comment by leoortiz** [comment]
> Can we have a clear answer about this container thing? It is completely missing in the docs and the above suggestion also does not work for me. I guess that is a common usecase to set a global website container width.
> 
> The issue what @PSoltes described above can be seen in this simple example:
> 
> ```js
>     container: {
>       screens: {
>         bla: "500px",
>         bli: "1000px"
>       }
>     },
> ```
> 
> The name does not matter. The container functions as breakpoint itself. If the size is smaller than a possible container width, the next smaller version gets used. That is not what we wanted in first place.
> 
> I found the solution of @RomainMazB better. As an alternative you could use `max-w-[1000px]` with the new tailwind jit.

Don't know if that's your case, but I tried it in a Next.js project and it only worked after I restarted the dev process.

**Comment by PSoltes** [comment]
> > Can we have a clear answer about this container thing? It is completely missing in the docs and the above suggestion also does not work for me. I guess that is a common usecase to set a global website container width.
> > The issue what @PSoltes described above can be seen in this simple example:
> > ```js
> >     container: {
> >       screens: {
> >         bla: "500px",
> >         bli: "1000px"
> >       }
> >     },
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > The name does not matter. The container functions as breakpoint itself. If the size is smaller than a possible container width, the next smaller version gets used. That is not what we wanted in first place.
> > I found the solution of @RomainMazB better. As an alternative you could use `max-w-[1000px]` with the new tailwind jit.
> 
> Don't know if that's your case, but I tried it in a Next.js project and it only worked after the dev process was restarted.

The thing i am talking about is when i set it in container screens in tailwind config. Breakpoint is also set to that value.
For example with tailwind config like this
`container: {
      screens: {
        DEFAULT: "100%",
        xs: "380px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1200px",
        "2xl": "1450px",
      },
    },`

generated css is like
![problem](https://user-images.githubusercontent.com/22454458/118122738-8d101b80-b3f3-11eb-8a03-65de297d158f.png)

**Comment by adamwathan** [comment]
There is no way to change the container width based on the screen size other than to configure the padding, no plans to change this currently.

The `screens` option in the container plugin is very old, and for backwards compatibility reasons behaves as described, where the width is always equal to the breakpoint, even when setting custom screens values.

If someone wanted to PR a new option like `sizes` or something that was a map of screenName -> custom max width I would be open to reviewing it.

**Comment by fultonm** [comment]
What about specifying 2xl in tailwind.config.js?

`An identifier or keyword cannot immediately follow a numeric literal.`

**Comment by IsraelOrtuno** [comment]
What about doing this?

```
  plugins: [
    plugin(function({addComponents, config}) {
      addComponents({
        '.container': {
          'max-width': config('theme.maxWidth.2xl')
        }
      })
    })
  ],
```

**Comment by Showrin** [comment]
> > Hey there, I found this solution
> > ```
> > module.exports = {
> >   theme: {
> >     container: {
> >       screens: {
> >          sm: "100%",
> >          md: "100%",
> >          lg: "1024px",
> >          xl: "1280px"
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > with this you don't have to create a new container.
> > Hope it helps :)
> 
> This should be added to the documentation 🎉

This solution saved my day 😅 Thanks so much @jorher 
I think this should be added in the doc.

**Comment by webcat12345** [comment]
> Hey there, I found this solution
> 
> ```
> module.exports = {
>   theme: {
>     container: {
>       screens: {
>          sm: "100%",
>          md: "100%",
>          lg: "1024px",
>          xl: "1280px"
>       }
>     }
>   }
> }
> ```
> 
> with this you don't have to create a new container.
> Hope it helps :)

This works awesome.

**Comment by prafulla-inx** [comment]
What if you want to do this way: 

`module.exports = {
  theme: {
    container: {
      screens: {
         sm: "90%",
         md: "80%",
         lg: "85%",
         xl: "1280px"
      }
    }
  }
}`

It doesn't seem to be working, in all cases it gives, 100%.

**Comment by anthonygedeon** [comment]
@prafulla-inx yep, I'm running into the same issue, whatever you change the value to it defaults to `100%`

```
container: {
    screens: {
         sm: "700px"
    }
},
```

**Comment by xSuffix** [comment]
> 

Percentages don't work here. The screen attribute overrides breakpoints for the container class. Breakpoints like 80% don't make sense, instead there will be no breakpoint. So additional attributes like custom padding will also not work for these breakpoints.

**Comment by onikaii** [comment]
> > 
> 
> Percentages don't work here. The screen attribute overrides breakpoints for the container class. Breakpoints like 80% don't make sense, instead there will be no breakpoint. So additional attributes like custom padding will also not work for these breakpoints.

same problem here, Percentages don't work any solution?

**Comment by rutpshah** [comment]
I have solved this way:

**tailwind.config.js:**
`module.exports = {
    theme: {
      container: {
        screens: {
          'mobile': '1440px',
          'tablet': '1440px',
          'desktop': '1440px'
        },
      },
    },
}`

html:
`<div class="container"></div>`

**Comment by inx-tapan** [comment]
Another option which fits good for me is :

```javascript const plugin = require('tailwindcss/plugin'),
theme: {
    extend: {
       screens: {
        'xxs': '370px',
        'xs': '480px',
        'sm': '576px',
        'md': '767px',
        'lg': '992px',
        'xl': '1200px',
        'xxl': '1400px',
      },
    }
},

plugins: [
    plugin(function({ addComponents }) {
      addComponents({
        '.container': {
          maxWidth: '100%',
          '@screen xxs': {
            maxWidth: '95%',
          },
          '@screen xs': {
            maxWidth: '95%',
          },
          '@screen sm': {
            maxWidth: '98%',
          },
          '@screen md': {
            maxWidth: '98%',
          },
          '@screen lg': {
            maxWidth: '992px',
          },
          '@screen xl': {
            maxWidth: '98%',
          },
          '@screen xxl': {
            maxWidth: '1300px',
          },
        }
      });
    })
  ]

  Then i can switch to any container size depending on screen resolution and change above config.

**Comment by popuguytheparrot** [comment]
this solution not working in 3.2.4 for me

```
module.exports = {
  theme: {
    container: {
      screens: {
         sm: "100%",
         md: "100%",
         lg: "1024px",
         xl: "1280px"
      }
    }
  }
}
```

**Comment by MaideAkdede** [comment]
> Hey there, I found this solution
> 
> ```
> module.exports = {
>   theme: {
>     container: {
>       screens: {
>          sm: "100%",
>          md: "100%",
>          lg: "1024px",
>          xl: "1280px"
>       }
>     }
>   }
> }
> ```
> 
> with this you don't have to create a new container. Hope it helps :)

:warning: It does NOT WORK properly like intended :warning: 

People haven't tested this thoroughly, it might LOOK like it work, but it doesn't.
This method create TWO min-width to the container. Such as : 

``` css
@media (min-width: 768px)
@media (min-width: 1496px)
<style>
.md\:container {
    max-width: 1496px;
}
```

**Comment by westtrade** [comment]
> > Hey there, I found this solution
> > ```
> > module.exports = {
> >   theme: {
> >     container: {
> >       screens: {
> >          sm: "100%",
> >          md: "100%",
> >          lg: "1024px",
> >          xl: "1280px"
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with this you don't have to create a new container. Hope it helps :)
> 
> ⚠️ It does NOT WORK properly like intended ⚠️
> 
> People haven't tested this thoroughly, it might LOOK like it works, but it doesn't. This method creates TWO min-width to the container. Such as :
> 
> ```css
> @media (min-width: 768px)
> @media (min-width: 1496px)
> <style>
> .md\:container {
>     max-width: 1496px;
> }
> ```
> 
> So the .container take the screen sizes of the Basic TAILWIND config + the screen sizes we entered

Agree. This method is broken

**Comment by bizmich** [comment]
> sm: "100%",
>          md: "100%",
>          lg: "1024px",
>          xl: "1280px"

but its not working with percent

**Comment by 123ten** [comment]
/** tailwindcss.config.js */
export default {
  theme: {
    screens: {
      container: "100%",
    }
  },
}

**Comment by 123ten** [comment]
`/** tailwindcss.config.js */
export default {
  theme: {
    screens: {
      container: "100%",
    }
  },
}`

**Comment by axelthat** [comment]
@MaideAkdede I don't see two min-width's anymore.
![image](https://github.com/tailwindlabs/tailwindcss/assets/31353695/cb56b5f3-326f-4a35-aa96-8c436a41df59)

**Comment by sovitranjitkar** [comment]
If anyone needs commonly used dimensions of `960px` and `1024px`, here is the code:

```
module.exports = {
	// ...
	theme: {
		extend: {
			screens: {
				lg: '990px',
				xl: '1054px',
			},
		},
	},
	corePlugins: {
		container: false
	},
	plugins: [
		function ({ addComponents }) {
			addComponents({
				'.container': {
					width: '100%',
					marginInline: 'auto',
					paddingInline: '15px',
					'@screen sm': {
						maxWidth: '610px',
						paddingInline: '0',
					},
					'@screen md': {
						maxWidth: '738px',
						paddingInline: '0',
					},
					'@screen lg': {
						maxWidth: '960px',
						paddingInline: '0',
					},
					'@screen xl': {
						maxWidth: '1024px',
						paddingInline: '0',
					},
				}
			})
		}
	],
} 
```
which will output as:

```
.container {
	width: 100%;
	margin-inline: auto;
	padding-inline: 15px;
}
@media (min-width: 640px) {
	.container {
		max-width: 610px;
		padding-inline: 0;
	}
}
@media (min-width: 768px) {
	.container {
		max-width: 738px;
		padding-inline: 0;
	}
}
@media (min-width: 990px) {
	.container {
		max-width: 960px;
		padding-inline: 0;
	}
}
@media (min-width: 1054px) {
	.container {
		max-width: 1024px;
		padding-inline: 0;
	}
}
```
OR if you need a fluid layout with a maximum width of `1024px`

```
module.exports = {
	// ...
	theme: {
		extend: {
			screens: {
				xl: '1054px',
			},
		},
	},
	corePlugins: {
		container: false
	},
	plugins: [
		function ({ addComponents }) {
			addComponents({
				'.container': {
					width: '100%',
					marginInline: 'auto',
					paddingInline: '15px',
					'@screen xl': {
						maxWidth: '1024px',
					},
				}
			})
		}
	],
}
```

which will output as:

```
.container {
	width: 100%;
	margin-inline: auto;
	padding-inline: 15px;
}
@media (min-width: 1054px) {
	.container {
		max-width: 1024px;
	}
}
```

**Comment by Giusti** [comment]
It seems this issue is still not fixed, even though it was closed

- container screen still creates additional min-width breakpoints which define a matching max-width for the container.
- without custom plugin changes or abusing padding it is not possible to define a custom max-width for a certain breakpoint
- if backwords compatibility is an issue why are we not introducing a maxWidth utility for the container and leave the existing screens as is ?
