### ISSUE TITLE
[Feature request] suffix for utility classes

### ISSUE THREAD

**Issue by mirkea** [tailwindcss/tailwindcss#1104]
My use case for this might be too specific but there might be other uses for this as well.

In my case I want to use .less with Tailwind's utility classes. The reason for this is that I can import that css file as a reference, and then only use the classes I need, something like this
```
@import (reference, less) "../../styles/tailwind.css"; 

.my-component {
   .p-4;   
   .bg-primary; 
   .rounded-lg;
}
```
This is simple to use and it just works in producing a minimal css, without the need for cssnano, purgecss or other plugins that  can be hit or miss. 

By default this works nicely but the problem is that vs-code doesn't provide auto suggest for those, and memorizing all the class names is not the most user friendly approach. 

This could be solved if the utility classes were defined as mixins, so if instead of `.p-1 {...}` there was `.p-1() {...}` then that would show up in the auto-suggest list. This is where the option of providing a suffix (`()` in this case) would be useful.

**Comment by GeoffSelby** [comment]
Why not use the `@apply` rule? [https://tailwindcss.com/docs/extracting-components#extracting-css-components-with-apply](https://tailwindcss.com/docs/extracting-components#extracting-css-components-with-apply)

**Comment by hacknug** [comment]
Have you tried [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) to get intellisense for Tailwind classes?

**Comment by adamwathan** [comment]
Tailwind isn't written in Less so we can't provide Less mixins. Instead I would recommend using the `@apply` feature as mentioned above, as that is directly based on the Less workflow you mentioned 👍
