### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by SylvanoTombo** [tailwindcss/tailwindcss#1105]
Hi, I installed tailwindcss with vuejs following the documentation but got some errors.

Failed to compile with 3 errors                     

These dependencies were not found:

* -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/base in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/assets/css/tailwind.css
* -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/components in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/assets/css/tailwind.css
* -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/utilities in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/assets/css/tailwind.css

To install them, you can run: npm install --save -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/base -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/components -!../../../node_modules/css-loader/index.js??ref--6-oneOf-3-1!../../../node_modules/postcss-loader/src/index.js??ref--6-oneOf-3-2!./tailwindcss/utilities

**Comment by hacknug** [comment]
Looks more like an issue with how your project is set up. Do you have a repo I can lone to take a look at?

Not sure how you're importing Tailwind's stuff but depending on your setup you'll have to use `@import` instead of `@tailwind`. You can read a little more about it here:
- https://tailwindcss.com/docs/functions-and-directives/#tailwind
- https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports

**Comment by SylvanoTombo** [comment]
I'll check that and post here the repo.Thanks

**Comment by SylvanoTombo** [comment]
Thank you..its work.It looks more like an issue with how i set up my project.
