### ISSUE TITLE
Feature request: Black and white w/ alpha colours

### ISSUE THREAD

**Issue by 1player** [tailwindcss/tailwindcss#111]
I propose we introduce the black colour with different alpha values, so that, e.g. `bg-black-50` sets a background-color of `rgba(0, 0, 0, 0.5)`.

The scale could be `black-10`, `black-20`... `black-90`, as `black-0` would actually be transparent, and `black-100` is already represented by the class `black`.

We will probably need the same for white colours.

I'll be working on a pull request.

**Comment by reinink** [comment]
Closing this, as per the discussion in #114.
