### ISSUE TITLE
@apply property !important compiles incorrectly.

### ISSUE THREAD

**Issue by WebKieth** [tailwindcss/tailwindcss#1118]
👋 Hi

I start new react app based on create-react-app without webpack config and I wont care about merging with custom, so I just configured scripts.

First case of project scripts:
```
    "start:scss": "sass --watch --no-source-map src/tailwind.scss src/tailwind.css",
    "build:scss": "sass --no-source-map src/tailwind.scss src/tailwind.css",
    "start:css": "postcss src/styles/tailwind.src.scss -o src/tailwind.scss -w",
    "build:css": "postcss src/styles/tailwind.src.scss -o src/tailwind.scss --env production",
```
Firstly run postcss - it goes to tailwind.src and compiles into scss - their compiler watch on and compile all new change into clean css, which imports to App.js.

When we try to compile `@apply some-property !important` with this config postcss compiles to
`some: property; !important;`, with dot-comma after `property`. And I got an error...
```bash
Error: expected "}".
   ╷
99 │       stroke: #EAECEF; !important;
```
=======
So, I just switch css proccess and update my scripts.
```
    "start:scss": "sass --watch --no-source-map src/styles/tailwind.src.scss src/tailwind.post.css",
    "build:scss": "sass --no-source-map src/tailwind.scss src/tailwind.css",
    "start:css": "postcss src/tailwind.post.css -o src/tailwind.css -w",
    "build:css": "postcss src/tailwind.post.css -o src/tailwind.css --env production",
```
Now, SCSS on first level and postCSS - after it, like a normal people do - cause POST...css, right?)
And I got an error from SCSS compiler...
```
Error: expected ";".
   ╷
45 │             @apply stroke-graylight !important;
```
Ok, this is not the end.... I know about `#{!important}` concat, I did it and all css chain works good, but now webpack got the same error as SASS compiler reject to me first time... 
Guys, this is a bug  -_-

UPD
Sry, forget about tailwind problem fragment code:
```
&:focus {
            @apply outline-none shadow-none bg-ui-bluedarker transition-0;
            @apply stroke-graylight #{!important};
            &#{$parent}--secondary {
                @apply text-white
            }
        }
```

**Comment by adamwathan** [comment]
Can you create a GitHub repo that reproduces the issue?

**Comment by WebKieth** [comment]
@adamwathan i'm confused - in a clean react + tailwind repo this problem won't appear. I need some time to analyze why. Real project is a fresh too, but has some differences. Custom config, more difficult button cunstruction etc....

**Comment by WebKieth** [comment]
@adamwathan Ok, I found a reason of my problem. It's inside my tailwind.config:
```
const UIcolorPallete = {
    dark: "#30333D;",
    brown: "#333333;",
    graydark: "#707D88",
    gray: "#C3CAD5;", /* Gray_middle */
    graylight: "#EAECEF;",
    green: "#4CDB96;",
    red: "#EB5757;",
    orange: "#F2994A;",
    yellow: "#F2C94C;",
    blue: "#3176FA;",
    bluedark: "#0158FF;",
    bluedarker: "#043590;",
    white: "#fff"
};

const IconSizes = {
    'icon-sm': '10px',
    'icon-md': '18px',
    'icon-lg': '30px'
}

const PointerInputSizes = {
    'checkbox': '20px'
}

const SVGcolorProps = Object.assign({}, {
    'current': 'currentColor',
}, UIcolorPallete);
```

After defining design guide objects I just assign thier for different keys like this:
```
theme: {
  extend: {
    fill: Object.assign({}, SVGcolorProps),
    stroke: Object.assign({}, SVGcolorProps),
  }
}
```
And got this problem.
When I correct it on static object like this:
```
stroke: {'dark': '#333'} 
```
`!important` directive works perfect

**Comment by WebKieth** [comment]
I've tried to inherit colors to stroke by using theme callback:

```
 colors: {
            transparent: 'transparent',
            black: '#000',
            white: '#fff',
            ui: {
					    dark: "#30333D;",
					    brown: "#333333;",
					    graydark: "#707D88",
					    gray: "#C3CAD5;", /* Gray_middle */
					    graylight: "#EAECEF;",
					    green: "#4CDB96;",
					    red: "#EB5757;",
					    orange: "#F2994A;",
					    yellow: "#F2C94C;",
					    blue: "#3176FA;",
					    bluedark: "#0158FF;",
					    bluedarker: "#043590;",
					    white: "#fff"
            }
          }
        },
```
And into the stroke:
```
stroke: (theme) => theme('colors', 'ui'),
```
Still errored

**Comment by WebKieth** [comment]
@adamwathan repo for issue: https://github.com/WebKieth/react-tailwind-tests

**Comment by WebKieth** [comment]
@adamwathan, I solve it. The main reason of this bug sits opposite the PC. 
I wrote all color values with dot-comma in the end. So tailwind just pass it into the value as is =)
When I erase last comma dots, important works properly, 
===
BUT... It will be a nice feature to replace this char from string values if it was setted as last.

**Comment by adamwathan** [comment]
Ah gotcha. Probably not going to add any fancy validation like that but glad you found the issue.
