### ISSUE TITLE
Border Styles

### ISSUE THREAD

**Issue by ConnorVG** [tailwindcss/tailwindcss#112]
`.border-dotted` is outputting `border-width: 0` due to the `borderStylesReset` (afaict). This means that `border-dotted` and `border-dashed` output `border-width: 0` nullifying the border style (as it removes the border).

Is this a bug or am I not understanding something? I can get `class=".border-dotted"` to work but I just *can't* get `@apply border-dotted;` to work...

https://github.com/tailwindcss/tailwindcss/blob/52f6fb23ebd54613ac90da0ab6b859ec213bc7e2/src/lib/generateUtilities.js#L61 is messing with https://github.com/tailwindcss/tailwindcss/blob/52f6fb23ebd54613ac90da0ab6b859ec213bc7e2/src/lib/generateUtilities.js#L64

**Comment by adamwathan** [comment]
I never thought to test this but it totally makes sense. Conveniently, I was already working on a fix for another issue that happens to fix this too :)

#116

**Comment by adamwathan** [comment]
Closing this as it's resolved in `develop` and will be included in an 0.2.0 release this week 👍
