### ISSUE TITLE
Parse Error When Trying To Use theme() Inside calc()

### ISSUE THREAD

**Issue by joelbyrd** [tailwindcss/tailwindcss#1126]
I'm using Tailwind CSS with PostCSS via Gulp. Just about everything works great. I'm trying to reference values from the config theme object in my CSS. I'm able to do the following just fine:

```css
height: theme('spacing.12');
```

However, when I try to use theme() inside of calc() (just like [in the documentation](https://tailwindcss.com/docs/functions-and-directives/#theme)):

```css
height: calc(100vh - theme('spacing.12'));
```

I get a Parse error from gulp-postcss ("Expecting 'SUB', 'LPAREN'....")

**Comment by adamwathan** [comment]
Can't seem to reproduce here, works on tailwind.run too:

https://tailwind.run/Wuixda

This must be an issue with another tool in the chain so I'm going to close as likely not anything we can fix in Tailwind, but if you provide a GitHub repo that reproduces the issue I'm happy to pull it down and troubleshoot it.

**Comment by joelbyrd** [comment]
> Can't seem to reproduce here, works on tailwind.run too:
> 
> https://tailwind.run/Wuixda
> 
> This must be an issue with another tool in the chain so I'm going to close as likely not anything we can fix in Tailwind, but if you provide a GitHub repo that reproduces the issue I'm happy to pull it down and troubleshoot it.

You're right! In my gulp file, I was passing the postcss-cssnext node package into the `postcss()` call - turns out postcss-cssnext is now deprecated (oops!) - once I removed that, the problem was fixed. Sorry for the false alarm - thanks for pointing me in the right direction!

![image](https://user-images.githubusercontent.com/987670/65157837-653e9980-d9ff-11e9-99dd-c5e9d26ebbd6.png)

**Comment by hacknug** [comment]
Take a look at [`postcss-preset-env`](https://preset-env.cssdb.org) if you want/need to write _futuristic_ css.
