### ISSUE TITLE
ResolveConfig Issue

### ISSUE THREAD

**Issue by cizza** [tailwindcss/tailwindcss#1129]
Hi,

I've upgraded to a 1.12 tailwindcss version and I've encountered an issue with the resolveConfing.js function.

I'm using basically the same syntax as displayed on the website:

`import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../../tailwind.config.js';

export default resolveConfig(tailwindConfig)`

However when I compile the stylesheets, I get an error:

ERROR in ./node_modules/reduce-css-calc/dist/parser.js
Module not found: Error: Can't resolve 'fs' in 'C:\xampp\htdocs\widow_source\node_modules\reduce-css-calc\dist'

I'm using laraveMix processing tailwind thusly:

`const mix = require('laravel-mix');
require('mix-tailwindcss');
require('laravel-mix-alias');

mix.js('resources/js/scripts.js', 'public/js')
    .sass('resources/sass/styles.scss', 'public/css')
    .tailwind()
    .version();`

Npm install of the missing 'fs' dependency doesn't solve the issue. 

Any help would be welcome, 

Thank you.

**Comment by adamwathan** [comment]
This is an annoying problem and I hope [this PR](https://github.com/MoOx/reduce-css-calc/pull/26) gets merged to fix the core of it, but in the mean time you need to stub the `fs` module in your webpack config:

https://webpack.js.org/configuration/node/#other-node-core-libraries

Setting `fs` to `false` or `'empty'` will both work 👍🏻

**Comment by adamwathan** [comment]
For Laravel Mix specifically, you'll want to update your config to this:

```js
const mix = require('laravel-mix');
require('mix-tailwindcss');
require('laravel-mix-alias');

mix.js('resources/js/scripts.js', 'public/js')
.sass('resources/sass/styles.scss', 'public/css')
.tailwind()
.version()
.webpackConfig({
  node: { fs: false }
});
```

**Comment by cizza** [comment]
Thank you!

**Comment by cizza** [comment]
In my case I had to provide 

.webpackConfig({
  node: { fs: 'empty' }
});

**Comment by m11m** [comment]
I worked around the issue with externals:

`
  externals: {
    fs: "commonjs fs"
  }
`

**Comment by bipsBro** [comment]
> I worked around the issue with externals:
> 
> `externals: { fs: "commonjs fs" }`

in which file @m11m ?

**Comment by adamwathan** [comment]
@bipsBro in your webpack config 👍 

https://webpack.js.org/configuration/externals/

**Comment by mehrunrasoli** [comment]
Tried to add tailwind custom-forms to my config and got this error. On the latest version of Laravel+Tailwindcss

Not sure why none of the above solutions work in my case.
