### ISSUE TITLE
Sidebar full height not working

### ISSUE THREAD

**Issue by cakerake** [tailwindcss/tailwindcss#1138]
I followed a tailwind template to make a full height sidebar but it stops right after screen height and when you scroll down it shows how it stopped expanding

here is the codepen

[https://codepen.io/cakerake/pen/jONdBRO](https://codepen.io/cakerake/pen/jONdBRO
)
can definitely use some help

**Comment by tehpsalmist** [comment]
Where did you get the tailwind template from? Your class names don't look right.

**Comment by cakerake** [comment]
that was the wrong codepen im sorry and ive updated it

https://codepen.io/cakerake/pen/jONdBRO

**Comment by tehpsalmist** [comment]
It's behaving as expected. `h-screen` sets the height to exactly `100vh`, it doesn't mean it will always extend to the full height of all content. You might want to try something like `h-full` where your container is going to hold all of the content and therefore always be as tall as all of the content. Alternatively, try flex box with `items-stretch` or maybe use JS to measure and set the height (not optimal, but an option).

**Comment by cakerake** [comment]
Is it possible to keep at at screen height but not let it scroll down the page as an alternative? So that I can keep the shadow in place

**Comment by tehpsalmist** [comment]
Sure, use absolute positioning or fixed positioning. Are you ok if we close this? It sounds like the rest of your questions can be answered in forums and stackoverflow.

**Comment by cakerake** [comment]
Yes I’ll close it thanks for answering my questions
