### ISSUE TITLE
[Feature Request] add `ripple`

### ISSUE THREAD

**Issue by nelwincatalogo** [tailwindcss/tailwindcss#1143]
e.g

```html
<div class="ripple">

</div>
```

reference: [https://codepen.io/finnhvman/pen/jLXKJw](https://codepen.io/finnhvman/pen/jLXKJw)

**Comment by adamwathan** [comment]
I think this is probably too opinionated to bake into the framework but you can add it to your own projects by creating a component class or a custom utility:

https://tailwindcss.com/docs/extracting-components
https://tailwindcss.com/docs/adding-new-utilities

**Comment by ZOLDIK0** [comment]
here's a ready utility if you are lazy to create yours
[https://github.com/jamessessford/tailwindcss-ripple](tailwindcss-ripple)
follow the installation guide.
