### ISSUE TITLE
[Feature Request] `-w` and `-h` support

### ISSUE THREAD

**Issue by Knovour** [tailwindcss/tailwindcss#1146]
Something like

```
'-w-100': 'calc(100% -100px)' 
'-h-100': 'calc(100vh - 100px)'
```

**Comment by MarcelloTheArcane** [comment]
or in rem, like the rest of tailwind:

```
-w-4 = calc(100% - 1rem)
```

See https://tailwindcss.com/docs/width/#app for other sizes.

**Comment by adamwathan** [comment]
I wouldn't use that naming convention personally, as the negative prefix typically means "negative value" in Tailwind. I usually use names like `w-(screen-4)` for that sort of thing personally.

No plans to implement this one sorry.
