### ISSUE TITLE
[Feature Proposal] Enhanced box-shadow

### ISSUE THREAD

**Issue by leesmith** [tailwindcss/tailwindcss#1147]
I recently read about how to get smoother and sharper shadows with layered `box-shadow`s: https://tobiasahlin.com/blog/layered-smooth-box-shadows/

I know the current `box-shadow`s are using this technique to a small degree but I really like the look of this where you use gradually decreasing alpha with each layer...so much sharper I guess.

This is probably just personal taste but I like these results.

**Before:**
![Screen Shot 2019-10-03 at 12 31 35 PM](https://user-images.githubusercontent.com/90055/66152022-218e8700-e5de-11e9-8756-68cc9a3b7a89.png)

**After:**
![Screen Shot 2019-10-03 at 12 54 42 PM](https://user-images.githubusercontent.com/90055/66152032-281cfe80-e5de-11e9-8afd-a30bf7481835.png)

CSS:
```
.shadow {
  box-shadow: 0 1px 1px 0 rgba(0,0,0,.08), 0 2px 2px 0 rgba(0,0,0,.05);
}

.shadow-md {
  box-shadow: 0 1px 1px rgba(0,0,0,.1), 0 2px 2px rgba(0,0,0,.08), 0 3px 3px rgba(0,0,0,0.06);
}

.shadow-lg {
  box-shadow: 0 1px 1px rgba(0,0,0,0.1), 0 2px 2px rgba(0,0,0,0.09), 0 4px 4px rgba(0,0,0,0.08), 0 8px 8px rgba(0,0,0,0.07);
}

.shadow-xl {
  box-shadow: 0 1px 1px rgba(0,0,0,0.1), 0 2px 2px rgba(0,0,0,0.09), 0 4px 4px rgba(0,0,0,0.08), 0 8px 8px rgba(0,0,0,0.07), 0 16px 16px rgba(0,0,0,0.06);
}

.shadow-2xl {
  box-shadow: 0 1px 1px rgba(0,0,0,0.1), 0 2px 2px rgba(0,0,0,0.09), 0 4px 4px rgba(0,0,0,0.08), 0 8px 8px rgba(0,0,0,0.07), 0 16px 16px rgba(0,0,0,0.06), 0 32px 32px rgba(0,0,0,0.05);
}
```

**Comment by Eoghan-K** [comment]
I can have a look at this

**Comment by adamwathan** [comment]
Not planning to change this in core as it’s a breaking change, so this is the sort of thing you should use your config file for 👍🏻
