### ISSUE TITLE
[Feature Proposal]: Add 'extend' for `variants` in config.js like as did for `theme`

### ISSUE THREAD

**Issue by kunwei-kooboo** [tailwindcss/tailwindcss#1148]
>current
```
theme: {
   extend: {}
}
```
>expected
```
variants: {
   extend: {}
}
```

**Comment by hacknug** [comment]
The issue here is that order of those variants is important and extending the default values would probably cause issues with some of them.

**Comment by adamwathan** [comment]
Since the order of variants is so important, I'm not planning to add support for this any time soon as there's no good way to extend the defaults and also control the order.

**Comment by sebastiandedeyne** [comment]
Would you consider supporting functions in `variants`, similar to `theme`?

This way I wouldn't need to remember the default values whenever I want to modify the variants.

```js
variants: {
    borderWidth: variants => [...variants, 'first', 'last'],
}
```

**Comment by codex-zaydek** [comment]
I would also like to see this but I totally understand the concern with order. I was quite surprised to learn that order a variant is listed can _break_ those classes, but this is a limitation with CSS, not with Tailwind itself.

That being said, if anyone stumbles on this issue in the future, I think what you’re looking for, at least what I needed, was this: https://tailwindcss.com/docs/configuring-variants/#default-variants-reference

[**# Default variants reference**](https://tailwindcss.com/docs/configuring-variants/#default-variants-reference)
```js
// Default configuration
module.exports = {
  // ...
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: ['responsive'],
    clear: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    fill: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    gap: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover', 'focus'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: ['responsive', 'focus'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    rotate: ['responsive', 'hover', 'focus'],
    scale: ['responsive', 'hover', 'focus'],
    skew: ['responsive', 'hover', 'focus'],
    stroke: ['responsive'],
    strokeWidth: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive'],
    transform: ['responsive'],
    transformOrigin: ['responsive'],
    transitionDuration: ['responsive'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    translate: ['responsive', 'hover', 'focus'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    wordBreak: ['responsive'],
    zIndex: ['responsive'],
  }
}
```

**Comment by Landish** [comment]
Hey @adamwathan , what do you think about @sebastiandedeyne's solution above? 

I was going to create feature proposal about this topic with the same exact solution, but then i found this issue and your concerns. 

If it's possible to have the function version as well, without messing css variants order, that would be absolutely amazing.

**Comment by adamwathan** [comment]
Yeah I would be open to the function implementation definitely 👍🏻

**Comment by adamwathan** [comment]
Random idea so I don’t forget, we currently pass some utility functions along as the second argument when you use the function syntax. We could create some useful utilities for this situation that let you insert variants at a specific spot in the list, like (on phone so forgive formatting)...

backgroundColor: (variants, { before }) => before(‘hover’, [‘disabled’])

It could be a partially applied function that knows about the current key as suggested above, or we could keep it simple and require you pass the variants in as the first arg. Could do “after” as well.

**Comment by adamwathan** [comment]
I’ll probably build this tomorrow if someone doesn’t PR it sooner, kinda excited 😅

**Comment by Landish** [comment]
The main idea behind this feature is that to write less code (variants) and not to memorize the order or go to the docs every time we need to add new variant. 

So, for me personally this code is overkill for simply adding a `group` variant to selectors:
```
backgroundColor: (variants, { before }) => before(‘hover’, [‘disabled’])
```
rather than this:
```
backgroundColor: variants => [...variants, 'first', 'last']
```

So, I would stick to simpler solution.

But, if the `before` or `after` args will not be required, then I guess, I can live with that. 😄 

On the other hand, since Tailwind comes with purge option, and i'm pretty sure that everyone is purging in production, why not add all variants to all selectors? 😄 How much more MB it will add to CSS file in development mode? 10? 100? 😄

**Comment by Landish** [comment]
I just realized that at this moment we can achieve same result with the following code:

```js
const cloneDeep = require('lodash/cloneDeep');
const { variants } = cloneDeep(require('tailwindcss/stubs/defaultConfig.stub'));
// ...
variants: {
   textColor: [...variants.textColor, 'group-hover']
},
```
