### ISSUE TITLE
tailwind cli output is not valid css

### ISSUE THREAD

**Issue by kilbiller** [tailwindcss/tailwindcss#1163]
Hi,

When you use the tailwind CLI without the -o flag the output is sent to stdout but the text "Done in x.xxs." is added at the end.

I'm using tailwind 1.1.2.

**Comment by clanghout** [comment]
For me this seems to be working fine.. I installed tailwind cli with `npm -g` and run `tailwind build file.css` and see no additional text at the end. Interested in where your issue originates from.

**Comment by kilbiller** [comment]
My bad it's not tailwind, yarn is causing the issue. I just found out running another command.
Sorry for the inconvenience.
