### ISSUE TITLE
Borders not visible with disabled preflight

### ISSUE THREAD

**Issue by stedekay** [tailwindcss/tailwindcss#1167]
I try to use tailwind in an existing project and therefore I disable Preflight in my tailwind.config.js

```js
corePlugins: {
    preflight: false,
}
```

But then it seems that the border classes don't seem to work.
I don't know if it also affects other classes of tailwind, just started testing it in my project.

When I enable preflight, everything works fine.

Is this a known issue or did I maybe forgot something else?

**Comment by adamwathan** [comment]
Not an issue per se, making the border class work as expected is just one of the jobs of preflight.

https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally

If you disable preflight you need to use `border border-solid border-gray-300` to get the same result.

**Comment by stedekay** [comment]
Thanks! It seems I haven't read the documentation carefully.

**Comment by jasonday** [comment]
This solution does not work with individual borders such as "border-l-4", as a 1px border is applied to the entire element.

**Comment by adamwathan** [comment]
You'll have to use `border-0 border-l-4 border-solid border-gray-300` in that case. These sorts of ergonomic inefficiencies are the reason we reset how the browser does borders by default in Preflight in the first place 👍🏻

**Comment by jasonday** [comment]
Gotcha. Thanks @adamwathan.

One note: it might be helpful to have preflight configurable, so that the user can define what resets they want included.

**Comment by tinwritescode** [comment]
```css
*,
::before,
::after {
  border-width: 0;
  border-style: solid;
  border-color: theme('borderColor.DEFAULT', currentColor);
}
```

Adding the above code snippet at the start of your `global.css` file may work.

Reference: https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally
