### ISSUE TITLE
Purgecss removes styling from preflight

### ISSUE THREAD

**Issue by chaucerbao** [tailwindcss/tailwindcss#1169]
I believe this issue can be resolved by either:

* Configuring the `defaultExtractor` to account for HTML tags.
* [Whitelisting](https://github.com/FullHuman/purgecss-docs/blob/master/whitelisting.md) all the declarations in preflight with `// purgecss start ignore` and `// purgecss end ignore` or individually with `// purgecss ignore`.

**Comment by adamwathan** [comment]
This only happens if you have some HTML you’ve forgotten to tell Purge to scan. This is common in SPA frameworks where there’s an index.html file hidden in a different place in the project than all your components for example.

**Comment by chaucerbao** [comment]
That definitely makes sense. In my case, I was attempting to set it up with [Next.js](https://nextjs.org/).
