### ISSUE TITLE
last-child in laravel mix with PostCss not rendered?

### ISSUE THREAD

**Issue by DavydeVries** [tailwindcss/tailwindcss#1172]
I like to use `border-b last:border-b-0` but it's not working. If I take a look at the rendered tailwind.css file, no `last-child` selector has been generated.

Do I something wrong?

**My Webpack.mix.js:**
```
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss')

mix.js('resources/js/app.js', 'public/js');

mix.sass('resources/sass/tailwind.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [tailwindcss('./tailwind.config.js')],
    });

mix.version();
```

**My tailwind.scss:**
```
@import "tailwindcss/base";

@import "tailwindcss/components";

@import "tailwindcss/utilities";
```

**Full rendered tailwind.css:**
https://gist.github.com/DavydeVries/f0b95ab5bc09820b3005c6604c0ad58f

**Note:**
I use this class in a vue component, not sure if this is an issue?
```
<template>
    <div class="w-full border-b border-solid border-grey-300 last:border-b-0">
        {{message}}
    </div>
</template>
```

**Comment by adamwathan** [comment]
Make sure you enable the `last` variant in your `tailwind.config.js` file:

https://tailwindcss.com/docs/pseudo-class-variants#last-child

**Comment by DavydeVries** [comment]
I'm feeling so stupid right now I read that docs like 20 times today. And now I just seeing this:
<img width="690" alt="Schermafbeelding 2019-10-18 om 19 46 26" src="https://user-images.githubusercontent.com/7860305/67116077-fca23280-f1df-11e9-8652-92d5c4266d5f.png">
