### ISSUE TITLE
How to rename a core plugin?

### ISSUE THREAD

**Issue by SilentSword69** [tailwindcss/tailwindcss#1174]
I want to rename the border core plugin prefix to b.

Use it like this.
```
<div class='b-grey-500 b-solid hover:b-red-300'></div>
```

**Comment by adamwathan** [comment]
The simplest approach currently is to disable the core plugin and supply your own plugin that uses the class names you want. No plans to make it any more straightforward than this currently, as adding more configuration introduces a lot of complexity and writing your own replacement plugin is only a few lines of code 👍
