### ISSUE TITLE
Responsive classes not working on IE and Edge

### ISSUE THREAD

**Issue by aerni** [tailwindcss/tailwindcss#1176]
I've encountered the weirdest issue where some responsive classes starting with `xl:` are not working on IE and Edge. In my case `xl:w-1/2` is not being detected, though it's in the stylesheet. Other breakpoint classes like `lg:w-1/3` etc. are working without problems. And other classes with the breakpoint `xl:` like `xl:flex-row` are working too. I'm trying to debug this for hours now and have no clue why this responsive class is not picked up by IE and Edge.

Weird enough, if I add the class manually at the end of my stylesheet like this, it works.
```css
@media (min-width: 1280px) {
  .xl\:w-1\/2 {
    width: 50%;
  }
}
```

Does anyone have a clue about this? You can check out my website [michaelaerni.ch](https://www.michaelaerni.ch/en) for an example of the issue.

**Comment by benface** [comment]
@aerni How big is your CSS file? I've experienced a similar issue in the past, where IE/Edge would seemingly stop applying CSS after a certain amount of rules, but my stylesheet was over 10 MB (it was only for development, and PurgeCSS would bring it down to ~20 KB for production).

**Comment by tlgreg** [comment]
Yes, it is the file size or actually the number of rules, but the 10MB css file also not the best.
The theoretical max ruleset count of IE is 65534, this css file has more than 137 thousand rules by counting "{" characters (cssstats or chrome's css overview actually got stuck processing it).

**Comment by aerni** [comment]
Yes, you're right. I just run PurgeCSS and it's working now. Guess I have to test in IE/Edge with PurgeCSS on. Thanks a lot!
