### ISSUE TITLE
Use normalize inside Shadow Dom

### ISSUE THREAD

**Issue by marijnbent** [tailwindcss/tailwindcss#1177]
When using Tailwindcss inside a shadow dom object, the normalize css is not fully used as the root of a shadow dom object is not <html>. What would be the appropriate way to reset the css inside the shadow dom object?

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

**Comment by hacknug** [comment]
I think it does apply, no? Maybe there's some specificity issues arounf there?

I opened #1111 to fix a shadow-dom related issue a while ago and I don't remember doing anything special just to get it working.

**Comment by adamwathan** [comment]
Closing this unless someone can provide a concrete example of a problem.
