### ISSUE TITLE
[Feature Proposal] Alternative way to declare a plugin to optionally accept options

### ISSUE THREAD

**Issue by benface** [tailwindcss/tailwindcss#1178]
Right now, if a plugin accepts options (other than values that it pulls from the config/theme), instead of directly exporting the plugin function, it needs to export a function that takes options as an argument and returns the real plugin. Which means that even if you don't want to pass any options and just use the defaults, you still have to import the plugin with an extra set of parentheses, e.g.:

```js
plugins: [
  require('tailwindcss-transforms')(),
]
```

...instead of the simpler, nicer-looking, and [more consistent with Tailwind's documentation](https://tailwindcss.com/docs/configuration/#plugins):

```js
plugins: [
  require('tailwindcss-transforms'),
]
```

To make this possible, Adam [suggested](https://github.com/benface/tailwindcss-filters/issues/2#issuecomment-480781001) the following PostCSS-inspired syntax before:

```js
tailwindcss.plugin('filters', function (options) {
  return function ({ addUtilities }) {
    // ...
  }
})
```

> This would let us type check on the return value of `plugin` and know to just invoke the underlying function if no options were passed. Wouldn't be a breaking change either way.

**Comment by zefexdeveloper** [comment]
+1 for this

**Comment by adamwathan** [comment]
This is supported in `master` and will be in the next release (#1268)
