### ISSUE TITLE
Default placeholder color discrepancy

### ISSUE THREAD

**Issue by scottzirkel** [tailwindcss/tailwindcss#118]
The placeholder text for a textarea seems to be a different color from that of the inputs.

![screen shot 2017-11-06 at 11 02 45 am](https://user-images.githubusercontent.com/1329131/32453572-28f3eb78-c2e2-11e7-9be0-10e9a0efac50.png)

_Screenshot from Chrome Canary 64.0.3260.0_

**Comment by adamwathan** [comment]
Thanks, fixed!
