### ISSUE TITLE
Conflict when using Tailwindcss within the WordPress admin area

### ISSUE THREAD

**Issue by marijnbent** [tailwindcss/tailwindcss#1183]
The class names are in conflict with WordPress admin styles. What would be the way to still use tailwind? Could I add a prefix somewhere to use styles like this: myname-text-lg?

**Comment by adamwathan** [comment]
Yep you can prefix the selectors:

https://tailwindcss.com/docs/configuration/#prefix

(Just use the search at the top of the docs and type "prefix" and you'll find this.)
