### ISSUE TITLE
Some kind of problem after today's update

### ISSUE THREAD

**Issue by afuno** [tailwindcss/tailwindcss#1184]
I look towards `autoprefixer`. It has been updated. And in my project only you and `postcss-preset-env` use it. But the problem may be due to another package. 

The problem is shown in the screenshots below. I also attached two yarn.lock files - before and after the update.

---

### Before the update

[yarn.lock](https://pastebin.com/raw/Ey7BUerw)

<img width="200" alt="before" src="https://user-images.githubusercontent.com/2853419/67490286-ab7cbd80-f67b-11e9-9402-34aa78e48553.png">

### After the update

[yarn.lock](https://pastebin.com/raw/ZWNqBW34)

<img width="200" alt="after" src="https://user-images.githubusercontent.com/2853419/67490310-b33c6200-f67b-11e9-91df-0cc9c95b5697.png">

---

[Comparison of two yarn.lock files](https://www.diffchecker.com/4SZVwrcF)

---

It can be seen that some of the styles work.

And judging by what I noticed - styles with a colon symbol do not work:

```
xs:text-xl
```

The code is present in the .css file. But the inspector in the browser does not see these styles for the elements.

**Comment by adamwathan** [comment]
Weird! Can you share the fully compiled CSS file?

**Comment by afuno** [comment]
@adamwathan https://www.diffchecker.com/3UJTG567

_The project code for the two files is identical. Only the `yarn upgrade` command was executed._

**Comment by adamwathan** [comment]
Definitely a real problem, related to this:

https://github.com/postcss/postcss/issues/1304#issuecomment-545941419

Working on it now 👍

**Comment by adamwathan** [comment]
Fixed in PostCSS v7.0.20 👍🏻
