### ISSUE TITLE
Ability to opt in to containment at specific breakpoints

### ISSUE THREAD

**Issue by fakingfantastic** [tailwindcss/tailwindcss#1185]
Hi  👋,

I was recently working with a colleague and they wanted the ability to use `.container`, but they wanted it to only start being contained at the `lg:`.

Naturally, I recommended them to add `lg:container`, but it didn't work. I looked through the compiled CSS and saw the selector wasn't in there.

So, a couple questions...
1. Can this be accomplished natively, or can I update the config to give me the utility?
2. Is this a good candidate for a feature request? I'd be happy to take a swing at it.

Let me know, thanks

**Comment by tlgreg** [comment]
`container` is a component so you can't use variants on it, also it is responsive by itself.

If you would only use the container for specific screen sizes you can customize the screens for just the container. It's actually not documented, but you can specify a `screens` key in its config.
Eg.:
```js
const pick = require('lodash.pick')
module.exports = {
  theme: {
    container: {
      screens: {
        lg: '1024px',
        xl: '1280px',
      },
    },
  },
}
```

If you need more then one type of container, for example at one place restrict to specific screens and others use all... You'll have to create your own component or utilities. With css or as a tailwindcss plugin.

An alternative, simple way is to just use `max-width` for the job as thats the main (and by default only) job of the `container`. The screen sizes are not included in the `maxWidth` config by default, but you could add them. Below config would create `max-w-screen-*` utilities and then you could use the `lg:max-w-screen-lg` class, it's not pretty, but declarative. :)
```js
const mapKeys = require('lodash.mapkeys')
module.exports = {
  theme: {
    extend: {
      maxWidth: theme => mapKeys(theme('screens', {}), (v, key) => `screen-${key}`),
    },
  },
}
```

**Comment by adamwathan** [comment]
Yeah I would recommend the `max-width` approach @tlgreg suggested, I use that a lot in my own projects 👍 I'm going to add the screen sizes to the max-width config by default in a future release to make this easier.

**Comment by phegman** [comment]
A little more verbose but here is how I did it w/out lodash

```javascript
maxWidth: theme => ({
    xs: "20rem",
    sm: "24rem",
    md: "28rem",
    lg: "32rem",
    xl: "36rem",
    "2xl": "42rem",
    "3xl": "48rem",
    "4xl": "56rem",
    "5xl": "64rem",
    "6xl": "72rem",
    full: "100%",
    ...Object.keys(theme("screens")).reduce((accumulator, key) => {
    accumulator[`screen-${key}`] = theme("screens")[key];

    return accumulator;
    }, {}),
}),
```
