### ISSUE TITLE
ResolveConfig Theme object mismatch

### ISSUE THREAD

**Issue by cizza** [tailwindcss/tailwindcss#1188]
Hello,

I've noticed a bit of a mismatch in the ResolveConfig.theme object. What I mean is this:

For example backgroundColor object resolves to:

`backgroundColor {
black: "#000000"
}`

however, the backgroundPosition object resolves to: 
`backgroundPosition {
bottom: "bottom",
center: "center",
left: "left",
left-bottom: "left bottom"
}`

Where in a case of a color, I would say the object is correctly built as a key - value pairs, the backgroundPosition object is built as a value - key  pair. 

Does it make any sense? 

It does create a bit of a problem for me, nothing unsolvable, but it would be nice to have a uniform approach to the object. 

Thanks,

**Comment by adamwathan** [comment]
Sorry not totally sure I understand, those look consistent to me? Can you show me a specific scenario with expected output and what you get now?

**Comment by adamwathan** [comment]
Just reading this again, they are both key-value. The keys are the suffixes used for the class names and the values are the value of the associated CSS property.

The object `{ black: '#000000' }` created `bg-black` and the object `{ 'left-bottom': 'left bottom' }` generates `bg-left-bottom`, so they are consistent. The framework wouldn't work if they weren't 😄 

You can see the whole object here:

https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js

**Comment by cizza** [comment]
Hi Adam, 

thank you for your reply. I get it and maybe the word "consistent" was a little bit misleading in what I was aiming at, however, looking at the source code I see, that I was wrong.
