### ISSUE TITLE
Can't generate hover variant for fill

### ISSUE THREAD

**Issue by justinekizhak** [tailwindcss/tailwindcss#1189]
I'm trying to generate hover and focus variants of my main color but I looked through my `global.css` where all the tailwind classes are generated and its not there. But I found responsive variants for my main color.

This is my `tailwind.config.js`
```js
module.exports = {
    theme: {
        extend: {
            colors: {
                main: "#B562E7",
            },
            fill: theme => ({
                'theme': theme('colors.'),
            })
        },
        variants: {
            fill: ['responsive', 'hover', 'focus']
        },
        plugins: []
    }
}

```

**Comment by adamwathan** [comment]
You have a typo in `theme('colors.')`, and the object shape for `fill` is wrong, it doesn't need a `theme` key, just spread in the colors:

```js
module.exports = {
    theme: {
        extend: {
            colors: {
                main: "#B562E7",
            },
            fill: theme => ({
                ...theme('colors'),
            })
        },
        variants: {
            fill: ['responsive', 'hover', 'focus']
        },
        plugins: []
    }
}
```

Here's a working example:

https://tailwind.run/U2P3pm

**Comment by justinekizhak** [comment]
Thanks. Sorry about that typo😅. I copied from the docs and did a sloppy job editing it.

**Comment by justinekizhak** [comment]
@adamwathan. Sorry if I'm bothering. This time I tried with the config you posted the hover variant is still not working.

The config I used
```js
module.exports = {
    theme: {
        extend: {
            colors: {
                main: "#B562E7",
            },
            fill: theme => ({
                ...theme('colors'),
            })
        },
        variants: {
            fill: ['responsive', 'hover', 'focus']
        },
        plugins: []
    }
}
```
and I was expecting this to work
```html
<svg viewBox="0 0 100 100" class="h-10 w-10 fill-red-500 hover:fill-green-500">
  <polygon points="0,0 0,100 100,100 100,0"/>
</svg>
```
Here is the link https://tailwind.run/U2P3pm/3

But I figured a workaround. Added this to the `tailwind.css`
```css
@variants focus, hover {
  .fill-green-custom {
    @apply fill-green-500;
  }
}  
```
and my new html looks like this
```html
<svg viewBox="0 0 100 100" class="h-10 w-10 fill-red-500 hover:fill-green-custom">
  <polygon points="0,0 0,100 100,100 100,0"/>
</svg>
```
Both the workaround and my expected way to do is posted on the link. Maybe I did something wrong.

**Comment by adamwathan** [comment]
Ah my mistake, variants and plugins should be one level higher, not nested under theme.

**Comment by justinekizhak** [comment]
Thanks

**Comment by vesper8** [comment]
@adamwathan any plans to add colors to fill by default? So that we can do things like `fill-current hover:fill-red-500` or what about `fill-opacity` ?

Now that we're using SVG icons more and more.. feels like this should be part of the core

**Comment by adamwathan** [comment]
@vesper8 Can you not just do this?

```html
<svg class="fill-current text-red-600 hover:text-red-500 text-opacity-50">...</svg>
```

**Comment by vesper8** [comment]
@adamwathan oh yea... weird.. I thought I tried something like that and it wasn't working.. but yea.. now that I try it again.. it's working fine.. my bad
