### ISSUE TITLE
[Feature Proposal] - Nested Group Hover

### ISSUE THREAD

**Issue by Ratko-Solaja** [tailwindcss/tailwindcss#1192]
**Hi,**

When creating nav dropdown, I usually just add `group` class to my `<li>` element, and then to my `<ul>` that is child of that `<li>` I add something like `opacity-0 invisible backface-invisible group-hover:opacity-100 group-hover:visible group-hover:backface-visible`. Which works fine, but then if my dropdown will have another dropdown, this won't work.

It would be awesome if we could have nested group hover. :)

**Comment by royvanv** [comment]
It is possible if you change the `group-hover` selector to a direct child selector and the right HTML structure.

```css
.group:hover > .group-hover\:visible {
    visibility: visible;
}
```

```html
<div class="group">
    <div>Parent</div>
    <div class="invisible group-hover:visible">
        <div class="group">
            <div>Child</div>
            <div class="invisible group-hover:visible">Grandchild</div>
        </div>
    </div>
</div>
```

There must a better way to handle nested group hovers!

**Comment by tlgreg** [comment]
Related conversation: https://github.com/tailwindcss/discuss/issues/337

**Comment by adamwathan** [comment]
I would recommend solving this problem with a [custom variant plugin](https://tailwindcss.com/docs/plugins/#adding-variants) for now, and maybe we can explore adding something to core in the future.

Something like this plugin would generate `group-2-hover` and `group-3-hover` variants that you could use to sort of "name" the nested groups and avoid collisions:

```js
const selectorParser = require('postcss-selector-parser')

module.exports = function ({ addVariant }) {
  addVariant('group-2-hover', ({ modifySelectors, separator }) => {
    return modifySelectors(({ selector }) => {
      return selectorParser(selectors => {
        selectors.walkClasses(sel => {
          sel.value = `group-2-hover${separator}${sel.value}`
          sel.parent.insertBefore(sel, selectorParser().astSync(prefixSelector(config.prefix, '.group-2:hover '))
          )
        })
      }).processSync(selector)
    })
  })

  addVariant('group-3-hover', ({ modifySelectors, separator }) => {
    return modifySelectors(({ selector }) => {
      return selectorParser(selectors => {
        selectors.walkClasses(sel => {
          sel.value = `group-3-hover${separator}${sel.value}`
          sel.parent.insertBefore(sel, selectorParser().astSync(prefixSelector(config.prefix, '.group-3:hover '))
          )
        })
      }).processSync(selector)
    })
  })
}
```

**Comment by christopher4lis** [comment]
Any chance there's an up-to-date version of the plugin above? Just tried it out with tailwindcss v1.4.6 and don't seem to be having any luck.

**Comment by ErickTamayo** [comment]
@christopher4lis I created a small plugin to be able to have what I call "named groups" that is similar to what @adamwathan does here.

You can take a look it here: https://github.com/ErickTamayo/tailwindcss-named-groups

**Comment by AndyOGo** [comment]
I have the same problem with nested groups, they aren't properly scoped.

CSS [`:not()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) helps to scope it.

```css
.group:hover > .group-hover {}
.group:hover :not(.group) .group-hover {}

.group:focus > .group-focus {}
.group:focus :not(.group) .group-focus {}
```

**Comment by AndyOGo** [comment]
@adamwathan 
I just released [`tailwindcss-nested-groups`](https://github.com/AndyOGo/tailwindcss-nested-groups) which scopes the groups as in my above comment.

**Comment by AndyOGo** [comment]
I released support for nested groups by scoping https://github.com/AndyOGo/tailwindcss-nested-groups

**Comment by pdevito3** [comment]
@adamwathan @simonswiss any more recent thoughts on this? would be cool if group was scoped by default or if we had a way to name them. not sure if that's built into JIT?

**Comment by LeaHabel** [comment]
@AndyOGo thanks for your plugin! Really love it :) Unfortunatly it doesn't work with the latest tailwind/postcss version. Any plans to update it?

**Comment by AndyOGo** [comment]
@LeaHabel 
Thank you.
I would need more data and ideally a reprodution repo.

Anyway, just in case you have JIT enabled?
The thing is JIT broke many things and tailwind still has some JIT related issues.
https://github.com/tailwindlabs/tailwindcss/issues?q=is%3Aissue+is%3Aopen+jit

**Comment by klausXR** [comment]
@adamwathan can you perhaps look into this after the JIT implementation? It would be very convenient to generate these at runtime. That plugin works, but they must be manually configured.

**Comment by yoobi** [comment]
> I would recommend solving this problem with a [custom variant plugin](https://tailwindcss.com/docs/plugins/#adding-variants) for now, and maybe we can explore adding something to core in the future.
> 
> Something like this plugin would generate `group-2-hover` and `group-3-hover` variants that you could use to sort of "name" the nested groups and avoid collisions:
> 
> ```js
> const selectorParser = require('postcss-selector-parser')
> 
> module.exports = function ({ addVariant }) {
>   addVariant('group-2-hover', ({ modifySelectors, separator }) => {
>     return modifySelectors(({ selector }) => {
>       return selectorParser(selectors => {
>         selectors.walkClasses(sel => {
>           sel.value = `group-2-hover${separator}${sel.value}`
>           sel.parent.insertBefore(sel, selectorParser().astSync(prefixSelector(config.prefix, '.group-2:hover '))
>           )
>         })
>       }).processSync(selector)
>     })
>   })
> 
>   addVariant('group-3-hover', ({ modifySelectors, separator }) => {
>     return modifySelectors(({ selector }) => {
>       return selectorParser(selectors => {
>         selectors.walkClasses(sel => {
>           sel.value = `group-3-hover${separator}${sel.value}`
>           sel.parent.insertBefore(sel, selectorParser().astSync(prefixSelector(config.prefix, '.group-3:hover '))
>           )
>         })
>       }).processSync(selector)
>     })
>   })
> }
> ```

Hello, I'm rather new to that and I've tried your code with v2.2.19 but it doesn't work, `prefixSelector` and `config` is an unknown function. Below is my file

```
// tailwind.config.js
const { selectorParser } = require('postcss-selector-parser');
const plugin = require('tailwindcss');
const { colors } = require('./styles/theme/beta/color');

// https://tailwindcss.com/docs/adding-new-utilities
module.exports = {
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontSize: {
        xs: '.70rem',
      },
      colors: {
        ...colors,
      },
      ...
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
      plugin(
          ({ addVariant }) => {
            addVariant('group-2-hover', ({
                                           modifySelectors,
                                           separator,
                                         }) => modifySelectors(({ selector }) => selectorParser((selectors) => {
                  selectors.walkClasses((sel) => {
                    sel.value = `group-2-hover${separator}${sel.value}`;
                    sel.parent.insertBefore(sel, selectorParser()
                        .astSync(prefixSelector(config.prefix, '.group-2:hover ')));
                  });
                })
                    .processSync(selector)));
          },
      ),
  ],
};
```

**Comment by tonioriol** [comment]
@yoobi couldn't make @adamwathan example work either. 

@AndyOGo plugin doesnt work for me either.

The one that worked for me is https://github.com/ErickTamayo/tailwindcss-named-groups from @ErickTamayo, thanks man :)

**Comment by maelquerre** [comment]
By looking in the source code of Tailwind CSS, I found a very concise way to add the named groups feature in the config, rather than installing a package. It works well (v3.0.13), not sure it's something safe to use in production though.
```js
const plugin = require('tailwindcss/plugin')

module.exports = {
  theme: {
    groups: ['example']
  },
  plugins: [
    plugin(({ addVariant, theme }) => {
      const groups = theme('groups') || []

      groups.forEach((group) => {
        addVariant(`group-${group}-hover`, () => {
          return `:merge(.group-${group}):hover &`
        })
      })
    })
  ]
}
```

**Comment by leo** [comment]
Thanks for the suggestion above, @maelquerre! 👏  It works quite well.

I think that, at the moment, that's really the cleanest way to do it.

In fact, I liked it so much that I extended it a bit and bundled it into a [tailwind-custom-groups](https://github.com/leo/tailwindcss-custom-groups) package, in case anyone wants to install it quickly (like me).

**Comment by AndyOGo** [comment]
@maelquerre 
Thanks for sharing.
What is the `:merge` doing exactly?

**Comment by anankitpatil** [comment]
> ```js
> plugin(({ addVariant, theme }) => {
>       const groups = theme('groups') || []
> 
>       groups.forEach((group) => {
>         addVariant(`group-${group}-hover`, () => {
>           return `:merge(.group-${group}):hover &`
>         })
>       })
>     })
> ```

This is not working for me... 2.1.3

theme: {
    groups: ['ved'],.....

plugins: [
    require('@tailwindcss/forms'),
    require('tailwindcss-truncate-multiline')(),
    plugin(({ addVariant, theme }) => {
      const groups = theme('groups') || [];
      groups.forEach((group) => {
        addVariant(`group-${group}-hover`, () => {
          return `:merge(.group-${group}):hover &`;
        });
      });
    }),
  ],


Am i doing something wrong?

**Comment by PortStone** [comment]
> 

I am using version `3.0.23` and it works.
If you have something like  `groups: ["example"]` you can use it like this:

``` html
<div class="group-example">
    <button>Dropdown</button>
    <div class="absolute hidden group-example-hover:block">
        <p>Content</p>
    </div>
</div>
```

**Comment by onmax** [comment]
You can also use [`tailwindcss-labeled-groups`](https://github.com/onmax/tailwindcss-labeled-groups) 😄

**Comment by moinulmoin** [comment]
> Thanks for the suggestion above, @maelquerre! 👏 It works quite well.
> 
> I think that, at the moment, that's really the cleanest way to do it.
> 
> In fact, I liked it so much that I extended it a bit and bundled it into a [tailwind-custom-groups](https://github.com/leo/tailwindcss-custom-groups) package, in case anyone wants to install it quickly (like me).

I am using it. Works well!

**Comment by boompikachu** [comment]
With TailwindCSS v3.1, we can use arbitrary variant to create nested group
```html
<div class="group">
  <div>Parent</div>
  <div class="invisible group-hover:visible">
    <div class="group-2">
      <div>Child</div>
      <div class="invisible [.group-2:hover_&]:visible">Grandchild</div>
    </div>
  </div>
</div>
```
Here's the playground https://play.tailwindcss.com/wYJHX4z5fi

**Comment by leo** [comment]
Thanks for sharing, @boompikachu! That's an interesting approach.

It seems to rely on the newly added [Arbitrary Variants](https://tailwindcss.com/blog/tailwindcss-v3-1#arbitrary-values-but-for-variants) feature, though, which means the code now contains an arbitrarily defined class name.

That's a first-class citizen feature of Tailwind CSS, so I think it's **totally fine to use**.

In our case, however, we're using the `tailwindcss/no-arbitrary-value` ESLint rule provided by [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) to prevent any arbitrary class names in our code, because we find it to be cleaner. Like this, all the possible class names are visible in and controlled from a single place: The Tailwind CSS config. Like that, it's impossible that someone could accidentally make the layout quite complex by adding lots of arbitrary classes that deviate from the main styling system.

Because of that, we'll continue maintaining and using [tailwindcss-custom-groups](https://github.com/leo/tailwindcss-custom-groups).

Thanks for the tip, though!

**Comment by ahjam-taoufik** [comment]
> You can also use [`tailwindcss-labeled-groups`](https://github.com/onmax/tailwindcss-labeled-groups) 😄

very nice solution ; it work

**Comment by otanim** [comment]
The issue seems to have existed in v3.1.8 but has been fixed in v3.2.4.

**Comment by nelisbijl** [comment]
> With TailwindCSS v3.1, we can use arbitrary variant to create nested group
> 
> ```
> <div class="group">
>   <div>Parent</div>
>   <div class="invisible group-hover:visible">
>     <div class="group-2">
>       <div>Child</div>
>       <div class="invisible [.group-2:hover_&]:visible">Grandchild</div>
>     </div>
>   </div>
> </div>
> ```
> 
> Here's the playground https://play.tailwindcss.com/wYJHX4z5fi

I had success with using [.group:hover_>_&]:bg-g-400 in Tailwind 3; only for direct childs!
It is useful for dynamic nesting where you do not know the nesting level
And even if you do, processing :class="{[`[group-${level}:hover_&]:visible`]: condition}" (vue) didn't work well

**Comment by royvanv** [comment]
> And even if you do, processing :class="{[`[group-${level}:hover_&]:visible`]: condition}" (vue) didn't work well

That's because Tailwind can't match the class when purging. See [Dynamic class names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names) for more information about class matching.

You have a few options:
1. Map `level` to a class within the controller (I'm not familiar enough with Vue to provide a complete example, but something like `{ 'name': '[group-name:hover_&]:visible' }` should work).
2. [Safelisting the classes](https://tailwindcss.com/docs/content-configuration#safelisting-classes) in your config. 
3. And the hardest option: building a [custom extractor](https://tailwindcss.com/docs/content-configuration#customizing-extraction-logic)
