### ISSUE TITLE
Form fields zoom on focus

### ISSUE THREAD

**Issue by nam-co** [tailwindcss/tailwindcss#1193]
Hi Adam, first of all, I thank you two for the excellent work on tailwind.
I notice on mobile/safari when you focus on a field the browser zooms in a little and extends the width of the page, please see the images of tailwind and B4. I wonder if there's a way to disable this

Appreciate any help,
Regards

![IMG_2802](https://user-images.githubusercontent.com/3951529/67644919-619e0c80-f8f3-11e9-8306-6e89d3f26c2f.PNG)

![IMG_2801](https://user-images.githubusercontent.com/3951529/67644922-64006680-f8f3-11e9-985d-c0466d1500cd.PNG)

![IMG_2800](https://user-images.githubusercontent.com/3951529/67644924-65ca2a00-f8f3-11e9-8adf-5b891d9a9b14.PNG)

**Comment by hacknug** [comment]
That's expected behaviour. Safari Mobile (and other mobile browsers) zoom in when focusing inputs with a `font-size` smaller than 16px.

Take a look at [this tweet](https://twitter.com/hack_nug/status/1187164868786434049?s=20) where I mentioned how to prevent this behavior the other day. Please make sure to read @lucalanca's comments regarding accessibility before you use it on production sites.

Also not an issue with Tailwind's core, better suited for [docs](https://github.com/tailwindcss/docs) or [discuss](https://github.com/tailwindcss/discuss).

**Comment by adamwathan** [comment]
Yep default browser behavior, if you don't want it to zoom use a font size of at least 16px in your own form fields 👍

**Comment by SachithNagesh** [comment]
I had the same issue, adding this meta tag solved it just like the tweet @hacknug suggested.

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover"></meta> 

Hope it helps someone.

**Comment by SachithNagesh** [comment]
I had the same issue, solved it by using the solution in the tweet @hacknug suggested.

`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover"></meta>`

Hope it helps someone.

**Comment by pierrebaronqumu** [comment]
@SachithNagesh That solution is quite bad for accessibility though. Some people do need to zoom in due to low vision.

**Comment by hashirshoaeb** [comment]
For nextjs >=14

```
export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
  maximumScale: 1,
  viewportFit: 'cover',
};
```
Link to documentation https://nextjs.org/docs/app/api-reference/functions/generate-viewport

**Comment by Darpan-favfly** [comment]
> For nextjs >=14
> 
> ```
> export const viewport: Viewport = {
>   initialScale: 1,
>   width: 'device-width',
>   maximumScale: 1,
>   viewportFit: 'cover',
> };
> ```
> 
> Link to documentation https://nextjs.org/docs/app/api-reference/functions/generate-viewport

this is really helpful, working🥳🥳

**Comment by dunkman32** [comment]
`export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
`

-  this worked for me... @Darpan-favfly tnx
