### ISSUE TITLE
Naming for @screen

### ISSUE THREAD

**Issue by psren** [tailwindcss/tailwindcss#12]
Naming is a bit weird here, if you add print-styles like mentioned in https://tailwindcss.com/docs/responsive-design/#print-screens combined with the ```@screen``` directive.
https://tailwindcss.com/docs/functions-and-directives#screen

This would result in ```@screen print``` which is weird.
I have no better name, maybe ```@named-media print``` or something like that?

Or is there a better way already baked in?

This is just a minor quirks in a great framework.
Wenn done, well done!

**Comment by reinink** [comment]
Fair point! We struggled a little to find the most appropriate name here. Originally it was `@breakpoint`, but then we realized this feature could really be used with any media query. Obviously `@media` is already used, so we came up with `@screen` instead. Now I get that "print" isn't exactly a screen, but I think it still works. In fact, printing is often used for generating PDFs, not burning toner onto paper. More than that, "print" is sort of the anomaly here, so I don't think it's wise to make this declaration more complicated just for it.
