### ISSUE TITLE
Reference theme.extend.x in Javascript

### ISSUE THREAD

**Issue by bradley-varol** [tailwindcss/tailwindcss#1201]
I've scoured the internet for how to do the following, with no luck:

*tailwind.config.js:*
```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    theme: {
        extend: {
            colors: {
                primary: defaultTheme.colors.purple,
            },
        },
    },
    variants: {},
    plugins: [],
};
```
*vue compoennt:*
```js
<script>
import resolveConfig from 'tailwindcss/resolveConfig';
const { theme } = resolveConfig('@/tailwind.config.js');

console.log(theme.extend.colors.primary[500]); // TypeError: "theme.extend is undefined"
</script>
```

Is it possible to access the extended theme from Javascript?
Awesome library, Adam. Thanks.

**Comment by tlgreg** [comment]
The resolved config doesn't have `extend` anymore, your values are merged in at that point, in the above example you have `theme.colors.primary`

**Comment by bradley-varol** [comment]
Thanks for a speedy response, @tlgreg , but `theme.colors.primary` is `undefined`.

**Comment by adamwathan** [comment]
`resolveConfig` expects a config _object_ to resolve, not a path:

```js
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../tailwind.config.js';
const { theme } = resolveConfig(tailwindConfig);
```

**Comment by bradley-varol** [comment]
Having changed to the code from the docs, I'm now presented with
`"export 'default' (imported as 'tailwindConfig') was not found in '@/tailwind.config.js'`
followed by
`TypeError: ""exports" is read-only"`.

**Comment by bradley-varol** [comment]
I've changed my imports to be like the docs and I'm getting the following error during compilation:

```
./components/HelloWorld.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/HelloWorld.vue?vue&type=script&lang=js&) 46:35-49
"export 'default' (imported as 'tailwindConfig') was not found in '@/tailwind.config.js' vendors.app.js:2885:15
TypeError: ""exports" is read-only"
```

**Comment by bradley-varol** [comment]
Adding `sourceType: 'unambiguous'` to my Babel config fixed this by allowing me to `import` a `module.exports`.

Thanks for your time, Adam.
