### ISSUE TITLE
hover: utility class for border width

### ISSUE THREAD

**Issue by ericbiewener** [tailwindcss/tailwindcss#1202]
It appears that hover classes for border width (eg `hover:border-2`) do not exist. Could these be added, or is this intentional?

**Comment by adamwathan** [comment]
Enabling other variants for each utility is explained in the docs:

https://tailwindcss.com/docs/border-width#responsive-and-pseudo-class-variants

You likely don’t actually want to change border width on hover though as it will cause your entire layout to shift. Better to have a border there the entire time and give it border-transparent hover:border-gray-300 for example so the size of the element doesn’t change.
