### ISSUE TITLE
[Feature Proposal] hw- for square size

### ISSUE THREAD

**Issue by jung-hunsoo** [tailwindcss/tailwindcss#1208]
While I've been so happy with Tailwind CSS, I found that square sizing is often used; e.g. `h-4 w-4` or `h-6 w-6`.

In my codes, almost every icons are wrapped like this.

So, how about providing a shorthand CSS or expression for these cases? `hw-4` instead of `h-4 w-4`.

**Comment by benface** [comment]
Hey @jung-hunsoo, this idea was suggested previously (https://github.com/tailwindcss/tailwindcss/issues/535), and Adam expressed interest in adding it. In the meantime, you can use [this plugin](https://github.com/ky-is/tailwindcss-plugin-width-height).

**Comment by jung-hunsoo** [comment]
Thanks @benface! Though it'd be a useful feature (and plug-in, too), I wouldn't introduce another plugin only for a minor advantage.
