### ISSUE TITLE
Support to pseudo-class :active

### ISSUE THREAD

**Issue by bruno02221** [tailwindcss/tailwindcss#121]
I propose a feature for handling "active" states as we already have for "hover" states.

This feature would allow a full interactive state for components like buttons:

```html
<button class="bg-blue hover:bg-blue-dark active:bg-blue-darker text-white p-4">
```

**Comment by reinink** [comment]
Yes for sure, we are planning on adding `active` and `focus` helpers in addition to `responsive` and `hover`. The challenge right now is keeping the CSS file size at a reasonable size, as adding all of these states to all the utilities would get quite large.

We're working on a system where you can enable or disable the responsive, active, focus and hover states on a per module basis.

**Comment by adamwathan** [comment]
Consolidate into #136.
