### ISSUE TITLE
Doesn't work well with SweetAlert2 npm package

### ISSUE THREAD

**Issue by Rajan** [tailwindcss/tailwindcss#1211]
SweetAlert2 is one of the top npm packages.

**Comment by Rajan** [comment]
It is visible on the bottem left corner.
<img width="1792" alt="Screenshot 2019-11-07 at 9 52 45 PM" src="https://user-images.githubusercontent.com/60307/68407099-fed92a80-01a8-11ea-87a2-9c722cbdb873.png">

**Comment by devcircus** [comment]
Works fine in an inertia project for me. Looks like your swal css isn't getting included correctly.

**Comment by Rajan** [comment]
Fixed by importing minified js and css separately.
