### ISSUE TITLE
Error when adding 'first' or 'last' variant

### ISSUE THREAD

**Issue by Jesus82** [tailwindcss/tailwindcss#1213]
Updated  from 0.6.1 to the latest version. Everything works fine, but when I try to add 'first' or 'last' class [as stated in the docs](https://tailwindcss.com/docs/pseudo-class-variants/#first-child):

    variants: {
         margin: ['responsive','first']
    }

It gives me an error

`TypeError: variantGenerators[variant] is not a function`

Any clues of what can be going wrong?

Thanks in advance!

**Comment by adamwathan** [comment]
Just tested this locally and seems to work, can you push a reproduction to GitHub? Or at least share your yarn.lock/package-lock.json file.

**Comment by Jesus82** [comment]
Hi, I am running it for storybook and under. So basically I cloned this repo https://github.com/mstrlaw/nuxt-storybook, did an npm update and the set tailwind to their latest version and followed the update guide.

Here's my package.json

```
{
  "name": "nuxt-storybook",
  "version": "1.0.0",
  "description": "Example of using Nuxt + Storybook",
  "author": "Lawrence Braun",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint",
    "storybook": "start-storybook -p 6060",
    "build-storybook": "build-storybook -c .storybook"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.8.0",
    "@nuxtjs/dotenv": "^1.4.1",
    "date-fns": "^2.0.0-beta.5",
    "nuxt": "^2.10.2",
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/vue": "^5.2.5",
    "autoprefixer": "^8.6.4",
    "babel-eslint": "^8.2.1",
    "babel-preset-vue": "^2.0.2",
    "cross-env": "^5.2.1",
    "eslint": "^5.0.1",
    "eslint-loader": "^2.2.1",
    "eslint-plugin-vue": "^4.0.0",
    "node-sass": "^4.13.0",
    "nuxt-svg-loader": "^1.0.1",
    "sass-loader": "^7.3.1",
    "tailwindcss": "^1.0.6",
    "webpack": "^4.41.2"
  }
}
```

**Comment by adamwathan** [comment]
Just went through those steps and it works as expected:

https://github.com/adamwathan/nuxt-storybook/commit/53cff8dcc40986aa17f020caa1065a2ed61a1f91

**Comment by vmitchell85** [comment]
In case anyone else finds this issue I solved it doing the following:

1. Ensuring Tailwind was updated to latest (1.2.0)
2. Deleting `node_modules` folder
3. Running `npm install`
4. Running `npm run dev`

**Comment by Nases** [comment]
Here is what I did,
1. Delete node_modules & package-lock.json
2. npm install -g npm-check-updates
3. ncu -u
4. npm update
5. npm install

And you are good to go!

**Comment by austriker27** [comment]
Thanks @Nases ! I had this issue on netlify and your post saved me.
