### ISSUE TITLE
prefix doesn't apply to group-hover

### ISSUE THREAD

**Issue by Mo7sin** [tailwindcss/tailwindcss#1215]
Hi,

I'm using a custom prefix `'tw-'` and i noticed that `group-hover`'s `group` class which should be `tw-group` in my case was generated as just `group` without prefix.

Is that intentional or is it a bug? I'm not sure.

tailwind version: 1.1.2

Thank you.

**Comment by adamwathan** [comment]
Bug for sure, thanks for reporting will try and get a fix out tomorrow.

**Comment by adamwathan** [comment]
This is fixed in the latest release 👍
