### ISSUE TITLE
Pixel offset in centered grid with percentage width (i.e. w-1/3) 

### ISSUE THREAD

**Issue by dsturm** [tailwindcss/tailwindcss#1223]
Hej,

I'm currently facing a problem, where children (w-1/3) in a centered flex element do not have the full width and result in a slight pixel offset over full width (w-100). It seems to appear only in Chrome (tested in 78.0.3904.97) and should not be Tailwind specific.

I created a little example: https://codepen.io/dcsturm/full/rNNZXQE

Though, any thoughts on how to fix this behaviour?

Regards,
Daniel

**Comment by hacknug** [comment]
I see the size difference but increasing the amount of decimals or using `    width: calc(100% / 3);` doesn't seem to fix it.

100% _unrelated_ to Tailwind and probably a better fit for [`/discuss`](https://github.com/tailwindcss/discuss) 👍

**Comment by dsturm** [comment]
@hacknug Yep, sure no Tailwind specific bug.
