### ISSUE TITLE
Error: Couldn’t find Tailwind screen: last

### ISSUE THREAD

**Issue by tranthaison1231** [tailwindcss/tailwindcss#1225]
I added prefix last-child in my project but it's have error 

```
StyledNavbar.Link = styled(Link)`
  ${tw`no-underline text-green-400 active:text-purple-600 last:text-purple-600`}
`;
```

tailwind.config.js

```
 variants: {
    textColor: ['responsive', 'hover', 'last'],
  },
```

**Comment by hacknug** [comment]
That's not a Tailwind issue. It is probably due to tailwind.macro being out of date and not maintained anymore.

**Comment by tranthaison1231** [comment]
@hacknug Do you have suggest for using tailwind , style component together?

**Comment by hacknug** [comment]
There's a few starters listed [in this repo](https://github.com/aniftyco/awesome-tailwindcss#starters-templates--themes) that might help you. if none of those work for you, try asking on Discord. There's probably someone who will be able to help you with that :+1:

**Comment by hacknug** [comment]
Just saw this on a couple other issues. Maybe they'll be helpful:
- https://github.com/aedificatorum/cra-tailwind-emotion-starter
- https://github.com/talensjr/gatsby-theme-tailwindcss/blob/master/theme/README.md

**Comment by adamwathan** [comment]
Yeah this is better suited for the tailwind.macro project, sorry 😞
