### ISSUE TITLE
Word-wrap and overflow-wrap

### ISSUE THREAD

**Issue by nicooprat** [tailwindcss/tailwindcss#1229]
Hi there,

I don't understand why `overflow-wrap` has been chosen instead of `word-wrap` for the `break-word` utility class. Here's a example of the two properties being used:

https://codepen.io/nicooprat/pen/xxxMEQy?editors=1000

![image](https://user-images.githubusercontent.com/645641/69140009-f266a300-0ac1-11ea-9d7b-bb80a36126d8.png)

This change comes from https://github.com/tailwindcss/tailwindcss/pull/681. 

Actually `overflow-wrap` only breaks lines between words, and `word-break: break-word;` does the same, but forces line break within words if necessary, so it's two different uses ; but I'm not sure the first one is really needed. At least, we could have one more utility class for the latter named `break-words-force` for example.

What do you think? Thanks.

**Comment by adamwathan** [comment]
`word-break: break-word` is not supported by Edge or IE11, and is [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break). You can use the `break-all` utility to get the effect you are looking for if I'm not mistaken.

**Comment by shengslogar** [comment]
@nicooprat Having a similar issue. Looks like even though `overflow-wrap: break-word` is supposed to act identical to the deprecated `word-break: break-word`, the former appears to work differently alongside flexbox. If you were to add `.min-width-0` or `.overflow-hidden` to your parent text container, `overflow-wrap` would behave as expected.
