### ISSUE TITLE
outline-none doesn't work on button with focus in chrome

### ISSUE THREAD

**Issue by desaintflorent** [tailwindcss/tailwindcss#1231]
Hi,

First of all, a big thank's for your work on Tailwindcss, it make coding css so cool again !

Maybe it's not a bug and you thought about this already, but it seems strange that outline-none doesn't set outline-none on focus too, on button element.
I noticed that only on Chrome and only on buttons. If I want to remove outline on focus, I need to do :

```
<button class="outline-none focus:outline-none">click-me</button>
```
If not I see a big blue outline when the button is in Focus state.

It seems that's its coming from normalize.css with :
```
button:focus {
  outline: 1px dotted;
  outline: 5px auto -webkit-focus-ring-color;
}
```

If I add `outline: none;` manually it's working too.

Is that a normal behaviour ?

**Comment by adamwathan** [comment]
You only need `focus:outline-none`:

```
<button class="focus:outline-none">click-me</button>
```

**Comment by AOHUA** [comment]
> You only need `focus:outline-none` for all browsers:
> 
> ```
> <button class="focus:outline-none">click-me</button>
> ```

This doesn't work for me in Chrome, I have to add both `outline-none` and `focus:outline-none` to remove the outline

**Comment by adamwathan** [comment]
Please share a JSFiddle or similar that demonstrates the problem. It does work in Chrome as demonstrated here:

https://jsfiddle.net/4mq2csa3/

**Comment by soorajvnair** [comment]
@adamwathan @desaintflorent @AOHUA  I'm also facing the same issue on my end and in my case, no matter what i add, the outline remains. I traced this back to the preflight styles. If i disable preflight, I'm good however with the preflight styles, the issue comes back.  Hope that helps.

**Comment by adamwathan** [comment]
Can you share a GitHub project that reproduces the issue?

**Comment by neural9** [comment]
It does work to remove the focus outline. Are you using extensions and using focus:outline-none in a separate css file? 

e.g.

.btn{
  @apply bg-blue-500 text-white font-bold py-2 px-4 rounded focus:outline
}
    
This won't work. The focus needs to be in the HTML page itself on every button.

**Comment by ThomOrlo** [comment]
@neural9 `@apply` will not work for pseudo-class.

Do this instead:
```css
.btn {
  @apply bg-blue-500 text-white font-bold py-2 px-4 rounded
}

.btn:focus {
  @apply outline-none
}
```

**Comment by neural9** [comment]
Brilliant - thank you

**Comment by Manubi** [comment]
Unfortunately it's wrong in the docs. 

`focus:outline-none` works in next.js

![Outline_-_Tailwind_CSS](https://user-images.githubusercontent.com/20935138/82380858-7b3aa900-9a29-11ea-9ec5-905d2d474336.png)

**Comment by estevanmaito** [comment]
@Manubi `outline` isn't only applied to focus.

You can apply an outline to almost everything, and this utility removes it.

Take a look at the first demo: https://developer.mozilla.org/en-US/docs/Web/CSS/outline

**Comment by ivanbtrujillo** [comment]
@desaintflorent I faced the same issue than you. The missing piece is enable "focus" as a variant for outline in tailwind.config.js:

```
module.exports = {
  ....
  variants: {
    outline: ["focus"],
  },
  ...
};

```

Then you need to add outline on focus: 
```
<button class="focus:outline-none">click-me</button>
```

Hope it helps!

**Comment by danielidt** [comment]
focus:outline-none works

but why does tailwind add this outline to buttons by default? do we really have to add focus:outline-none to every button?

is there some way to remove outlines by default?

**Comment by vesper8** [comment]
As of September 2020 the only way I could get this outline to go away was adding `shadow-none`

It looks like browsers now use box-shadow for the outline

**Comment by adamwathan** [comment]
> focus:outline-none works
> 
> but why does tailwind add this outline to buttons by default? do we really have to add focus:outline-none to every button?
> 
> is there some way to remove outlines by default?

Tailwind doesn’t add the outline, browsers do. You can remove the outline for all elements if you like by adding a custom base style in your CSS that removes the focus outline but that’s very bad for accessibility so we will never do that by default.

**Comment by adamwathan** [comment]
@vesper8 Hmm I’m not sure that’s true, `outline` still controls the focus outline in every browser I’ve tried. Do you have a reproduction?

**Comment by vesper8** [comment]
@adamwathan don't really have something I can share quickly.. I just know that for me the `tw-outline-none` was doing nothing and only once I added `tw-shadow-none` did the blue outline go away on Chrome desktop.

It might have something to do with all these other css files I include

```
@import '~bootstrap/dist/css/bootstrap.min.css';
@import '~bootstrap-vue/dist/bootstrap-vue.css';
@import '~@fortawesome/fontawesome-free/css/all.min.css';
@import '~sweetalert2/dist/sweetalert2.min.css';
@import '~vue-swipe-actions/dist/vue-swipe-actions.min.css';
```

**Comment by adamwathan** [comment]
Sounds like you were undoing the blue shadow added by Bootstrap, not by the browser. Chrome doesn't add a blue box shadow, it adds a very dark thick focus ring that looks like this:

![image](https://user-images.githubusercontent.com/4323180/93024186-8ad69280-f5c2-11ea-8238-885b0f9b06c0.png)

**Comment by vesper8** [comment]
Ahh makes sense.. thanks for clarifying!

**Comment by arcanis** [comment]
> Tailwind doesn’t add the outline, browsers do. You can remove the outline for all elements if you like by adding a custom base style in your CSS that removes the focus outline but that’s very bad for accessibility so we will never do that by default.

I think it's incorrect in this case - the outline is enforced by the following code:

https://github.com/tailwindlabs/tailwindcss/blob/18baa4e7a8edc31100654f75aff606c1896266c0/src/plugins/css/preflight.css#L32-L40

Adding the `:focus` works because the specificity then becomes equal to this rule.

**Comment by vorja** [comment]
> As of September 2020 the only way I could get this outline to go away was adding `shadow-none`
> 
> It looks like browsers now use box-shadow for the outline

Using Chrome and that fixed it.

**Comment by PataraKaxi** [comment]
Hi ! 
I have already tried a lots of way but achieved only one.
```<button mat-menu-item style="outline: none"> Simply 😄  </button>```
I don't like, when I write in style, but if sometimes no way, no problem...

**Comment by lordvcs** [comment]
For forms I had to use `focus:ring-0` to get it to work

**Comment by juanpprieto** [comment]
focus:ring-transparent did it for me on an input

**Comment by Carloosolrac** [comment]
Same issue. Adding `focus:ring-0` or `focus:ring-transparent` solve the problem of just `focus:outline-none`

**Comment by michabbb** [comment]
hi everyone, i read the [docs](https://tailwindcss.com/docs/outline) and i am trying to disable outlines for `button:focus`. because i don´t know how to do this specific i followed the docs and added:

```
module.exports = {
    corePlugins: {
      // ...
     outline: false,
    }
  }
```

this, but still... the outline is there.... would be happy if someone could help me here.
thank you!

**Comment by shipbreaker** [comment]
I'm trying to use Tailwind with Angular Material and I can't seem to get rid of the outlines that it adds to Angular components. Angular Material already has it's own outlines, and I don't want Tailwind to automatically add any. Is there any way to disable them globally? Adding `focus:ring-0` seems to work for forms, but I don't want to add these classes for every form field and button of my app.

**Comment by sebszocinski** [comment]
Yeah the `outline: false` corePlugin doesn't appear to work for buttons.

**Comment by Local9** [comment]
> Same issue. Adding `focus:ring-0` or `focus:ring-transparent` solve the problem of just `focus:outline-none`

If anything, this showed me that I need to look at all my classes, such a large application where I had to do this on each input that had the outline disabled, personal failure.

**Comment by alexpineda** [comment]
I'm having the same issue with blue outline around Material buttons

**Comment by arifullahjan** [comment]
@michabbb  try this https://github.com/tailwindlabs/tailwindcss/discussions/2949

**Comment by djyra** [comment]
I had similar issue and it was when I had active state on button, it would appear and disappear after click, adding outline-none to existing focus:outline-none solved that for me. Posting in case someone gets similar behavior.

**Comment by TanZng** [comment]
```html
class = "border-transparent focus:border-transparent focus:ring-0"
```
worked for me

**Comment by nandkk05** [comment]
> ```
> class = "border-transparent focus:border-transparent focus:ring-0"
> ```
> 
> worked for me

Thanks, @TanZng this is working for me.

**Comment by huylee99** [comment]
> For forms I had to use `focus:ring-0` to get it to work

Insane. It works for me, thanks!

**Comment by nvrr** [comment]
border-0 border-b-[0.2px] border-opacity-10 focus:ring-0  focus:border-b-ownBlack focus:border-opacity-10 
   *******try this********

**Comment by chauhanshilpa** [comment]
focus:ring-0 with focus:outline-none worked for me

**Comment by DennisMartel** [comment]
this worked for me

&:focus {
    @apply focus:ring-0 focus:ring-offset-0;
  }

**Comment by toni-sharpe** [comment]
Best thing you could do is just leave it. Can you see it clearly enough to complain? Then you don't need it, and are taking it away from [someone who does](https://www.who.int/news-room/fact-sheets/detail/blindness-and-visual-impairment).

Worth noting that people who rely on these things are using them as a tool across all the websites they use in a broswer, this consistency is very valuable. Like the back button, tab functionality and other things that the browser handles the same across everything.

A possible alternate idea would be to play aroud with the site palette and see how it can be incorporated
