### ISSUE TITLE
Allow configuration for using px instead of rem

### ISSUE THREAD

**Issue by jaschaio** [tailwindcss/tailwindcss#1232]
I don't really know why the previous issues #800 and #968 got closed without a real response.

There are as much valid use cases for using `rem` as there are for using `px`.

Lets take the simple example of a website builder which has two seperate user interfaces. One that includes all the App Components designed using Tailwind, and another which includes the user generated content. If I would like to scale up or down only the user generated content area of the UI by modifying the `font-size: 16px` property on the body element, it only works if the rest of the user interface has a fixed sizes using `px` instead of `rem`. If everything uses `rem` I can't change the size of things independently of each other.

**Comment by adamwathan** [comment]
You can configure Tailwind to use whatever units you want, just open up your `tailwind.config.js` file and and go to town.

https://tailwindcss.com/docs/theme

We can only provide one default configuration and the default configuration we've chosen to provide uses `rem` to size things. If you want to use pixels you can provide your own pixel-based configuration.

**Comment by stuyam** [comment]
I have an app where we are running bootstrap 3 which had the root font size set to 14px. The current rems are based off the assumption you use a 16px root font size. I know the config can be updated to change all of these values. However I love keeping the config as stock as possible so when tailwinds updates or adds other values or properties those new ones will _just work_. It would be great if there were a "defaultUnit" or "unit" or something setting in tailwind that defaults to "rem" but could be set to "px".

I love tailwind because it can be so light weight and can be dropped into any project, but so much of it's config assumes that project already uses a root font size of 16px. I think it could be a lot easier to add to existing projects if there was an easy switch for pixels.

For now Ill copy and past config and convert by hand ¯\_(ツ)_/¯

**Comment by risingblock** [comment]
I had this problem as well, so I did the conversion for font size, spacing and line height (assuming base 16px). I'll leave it here to save somebody some time. <3 tailwind

```
module.exports = {
  theme: {
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
      '5xl': '48px',
      '6xl': '60px',
      '7xl': '72px',
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      14: '56px',
      16: '64px',
      20: '80px',
      24: '96px',
      28: '112px',
      32: '128px',
      36: '144px',
      40: '160px',
      44: '176px',
      48: '192px',
      52: '208px',
      56: '224px',
      60: '240px',
      64: '256px',
      72: '288px',
      80: '320px',
      96: '384px',
    },
    extend: {
      lineHeight: {
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
      },
    },
  },
}
```

**Comment by jasontxf** [comment]
Thanks, @risingblock Just the thing I'm looking for :D

**Comment by nitaking** [comment]
@risingblock me too!

**Comment by joshuasweb** [comment]
@risingblock Thanks dude!

**Comment by yellow1912** [comment]
I'm wondering if there is a way to grab the default configs, loop through it, and generate the px based config from that? It would save much time, especially when tailwind base is constantly updated.

**Comment by wenerme** [comment]
Have the same problem, when using shadow dom, the rem is controlled by outside html, the sdk use tailwindcss, so can not use rem, unless the consumer use 16px based rem too.

**Comment by wenerme** [comment]
@yellow1912 the default is here https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L7

**Comment by zbecknell** [comment]
FYI: if anyone wants to use the default config to convert to pixels, this VS Code plugin allows quick conversion: https://marketplace.visualstudio.com/items?itemName=sainoba.px-to-rem

You can select all and convert at once. In my case I decided to go to the sections I needed and convert one-by-one to then copy over to my config file.

This would be such a nice option to have baked in to know you don't have to manually specify these values (in case future properties are added). Wonder if a plugin can change such things or if that's outside the reach of plugins...

**Comment by joshua-scott** [comment]
Here's an update to @risingblock's config for Tailwind v3. It converts everything in the default config that uses rem to px (assuming 16px base). I used the [px-to-rem extension](https://marketplace.visualstudio.com/items?itemName=sainoba.px-to-rem) suggested by @zbecknell's to do it quickly.

```
theme: {
  /**
   * Default tailwind values converted from rem to px:
   * */
  borderRadius: {
    none: "0px",
    sm: "2px",
    DEFAULT: "4px",
    md: "6px",
    lg: "8px",
    xl: "12px",
    "2xl": "16px",
    "3xl": "24px",
    full: "9999px",
  },
  columns: {
    auto: "auto",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    10: "10",
    11: "11",
    12: "12",
    "3xs": "256px",
    "2xs": "288px",
    xs: "320px",
    sm: "384px",
    md: "448px",
    lg: "512px",
    xl: "576px",
    "2xl": "672px",
    "3xl": "768px",
    "4xl": "896px",
    "5xl": "1024px",
    "6xl": "1152px",
    "7xl": "1280px",
  },
  fontSize: {
    xs: ["12px", { lineHeight: "16px" }],
    sm: ["14px", { lineHeight: "20px" }],
    base: ["16px", { lineHeight: "24px" }],
    lg: ["18px", { lineHeight: "28px" }],
    xl: ["20px", { lineHeight: "28px" }],
    "2xl": ["24px", { lineHeight: "32px" }],
    "3xl": ["30px", { lineHeight: "36px" }],
    "4xl": ["36px", { lineHeight: "36px" }],
    "5xl": ["48px", { lineHeight: "1" }],
    "6xl": ["60px", { lineHeight: "1" }],
    "7xl": ["72px", { lineHeight: "1" }],
    "8xl": ["96px", { lineHeight: "1" }],
    "9xl": ["144px", { lineHeight: "1" }],
  },
  lineHeight: {
    none: "1",
    tight: "1.25",
    snug: "1.375",
    normal: "1.5",
    relaxed: "1.625",
    loose: "2",
    3: "12px",
    4: "16px",
    5: "20px",
    6: "24px",
    7: "28px",
    8: "32px",
    9: "36px",
    10: "40px",
  },
  maxWidth: ({ theme, breakpoints }) => ({
    none: "none",
    0: "0px",
    xs: "320px",
    sm: "384px",
    md: "448px",
    lg: "512px",
    xl: "576px",
    "2xl": "672px",
    "3xl": "768px",
    "4xl": "896px",
    "5xl": "1024px",
    "6xl": "1152px",
    "7xl": "1280px",
    full: "100%",
    min: "min-content",
    max: "max-content",
    fit: "fit-content",
    prose: "65ch",
    ...breakpoints(theme("screens")),
  }),
  spacing: {
    px: "1px",
    0: "0",
    0.5: "2px",
    1: "4px",
    1.5: "6px",
    2: "8px",
    2.5: "10px",
    3: "12px",
    3.5: "14px",
    4: "16px",
    5: "20px",
    6: "24px",
    7: "28px",
    8: "32px",
    9: "36px",
    10: "40px",
    11: "44px",
    12: "48px",
    14: "56px",
    16: "64px",
    20: "80px",
    24: "96px",
    28: "112px",
    32: "128px",
    36: "144px",
    40: "160px",
    44: "176px",
    48: "192px",
    52: "208px",
    56: "224px",
    60: "240px",
    64: "256px",
    72: "288px",
    80: "320px",
    96: "384px",
  },
}
```

**Comment by PooSham** [comment]
@joshua-scott I created a function that recursively looks after values that are formatted like float numbers and ending with "rem", and converts them to px. 

```
function rem2px(input, fontSize = 16) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case "object":
      if (Array.isArray(input)) {
        return input.map((val) => rem2px(val, fontSize));
      } else {
        const ret = {};
        for (const key in input) {
          ret[key] = rem2px(input[key]);
        }
        return ret;
      }
    case "string":
      return input.replace(
        /(\d*\.?\d+)rem$/,
        (_, val) => parseFloat(val) * fontSize + "px"
      );
    default:
      return input;
  }
}
```

You can then call it with the default theme by importing it:

    const defaultTheme = require("tailwindcss/defaultTheme");

And my theme configuration looks something like this:

```
...
borderRadius: rem2px(defaultTheme.borderRadius),
columns: rem2px(defaultTheme.columns),
fontSize: rem2px(defaultTheme.fontSize),
lineHeight: rem2px(defaultTheme.lineHeight),
minHeight: {
  ...rem2px(defaultTheme.minHeight),
  4: "16px",
  8: "32px"
},
...
```

**Comment by rikgirbes** [comment]
Awesome @PooSham, although this really should be in the core config as "unit" or such... Don't you think? This feels kinda hackish....

**Comment by joshua-scott** [comment]
@PooSham awesome! Using your function I simplified my tailwind config to this:

```
theme: {
  /**
   * Default tailwind values converted from rem to px:
   **/
  borderRadius: rem2px(defaultTheme.borderRadius),
  columns: rem2px(defaultTheme.columns),
  fontSize: rem2px(defaultTheme.fontSize),
  lineHeight: rem2px(defaultTheme.lineHeight),
  maxWidth: ({ theme, breakpoints }) => ({
    ...rem2px(defaultTheme.maxWidth({ theme, breakpoints })),
  }),
  spacing: rem2px(defaultTheme.spacing),
}
```

**Comment by ineptian** [comment]
@PooSham I am a little confused about the first and second steps in your solution. Where do you store this function and where do you call it?

**Comment by PooSham** [comment]
@ineptian Sorry I wasn't clear, the second step doesn't call the function, it just imports the default configuration so that the function can be called with it later on in step 3. I have the function stored in tailwind.conf.js, before I export the configuration. The "require" line is in the beginning of the file. 

Here's a complete tailwind.conf.js:

```javascript
const defaultTheme = require("tailwindcss/defaultTheme");

function rem2px(input, fontSize = 16) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case "object":
      if (Array.isArray(input)) {
        return input.map((val) => rem2px(val, fontSize));
      } else {
        const ret = {};
        for (const key in input) {
          ret[key] = rem2px(input[key]);
        }
        return ret;
      }
    case "string":
      return input.replace(
        /(\d*\.?\d+)rem$/,
        (_, val) => parseFloat(val) * fontSize + "px"
      );
    default:
      return input;
  }
}

module.exports = {
  content: ["src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "media",
  theme: {
    borderRadius: rem2px(defaultTheme.borderRadius),
    columns: rem2px(defaultTheme.columns),
    fontSize: rem2px(defaultTheme.fontSize),
    lineHeight: rem2px(defaultTheme.lineHeight),
    minHeight: {
        ...rem2px(defaultTheme.minHeight),
        4: "16px",
        8: "32px"
    },
  }
};
```

**Comment by ineptian** [comment]
@PooSham Thanks. Got this working. This is slick. I do a lot of landing pages for random clients and sometimes their native REMS are whacky, so this helps a ton.

In case anyone else that is illiterate like me needs clarification:

Paste the following above ```module.exports = {``` in your tailwind.config.js

```
const defaultTheme = require("tailwindcss/defaultTheme");

function rem2px(input, fontSize = 16) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case "object":
      if (Array.isArray(input)) {
        return input.map((val) => rem2px(val, fontSize));
      } else {
        const ret = {};
        for (const key in input) {
          ret[key] = rem2px(input[key]);
        }
        return ret;
      }
    case "string":
      return input.replace(
        /(\d*\.?\d+)rem$/,
        (_, val) => parseFloat(val) * fontSize + "px"
      );
    default:
      return input;
  }
}
```
And then within the area where you define all your tailwind theme settings ```theme {}``` add:
```
borderRadius: rem2px(defaultTheme.borderRadius),
    columns: rem2px(defaultTheme.columns),
    fontSize: rem2px(defaultTheme.fontSize),
    lineHeight: rem2px(defaultTheme.lineHeight),
    maxWidth: ({ theme, breakpoints }) => ({
      ...rem2px(defaultTheme.maxWidth({ theme, breakpoints })),
    }),
    minHeight: {
        ...rem2px(defaultTheme.minHeight),
        4: "16px",
        8: "32px"
    },
```
I also agree that this should be native within tailwind. Would make using it even that much easier. Should be as simple as setting "rem" or "px" in the config I feel like.

@joshua-scott How did you figure out how to implement this function with max-width like that? That is also super helpful, I took a shot at it myself before I saw that you had already figured it out. I am just wondering why it needs to be formatted differently than the others.

Thanks to you both!

**Comment by LookRain** [comment]
Hi I know this is an old thread, but I think I figured out a better way to do this with postcss.

Just install this [postcss plugin](https://github.com/TheDutchCoder/postcss-rem-to-px) and add it in your `postcss.config.js`


```js
module.exports = {
  plugins: {
    tailwindcss: {},
   '@thedutchcoder/postcss-rem-to-px': {}, // you can add option like the base font size
    autoprefixer: {},
  },
};
```

**Comment by kevinmu17** [comment]
With big thanks to @PooSham
For people who want to stick with the REM like me but want to see the pixel units as a hint, here you go

```js
function rem2px(input, basePixel = 16) {
    // console.log(input);
    if (input == null) {
        return input;
    }
    switch (typeof input) {
        case "object":
            if (Array.isArray(input)) {
                return input.map((val) => rem2px('\n' +val, basePixel))
            } else {
                const ret = {}
                for (const key in input) {
                    if (Array.isArray(input[key])) {
                        let item = []
                        input[key].map((val) => {
                            switch (typeof val) {
                                case "object":
                                    const lineHeightObject = {}
                                    for (const key in val) {
                                        item.push(val[key] + ' /**' + rem2px(val[key]) + '*/')
                                    }
                                case "string":
                                    item.push(val + ' /**' + rem2px(val) + '*/')
                            }
                            ret[key] = item
                        })
                    } else {
                        ret[key] = input[key] + ' /**' + rem2px(input[key]) + '*/'
                    }
                }
                return ret
            }
        case "string":
            return input.replace(
                /(\d*\.?\d+)rem$/,
                (_, val) => parseFloat(val) * basePixel + "px"
            );
        default:
            return input;
    }
}
```

Made this solution pure as temporary patch for phpStorm

**Comment by PooSham** [comment]
> With big thanks to @PooSham For people who want to stick with the REM like me but want to see the pixel units as a hint, here you go
> 
> ```js
> function rem2px(input, basePixel = 16) {
>     // console.log(input);
>     if (input == null) {
>         return input;
>     }
>     switch (typeof input) {
>         case "object":
>             if (Array.isArray(input)) {
>                 return input.map((val) => rem2px('\n' +val, basePixel))
>             } else {
>                 const ret = {}
>                 for (const key in input) {
>                     if (Array.isArray(input[key])) {
>                         let item = []
>                         input[key].map((val) => {
>                             switch (typeof val) {
>                                 case "object":
>                                     const lineHeightObject = {}
>                                     for (const key in val) {
>                                         item.push(val[key] + ' /**' + rem2px(val[key]) + '*/')
>                                     }
>                                 case "string":
>                                     item.push(val + ' /**' + rem2px(val) + '*/')
>                             }
>                             ret[key] = item
>                         })
>                     } else {
>                         ret[key] = input[key] + ' /**' + rem2px(input[key]) + '*/'
>                     }
>                 }
>                 return ret
>             }
>         case "string":
>             return input.replace(
>                 /(\d*\.?\d+)rem$/,
>                 (_, val) => parseFloat(val) * basePixel + "px"
>             );
>         default:
>             return input;
>     }
> }
> ```
> 
> Made this solution pure as temporary patch for phpStorm

That's not a bad idea, but this solution seems unnecessarily complex and actually incomplete. You should just update the "string" case, like this:


```javascript
function rem2px(input, fontSize = 16) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case "object":
      if (Array.isArray(input)) {
        return input.map((val) => rem2px(val, fontSize));
      } else {
        const ret = {};
        for (const key in input) {
          ret[key] = rem2px(input[key]);
        }
        return ret;
      }
    case "string":
      return input.replace(
        /(\d*\.?\d+)rem$/,
        (_, val) => `${input} /** ${parseFloat(val) * fontSize}px */`
      );
    default:
      return input;
  }
}
```

**Comment by fweth** [comment]
What if you want to use `px` for margins, paddings, gaps, etc. but `rem` for width and height?  Then customizing `spacing` wouldn't work?  Here is a good article on the topic:

https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/

I think `rem` should be used for positive space and `px` for negative space.  So if somebody changes their base font size, it shouldn't crank up all the white space on the page, but make the layout denser, in order to still fit a good amount on content in the window.

**Comment by abrehamgezahegn** [comment]
For anyone who is still looking for a workaround. Here is I used. I used [postcss-rem-to-pixel](https://www.npmjs.com/package/postcss-rem-to-pixel)

convertRemToPixel.js
```
var fs = require("fs");
var postcss = require("postcss");
var remToPx = require("postcss-rem-to-pixel");

const replaceRem = (filePath) => {
  var css = fs.readFileSync(filePath, "utf8");
  var options = {
    replace: false,
    rootValue: 16,
    unitPrecision: 5,
    propList: ["*"],
    selectorBlackList: [],
    replace: true,
    mediaQuery: false,
    minRemValue: 0,
  };
  var processedCss = postcss(remToPx(options)).process(css).css;

  fs.writeFile(filePath, processedCss, function (err) {
    if (err) {
      throw err;
    }
    console.log("Rem file written.");
  });
};

replaceRem("./src/output.css");
```


package.json
{ 
  ...
  "scripts": {
     ...
    "build:tw": "tailwindcss -i ./src/index.css -o ./src/output.css && node src/utils/remToPixel.js",  // run the util using node 
  },
}

**Comment by HullQin** [comment]
Thank @PooSham . And I do some other work on that:

- Transfer rem2px on function configs, which can transfer [maxWidth](https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L638) correctly. (Line 22)
- Add fontSize argument on object. (Line 14)

```js
const defaultTheme = require('tailwindcss/defaultTheme');

function rem2px(input, fontSize = 16) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case 'object':
      if (Array.isArray(input)) {
        return input.map((val) => rem2px(val, fontSize));
      }
      const ret = {};
      for (const key in input) {
        ret[key] = rem2px(input[key], fontSize);
      }
      return ret;
    case 'string':
      return input.replace(
        /(\d*\.?\d+)rem$/,
        (_, val) => `${parseFloat(val) * fontSize}px`,
      );
    case 'function':
      return eval(input.toString().replace(
        /(\d*\.?\d+)rem/g,
        (_, val) => `${parseFloat(val) * fontSize}px`,
      ));
    default:
      return input;
  }
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['src/**/*.{js,jsx,ts,tsx}'],
  theme: rem2px(defaultTheme),
};
```

**Comment by TheMangoTrain** [comment]
This is a problem for me too. I ended up using a PostCSS plugin to convert rem-to-px automatically. I don't want to copy-paste things nor make choices, and be able to toggle the plugin on/off.

Use case: a Chrome Extension that injects a small floating UI (box with controls) onto every webpage visited. I use TW to style it. Webpages in the wild all have crazy base styles that affect the box UI.

**Comment by GorvGoyl** [comment]
I'm using twind.style to inject tailwind to shadow dom and managed to convert rem to px https://gourav.io/blog/tailwind-in-shadow-dom#configure-twind

**Comment by baptisteArno** [comment]
Thank guys. 🙏

I needed this because I'm implementing a widget library with Shadow DOM. Having the sizing in px is mandatory, because the widget will be added to any website

**Comment by longzheng** [comment]
> Hi I know this is an old thread, but I think I figured out a better way to do this with postcss (assuming you are using postcss and want to apply the rem->px conversion across your project)
> 
> Just install this [postcss plugin](https://github.com/TheDutchCoder/postcss-rem-to-px) and add it in your `postcss.config.js`
> 
> ```js
> module.exports = {
>   plugins: {
>     tailwindcss: {},
>    '@thedutchcoder/postcss-rem-to-px': {}, // you can add option like the base font size
>     autoprefixer: {},
>   },
> };
> ```


This is exactly what I needed.

Just in case anyone else is also confused, the plugin README has the incorrect name for the install instructions. You'll need 
```
npm install @thedutchcoder/postcss-rem-to-px
```

**Comment by pgmichael** [comment]
Adding my +1 to re-open this! It would be nice to have a single option that would change all values rather than having to do it manually, add further dependencies or use a function inside `tailwind.config.js` which makes customizing further values harder.

I am developing an extension that injects a React app into the current tab of the user. To prevent any potential conflicts with existing styles, I have contained my app within a shadow root. However, given that rem values are inherently derived from the base html element, this causes inconsistencies in style rendering (ex: on one page `text-sm` could be `7px` and on the other `12px`).

Right now I'm fetching the text content of my stylesheet and using a regex to convert all `rem` values to `px`. It works.. but it's quite hacky!

**Comment by JohnCido** [comment]
> > 嗨，我知道这是一个旧线程，但我认为我找到了一种更好的方法来使用 postcss 来做到这一点（假设您正在使用 postcss 并希望在您的项目中应用 rem->px 转换）
> > 只需安装这个[postcss 插件](https://github.com/TheDutchCoder/postcss-rem-to-px)并将其添加到您的`postcss.config.js`
> > ```js
> > module.exports = {
> >   plugins: {
> >     tailwindcss: {},
> >    '@thedutchcoder/postcss-rem-to-px': {}, // you can add option like the base font size
> >     autoprefixer: {},
> >   },
> > };
> > ```
> 
> 这正是我所需要的。
> 
> 为了防止其他人也感到困惑，插件自述文件的安装说明名称不正确。你需要
> 
> ```
> npm install @thedutchcoder/postcss-rem-to-px
> ```

This is the most simple way to achieve quick rem to px convertion.

**Comment by jmiller-rise8** [comment]
https://www.npmjs.com/package/@rise8/tailwind-pixel-perfect-preset

**Comment by cumber** [comment]
The trouble is Tailwind's default config **doesn't** entirely use `rem`. It mostly does, but then it uses `px` for border width, shadows, underline offsets, etc. And of course there's the `px` size for `1px` spacing etc.

The net result is that *most* things will scale with the root font size, but *some* things won't. So this setup denies the user the ability to change their default text size independently from the scale of the entire design (e.g. to enlarge text for accessibility reasons), but it also fails to make the root font scale the site's design. Instead Tailwind designs effectively rely on the root font size at runtime being pretty close to a fixed value the designer had in mind, despite that value actually being dependent on the browser and the user's settings.

The claimed advantage of using `rem` everywhere is that it makes the site's design automatically scale when the root font size is adjusted. But adjusting the default font size is a really weird way to scale the *design* (rather than the text) anyway. If the *user* wants to do that, they'll use the zoom settings in the browser. If the *designer* wants to do that (e.g. to make things bigger on large screens), that's what `transform: scale` is for. Using `rem` everywhere is unnecessary for making the site scalable, and using `rem` *nearly* everywhere makes it scale worse than just using `px` everywhere.

**Comment by SentretC** [comment]
On desktop it might be good enough to scale everything together (but I don't think developers should do that - users will set a global scaling if they prefer). However on mobile it can be a waste of screen space to also scale up spacing when the user just needs larger texts.

I would prefer having not just one, but separate options for different kinds of sizes.

**Comment by maxxxxxdlp** [comment]
I was in a situation where I needed to make Tailwind use em instead of rem (see https://github.com/tailwindlabs/tailwindcss/discussions/3105#discussioncomment-7354432). My solution should work for your case too with a modification:

<details>
<summary>Here is a tiny PostCSS plugin, that replaces all occurrences of "rem" with "em" in the output CSS files:</summary>

```js
const convertRemToEm = {
  postcssPlugin: 'convertRemToEm',
  // When debugging this, https://astexplorer.net/#/2uBU1BLuJ1 is very helpful
  Declaration(declaration) {
    declaration.value = declaration.value.replaceAll(remRegex, 'em');
  },
};

// Regex to find all occurrences of "rem" units
const remRegex = /(?<=\d)rem/g;

/** @type {import('postcss-load-config').Config} */
module.exports = {
  plugins: [
    // ... your other plugins here
    // Add this plugin:
    convertRemToEm,
  ],
};
```
</details>

If you want to use px instead, it might look something like this:

```js
const convertRemToEm = {
  postcssPlugin: 'convertRemToEm',
  // When debugging this, https://astexplorer.net/#/2uBU1BLuJ1 is very helpful
  Declaration(declaration) {
    declaration.value = declaration.value.replaceAll(
      remRegex,
      (_, number) => `${Number.parseInt(number) * 16}px`,
    );
  },
};

// Regex to find all occurrences of "rem" units and capture the number
const remRegex = /(\d+\.?\d+)rem/g;

/** @type {import('postcss-load-config').Config} */
module.exports = {
  plugins: [
    // ... your other plugins here
    // Add this plugin:
    convertRemToEm,
  ],
};
```

**Comment by LeoRedin** [comment]
> I was in a situation where I needed to make Tailwind use em instead of rem (see [#3105 (comment)](https://github.com/tailwindlabs/tailwindcss/discussions/3105#discussioncomment-7354432)). My solution should work for your case too with a modification:
> 
> Here is a tiny PostCSS plugin, that replaces all occurrences of "rem" with "em" in the output CSS files:
> ```js
> const convertRemToEm = {
>   postcssPlugin: 'convertRemToEm',
>   // When debugging this, https://astexplorer.net/#/2uBU1BLuJ1 is very helpful
>   Declaration(declaration) {
>     declaration.value = declaration.value.replaceAll(remRegex, 'em');
>   },
> };
> 
> // Regex to find all occurrences of "rem" units
> const remRegex = /(?<=\d)rem/g;
> 
> /** @type {import('postcss-load-config').Config} */
> module.exports = {
>   plugins: [
>     // ... your other plugins here
>     // Add this plugin:
>     convertRemToEm,
>   ],
> };
> ```
> 
> If you want to use px instead, it might look something like this:
> 
> ```js
> const convertRemToEm = {
>   postcssPlugin: 'convertRemToEm',
>   // When debugging this, https://astexplorer.net/#/2uBU1BLuJ1 is very helpful
>   Declaration(declaration) {
>     declaration.value = declaration.value.replaceAll(
>       remRegex,
>       (_, number) => `${Number.parseInt(number) * 16}px`,
>     );
>   },
> };
> 
> // Regex to find all occurrences of "rem" units and capture the number
> const remRegex = /(\d+\.?\d+)rem/g;
> 
> /** @type {import('postcss-load-config').Config} */
> module.exports = {
>   plugins: [
>     // ... your other plugins here
>     // Add this plugin:
>     convertRemToEm,
>   ],
> };
> ```

 Hello! I'm facing the same issue, Im creating a web component and then I got into the same problem. [Here's ](https://codesandbox.io/s/react-tailwind-starter-forked-3px6v4?file=/src/components/ChatContainer.js) a sandbox in case you have some time, I cannot seem to bypass the html font sizing. This is a simpler example but if I get that going the rest should be fine

**Comment by lucasdellabella** [comment]
> Just install this [postcss plugin](https://github.com/TheDutchCoder/postcss-rem-to-px) and add it in your `postcss.config.js`

Reporting in - @thedutchcoder's postcss plugin is the way to go.

**Comment by TimonPeng** [comment]
Resize rem:

```javascript
function remResize(input, ratio = 1) {
  if (input == null) {
    return input;
  }
  switch (typeof input) {
    case 'object':
      if (Array.isArray(input)) {
        return input.map((val) => remResize(val, ratio));
      }
      const ret = {};
      for (const key in input) {
        ret[key] = remResize(input[key], ratio);
      }
      return ret;
    case 'string':
      return input.replace(/(\d*\.?\d+)rem$/, (_, val) => `${parseFloat(val) / ratio}rem`);
    case 'function':
      return eval(input.toString().replace(/(\d*\.?\d+)rem/g, (_, val) => `${parseFloat(val) / ratio}rem`));
    default:
      return input;
  }
}
```

```
module.exports = {
  theme: {
    ...remResize(defaultTheme, 0.625),
    colors: {},
  },
};
```

**Comment by tolotrasamuel** [comment]
How to achieve this in tailwind v4 ?there is no more tailwind.config.js in v4

**Comment by wongjn** [comment]
Configuration is done in CSS, see https://tailwindcss.com/docs/theme. So to change the `--spacing` variable used by margin, padding and other utilities:

```css
@theme {
  --spacing: 4px;
}
```

**Comment by davidgilbertson** [comment]
UnoCSS has `@unocss/preset-rem-to-px`, it would be nice if Tailwind made it just as easy to use `px` everywhere instead of `rem`.

@adamwathan this is closed, but if the issue is taken to mean "EASILY allow configuration for using px instead of rem" really it should still be open. I'm new to Tailwind, and using v4 and I see no easy way to do this.

**Comment by ansavchenco** [comment]
I was able to make it work with the [postcss-rem-to-responsive-pixel](https://github.com/sonofmagic/postcss-plugins/tree/main/packages/postcss-rem-to-responsive-pixel) plugin. No need to mess with the tailwind theme config!

```
npm i postcss postcss-rem-to-responsive-pixel -D
```

```javascript
// postcss.config.js
module.exports = {
  plugins: [
    require("postcss-rem-to-responsive-pixel")({
      rootValue: 14,
      propList: ["*"],
      transformUnit: "px",
    }),
  ],
};
```

```javascript
// vite.config.ts
import { defineConfig } from 'vitest/config'
import postcssRemToPixel from 'postcss-rem-to-responsive-pixel'

export default defineConfig({
  // ...
  css: {
    postcss: {
      plugins: [
        postcssRemToPixel({
          rootValue: 14,
          propList: ['*'],
        }),
      ],
    },
  },
  // ...
})
```

Not sure if there are any downsides to this but for me it has been working nicely so far.
