### ISSUE TITLE
CSS Variables and Screen doesn't work

### ISSUE THREAD

**Issue by davidhellmann** [tailwindcss/tailwindcss#1233]
When I assign css vars to  screen options it doesn't work.

DOESNT'T WORKS:
This is my Part in the Tailwind Config
```js
    screens: {
      'min': 'var(--bp-min)',
      's': 'var(--bp-s)',
      'm':'var(--bp-m)',
      'l': 'var(--bp-l)',
      'max': 'var(--bp-max)',
    },
```

CSS
```css
h1 {
  @apply text-red;

  @screen l {
    @apply text-green;
  }
}
```

WORKS:
This is my Part in the Tailwind Config
```js
    screens: {
      'min': '320px',
      's': '600px',
      'm':'800px',
      'l': '1200px',
      'max': '1600px',
    },
```

CSS
```css
h1 {
  @apply text-red;

  @screen l {
    @apply text-green;
  }
}
```

My app.pcss looks like this:
```css
@import '01-settings.pcss'; // Here are the css vars

@import 'tailwindcss/base';
@import 'tailwindcss/components';

@import 'test.pcss';

/*@import '02-tools.pcss';*/
/*@import '03-generic.pcss';*/
/*@import '04-elements.pcss';*/
/*@import '05-objects.pcss';*/
/*@import '06-components.pcss';*/
/*@import '07-vendors.pcss';*/

@import 'tailwindcss/utilities';
```

The CSS Vars looks like this:
```css

:root {
  --bp-min: 320px;
  --bp-s: 600px;
  --bp-m: 800px;
  --bp-l: 1200px;
  --bp-max: 1600px;
}
```

Maybe I forget something?

**Comment by hacknug** [comment]
Probably because the spec doesn't support it yet. I don't think it is a Tailwind issue (would need to see the output code to tell if it really is).

https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries

**Comment by davidhellmann** [comment]
Looks like you are right Never tried that before. For me a no brainer but it isn't :D 
Thanks!

**Comment by atumas-bananamilk** [comment]
Is this fixed yet? Just tried, doesn't work still.

```
screens: {
  xs: 'var(--mantine-breakpoint-xs)',
  sm: 'var(--mantine-breakpoint-sm)',
  md: 'var(--mantine-breakpoint-md)',
  lg: 'var(--mantine-breakpoint-lg)',
  xl: 'var(--mantine-breakpoint-xl)',
}
```

**Comment by botmaster** [comment]
Hello,
I don't understand why it doesn't work with sizes. It works with colors and font families, but not with screens.
Any update ?

**Comment by alinasrabadi** [comment]
Doesn't work still!

**Comment by RobinMalfait** [comment]
As stated earlier, this is not a Tailwind CSS issue, but something you can't do in the browser so there is unfortunately nothing we can do at this point.
