### ISSUE TITLE
@apply doesn't work inside <style jsx></style>

### ISSUE THREAD

**Issue by himanshu-dhiman26** [tailwindcss/tailwindcss#1234]
Hi @adamwathan ,

I was working on a React component in NextJS and was using Tailwind to customize the designs. Putting the tailwind classes in `className` works fine while using like :

```
<component className="tw-class-1 tw-class-2 tw-class-3 tw-class-4 tw-class-5 tw-class-6" />
```

But, since I am using too many classes for the component, and it will be a common style. I wanted to make it work by using @apply into another custom class. Something like :

```
<component className="custom-class" />
```

and  CSS goes like : 

```
.custom-class {
    @apply tw-class-1 tw-class-2 tw-class-3 tw-class-4 tw-class-5 tw-class-6;
}
```

BTW I am using Styles as JSX. So, finally I want my component to look like :

```
import React from 'react';

const Component = (props) => (
  <div>
     <div className="custom-class">
     </div>
     
     <style jsx>
      {`
            .custom-class {
                @apply tw-class-1 tw-class-2 tw-class-3 tw-class-4 tw-class-5 tw-class-6;
             }
      `}
      </style>

  </div>
);

export default Component;
```

But this doesn't works out. Error I get is while inspecting the element

![Screenshot 2019-11-22 at 2 20 05 PM](https://user-images.githubusercontent.com/39363104/69411622-53e17880-0d33-11ea-98a7-bd28f10b5d2f.png)

Can you help me out in understanding if I am doing anything wrong, or does it support working under <style jsx> or not? An alternate solution would be appreciated.

Thanks

**Comment by hacknug** [comment]
Is postcss running on your project? Tailwind is nothing but a postcss plugi. so you'll always need to process everything with it to get actual CSS code.

I have no idea how `<style jsx>` works but maybe this plugin would help? https://github.com/giuseppeg/styled-jsx-plugin-postcss

**Comment by himanshu-dhiman26** [comment]
Thanks @hacknug for responding.

Yes, I have configured a postcss plugin in project. But I am not sure that it will take care of <style jsx> or not.

Here is my postcss.config.js

```
const tailwindCss = require('tailwindcss');
const postCss = require('postcss-preset-env');

module.exports = {
  plugins: [tailwindCss, postCss],
};
```

And I am also using @zeit/next-css, to process external CSS files, as it has to be server side rendered.

I will try the plugin you shared, and will get back to you.

Thanks

**Comment by himanshu-dhiman26** [comment]
Thanks @hacknug ,

The plugin you shared worked for me.

If you are using the plugin in nextJS then you need to use this plugin with `next/babel` preset. You can configure it like this in your `.babelrc`:

```
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": [
            "styled-jsx-plugin-postcss"
          ]
        }
      }
    ]
  ]
}
```

**Comment by fillipvt** [comment]
@adamwathan @himanshu-dhiman26 Is this still working?

I'm using [nextjs tailwindcss example](https://github.com/zeit/next.js/tree/master/examples/with-tailwindcss) along with the solution posted here and I'm not able to inject styled with `@apply`

Here's a repo show casing this: https://github.com/fillipvt/with-tailwindcss (take a look at `pages/index.js`)

And here's the deployment url: https://with-tailwindcss-git-master.fillipvt.now.sh

If you inspect the H1 you'll see this:

````
.red.jsx-308251731 {
    @apply text-red-500: ;
}
````

So postcss is not working inside styled-jsx. Not sure where I went wrong. Any help would be greatly appreaciated.

**Comment by fillipvt** [comment]
Okay, got it working! For future reference the [Next.js docs explain](https://nextjs.org/docs/advanced-features/customizing-postcss-config) that if we want to modify the PostCSS config we need to replicate the default one and use an object syntax:

Here's how a config would look like nowadays in order for it to work without problems with styled-jsx:

````
const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss': {},
    '@fullhuman/postcss-purgecss': isProd ? {
      content: 
        [
          './pages/**/*.{js,jsx,ts,tsx}',
          './components/**/*.{js,jsx,ts,tsx}',
        ],
        defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
    } : false,
    'postcss-nested': {},
    'postcss-custom-properties': {},
    'postcss-flexbugs-fixes': {},
    'postcss-preset-env': {
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
      features: {
        'custom-properties': false,
      },
    },
  },
};
````

**Comment by Akumzy** [comment]
@fillipvt Thank you so much I have spent about 3 days looking for a solution for this error

**Comment by alexvilchis** [comment]
Hello, @fillipvt 

Your solution didn't do the trick for me. I copied the files in your repo (only prefixing src/ as my components reside there) but when I start the project it never loads the page, it just keeps hanging forever.

**Comment by loicnestler** [comment]
Hey @fillipvt!

Doesn't work for me as well. Looks like the tailwind css file now won't get loaded.

**Comment by fillipvt** [comment]
@loicnestler @alexvilchis 

This works perfectly fine in latest next.js and tailwindcss packages:

```
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}

```

```
// postcss.config.js

module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-flexbugs-fixes': {},
    'postcss-preset-env': {
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
      features: {
        'custom-properties': false,
      },
    },
  },
};

```

BTW there is no need to have PurgeCSS now since Tailwind includes it.

**Comment by alexvilchis** [comment]
It works! Thanks a lot

**Comment by shubhamkes** [comment]
> @loicnestler @alexvilchis
> 
> This works perfectly fine in latest next.js and tailwindcss packages:
> 
> ```
> // .babelrc
> {
>   "presets": [
>     [
>       "next/babel",
>       {
>         "styled-jsx": {
>           "plugins": ["styled-jsx-plugin-postcss"]
>         }
>       }
>     ]
>   ]
> }
> ```
> 
> ```
> // postcss.config.js
> 
> module.exports = {
>   plugins: {
>     tailwindcss: {},
>     'postcss-flexbugs-fixes': {},
>     'postcss-preset-env': {
>       autoprefixer: {
>         flexbox: 'no-2009',
>       },
>       stage: 3,
>       features: {
>         'custom-properties': false,
>       },
>     },
>   },
> };
> ```
> 
> BTW there is no need to have PurgeCSS now since Tailwind includes it.
> Also, I haven't updated the repo but I've tested this in a separate private repo and it just works.

have applied the changes as mentioned
But For me styles within   <style jsx> </style>  still not reflecting however tailwind classes are reflecting.

**Comment by PaulPCIO** [comment]
When I extend the babel presets I run into this error?
>Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config

if I remove the `styled-jsx-plugin-postcss` everything works fine.

Here are my files:

```javascript
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ],
  "plugins": [
    [
      "babel-plugin-react-intl",
      {
        "ast": true,
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "extractFromFormatMessageCall": true
      }
    ],
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "lib",
        "style": "index.css"
      }
    ],
    [
      "import",
      {
        "libraryName": "@ant-design/icons",
        "libraryDirectory": "lib/icons",
        "camel2DashComponentName": false
      },
      "@ant-design/icons"
    ],
    ["inline-react-svg"]
  ]
}
```


```javascript
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-flexbugs-fixes': {},
    'postcss-preset-env': {
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3,
      features: {
        'custom-properties': false
      }
    }
  }
}

```

**Comment by codfish** [comment]
@PaulPCIO I'm seeing the same thing, but not just that, 

```
info  - Using external babel configuration from /.../.babelrc
[styled-jsx] Loading plugin from path: /.../node_modules/styled-jsx-plugin-postcss/index.js
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
error - ./src/components/Header.js
Error: /.../src/components/Header.js: postcss failed with Starting inspector on 127.0.0.1:9229 failed: address already in use
TypeError: Invalid PostCSS Plugin found: [1]
    at Array.forEach (<anonymous>)
```

I'm following everything in @fillipvt comment [here](https://github.com/tailwindlabs/tailwindcss/issues/1234#issuecomment-631817677) exactly, but still ending up with the above issues. Using that as a starting point I've also tried a bunch of different variations, object format for postcss config plugins, `require`, etc. Nothing seems to be working

### Versions

- next v10
```
"postcss-flexbugs-fixes": "^5.0.1",
"postcss-preset-env": "^6.7.0",
"styled-jsx-plugin-postcss": "^3.0.2",
"stylelint-config-recommended": "^3.0.0",
"tailwindcss": "^1.9.6"
```

### Use case

When trying to apply specific styling to a component that isn't covered by tailwind's utility classes, but I want to use the `theme` function and/or `@screen` directive.

**Comment by PaulPCIO** [comment]
@codfish mind sharing your config, I tried removing that but I still get the `Invalid PostCSS Plugin found: [0]`

I just started a fresh project, so everything on the latest versions aswell.

**Comment by codfish** [comment]
@PaulPCIO sure thing, here it is:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-preset-env': {
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
      features: {
        'custom-properties': false,
      },
    },
  },
};
```

current deps:

```json
"scripts": {
  "dev": "NODE_OPTIONS='--inspect' next dev",
  "build": "next build",
  "start": "next start"
},
"dependencies": {
  "@apollo/client": "^3.2.5",
  "@babel/runtime": "^7.12.5",
  "clsx": "^1.1.1",
  "deepmerge": "^4.2.2",
  "graphql": "^15.4.0",
  "next": "^10.0.1",
  "prop-types": "^15.7.2",
  "react": "^17.0.1",
  "react-dom": "^17.0.1"
},
"devDependencies": {
  "cod-scripts": "^5.0.0",
  "postcss-flexbugs-fixes": "^5.0.1",
  "postcss-preset-env": "^6.7.0",
  "styled-jsx-plugin-postcss": "^3.0.2",
  "stylelint-config-recommended": "^3.0.0",
  "tailwindcss": "^1.9.6"
},
```

**Comment by DaniGuardiola** [comment]
I'm having trouble setting this up as well. Here are my files:

```jsonc
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}
```

```js
// postcss.config.js
module.exports = {
  plugins: ['tailwindcss', 'autoprefixer']
}
```

```jsonc
// deps (package.json)
{
  "dependencies": {
    "bluebird": "^3.7.2",
    "classnames": "^2.2.6",
    "next": "10.0.2",
    "next-mdx-remote": "^1.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "@types/bluebird": "^3.5.33",
    "@types/classnames": "^2.2.11",
    "@types/node": "^14.14.9",
    "@types/react": "^17.0.0",
    "autoprefixer": "^10.0.2",
    "gray-matter": "^4.0.2",
    "postcss": "^8.1.8",
    "styled-jsx-plugin-postcss": "^3.0.2",
    "tailwindcss": "^2.0.1",
    "typescript": "^4.1.2"
  }
}
```

I really don't know why this isn't working. I'm getting the `Invalid PostCSS Plugin found: [0]` error.

There's also this:

```
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
```

What am I doing wrong? :(

**Comment by codfish** [comment]
FYI, seems to be working for me with `postcss-flexbugs-fixes` back in with latest `tailwind` (v2) & postcss-flexbugs-fixes (v5.0.2) versions.

**Comment by codfish** [comment]
upgraded to v2, ran into similar issues and went down similar rabbit holes to figure things out, similar to linked issues by  @DaniGuardiola ... ended up removing styled-jsx-plugin-postcss, deleted the overwritten babelrc config, deleted any and all styled-jsx in the app that was using tailwind (and otherwise) and just moved styles to css modules which are supported out of the next.js box. https://github.com/vercel/next.js/issues/19477#issuecomment-732954621

**Comment by DaniGuardiola** [comment]
@codfish FYI, apparently this was the bug at the root of this issue: https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/42

However, I haven't tried the fix as I ended up using a different approach (not css modules though as they don't apply to my use case).

**Comment by white-room** [comment]
@DaniGuardiola @codfish using the tailwindcss postcss7 compatibility build sorted my issues and now have taildwindcss@2 and next@10 working with styled-jsx

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by DaniGuardiola** [comment]
@white-room you shouldn't need that anymore, as the plugins peer dependency was updated to post CSS 8

**Comment by gilvaju** [comment]
Hi guys, i have the sma issue. @apply dont work for me inside style tag with jsx

deps:

`
    "postcss": "^8.3.6",
    "tailwindcss": "^2.2.7",
`

`
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}
`

The config aboce, dont work for me. :(

**Comment by tangye1234** [comment]
Cannot use tailwindcss in jsx either.

**Comment by lednhatkhanh** [comment]
Adding `"styled-jsx-plugin-postcss"` worked for me.

**Comment by kayvaninvemo** [comment]
For me it was a bit confusing to fix the issue.
First install 

```npm i -D styled-jsx-plugin-postcss```

And then you need this in `.babelrc` file at the rrot of the project
```
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}
```

**Comment by jim-spot** [comment]
Does anyone know how to do this and still keep SWC support? Seems like the moment you add a .babelrc file it switches back to using webpack.

**Comment by andriilive** [comment]
@jim-spot check the `forceSwcTransforms` (experimental)

https://nextjs.org/docs/messages/swc-disabled#possible-ways-to-fix-it
