### ISSUE TITLE
Custom type selector is overriding class selector?

### ISSUE THREAD

**Issue by songololo** [tailwindcss/tailwindcss#1235]
When customising the `span` selector in my CSS setup, for example:

```
span {
  @apply font-normal;
}
```

It will override more specific class selectors in my `vue` component, for example:

```
.heading {
  @apply font-semibold;
}
```
This only happens for the `span` selector and I am not experiencing any other issues with selector specificity.

This would seem like a bug unless I'm missing something?

Thanks.

**Comment by adamwathan** [comment]
Can you share your complete CSS file?

**Comment by adamwathan** [comment]
Here's an example that shows things working as expected:

https://tailwind.run/cH5cuF/1

Make sure your CSS declarations are in the right order, base styles (like `span { ... }`) should come after `@tailwind base` and component classes (like `.heading`) should come after `@tailwind components`.

This isn't actually a Tailwind-specific thing, order of declarations matters in CSS, later declarations take precedence over earlier declarations that have the same specificity.

**Comment by songololo** [comment]
Thanks.

The import order is as follows:

```
@import "tailwindcss/base";
@import "./custom-base-styles.css";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

The `span` base style is defined in `custom-base-styles.css`.

The `.heading` class is defined inside the scoped CSS of my `vue` component, which is why I'm puzzled about the behaviour.

The `span` selector combined with font weights is the only instance where I'm having trouble. This may be some quirk elsewhere...
