### ISSUE TITLE
`italics` rule breaks encoding in print

### ISSUE THREAD

**Issue by andrenanninga** [tailwindcss/tailwindcss#1243]
Using the `italics` class breaks the encoding of my page and results in garbled text when trying to print. 

using:
chrome: Version 78.0.3904.108 (Official Build) (64-bit)
mac-os: Version 10.15.1 (19B88)

Using Chrome's print preview I get the following preview with garbled text instead of the expected text of `Making this text italic breaks the encoding for this document in print` (which you can see in the background).
![Screenshot 2019-12-01 at 12 01 29](https://user-images.githubusercontent.com/2734162/69913012-66923680-1432-11ea-86cd-f540de7ea5e8.png)

When I remove either the `italic` class or the tailwind import the issue goes away. Applying the css `font-style: italic` manually without any tailwind works normally and doesn't cause any issue.

I've created a minimal reproduction of the issue here https://codesandbox.io/s/static-cmn0x. The issues is reproducible by following these steps:

1. Open codesandbox link
2. In Codesandbox, "Open page in new window" (https://cmn0x.csb.app/)
3. Open print preview (⌘+p)
4. Observe the garbled text

**Comment by hacknug** [comment]
I really can't think of any reason why things would get messed up when using `.italic` besides something being wrong with the fonts you're using. Since you're not even using custom fonts, I'm not sure where this could be coming from but I can say it looks good on Safari and Firefox (not Chrome Canary though).

Have you checked how this looks like on other Chromium-based browsers?

**Comment by andrenanninga** [comment]
Dug into it a bit more and seems to be an issue with the `BlinkMacSystemFont` font. I've created an example without tailwind but with a list of `<p>` each with one of the font-families defined in the tailwind fontstack. (https://codesandbox.io/s/static-uwipl)

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2734162/69916550-93f3da00-145c-11ea-8465-7fe23dd8ed66.png">

As you can see, only the row with `BlinkMacSystemFont` is showing the issue.

**Comment by andrenanninga** [comment]
I found a issue concerning this issue [in the chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1018581&q=BlinkMacSystemFont&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). I will close the issue here.

**Comment by MrSunshyne** [comment]
Found out about this bug the hard way. 

Came here to report it & saw this issue. It's still unresolved as of now in chromium.

If it may help others: **Just remove italics and your print/preview will render fine.**

**Comment by DamodarDahal** [comment]
This issue has been resolved in Chromium 86.0.4184.0.

Read comment 39 on https://bugs.chromium.org/p/chromium/issues/detail?id=1018581#c39.
