### ISSUE TITLE
Option for turn everything Grayscale

### ISSUE THREAD

**Issue by shimulch** [tailwindcss/tailwindcss#1248]
I really liked the idea from Refactoring UI book to turn everything Grayscale to let spacing, size etc to do the heavy lifting rather than colors. I believe that would be a great way to improve design.

So I would like to request for an option to turn everything Grayscale in tailwind. From my understanding, it might be easy just to override existing colors with different shades of Gray. 

I don't know if thats falls into the scope of tailwindcss, but personally I would love to use that feature.

If anyone knows if that can be done already in tailwindcss please let me know. Else if you guys think it can be a valuable feature in tailwindcss, I am willing to assist with PR after discussion.

**Comment by royvanv** [comment]
So this is basically the following CSS?

```CSS
body {
    filter: grayscale(1);
}
```

Not sure if it's something that should be in the core of Tailwind. Are you using it solely for development purposes or are you planning on using it in a live website?

If you real need it you can write a plugin for it, of course. If it's decided to be integrated it's also nice starting point for a PR.

**Comment by hacknug** [comment]
I'd either go with @royvanv's approach or limit myself to only use the `gray` palette.

**Comment by shimulch** [comment]
@royvanv Thanks. I didn't know about this filter property of CSS. I guess this would be unnecessary as same effect can be achieved by so simple trick.

No I am not planning it for any live website. Just for development. 

Thanks a lot.

**Comment by royvanv** [comment]
No problem, @shimulch.
