### ISSUE TITLE
Add font-0 utility class

### ISSUE THREAD

**Issue by khalyomede** [tailwindcss/tailwindcss#1256]
I want to be able to use a class that will apply a `font-size: 0;`.

I have a use case when this could be useful: when you try to use the following hack to remove any spaces between elements of an unordered list:

- Make the container have a `font-size: 0;`
- Make the children have a `font-size: 1rem`
- No uncontrolled spaces between children
- Profit

Here is a JSFiddle showing the differences between without this "hack":

[https://jsfiddle.net/n8gd0sj9/2/](https://jsfiddle.net/n8gd0sj9/2/)

And with:

[https://jsfiddle.net/n8gd0sj9/1/](https://jsfiddle.net/n8gd0sj9/1/)

Do you think it's worth it?

**Comment by royvanv** [comment]
You could use flexbox to solve this issue or remove the whitespace from the HTML.

**Comment by adamwathan** [comment]
For this particular situation you should definitely just use flexbox. If you want to add a font-size 0 utility you can do so in your config file:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      fontSize: {
        '0': '0px',
      }
    }
  }
}
```
