### ISSUE TITLE
[Bug?] - Top/Right/Bottom/Left not working

### ISSUE THREAD

**Issue by Marfru** [tailwindcss/tailwindcss#1257]
Hello!

I've been working for a couple of months with Tailwind, and it's awesome.

Everything works smoothly, but the **Top / Right / Bottom / Left utilities** never worked for me. I'm wondering if it's something on my side, or if I'm not the only one experiencing this.

`/docs/top-right-bottom-left/#app`

Regards.

**Comment by royvanv** [comment]
Did you add a position class, like `absolute` or `fixed`? 

https://developer.mozilla.org/en-US/docs/Web/CSS/top

**Comment by adamwathan** [comment]
They definitely work:

https://tailwind.run/kjEQfM

Closing since this is user error but happy to look at your code and help.

**Comment by nicoja** [comment]
Hello,

@adamwathan if you start from your example : https://tailwind.run/kjEQfM and set top-1 or top-2, etc ... to the first element, absolute positioning is not working. Why ?

Regards

**Comment by adamwathan** [comment]
Tailwind.run uses Tailwind CSS v1.1, `top-1` and `top-2` don't exist by default in that version of Tailwind (they were added in v2).

**Comment by nicoja** [comment]
Ok thanks for reply. I did not see that this was v1.
