### ISSUE TITLE
Maybe a typo `postcss.config.js` → `webpack.config.js`

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindcss/tailwindcss#1261]
Is this supposed to be `webpack.config.js` instead of `postcss.config.js` 👇

<img width="696" alt="tailwind" src="https://user-images.githubusercontent.com/16436270/70861366-f4057880-1f52-11ea-83ee-3b4e219dde8f.png">

I’m not sure but it’s under the Webpack heading so I assumed :)

**Comment by deadcoder0904** [comment]
And PostCSS heading is just above where it’s already declared so a bit confusing to me tbh

**Comment by devcircus** [comment]
It's correct. It's showing that you can add it to your postcss config file or just directly add it to your webpack config.

**Comment by adamwathan** [comment]
Yeah those instructions are correct. Webpack will read from your postcss.config.js file if present.
