### ISSUE TITLE
Ability to override @screens in plugins

### ISSUE THREAD

**Issue by cizza** [tailwindcss/tailwindcss#1270]
Hello Adam,

I've got a feature request. I'd like to be able to override the screens in the plugins on demand. I came across a use case when writing a plugin. I have screens defined in the tailwind.config.js as:

`"theme": {
        "screens": {
            "xl": {"min": "1279px"},
            "lg": {"max": "1278px"},
            "md": {"max": "1023px"},
            "sm": {"max": "767px"},
            "xs": {"max": "640px"}
        }
}`

I'm building a plugin which requires a side effect for which I need to pass the screens as:

`const screens = {
            "xs": {"min": "0px"},
            "sm": {"min": "767px"},
            "md": {"min": "1023px"},
            "lg": {"min": "1278px"},
            "xl": {"min": "1279px"}
        };`

Looking at the source code I don't think it is possible as it seems to me that tailwind will always pull screens as defined in the the tailwind.config.js  

The plugin is a simple component helper class for defining grid like blocks.

I'm posting the code here as well for a reference.

`module.exports = function() {
    return function({ addComponents, theme }) {

        const screens = [ 'xl','lg','md', 'sm', 'xs'];

        const columns = theme('columns').forEach((col) => {
            screens.forEach(screen => {
                const classKey = `.${screen}\\:col-${col.columns}-${col.gap}`;
                const value = {
                    '> *' : {
                        width: `calc((${col.width} / ${col.columns}) - (${col.gap} * (${col.columns} - 1) / ${col.columns}) - 0.02px)`,
                        margin: `0 ${col.gap} ${col.gap} 0`
                    }
                };
                let screenKey = `@screen ${screen}`;
                addComponents({[screenKey] : {[classKey] : value}});
            });
        });

        theme('columns').forEach((col) => {
            screens.forEach((screen, index) => {

                const classKey = `.${screen}\\:col-${col.columns}-${col.gap}`;
                let selector = `> *:nth-of-type(${col.columns}n)`;

                const value = {
                    [selector]: {
                        marginRight: 0
                    }
                };
                let screenKey = `@screen ${screen}`;
                addComponents({[screenKey] : {[classKey] : value}});
            });
        });
    }
};`

One more thing I'd like to explain. I realize the screens defined in the config file might look a bit odd but it is my preferred use case and there's no way I could possibly change it.

**Comment by cizza** [comment]
I have been fiddling with this component plugin little bit more and although I think it would be a nice feature to have to be able to define custom screens in the plugins, I'm abandoning this component. It's simply not worth the time, it will be very difficult to implement the side effect to work properly. I'll use native grid for this. I'll leave this opened for now, if you'll consider implementing the feature.

**Comment by adamwathan** [comment]
Sorry I don't think I totally understand what you want to do. Do you want your plugin to completely override the screens for all utilities for the whole build? Or do you just want your plugin to use different screens than the rest of Tailwind? Either way it doesn't sound like something I want to support with any first class feature but if you want to go in to more detail happy to discuss alternative solutions that can be done in user-land.

**Comment by cizza** [comment]
Hi Adam, 

sorry for not being clear about this. I would like to be able to supply the screen sizes for the plugin only, not to override the whole build. I will have to get back on this in the future. I'm sure I'll get to a use case and I will supply a detailed example. Let's keep this closed. Thank you.
