### ISSUE TITLE
[Feature Proposal] Loading spinners and progress bars

### ISSUE THREAD

**Issue by brpaz** [tailwindcss/tailwindcss#1276]
Hello.

I am starting working with Tailwind and has been a great experience so far. 
I came to the necessity of implementing a loading spinner in a button when submitting a form. 

I found this [plugin](https://github.com/aniftyco/tailwindcss-spinner) that does what I need, but I think it would be nice to have something like this built-in tailwind.

Loading indicators are a very common need for all kinds of applications.

What do you think?

Thank you.

**Comment by bourhaouta** [comment]
I think spinners are more of an UI than an utility :thinking:

**Comment by adamwathan** [comment]
This is a bit too opinionated to be in Tailwind core I think.

@brandonpittman is working on a plugin you might be interested in that seems to help with this a bit at least:

https://www.npmjs.com/package/tailwindcss-plugin-delight

**Comment by hacknug** [comment]
@brpaz wouldn't mind expanding `tailwindcss-spinner` if you have any ideas for it. Just open an issue and we can discuss it if you have something in mind 👍

**Comment by brandonpittman** [comment]
I'm gonna have to start working on the delight plugin again. 👷🏻
