### ISSUE TITLE
output classes mapped to pojo object.

### ISSUE THREAD

**Issue by ericwooley** [tailwindcss/tailwindcss#1282]
I'm trying to find a way where I can comfortably get the class names in js. Hopefully this is already done. Ideally I'm looking for a plugin(?) which would create a javascript (or typescript) file that looks like this:

```ts
export default {
  flex: 'flex',
  flexInitial: 'flex-initial',
  //...
  bgRed100: 'bg-red-100',
  bgRed200: 'bg-red-200',
  //...
  textRed100: 'text-red-100',
  textRed200: 'text-red-200',
  // ...
}
```
Theoretically jsdoc comments could be added from wherever the docs are generated from the website.

I have been looking for a way to pull this off, and haven't found anything yet. Apologies if this is already a solved issue! 

My use case is to use tailwind with https://github.com/JedWatson/classnames. EG: 

```tsx
import tw from './twAsJS' // or whatever
import cx from 'classnames'

export const Input = (props) => 
  <input {...props} className={cx({[tw.bgRed100]: props.error, [tw.ml1]: true, [tw.p4]: true] })} />
```

Using a POJO, i could get autocomplete, typesafety, etc...

**Comment by adamwathan** [comment]
Nothing really built in to Tailwind to do this and a bit out of scope I think. You could write a regular PostCSS plugin that walks your CSS and builds up this object without a ton of work though, I bet it is only 5-10 lines of JS 👍
