### ISSUE TITLE
Escape classnames that start with a number need to be escaped

### ISSUE THREAD

**Issue by samselikoff** [tailwindcss/tailwindcss#1287]
I tried using a string that started with a number for a custom responsive screen size and it didn't work, because the number wasn't escaped.

I was able to make it work on my own, here's what the escaped class for `1black` looks like

```js
CSS.escape('1black') // "\31 black"
```

and I was able to define the corresponding class like this

```css
.\31 black {
  background-color: black;
}
```

and use it like this: `<div class='1black'>Text</div>`.

If we escape it we could use keys like `3xl` for responsive prefixes, to match the conventions Tailwind uses for tshirt sizes.

**Comment by lateek35** [comment]
I think they didn't handle this case as it doesn't follow the [W3C specification](https://www.w3.org/TR/CSS21/syndata.html#characters) about classes name. 
Ideally, they shouldn't start with a digit, two hyphens, or a hyphen followed by a digit.

**Comment by samselikoff** [comment]
Ah I see. I just tried it out and it seemed to work but that seems to be legitimate.

**Comment by adamwathan** [comment]
From that same spec:

> ...and "\32" is allowed at the start of a class name, even though "2" is not).

So looks like it's fine as long as it's escaped. I think I should probably escape them no matter what and if it's a problem in some browser that can be on the user to decide if they want to use a number-prefixed breakpoint or not. We don't ship with any by default so no problems there.

**Comment by adamwathan** [comment]
This already works fine, Sam was on an old version of Tailwind 👍
