### ISSUE TITLE
[Question] shouldn't this "/" be escaped in the regex provided in the docs?

### ISSUE THREAD

**Issue by mustafawm** [tailwindcss/tailwindcss#1296]
Hello,

Shouldn't the `/` be escaped (`\/`) in the below regex [docs](https://tailwindcss.com/docs/controlling-file-size/#writing-purgeable-html)

```
/[\w-:/]+(?<!:)/g
```

![Screen Shot 2020-01-07 at 8 29 19 am](https://user-images.githubusercontent.com/13101565/71861126-db3e4c00-3127-11ea-85f2-4c5bf6bc654d.png)

**Comment by adamwathan** [comment]
Works fine in JavaScript, try it out 👍🏻
