### ISSUE TITLE
".container" doesn't get the custom prefix applied to it

### ISSUE THREAD

**Issue by Sammyjo20** [tailwindcss/tailwindcss#1297]
I've just started using the `prefix` option to add a `qh-` prefix to all of my classes, but this prefix isn't applied to `.container`. Would it be useful to either add a customisation option in the `container` options for this prefix, or simply prepend the prefix on to the class during compilation?

**Comment by adamwathan** [comment]
The prefix should definitely be applied to the container, here's a demo showing that:

https://tailwind.run/wF9f4n/2

(Check the CSS -> compiled tab)

Can you create a GitHub repo that reproduces the issue?

**Comment by Sammyjo20** [comment]
Ah! It was my silly mistake, in a part of my app I'm caching the stylesheet and I forgot to clear the cache before making all of these changes!

Sorry about that, Adam!
