### ISSUE TITLE
Atomic CSS 

### ISSUE THREAD

**Issue by benfrain** [tailwindcss/tailwindcss#13]
Hello, could you explain how tailwind differs from Atomic CSS (http://acss.io)? 

Are there any fundamental design differences that led to you creating something different rather than using an existing utility framework such as Atomic?

May also be good to link to 'prior art' such as Atomic in this respect within the docs?

**Comment by niallobrien** [comment]
For starters, look at the syntax of the Atomic library; I nearly puked and immediately closed the tab. :rofl:

**Comment by joshmanders** [comment]
oh god, I didn't even notice that, @niallobrien. That syntax is hideous.

**Comment by VinSpee** [comment]
syntax is a matter of opinion. I think an actual answer would be more useful.

Conceptually they're similar. The primary differences IMO:

- tailwind has a set of opinions in an effort to make it practical, whereas Atomic CSS doesn't, in an effort to be more flexible.
- Atomic CSS's [Atomizer](https://acss.io/guides/atomizer.html) ensures your CSS output is as small as possible, whereas tailwind will give you a full stylesheet, no matter what you're actually consuming.

**Comment by benfrain** [comment]
@VinSpee thanks 👍

**Comment by niallobrien** [comment]
Correct, though I liken it more to Tachyons or BassCSS.

**Comment by sebastienbarre** [comment]
Definitely closer to Tachyons. This project has [nice colors](https://tailwindcss.com/docs/colors/), and good (in-progress) doc, though it could use a [components example gallery](http://tachyons.io/components/)) in the long-run. I do like Tachyons [type scale](http://tachyons.io/docs/typography/scale/) and [measure](http://tachyons.io/docs/typography/measure/) better, but, you know, taste. Keep up the great work.

**Comment by DCzajkowski** [comment]
Tailwind has also awesome utilities that work with PostCSS like `@apply` or `@responsive`.

**Comment by davidhemphill** [comment]
Really enjoying the discussion here! We're working hard on refining the messaging around the commonalities and differentiation between other popular frameworks, and will be making some changes in that direction soon.

That said, we're trying to keep the main repo's issue tracker for bugs, issues and feature suggestions. I'd love it if you'd continue the discussion over at our [/discuss](https://github.com/tailwindcss/discuss/issues) repo. Thank you!

**Comment by thierryk** [comment]
@niallobrien here is the "[big picture](https://github.com/jitendravyas/Q-A/issues/5)".
