### ISSUE TITLE
Confusing webpack instructions

### ISSUE THREAD

**Issue by simonh1000** [tailwindcss/tailwindcss#1300]
I cannot get webpack to work. The biggest blocker is that postcss-import provides this as an example reads:
```
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {},
    'cssnano': {}
  }
}
```
whereas as the [tailwind docs](https://tailwindcss.com/docs/installation#webpack) refer to 
```
module.exports = {
  plugins: [
    // ...
    require('tailwindcss'),
    require('autoprefixer'),
    // ...
  ]
}
```
plugins is a list, rather than an object and it is not at all clear how to combine them

**Comment by adamwathan** [comment]
They are just alternative syntaxes for the same thing. Personally I prefer the array syntax because it's more flexible.

The equivalent array version of your first example is this:

```
module.exports = {
  parser: 'sugarss',
  plugins: [
    require('postcss-import'),
    require('postcss-preset-env'),
    require('cssnano'),
  ]
}
```

You can learn about PostCSS's config format here: https://github.com/michael-ciniawsky/postcss-load-config

**Comment by simonh1000** [comment]
thanks a lot. Feel free to close but do keep in mid that tailwind was my introduction to postcss, so this sort of discrepancy comes early in the learning curve
