### ISSUE TITLE
New utilities with @apply?

### ISSUE THREAD

**Issue by Waleedov** [tailwindcss/tailwindcss#1302]
Hi,
How can I use the @apply feature when adding my custom utilities?
`
module.exports = {
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.rotate-0': {
          transform: 'rotate(0deg)',
        },
        '.rotate-90': {
          transform: 'rotate(90deg)',
        }
      }
      addUtilities(newUtilities)
    }
  ]
}
`

But when I do this
`
.title {
	@apply rotate-90;
}`
I get errors.

**Comment by adamwathan** [comment]
Should work fine, here's a demo using your exact code that works:

https://tailwind.run/zyXrs2/2

**Comment by Waleedov** [comment]
Thank you! your demo made it very clear.

**Comment by AlfieElizondo** [comment]
Still doesn't wok with pseudo selectors like focus: or hover: right?

Read several discussions but couldn't find the one with the solution just the feature request
