### ISSUE TITLE
Leading-none with truncate crops some letters

### ISSUE THREAD

**Issue by poulainv** [tailwindcss/tailwindcss#1317]
Hi,

**Bug description**

When I use `leading-none truncate` on text, some letters as `g` and `j` are cropped.
I often use it in order to handle text alignement, not sure it's a best practice.

**Bug reproduction**
https://codesandbox.io/s/static-52bue?fontsize=14&hidenavigation=1&theme=dark

**Comment by adamwathan** [comment]
This is just how CSS works unfortunately, nothing we can do to change how this works on our end. `overflow: hidden` plus `line-height: 1` will result in things being cropped.

**Comment by vricop** [comment]
> Hi,
> 
> **Bug description**
> 
> When I use `leading-none truncate` on text, some letters as `g` and `j` are cropped.
> I often use it in order to handle text alignement, not sure it's a best practice.
> 
> **Bug reproduction**
> https://codesandbox.io/s/static-52bue?fontsize=14&hidenavigation=1&theme=dark

That's a CSS bug. I

> This is just how CSS works unfortunately, nothing we can do to change how this works on our end. `overflow: hidden` plus `line-height: 1` will result in things being cropped.

And padding too.

**Comment by vricop** [comment]
> This is just how CSS works unfortunately, nothing we can do to change how this works on our end. `overflow: hidden` plus `line-height: 1` will result in things being cropped.

And padding.
