### ISSUE TITLE
[1.2.0] Translate not working without x or y value

### ISSUE THREAD

**Issue by TomS-** [tailwindcss/tailwindcss#1320]
On the 1.2.0 documentation it is stated:
```
// .translate-{distance}
// .translate-x-{distance}
// .translate-y-{distance}
// .-translate-{distance}
// .-translate-x-{distance}
// .-translate-y-{distance}
```
However, from what I can tell only:
```
// .translate-x-{distance}
// .translate-y-{distance}
// .-translate-x-{distance}
// .-translate-y-{distance}
```
is available. Trying to do -translate-1/2 does nothing but I expect it to define -50% on the x and y axis.

**Comment by adamwathan** [comment]
Yep good catch that's a mistake in the release notes, only the separate directions are provided 👍
