### ISSUE TITLE
Font weight does not display correctly on Linux

### ISSUE THREAD

**Issue by khanhhuy** [tailwindcss/tailwindcss#1328]
Reproduction link: https://tailwindcss.com/docs/font-weight/#app

OS (both are booted from a fresh USB iso):
- Ubuntu 19.10
- Linux MX 19

Browser: 
- Chromium: Version 79.0.3945.117
- Firefox: 72.0.1

![image](https://user-images.githubusercontent.com/11194590/72962235-5ec59180-3de6-11ea-8413-80bc8a694176.png)

**Comment by vricop** [comment]
> Reproduction link: https://tailwindcss.com/docs/font-weight/#app
> 
> OS (both are booted from a fresh USB iso):
> 
>     * Ubuntu 19.10
> 
>     * Linux MX 19
> 
> 
> Browser:
> 
>     * Chromium: Version 79.0.3945.117
> 
>     * Firefox: 72.0.1
> 
> 
> ![image](https://user-images.githubusercontent.com/11194590/72962235-5ec59180-3de6-11ea-8413-80bc8a694176.png)

What fonts are you loading. Make sure that font has those font families or the browser will pick the closest weight. ¿Is that Liberation sans?

**Comment by khanhhuy** [comment]
Hi Víctor,

Thank you for your reply, I just checked and the rendered font is Liberation sans.

So I guess the tailwind website doesn't provide its own font (e.g. from Google fonts) but it depends on the installed fonts on the system right?

**Comment by vricop** [comment]
> Hi Víctor,
> 
> Thank you for your reply, I just checked and the rendered font is Liberation sans.
> 
> So I guess the tailwind website doesn't provide its own font (e.g. from Google fonts) but it depends on the installed fonts on the system right?

[Liberation sans](https://fonts.adobe.com/fonts/liberation-sans#fonts-section) only has regular and bold (besides italics)

No, Tilwind doesn't include fonts. [Inter](https://rsms.me/inter/) font can be downloaded here. Hope that helps.
