### ISSUE TITLE
with important: '.myclass' I loose hover

### ISSUE THREAD

**Issue by matteofrana** [tailwindcss/tailwindcss#1334]
If in my tailwind.config.js I set
`important: '.react-bricks'`

inside a `<div class="react-bricks">` I correctly have all the Tailwind classes, but the `hover:___` classes are not applied.

**Comment by adamwathan** [comment]
From another issue:

> Hey thanks for raising this again, right now this is just not supported by design, the feature is really only meant to be used with IDs currently (since the goal is to raise specificity, not to scope things).
> 
> I've pushed an update to explicitly forbid including classes in the `important` option to help people avoid running into this:  
>
> https://github.com/tailwindcss/tailwindcss/commit/ad850ac49128dfcc292f0025c8c42f26bc26c735
