### ISSUE TITLE
Passing Array to addBase outputs duplicate CSS

### ISSUE THREAD

**Issue by isoppp** [tailwindcss/tailwindcss#1335]
## Summary

I attempted to reuse font-family settings which are in theme.
But when passing the Array using `config('theme.fontFamily.xxx')` to addBase, duplicated CSS will be created.

### tailwind.config.js

*Originally I defined 'display' for headings and wanted to setup to heading tags.
*If pass a connected string directly, it works.

```
module.exports = {
  corePlugins: {
    preflight: false,
  },
  plugins: [
    function({ addBase, config }) {
      addBase({
        h1: { fontFamily: config('theme.fontFamily.serif') },
        margin: ['2px', '4px'],
      })
    },
  ],
}
```

### css

```
@tailwind base;
```

### Result 

```
h1 {
  font-family: -apple-system;
  font-family: BlinkMacSystemFont;
  ...
  margin: 2px;
  margin: 4px
}
```

### My Expectation

It should be same as theme setting output like:

```
h1 {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
  margin: ??? being 4px only or it would be better to output some message
}
```

---

I saw the codebase for solving this problem, but I was not able to imagine how to use Array and how the situation do users want to use it in.

My idea is to prohibit use Array or to convert from Array to string automatically and show a warning because it always causes duplicated CSS.

Are there good ideas?
 I'm willing to contribute to solving it if the solution looks not tough for me :)

**Comment by adamwathan** [comment]
Don't use arrays for this, use strings. The CSS-in-JS syntax expects you to author it like CSS:

```js
addBase({
  h1: { fontFamily: config('theme.fontFamily.serif').join(', ') },
  margin: '2px 4px',
})
```

No plans to introduce any additional complexity or magic to how this works, just write it like CSS 👍

**Comment by isoppp** [comment]
I understood your intention.
Thank you for taking the time😄
