### ISSUE TITLE
Grid w-1/2 gives error in pug

### ISSUE THREAD

**Issue by Venegrad** [tailwindcss/tailwindcss#1339]
Hi guys, how i can write grid syntax in pugjs? When i try write .w-1/2, that gives and error. I can div(class="w-1/2") but it weird.. Maybe tailwind have option like "separator" but for grid?

**Comment by tlgreg** [comment]
Pug reserves every special character for future use in its own syntax and doesn't have a way to escape inside the class-name shorthand.

On tailwind's side, there is no configuration option for this specifically, the names inside the config can be changed freely though. This naming convention is used only in `width` at the moment and also in `translate` in the upcoming `1.2` release.

Related issue: https://github.com/tailwindcss/tailwindcss/issues/785
