### ISSUE TITLE
TailwindCSS 🇫🇷 documentation's complete!

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#134]
Hey guys, thank you for your amazing work 😁

I decided to contribute and help you by translating Tailwind documentation to french 🇫🇷!
You can find files here: https://github.com/HapLifeMan/tailwindcss-fr

Hope you'll integrate it soon ❤️

**Comment by m1guelpf** [comment]
Maybe this could make use of the Laravel language files? I don't know for sure, but I think you can use them with Jigsaw.

**Comment by reinink** [comment]
Wow, this is an impressive amount of effort! Which makes me a little sad to say that at this point we don't plan to offer multiple languages on the official Tailwind CSS site. It's simply too much of maintenance burden.

That said, there is nothing stopping you maintaining this on another website.

I hope that makes sense. Thanks for your interest in this project! 💪

**Comment by HapLifeMan** [comment]
I understand @reinink... At least is it possible to maintain a French documentation on a `fr` subdomain of `tailwindcss.com` where a Github repo were based? :/

**Comment by reinink** [comment]
My concern here is this will still ultimately look like official documentation. We're really going for more of the [Bootstrap approach](https://getbootstrap.com/docs/4.0/about/translations/) to translations. Maybe we'll even add a page some day that links to community driven language sites, assuming we get a few.

**Comment by sgraewe** [comment]
So we can create a fork and you will link the translations? :)
