### ISSUE TITLE
Your current PostCSS version is 7.0.26, but postcss-functions uses 6.0.23

### ISSUE THREAD

**Issue by mattbasile** [tailwindcss/tailwindcss#1340]
Hey Guys,

Loving tailwind, but running into a little issue with my build. 
Trying to create some custom themes by referencing other values, https://tailwindcss.com/docs/theme/#referencing-other-values, but with the latest version of PostCSS `^7.0.26` I get this error:
```
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.26, but postcss-functions uses 6.0.23. Perhaps this is the source of the error below.
postcssNode: Declaration {
    raws: {},
    type: 'decl',
    prop: 'background-color',
    value: [Function: light],
    parent: Rule {
      raws: {},
      type: 'rule',
      nodes: [Array],
      selector: '.bg-primary-light',
      lastEach: 4,
      indexes: [Object],
      parent: [AtRule],
      source: [Object]
    },
```
Looks like the function I've implemented for `primary-light` is not running, and when I checked Tailwind's dependencies it looks like `postcss-functions` is relying on 6.0.23. 

Without bumping down my PostCSS dependency are there any alternatives or solutions?

For reference here's a basic example of what's going on in my tailwind.config.js:
```
module.exports = {
  theme: {
    colors: {
      blue: {
        main: '#001C43
     },
      primary:{
        main: (theme) => theme.colors.blue.main,
     },
  },
},
```

**Comment by tlgreg** [comment]
There are several issues with the above config unfortunately.

- `theme` is a function, you can't access the theme values directly on it as properties.
- `theme` is only allowed on the plugin namespace level, not any deeper.
- The above example, referencing colors from colors is not supported as it results in an infinite loop.

Docs on referencing other values in the config:
https://tailwindcss.com/docs/theme#referencing-other-values

In the above case, I probably wouldn't even use the `theme` reference function if this is purely the desired result, just go very vanilla javascript.
```js
const brandBlue = '#001C43`

module.exports = {
  theme: {
    colors: {
      blue: {
        main: brandBlue,
      },
      primary: {
        main: brandBlue,
      },
    },
  },
}
```
**Note:** This overrides any default color as it is not under `theme.extend`.

**Comment by adamwathan** [comment]
Yeah this is a mistake in how your config is constructed, not an issue with dependencies. Second what @tlgreg suggested 👍
