### ISSUE TITLE
Pseudo selector styles do not apply when referencing a component class with an "alias" class.

### ISSUE THREAD

**Issue by DerekAlanGilbert** [tailwindcss/tailwindcss#1344]
For example: 

If I'm adding a component like this:

```
    '.btn': {
      backgroundColor: theme('backgroundColor.teal.default'),
      color: theme('backgroundColor.white'),
      '&:hover': {
        backgroundColor: theme('backgroundColor.teal.hover')
      },
```

and I go to use it in a fashion like so:

```
.some-specific-button {
@apply btn;
}
```

The hover class will not be applied to a button with the `some-specific-button` class.

**Comment by adamwathan** [comment]
Hey @DerekAlanGilbert! Right now @apply is not designed to be used with complex classes like your `btn` example and only meant to be used with simple utilities that don't include pseudo-selectors or have extra styles defined in media queries, etc.

Personally I would recommend using a "multi-class" pattern here:

http://nicolasgallagher.com/about-html-semantics-front-end-architecture/#component-modifiers

If you really want to be able to do what you're trying to do though maybe look at [postcss-extend-rule](https://github.com/csstools/postcss-extend-rule).

Closing as no plans to make @apply support this currently.

**Comment by DerekAlanGilbert** [comment]
@adamwathan thanks for looking into it, i'll take a look at those!
