### ISSUE TITLE
[1.2.0] Unable to exclude new core plugins in tailwind config

### ISSUE THREAD

**Issue by occupant** [tailwindcss/tailwindcss#1364]
Hi there,

Just updated to v1.2 today and noticed that autoprefixer was really noisy - I'm using `autoprefixer grid: autoplace` for IE 11 CSS grid support. It seems the new grid utilities are causing the warnings because they're unable to prefix for IE 11. [IE support](https://github.com/postcss/autoprefixer#grid-autoplacement-support-in-ie)

So, I decided I would disable the new utilities for now, updated the corePlugins in my tailwind.config.js, setting the new utilities to `false` but they all still are compiling. If I revert back to 1.1.4, my utitlities set to false (ie. `wordBreak`) work as expected and the CSS for these is excluded.

**Comment by Macxim** [comment]
Hi, could you elaborate on how you excluded the new core plugins?
I just did this and it's working fine for me.

```js
  corePlugins: {
    // Disable Grid classes
    gap: false,
    rowGap: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridAutoFlow: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    columnGap: false
}
```

**Comment by occupant** [comment]
@Macxim I have added them to the corePlugins in my tailwind.config.js. 

However, I've tried again on a few repositories this morning and it looks like the issue must have been with my code. Disabling the core plugins does seem to work as intended. Apologies for the confusion - facepalm
