### ISSUE TITLE
[1.2.0] Unrecognised input. Possibly missing opening

### ISSUE THREAD

**Issue by nghiepit** [tailwindcss/tailwindcss#1365]
Hi guys,

I'm using less and `@import '~tailwindcss/dist/utilities.css'`
```
Unrecognised input. Possibly missing opening '{'
      in /***/node_modules/tailwindcss/dist/utilities.css (line 10114, column 0)
[ error ] ./resources/stylesheets/styles.less

  --transform-scale-y: 0
}
```
in `utilities.css` contains invalid syntax
```
.scale-0 {
  --transform-scale-x: 0;
  --transform-scale-y: 0
}
```

**Comment by tlgreg** [comment]
This seems like a `less` issue not being able to parse the custom property without the semicolon.
The missing semicolon is valid as the last property and `postcss` generates the css output that way.
https://github.com/less/less.js/issues/3396 seems related as less fails with a few other valid custom property declarations too.

**Comment by nghiepit** [comment]
Thanks @tlgreg

**Comment by matthew-dean** [comment]
FYI this isn't related to custom properties, it's just a historical Less requirement that declarations end in semi-colons.
