### ISSUE TITLE
Different output for transition-slower & duration-500

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindcss/tailwindcss#1370]
I have the following code where the `Indigo` button (`transition-slower`) rotates only text while `Pink` button (`duration-500`) rotates the whole button.

```css
<div class="min-h-screen flex justify-center items-center">
	<button class="transition transition-slower ease-in-out transform hover:rotate-180 bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Rotate Me!</button>
	
	<button class="transition duration-500 ease-in-out transform hover:rotate-180 bg-pink-600 text-white font-bold py-2 px-4 rounded-lg">Rotate Me!</button>
</div>
```

The notable difference in both button’s code is `transition-slower` & `duration-500`.

And the weird part is as discussed in this PR https://github.com/tailwindcss/tailwindcss/pull/1273 both have similar CSS properties, i.e, `transition-duration: 500ms;`

Here’s a demo GIF in action (~2.8 MB)👇

![tailwind-err](https://user-images.githubusercontent.com/16436270/74011723-86078b80-49ae-11ea-84cf-faa41d792309.gif)

**Comment by deadcoder0904** [comment]
On further investigation, I found https://github.com/tailwindcss/tailwindcss/pull/1273/commits/d5199e40756691b149c6a1b998bf62aedd80f30d where all the `transition-*` utilities are replaced with `duration-*`. Is this correct so I can close this thing?

**Comment by adamwathan** [comment]
Yeah there is no transition-slower utility. The documentation is the canonical source of truth for this stuff:
https://tailwindcss.com/docs/transition-duration/#app
