### ISSUE TITLE
cannot use max-width with media queries

### ISSUE THREAD

**Issue by deebov** [tailwindcss/tailwindcss#1371]
I am trying to use desktop first media queries by overwriting the default screen property like this:

```json
    theme: {
        screens: {
            xl: { max: "1079px" },
            lg: { max: "1023px" },
            md: { max: "767px" },
            sm: { max: "639px" }
        }
}
```

but it doesn't add max-width media queries. Instead, it just overwrites the default min-width queries

**Comment by ryanfitzer** [comment]
Use the [`raw` key](https://tailwindcss.com/docs/breakpoints/#custom-media-queries) instead:

```js
theme: {
  screens: {
    xl: { raw: "screen and (max-width: 1079px)" },
    lg: { raw: "screen and (max-width: 1023px)" },
    md: { raw: "screen and (max-width: 767px)" },
    sm: { raw: "screen and (max-width: 639px)" }
  }
}
```

**Comment by adamwathan** [comment]
The JS objects are merged so you are replacing the keys when you define new screens with the same names. If you want screens that have both a max width and a min width, use this sort of syntax:

```js
// tailwind.config.js
module.exports = {
  theme: {
    screens: {
      'sm': {'min': '640px', 'max': '767px'},
      'md': {'min': '768px', 'max': '1023px'},
      'lg': {'min': '1024px', 'max': '1279px'},
      'xl': {'min': '1280px'},
    },
  }
}
```
