### ISSUE TITLE
Is there a way to get a function to convert tailwind classes into CSS.

### ISSUE THREAD

**Issue by GTDev87** [tailwindcss/tailwindcss#1376]
Feature Idea.

I like using CSS in JS features and I have used [Babel Plugin Tailwind Components](https://github.com/bradlc/babel-plugin-tailwind-components), but it seems that the project is a bit behind in the version and I'm having some trouble using the next branch [see here](https://github.com/bradlc/babel-plugin-tailwind-components/issues/52).  

I was wondering if there is a way to expose a function for javascript that would convert a tailwind css class into js like the `@apply` function so I can use it in my JSX.  I know this is outside the scope of the project a bit but it could help the Babel Plugin Tailwind Components repo and also it would help me if I can just run it myself without a String Literal in my own codebase.

Thanks

**Comment by adamwathan** [comment]
Best bet is probably a custom tool that uses PostCSS to try and find a matching class and grab the declarations. Unfortunately not something I can prioritize including in Tailwind itself or providing a first-party solution for any time soon 😞
