### ISSUE TITLE
Diffrent files

### ISSUE THREAD

**Issue by cdidn** [tailwindcss/tailwindcss#1377]
hey sir im see css files from your tutorials https://polished-sunset-0ex44e5cb9xt.tailwindcss.com/css/iframe.css?id=750d2760e85086dceab0

its diffrent from your release v1.2.0 in the website?

please answer

**Comment by jgraham44** [comment]
That file is different from the v1.2.0 release.

The difference being the [transitions](https://tailwindcss.com/docs/transition-duration).

Current [cdn link](https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css) to current (1.2.0) css file.

**Comment by ChristianHuff-DEV** [comment]
In addition to changing `transition-slow`/`transition-medium` to i.e. `duration-200`. You also need to add `transform` to the class.

This is how it works for me with v1.2.0:
```html
 <div
        :class="
          sidebarOpen
            ? 'translate-x-0 ease-out duration-200'
            : '-translate-x-full ease-in duration-200'
        "
        class="transform z-30 fixed inset-y-0 left-0 w-64 bg-gray-100 border-r overflow-y-auto sm:static sm:block sm:translate-x-0 "
      >
```

**Comment by adamwathan** [comment]
The files in that demo are using a custom build from before the new APIs were finalized. Don't worry about those files :)
