### ISSUE TITLE
Max-width breakpoints don't work as documented

### ISSUE THREAD

**Issue by Jnforja** [tailwindcss/tailwindcss#1382]
According to the documentation found [here](https://tailwindcss.com/docs/breakpoints/#max-width-breakpoints), to add custom max-width we use the config below:

```
// tailwind.config.js
module.exports = {
  theme: {
    screens: {
      'sm': {'max': '639px'},
      'md': {'max': '767px'},
      'lg': {'max': '1023px'},
      'xl': {'max': '1279px'},
    }
  }
}
```

However, I couldn't make this work when applying two different breakpoints to the same html element. The class targeting the biggest screen resolution overrides the smaller one. Example:
`<div className='lg:w-10/12 sm:w-full'>Hello</div>`, on a 400px screen, lg:w-10/12 will be the one applied instead of sm:w-full

I found a fix for this by changing the order of the screens and changing the prefixes names. 
```
 screens: {
        mxl: { max: '1279px' },
        mlg: { max: '1023px' },
        mmd: { max: '767px' },
        msm: { max: '639px' },
      }
```

Still, I believe it would be useful for the community to either change tailwind to match the documentation, or to change the documentation to match tailwind current behavior.

**Comment by macagoraga** [comment]
I think you want to do:

`<div className='lg:w-10/12 w-full'>Hello</div>`

Without "sm" so w-full is applied for all up to "lg"

**Comment by adamwathan** [comment]
You shouldn't need to change the prefix names but you're right that the order does matter, the CSS is generated in the same order you specify in your config and since declaration order determines which class "wins" in CSS, you need to make sure you define things in the order you want.

Would welcome a PR to the docs that reverses the order of the max-width breakpoint example to avoid any confusion here 👍🏻

**Comment by Jnforja** [comment]
I'm sorry I wasn't explicit enough. 

If I change the order of the prefixes, but do not change the prefixes names, the class that's targeting the bigger screen will be applied instead of the smaller one. So in order for the documentation to be correct without changing the code, that will have to be pointed out.

**Comment by jen-prince** [comment]
I also am experiencing what @Jnforja mentions about needing to rename the prefixes to keep the bigger screen class from being applied instead of the smaller one.
