### ISSUE TITLE
Position sticky in iOS Safari

### ISSUE THREAD

**Issue by jshah4517** [tailwindcss/tailwindcss#1385]
I've been using the `sticky` utility in Tailwind which works great, but noticed today that it wasn't working in iOS (version 12.4.5) Safari.

Checking https://caniuse.com/#search=position%3Asticky it seems to say you need to set the CSS as the following. I've tried this in my project by adding it manually and it works.
```
position: -webkit-sticky;
```

Just to note, it says the same for Safari (MacOS), but I didn't seem to need to add the above code as it was already working.

Would it be possible to have this automatically added to the `sticky` utility? So it should generate the following code:
```
position: -webkit-sticky;
position: sticky;
```

I'd be happy to submit a PR if this is something you'd be willing to consider.

**Comment by adamwathan** [comment]
You should use autoprefixer to handle this sort of thing 👍🏻 There's a bunch of other things it will fix for you as well.

https://tailwindcss.com/docs/browser-support#vendor-prefixes

**Comment by jshah4517** [comment]
Works perfect, thanks! 👍
