### ISSUE TITLE
Import just specific modules like spacing and typography [feature request]

### ISSUE THREAD

**Issue by JuanmaMenendez** [tailwindcss/tailwindcss#1386]
Will be great to have the option of just Import specific modules we need in our projects like spacing and typography but not borders and transitions. 

That would save the user the need to download css code that he will never use.

**Comment by adamwathan** [comment]
Already possible!

https://tailwindcss.com/docs/configuration/#core-plugins

> If you'd like to whitelist which core plugins should be enabled, provide an array that includes a list of the core plugins you'd like to use:

```js
// tailwind.config.js
module.exports = {
  corePlugins: [
    'margin',
    'padding',
    'backgroundColor',
    // ...
  ]
}
```
