### ISSUE TITLE
Add `cursor-grab` and `cursor-grabbing`

### ISSUE THREAD

**Issue by wvffle** [tailwindcss/tailwindcss#1391]
Hey!
I'm in need of `cursor-grab` and `cursor-grabbing` classes. They may come in handy when designing components with drag and drop support ;)

**Comment by hacknug** [comment]
You can altready customize your cursors using your config file as shown in the docs: https://tailwindcss.com/docs/cursor/#app

**Comment by wvffle** [comment]
Thanks! I didn't see it for some reason

**Comment by dfallman** [comment]
Bump. Understand you can customize this but I wonder what the rationale is for not including the grab and crosshair cursors our of the box? Surely that can't add much to the overall file size?

I think many of us (including myself) are just lazy and can't be bothered with the config file for this and will just add `style="cursor: grab;"` where we need it.

**Comment by hacknug** [comment]
Maybe it's a good time to revisit now that we have the JIT engine and v3 is otw.

@adamwathan want me to open a PR with the rest of the default values?

**Comment by jeffphp** [comment]
With TailWind 3, you cqn add these custom classes : `cursor-[grab]` and `cursor-[grabbing]`

**Comment by hacknug** [comment]
> With TailWind 3, you can add these custom classes : cursor-[grab] and cursor-[grabbing]

Both `.cursor-grab` and `.cursor-grabbing` are supported by default. All keyword values have been supported for a while so I think everything is properly documented as it is. Maybe I'm missing something?

**Comment by dfallman** [comment]
Yes. The discussion above refers to version 2.x
