### ISSUE TITLE
[Change Proposal]: Change default z-index increment to +1 (not +10)

### ISSUE THREAD

**Issue by TurboTobias** [tailwindcss/tailwindcss#1392]
Love Tailwind ❤️ 

**Proposal**
Z-index currently increments by +10 by using `.z-0`, `.z-10`, `.z-20`, etc.

I suggest to change the default to increment by +1  `.z-1`, `.z-2`.

It's easier to keep control of orders and not get into stack order wars. Increasing the stack order by +10 is to my experience rarely, if ever, necessary. Increasing the stack order by 1 more than other stacks will put it on the top of the stack.

Increasing the stack order by +10 is parallel to standing in queue in Italy or India where someone can take advantage of a gap in the queue and just inconsiderately insert themselves +10 spots. Yes, I'm queue culture discriminating against the Italians and Indians.

**Comment by royvanv** [comment]
This would cause a breaking change, so I doubt it will change in 1.x. 

I reckon the steps of 10 are implemented to be able to add values in between. You could override them in the config if you want to.

**Comment by tlgreg** [comment]
Imo gaps in the z-index have bigger pros with tailwindcss, then cons.
Inserting a new z-index can only happen in one place, which means the chance that a new z-index is redundant is also a lot smaller.
While if you need to shift values to insert a new one then you'll have to change a lot of classes that might be scattered around in many files.

Personally I prefer gaps in values and more semantic names in the classes, but those names are hard to generalize for a default config.

**Comment by TurboTobias** [comment]
@royvanv makes sense 👍 just for clarification, I assumed this to be a 2.0 change, because of it being just a slight nice-to-have. The config override works great 👌

@tlgreg 
Correct me if I'm wrong (because I am probably) but why do you need gaps? To my experience you wouldn't need gaps because there's an "organic" z order of elements until you use z-indexes which overrules those native orders, making redundant z-indexes "organically" fall above or below each other if conflicting, in which case you just need to increment by one if the order is wrong - just like z-indexes are intended (I assume) to be used.

If you have many redundant z-indexes that must be updated in multiple files, how does gaps (0, 10, 20) solve that? If primarily using tailwind you would just conflict 10 = 10 and 20 = 20, mirroring the conflict that can occur with z-index 1 and 2.

**Comment by TurboTobias** [comment]
Another benefit I see from keeping z-indexes low are parallel to low css specificity. Just like using BEM is fantastic because you have so little specificity issues because it's usually just 10 points (one .class) that all styles adhere to (in addition to the order in which they're implemented). Imagine if having z-index with 10, 20, 30 - and then someone needs to get in between that 10 and 20 and inserts an 11 somewhere; you potentially have 30 layers of z indexes (although not likely). What you do have is a bad stomach from the unknown. Inspecting every suspected element from being the one that ruins the z-index order instead of just knowing that rarely anything will (at least should) exceed 4

**Comment by adamwathan** [comment]
Yeah no plans to change this, I don't see any actual disadvantage to using steps of 10 (and I still prefer having the comfort of being able to add an in-between value if I ever really needed it) and it's definitely not worth a breaking change. Thanks though!
