### ISSUE TITLE
reactivity do not work with @apply  

### ISSUE THREAD

**Issue by naschidaniel** [tailwindcss/tailwindcss#1393]
Tailwind is great and i am using it with VueJS.

.content >>> h1 {
@apply text-xl text-red-600 md:text-6xl;
}

leads to.

(2:1) `@apply` cannot be used with `.md\:text-6xl` because `.md\:text-6xl` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.md\:text-6xl` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

.content >>> h1 {
@apply text-xl text-red-600;
}

works.

In the Docs there is nothing written about reactivity. Does reactivity works with @apply.

**Comment by adamwathan** [comment]
Not related to reactivity just a limitation of how apply works:

https://github.com/tailwindcss/discuss/issues/91
