### ISSUE TITLE
:child prefix

### ISSUE THREAD

**Issue by SamGoody** [tailwindcss/tailwindcss#1395]
First, Tailwind is awesome. Thank you very much!!

One case where I think TW's output is error prone (and ugly), is with repeating elements, such as [this example](https://tailwindcss.com/components/cards/):
```
 <div class="px-6 py-4">
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
  </div>
```
This could be solved by extracting a CSS components, but that is not ideal when the rules will only be used in on instance.

### Feature Proposal
I propose adding another prefix `child:`, as in `child:rounded-full`.  
This applies the rule to all of the immediate children of the element, with a lower precedence than classes applied to items themselves, so it can be overruled as needed. Done by adding to TW inheritance rules:
```child\:rounded-full > * { border-radius: 9999px; }```.

This will play to the strengths of Tailwind, and be a good argument for Tailwind over inline CSS. Many times I have wanted to apply a rule to the children, and if it could be through a prefix, that would be amazing.

In addition, you could add a `all:rounded-full` which applies to all descendants, and in this way solve cases such as [here](https://tailwindcss.com/components/navigation/) :
```
<ul class="flex border-b all:inline-block">
  <li class="-mb-px mr-1">
    <a class="bg-white border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="#">Active</a>
  </li>
  <li class="mr-1">
    <a class="bg-white py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold" href="#">Tab</a>
  </li>
</ul>
```

The only downside I see is that it will add to the size of uncompressed Tailwind, perhaps even more than other prefixes. But for regular builds that should not be an issue, and the benefit would be enormous.

Please consider it a few minutes before dismissing - I think it could make for a HUGE difference to Tailwind.

Thanks again!

**Comment by adamwathan** [comment]
Might explore adding this to core in the future but in the mean time check this plugin out, it does just what you're looking for:

https://github.com/benface/tailwindcss-children

**Comment by royvanv** [comment]
> One case where I think TW's output is error prone (and ugly), is with repeating elements, such as [this example](https://tailwindcss.com/components/cards/):
> 
> ```
>  <div class="px-6 py-4">
>     <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
>     <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
>     <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
>   </div>
> ```

In this example you could also add the classes `mr-2 last-child: mr-0`  to achieve the same effect, but this just as ugly. This is how I would write it when using frameworks like Angular or Vue, using their looping (`ngFor`/`v-for`) utilities.

**Comment by adamwathan** [comment]
Closing right now since no concrete plans to add this to core.
