### ISSUE TITLE
[Feature Request] Orientation

### ISSUE THREAD

**Issue by vmitchell85** [tailwindcss/tailwindcss#1397]
It'd be awesome to have some [orientation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/orientation) classes.

My use case was showing (`display: block;`) or hiding (`display: none;`) something on landscape. Not sure if there would be enough people who would need/want this for it to be worth the effort.

Not sure what the best class syntax would be either.

**Comment by tlgreg** [comment]
You can use it as a raw breakpoint currently, the docs even have `orientation` as an example.
https://tailwindcss.com/docs/breakpoints#custom-media-queries
