### ISSUE TITLE
[Feature request] Extend transitions to include transition delay  

### ISSUE THREAD

**Issue by jgraham44** [tailwindcss/tailwindcss#1399]
It would be helpful to extend the default transition helper classes to include 'transition-delay'.

```
.transition-delay-300 {
    transition-delay: 300ms;
}
``` 
I find it useful in working with vuejs transitions.

**Comment by digitiz-ft** [comment]
I think what you're talking about is already in the latest version (1.2.0) of TailwindCSS
Here the [link](https://tailwindcss.com/docs/transition-duration/) to the doc

**Comment by francoistomasi** [comment]
I read wrong ! My mistake 🙄

**Comment by digitiz-ft** [comment]
I read wrong ! My mistake 🙄

**Comment by JayBox325** [comment]
This would be a great addition. 👍🏻

**Comment by matheusalbino** [comment]
Following the pattern, maybe `delay-300` is better. This is a nice addition.

**Comment by philippbosch** [comment]
I would also like to see this happen so I created a PR ☝️. Curious to learn what @adamwathan's thoughts are.
