### ISSUE TITLE
Pseudo Element don't works

### ISSUE THREAD

**Issue by MattixNow** [tailwindcss/tailwindcss#1400]
I try the `:last` and `:first` pseudo element but it don't works,
reproduction : https://codepen.io/MatteoGauthier/pen/ExjWdzo?editors=1111

**Comment by jgraham44** [comment]
@MattixNow did you add first and last to you config?

```
// tailwind.config.js
module.exports = {
  variants: {
    // ...
-   fontSize: ['responsive'], // default
+   fontSize: ['responsive', 'first', 'last']
  }
}
```
Just tried an example base on yours and it worked fine.

```
<div id="app">
   <p v-for="item in items" class="first:text-xl" :key="item">
      {{ item }}
   </p>
</div>
```

**Comment by MattixNow** [comment]
Thanks you for your fast reply
Yes i've forgot it, I hadn't seen it on the documentation (ux issue?)

**Comment by jgraham44** [comment]
No problem! The customization portion is hidden at the bottom of all the categories and can be used with the traditional and [pseudo-class variants](https://tailwindcss.com/docs/pseudo-class-variants).
