### ISSUE TITLE
Does `clear-none` exist?

### ISSUE THREAD

**Issue by mjankowski** [tailwindcss/tailwindcss#1401]
The docs site claims there's a `clear-none` - https://tailwindcss.com/docs/clear/#dont-clear - but it doesn't look like it's defined? https://github.com/tailwindcss/tailwindcss/blob/master/src/plugins/clear.js

**Comment by florianbouvot** [comment]
@mjankowski I create a PR to add this missing classe.

**Comment by adamwathan** [comment]
Got those changes merged in and will tag a release with them soon 👍🏻
