### ISSUE TITLE
Can not apply font- family classes

### ISSUE THREAD

**Issue by assimovt** [tailwindcss/tailwindcss#1411]
👋 I'm trying to apply `.font-mono` but it throws me this error:

```
Syntax error: `@apply` cannot be used with `.font-mono` because `.font-mono` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.font-mono` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree. (33:3)
```

My style definition:

```
.editor {
  @apply text-xs;
  @apply leading-5;
  @apply text-gray-600;
  @apply font-mono;
}
```

When I remove `font-mono`, it works just fine. Tailwind version: `1.2.0`.

What am I doing wrong? Thx!

**Comment by adamwathan** [comment]
Can you share your complete CSS? It does work by default:

https://tailwind.run/5UEWGo

Closing as this is just a configuration/CSS authoring issue but happy to help you get it figured out here still.

**Comment by assimovt** [comment]
Sorry, it was my bad. I had the font family overridden in the config (as per examples) and completely forgot about the monospace. All 👌🏽 Thank you @adamwathan Really awesome project, I am starting to like CSS again 😅
