### ISSUE TITLE
use @apply with stylus 

### ISSUE THREAD

**Issue by yyyang1996** [tailwindcss/tailwindcss#1412]
I found the documentation says that we can't use Tailwind's @apply feature without wrapping the entire CSS rule in @css. Bug it can work even though I didn't  use @css, why?

[demo repo](https://github.com/yyyang1996/vuepress-tailwind-starter)
```
yarn install
yarn dev
```

**Comment by adamwathan** [comment]
I think Stylus might have made a change to make it possible without using `@css` 👍 

Closing since not a Tailwind bug/issue.

**Comment by windware-ono** [comment]
@apply works fine in stylus.

@adamwathan
You need to fix the document.

https://github.com/stylus/stylus/issues/2335
https://tailwindcss.com/docs/using-with-preprocessors#stylus
