### ISSUE TITLE
Give control to media queries order

### ISSUE THREAD

**Issue by NuriddinK** [tailwindcss/tailwindcss#1414]
I changed my media queries to be desktop first since most of our users come from here.
The problem is that the small screen media query gets overridden by the bigger rule. 

**How to reproduce:**
create an HTML grid with `grid grid-cols-4 md:grid-cols-2 sm:grid-cols-1` on the parent.

change screens rules in `tailwind.config.js`.
```
screens: {
    'xs': {'max': '576px'},
    'sm': {'max': '768px'},
    'md': {'max': '992px'},
    'lg': {'max': '1200px'},
},
```

`sm:grid-cols-1` will not work, this might be related to the order of the rules.

**Comment by NuriddinK** [comment]
I was able to fix it change the order of the dictionary. It might be useful to specify in the docs.

**Comment by adamwathan** [comment]
You can already do this, put the screens in the order you want them.

```js
screens: {
    'lg': {'max': '1200px'},
    'md': {'max': '992px'},
    'sm': {'max': '768px'},
    'xs': {'max': '576px'},
},
```
