### ISSUE TITLE
[Feature proposal] Transform utilities without `transform` class

### ISSUE THREAD

**Issue by vricop** [tailwindcss/tailwindcss#1417]
I always forget to add `transform` additional class when working with `scale`, `translate`, etc. There's a better way using attribute selectors, I implemented this in my own library (still testing). Maybe Tailwind can benefit from this. You can see my implementation in [PetricorCSS](https://github.com/vricop/PetricorCSS/blob/5c5ab9a6935390cbf48b98d3eaae912afd5f0614/_base.scss#L149)

**Comment by adamwathan** [comment]
This is a pretty clever idea! The only thing I don't like is that there is no attribute selector in CSS that says "one of the whitespace separated values in this attribute _starts with_ this string", the best you can do is search the whole attribute for a substring, which means if someone had any custom class that matched those patterns (like `zoom-scale-max` or even `grayscale-filter`) or something, it would trigger the transform which feels a little not-bullet-proof-enough to me :/

Going to stick with what we have for now but can always revisit this later if anyone has any clever ideas 👍🏻
