### ISSUE TITLE
Possible Bug When Customizing Translate Scales?

### ISSUE THREAD

**Issue by EvilLooney** [tailwindcss/tailwindcss#1433]
Hi,

I am extending the transform scale in my tailwind.config.js file:
`module.exports = {
  theme: {
    extend: {
      translate: {
        'test': '10px'
      }
    }
  }
}`

However, this only produces:
`.translate-x-test {
  --transform-translate-x: 10px;
}`
and not:
`.-translate-x-test {
  --transform-translate-x: -10px;
}`

Is this the expected behaviour? If so, maybe the docs should indicate this.

Thanks.

P.S. I am using the spacing utilities instead as they produce the negative values.

**Comment by adamwathan** [comment]
This is expected behaviour yeah, if you want to add negative values you need to add them yourself by prefixing the key with `-`:

```js
module.exports = {
  theme: {
    extend: {
      translate: {
        '-test': '-10px',
        'test': '10px',
      }
    }
  }
}
```

We document this in most places where it works but don't have it here, need to add it thanks for catching.
