### ISSUE TITLE
Form element margin reset

### ISSUE THREAD

**Issue by subhero24** [tailwindcss/tailwindcss#1436]
Tailwind base css sets the margin and padding to 0 for a lot of form elements. A form itself has no such css reset, and the default stylesheet in browsers defaults to margin-block-end: 1em;

Should the tailwind base css also reset margins on the form element, or should I do this in my own stylesheet?

**Comment by benface** [comment]
> A form itself has no such css reset, and the default stylesheet in browsers defaults to margin-block-end: 1em;

Which browser(s) do you see that in? In my experience that's not the case.

**Comment by subhero24** [comment]
Just opening the following html has the bottom margin on the form in latest version of Chrome, Safari and Firefox.

```html
<html>
  <body>
    <form></form>
  </body>
</html>
```

**Comment by adamwathan** [comment]
Not seeing this, this is Safari:
![image](https://user-images.githubusercontent.com/4323180/76474335-b4bfba00-63d1-11ea-891e-d05765bfea4c.png)

Chrome:
![image](https://user-images.githubusercontent.com/4323180/76474341-bb4e3180-63d1-11ea-966a-7c910045e4bb.png)

Firefox:
![image](https://user-images.githubusercontent.com/4323180/76474385-e33d9500-63d1-11ea-9eb2-fca965e8c4b2.png)

Can't find any evidence of forms having a default margin-block-end of 1em anywhere.

**Comment by subhero24** [comment]
This is strange. Just opening a local html file with only a form in the body and this is what chrome gives me:

![Screenshot 2020-03-12 at 00 56 14](https://user-images.githubusercontent.com/1171150/76474714-c8cce100-63fc-11ea-86c4-89ab7142ac58.png)

**Comment by subhero24** [comment]
Ah, I found the issue. Apparently the form has a margin-block-end if the `<!DOCTYPE html>` is missing from the document
