### ISSUE TITLE
[Feature Proposal] Option to generate utilities from screens object only

### ISSUE THREAD

**Issue by thanosisalive** [tailwindcss/tailwindcss#1439]
Right now I'm using something like this:
```
screens: {
  xs: '0',
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px'
}
```
The `xs` key with `0` value allows us to sort **breakpoint classes** in alphabetical order:
`xs:bg-red-100 xs:text-red-600 sm:bg-green-100 sm:text-green-600 md:bg-blue-100 md:text-blue-600`

Another example:
```
screens: {
  b0: '0',
  b1: '640px',
  b2: '768px',
  b3: '1024px',
  b4: '1280px'
}
```
This allows us to sort **all classes** in alphabetical order.

I can remove unwanted classes (without breakpoints) using `purgecss`, but I would like to be able to disable them altogether (so that you cannot use breakpointless classes in development).

I know it looks verbose to write so many `xs` but some people prefer consistency over brevity.

**Comment by adamwathan** [comment]
Hey! Interesting idea — I haven't heard this request from anyone else so I'm going to say no as an official feature right now, but you can actually do this in user-land!

To do it you need to write a very simple PostCSS plugin, which you can inline directly into your PostCSS config file:

```js
// postcss.config.js
module.exports = {
  plugins: [
    require('tailwindcss'),
    function(css) {
      let removing = false

      css.each(node => {
        if (node.type === 'comment' && node.toString() === '/* postcss start remove */') {
          removing = true
        } else if (node.type === 'comment' && node.toString() === '/* postcss end remove */') {
          removing = false
        }

        if (removing) {
          node.remove()
        }
      })
    },
    require('autoprefixer'),
  ],
}
```

What this plugin does is let you delimit chunks of a CSS file to automatically be removed using comments.

So if you do this in your CSS file, you'll get the results you want:

```css
@tailwind base;
@tailwind components;

/* postcss start remove */
@tailwind utilities;
/* postcss end remove */

@tailwind screens;
```

Hope that helps!
