### ISSUE TITLE
tailwindcss.co.uk documentation broken

### ISSUE THREAD

**Issue by paulblamire** [tailwindcss/tailwindcss#1453]
Hi

When I googled for tailwind css documentation the .co.uk site was the higher result for me.

The installation guide of the docs didn't render. Upon inspecting the console output I found the following error.

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".

    at new Function (<anonymous>)
    at Object.Hogan.makeTemplate (docsearch.min.js:2)
    at Object.Hogan.generate (docsearch.min.js:2)
    at Object.Hogan.compile (docsearch.min.js:2)
    at Function.getSuggestionTemplate (docsearch.min.js:2)
    at new DocSearch (docsearch.min.js:2)
    at Factory (docsearch.min.js:2)
    at (index):1084

This issue is not present on the .com version - which I found in a subsequent google search.
Also the version numbers in the documentation drop-down do not include v1.2.0 in the uk version if that helps. 

https://tailwindcss.co.uk/docs/installation/
https://tailwindcss.com/docs/installation/

Thanks,

Paul

**Comment by adamwathan** [comment]
Weird, no idea who created the .co.uk version, it's not official or maintained by us :/ Closing since we can't do anything about it.

**Comment by paulblamire** [comment]
No problem, thank you :-)
