### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '{' setting up tailwind with postcss

### ISSUE THREAD

**Issue by dephiros** [tailwindcss/tailwindcss#1458]
I am trying to set up tailwind with 11ty and postcss
The css is compiled successful using both postcss-cli and parcel but when I load the css in the browser, I keep getting an error: `Uncaught SyntaxError: Unexpected token '{'`

Reproduce issue:
- repo https://github.com/dephiros/11ty-tailwind
- Run `./Taskfile`
- Open http://localhost:8094 and see the error in the console

Appreciate any help!

**Comment by adamwathan** [comment]
Is it possible to build without minifying so we can actually see where the error is?

**Comment by dephiros** [comment]
Thanks Adam for the quick response. I didn't think of that(actually tried and reformatted the response in vscode)
Let me take a quick look

**Comment by dephiros** [comment]
If you pull the latest `master`, I uncommented cssnano in postcss so should no longer minify. Note: you might have to remove cache before rerun: `rm -rf dist .parcel-cache && run`.

 Chrome points to `html {` which does not makes sense to me. I attached the css file and screenshot here too
[index.css.zip](https://github.com/tailwindcss/tailwindcss/files/4351108/index.css.zip)
<img width="336" alt="Screen Shot 2020-03-18 at 12 51 08 PM" src="https://user-images.githubusercontent.com/2289753/77001615-6f424600-6917-11ea-9e21-921fde74d3a3.png">

**Comment by dephiros** [comment]
I run the file through csslint.net and it seems to point to a bunch of errors starting at line 11865:
```
.grid-cols-1 {
  grid-template-columns: repeat(1, minmax(0, 1fr));
}

.grid-cols-2 {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.grid-cols-3 {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}
```
<img width="1075" alt="Screen Shot 2020-03-18 at 12 56 48 PM" src="https://user-images.githubusercontent.com/2289753/77002012-11622e00-6918-11ea-8b40-580e9010c8c6.png">

**Comment by dephiros** [comment]
Found the issue! My silly self included the stylesheet through a script tag instead of a style tag 🤦

Sorry for the noise and thank you for your help Adam!
