### ISSUE TITLE
where can I use @apply in a vue-cli app?

### ISSUE THREAD

**Issue by mark-hahn** [tailwindcss/tailwindcss#1465]
I'm building a vue-cli app.  @apply doesn't seem to work in any file I can find.  This is my test css ...

```
.markdown > h1,
h1.markdown {
  @apply mb-1;
  @apply leading-none;
  @apply text-gray-900;
  @apply font-light;
  @apply text-3xl;
}
```
I've tried it in index.css, tailwind.css, and in the styles section of a vue component.  I've also put it in a file and tried importing it in my main js file ...
```
import './assets/styles/index.css'
import './assets/css/tailwind.css'
import './assets/css/markdown.css'
```
What am I missing?

**Comment by adamwathan** [comment]
Here's an example of a vue-cli app that's configured correctly for `@apply` to work:

https://github.com/tailwindcss/designing-with-tailwindcss/tree/master/04-building-a-dropdown-menu/01-styling-the-basic-dropdown-elements

Not sure what part you're missing but you should be able to at least trace down the differences.
