### ISSUE TITLE
Internet Explorer 11 - rotate doesn't work

### ISSUE THREAD

**Issue by xApep** [tailwindcss/tailwindcss#1468]
Hey.
I've notice that rotate class doesn't work on IE 11.
You can simply test your website with IE 11 https://tailwindcss.com/docs/rotate/

I had to add custom class to IE fix "-ms-transform:"

**Comment by royvanv** [comment]
Shouldn't this be handled by Autoprefixer? What does your browserlist look like, in either the `.browserslistrc` or the `browserslist` property in your `package.json`?

**Comment by adamwathan** [comment]
Yep this is intentional and in the documentation.

![Uploading A748FC00-1A2A-4DBF-BCCF-CA887093E90F.png…]()
