### ISSUE TITLE
Algogia's DocSearch not very precise

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#148]
Hey,

I tried to search through the docs and I saw this:

<img width="527" alt="capture d ecran 2017-11-08 a 13 51 51" src="https://user-images.githubusercontent.com/1854141/32550134-4f3abb76-c48c-11e7-9e93-15e676127ee2.png">
<img width="524" alt="capture d ecran 2017-11-08 a 13 52 25" src="https://user-images.githubusercontent.com/1854141/32550155-599418f6-c48c-11e7-88c7-b3aea108a847.png">

In the main `Styles` menu, Algolia doesn't show correctly nested pages as `Border Colors`, `Background Colors` etc...

Any fix @LukyVj? :)

**Comment by LukyVj** [comment]
Hey @HapLifeMan ! Thanks for opening the issue! 
It's something that can be fixed! I let my colleague @maxiloc ( aka docsearch specialist :) ) respond to you with a solution! 

Let me know if I can do anything else!

**Comment by maxiloc** [comment]
Hey, I updated the config. I did a mistake when I first configured it. Should be fixed and live now.
Feel free to ping me if you see other relevance issue.

![image](https://user-images.githubusercontent.com/1689007/32550819-cee6a130-c48e-11e7-8d01-12dd3f9fe237.png)
![image](https://user-images.githubusercontent.com/1689007/32550831-d594dfec-c48e-11e7-9234-c218f2408b59.png)

**Comment by HapLifeMan** [comment]
Thank you everything is good now :D

**Comment by reinink** [comment]
@maxiloc Huge thanks for your help here! 🙇
