### ISSUE TITLE
[Bug] hover:z-50

### ISSUE THREAD

**Issue by akshatbhargava123** [tailwindcss/tailwindcss#1480]
`hover:` prefix with z-index doesn't work as expected.

It should apply the corresponding `z-{x}` class when I use `hover:z-{x} ` but it doesn't currently.

**Comment by adamwathan** [comment]
It does work, just make sure you enable the `hover` variant in your Tailwind config for the `zIndex` utilities:

https://tailwind.run/j3GK9b

**Comment by adamwathan** [comment]
This is documented on the z-index page in the "customizing" section:

https://tailwindcss.com/docs/z-index/#responsive-and-pseudo-class-variants

**Comment by HisRoyalWONGiness** [comment]
Can someone please help explain in detail, nothing has worked for me and I'm having the same issue
