### ISSUE TITLE
[Feature Proposal] Changing Spacing/Sizing (and other) Keys

### ISSUE THREAD

**Issue by moshemo** [tailwindcss/tailwindcss#1484]
I personally am not a big fan of the naming convention for margins, padding, width, etc.  For example, I have to remember that there is no w-7 or w-11.  Also, it seems to me that the key names are directly related to the values -- something I thought we were trying to get away from.  

As such, I'd like to suggest a new system -- inspired in part by the new naming convention for colors.  I'll first show what I have and then explain what I'm doing:

```
    spacing: {
      "0": "0",
      "1": "0.125rem",
      "2": "0.25rem",
      "3": "0.5rem",
      "4": "0.75rem",
      "5": "1rem",
      "6": "1.25rem",
      "7": "1.5rem",
      "8": "2rem",
      "9": "2.5rem",
      "10": "3rem",
      "20": "4rem",
      "30": "5rem",
      "40": "6rem",
      "50": "8rem",
      "60": "10rem",
      "70": "12rem",
      "80": "14rem",
      "90": "16rem",
      "100": "20rem",
      "200": "24rem",
      "300": "28rem",
      "400": "32rem",
      "500": "40rem",
      "600": "48rem",
      "700": "56rem",
      "800": "64rem",
      "900": "80rem"
    },
```

The idea of this system is that I have a sense of how large my spacing value is based on whether it is a single digit value, double digit or triple digit.  Also, I don't have to remember which names exist -- since all numbers increase in sequential order.

As such, I can quickly zero in on the type of spacing value I am looking for and then cycle up and down to get the actual look that I want.

I know that I can override the defaults in tailwind -- but it seems to me that a system like this would be nice to bake into the core of tailwind.  And not just for margins and widths -- also for other elements like line-height and letter-spacing.  

`lh-100` (for line-height) and `ls-100` (for letter spacing) is easier to remember than `leading-snug` and `tracking-wide`.  In terms of line heights with rem values -- you could add `lh-100r` or something similar.

The point is that I think the naming convention could be improved upon to make it a) more consistent and b) easier to remember and use.

**Comment by adamwathan** [comment]
This would be a massive breaking change unfortunately which comes at a huge cost to our user base so no plans to change this. I like the current system better personally, because the numbers are actually relative to each other (mt-16 is twice as much margin as mt-8) but I agree it's not perfect. Thanks for the suggestion though.

**Comment by moshemo** [comment]
Perhaps you could implement something like this for letter-spacing and line-height.  You could deal with the issue of breaking changes by grandfathering in the old system for a set number of updates and then phase them out.

Didn't think about (or even know about) the relative values.  I agree that is a big plus (and may go back for that benefit alone).
