### ISSUE TITLE
font-sans not working by default

### ISSUE THREAD

**Issue by ryangjchandler** [tailwindcss/tailwindcss#1485]
After setting up Tailwind in a new Laravel project, all fonts are defaulting to Times / serif stack. 

Inspecting element shows that the `font-sans` class is not being correctly compiled and includes lots of white space (see screenshot):

![image](https://user-images.githubusercontent.com/41837763/77465093-09b2f580-6e00-11ea-81c7-999e7b74b6eb.png)

I haven't modified the default config file either.

**Comment by ryangjchandler** [comment]
The same thing is happening with the other font stacks too out of the box. Looks like the quotations are being escaped and are therefore invalid.

**Comment by adamwathan** [comment]
Can you create a GitHub repo that reproduces? Never seen this one 🤔

**Comment by ryangjchandler** [comment]
> Can you create a GitHub repo that reproduces? Never seen this one 🤔

https://github.com/ryangjchandler/ryangjchandler has the problem on master.

**Comment by ryangjchandler** [comment]
Further note, if I overwrite the `theme.fontFamily.sans` array in the config, it will work fine.

**Comment by florianbouvot** [comment]
@ryangjchandler `.font-sans`classes looks good in your compiled CSS file so I think the issue is rated to `<style>{{ file_get_contents(public_path('css/app.css')) }}</style>` in `master.blade.php`...

**Comment by adamwathan** [comment]
Yep that's definitely the issue. Use `{!! !!}` so the content isn't escaped.

**Comment by ryangjchandler** [comment]
> Yep that's definitely the issue. Use `{!! !!}` so the content isn't escaped.
> 
> 
> 
> (or of course use an external CSS file with a `<link>` tag, just assuming you need it inline for whatever reason.)

Ah, I'm an idiot lol. Thanks fellas
