### ISSUE TITLE
Max-width break points. Styles being overwritten by previous break point

### ISSUE THREAD

**Issue by AshDavies247** [tailwindcss/tailwindcss#1490]
When using the following for max-width break points:

`		screens: {

			xs: { max: '350px'},

			sm: { max: "639px" },
			// => @media (max-width: 639px) { ... }

			md: { max: "767px" },
			// => @media (max-width: 767px) { ... }

			lg: { max: "1023px" },
			// => @media (max-width: 1023px) { ... }

			xl: { max: "1279px" }
			// => @media (max-width: 1279px) { ... }
		},
`
Due to the way the CSS file is created, the xl rules are always placed after the sm rules, meaning that smaller break point styles aren't respected when a larger break point has already been defined.

Example. In this div:
`<div class="mb-8 xl:mb-4 sm:mb-2">`
With the break points being max break points, you would expect the div to initially have mb-8, then mb-4 at the correct break point and then finally end on mb-2. What's actually happening is that mb-4 is being respected at the correct break point, but because the xl styles come after the sm styles in the stylesheet, the mb-2 is immediately being overwritten and isn't respected.

**Comment by adamwathan** [comment]
Put your breakpoints in the reverse order, we don't do anything smart here we just respect the order you've defined 👍  We should update the docs though as we have it reversed there.
