### ISSUE TITLE
Update background-size docs code snippets

### ISSUE THREAD

**Issue by abhishekashyap** [tailwindcss/tailwindcss#1495]
> https://tailwindcss.com/docs/background-size/

It needs to be camel case (backgroundImage) not kebab case (background-image) even though the docs say it can be either.

**Comment by royvanv** [comment]
Which section are you referring to?

**Comment by abhishekashyap** [comment]
[Auto](https://tailwindcss.com/docs/background-size/#auto)
[Cover](https://tailwindcss.com/docs/background-size/#cover)
[Contain](https://tailwindcss.com/docs/background-size/#contain)

![Uploading Screenshot 2020-03-27 at 6.24.58 PM.png…](Screenshot)

Previous: `<div class="bg-cover bg-center ..." style="background-image: url(...)"></div>`
Recommended: `<div class="bg-cover bg-center ..." style="backgroundImage: url(...)"></div>`

**Comment by royvanv** [comment]
> Recommended: `<div class="bg-cover bg-center ..." style="backgroundImage: url(...)"></div>`

Where are you getting your information? This is invalid CSS!

**Comment by abhishekashyap** [comment]
I'm sorry, I mistook them for dynamic style bindings in Vue.
