### ISSUE TITLE
Add more flex property classes, such as flex-grow-2

### ISSUE THREAD

**Issue by cliffordp** [tailwindcss/tailwindcss#1501]
From https://github.com/tailwindcss/tailwindcss/issues/603:
> We didn't provide flex-basis utilities originally because width does the same thing for 99.9% of cases and we didn't want to increase the size of the framework, but you could easily add your own flex-basis utilities by following the documentation:

https://stackoverflow.com/a/34734145/893907 provides a good explanation of why *width* classes wouldn't satisfy all the flex-grow, flex-basis, etc. classes.

https://tailwindcss.com/docs/flex-grow/ has `.flex-grow` and `.flex-grow-0` but why not more?

Basically, I want to do this via Tailwind classes:
![image](https://user-images.githubusercontent.com/1812179/77797549-428cdd80-703f-11ea-9328-dd4ae5997d85.png)

Adding even a hundred more classes isn't going to significantly increase the size of the library, and with the great build tools like include/exclude/PurgeCSS, there's no major risk in my opinion.

Thanks for Tailwind!

**Comment by adamwathan** [comment]
Width and flex-basis are definitely interchangeable except for very rare situations (specifically involving CSS grid and flexbox where you are trying to progressively enhance flexbox to CSS grid). The StackOverflow question you linked is comparing width to _flex-grow_ not flex-basis.

You can add `flex-grow-2` if you like by adding it to your config file 👍 Then you'd do this to accomplish what's in that screenshot:

```
<div class="flex-grow-2 flex-shrink w-1/2">...</div>
```

https://tailwindcss.com/docs/flex-grow/#grow-values
