### ISSUE TITLE
Roadmap or new release

### ISSUE THREAD

**Issue by boukenka** [tailwindcss/tailwindcss#1508]
Hello,

Is there a roadmap or plan for new releases in the near future ?
Thank you for any answer. 😄 

PS : The last release was on February 5.
PS : I know there is a project in progress to create components by the creators of Tailwind CSS !

**Comment by adamwathan** [comment]
Will release when we've merged enough stuff to warrant a new release 👍 No specific roadmap or timeline right now, at the moment I have too much to do with Tailwind UI but will be working on new Tailwind CSS updates when I'm sufficiently caught up there.

**Comment by farshad-sadri** [comment]
Regarding the same question, I'd like to ask if you have a more specific timeline for developing on Dark Mode feature. 
Thank you

**Comment by adamwathan** [comment]
Dark mode is already available begins the “darkModeVariant” flag 👍🏻

https://github.com/tailwindlabs/tailwindcss/pull/2279
