### ISSUE TITLE
Issue with loading border-{color} from config

### ISSUE THREAD

**Issue by filipesmedeiros** [tailwindcss/tailwindcss#1519]
Hey! First: love Tailwind, very awsome.

So, I was trying to design theming, and I think I've arrived to a decent solution, I just use the nested syntax in `tailwind.config.js` and then use a `body` class to control what theme is active.

Looks something like this:

`tailwind.config.js`
```
module.exports = {
	theme: {
		colors: {
			brandColor: '#ffc045',
			brandColorDark: '#ff9b00',
			default: {
				main: '#7c0000',
                                ...

				// Pricing tiers border colors
				simple: '#ffd645',
			},
			dark: {
				main: '#ffc353',
                                ...

				// Pricing tiers border colors
				simple: '#ffd645',
			},
		},
        },
}
```

`theme.scss`
```
.color-brand {
	@apply text-brandColor;
}

.color-brand-dark {
	@apply text-brandColorDark;
}

body.default {
	@apply text-default-main bg-default-bg;

	.color-light {
		@apply text-default-light;
	}

	@each $specific in constants.$specifics {
		.color-spec-#{$specific} {
			@apply text-default-#{$specific};
		}
	}

	@each $tier in constants.$pricingTiers {
		.border-tier-#{$tier} {
			@apply border-default-#{$tier};
		}
	}
}

body.dark {
	@apply text-dark-main bg-dark-bg;

	.color-light {
		@apply text-dark-light;
	}

	@each $specific in constants.$specifics {
		.color-spec-#{$specific} {
			@apply text-dark-#{$specific};
		}
	}

	@each $tier in constants.$pricingTiers {
		.border-tier-#{$tier} {
			@apply border-dark-#{$tier};
		}
	}
}
```

The issue: Tailwind is not finding the class `.border-default-simple`, although it's finding both `.text-default-simple` and `.border-dark-simple`.

Am I doing something wrong or this is a bug?

Thanks!

EDIT: I didn't post more code so this doesn't become a tech help issue, but I assume the fact that Tailwind is finding the other similar classes is enough to maybe understand what's causing the issue?

Ah and the error is the syntax one `Syntax error: @apply cannot be used with .border-default-simple because .border-default-simple either cannot be found, or its...`

A development: apparently for some reason, when I use the `.text-default-simple` class, it changes both the `color` and `border-color` CSS properties. Hmmm

**Comment by filipesmedeiros** [comment]
Well after a bit of testing, I came to a very weird conclusion: it seems that *only* `.border-default-{word}` gives problems. Any other name for the theme (instead of default) worked, and it only bugged out with `.border-{color}`.

I changed the class to `.border-light-{color}` and everything works normally. Weird.

**Comment by florianbouvot** [comment]
@filipesmedeiros you find the issue, `default` is use by tailwind, I think you can close your issue 😉

**Comment by adamwathan** [comment]
Yeah `default` has special behavior for border colors (it sets the default border color when just using the `border` class) and doesn't generate a `border-default` class. Since `borderColor` inherits from `colors`, using `default` in the colors key is what is causing the issue.

I would recommend just using a different word like `base`, `normal`, or maybe `light` in your case. Agree this is sort of weird and complex behavior and if I was building Tailwind from scratch I'd probably do it differently, but unfortunately doing anything about it would be a breaking change and really want to avoid frequent breaking changes.

**Comment by filipesmedeiros** [comment]
@adamwathan Hey! Thanks for the explanation. Do you think we can have at least like a warning in the docs?

**Comment by adamwathan** [comment]
@filipesmedeiros Yep I think we can do that, where would you recommend we explain it so that you would have actually found it?

**Comment by filipesmedeiros** [comment]
@adamwathan Hmm probably in the [colors ](https://tailwindcss.com/docs/customizing-colors) page right? Since this is a matter of extending/overriding the color palette.

Maybe something like a section "Caveats" or "Things to notice"?
I can PR that change (if the docs code is open source), if you want!
