### ISSUE TITLE
How to whitelist class patterns when using PurgeCSS

### ISSUE THREAD

**Issue by kaleidografik** [tailwindcss/tailwindcss#1526]
I am trying to preserve all TailwindCSS colour classes (i.e bg-green, bg-red, text-green, text-red) when it is processed via PurgeCSS. These colour classes are set in the CMS rather than code so we cannot search the code using content/extractor for them as they don't (all) exist here.

Therefore I want to use the whitelisting feature of PurgeCSS to retain all classes that beginning with 'bg-' or 'text-'. However, the pattern I have below doesn't seem to be doing the trick? Any ideas how to tweak it?

whitelistPatterns: ['^bg\-', '^text\-'],

**Comment by tlgreg** [comment]
It should be regexp, not a string.
```js
{
  whitelistPatterns: [/^bg-/, /^text-/],
}
```

**Comment by phuclh** [comment]
@tlgreg @kaleidografik I tried a lot of ways but it still purges all classes. Can you guys help me?

```
safelist: {
    standard: [/^bg-/, /^text-/]
}
```

```
safelist: [/^bg-/, /^text-/]
```

```
whitelistPatterns: [/^bg-/, /^text-/]
```

My full `tailwind.config.js`

```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: {
        content: [
            './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
            './vendor/laravel/jetstream/**/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php',
        ],
        whitelistPatterns: [/^bg-/, /^text-/]
    },

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            }
        },
    },

    variants: {
        extend: {
            opacity: ['disabled'],
        },
    },

    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio')
    ],
};
```

**Comment by kaleidografik** [comment]
Hey @phuclh - try there following, which worked for me back on TW 2.0.2. But I believe it should still work. We've recently moved to JIT mode which is slightly different.

```
purge: {
    enabled: true,
    mode: 'layers',
    layers: ['base', 'components', 'utilities'],
    content: [
    ],
    options: {
        defaultExtractor: content => content.match(/[\w-/:.]+(?<!:)/g) || [],
        safelist: [/^bg-/, /^text-/, /^border-/], // Retain all classes starting with...,
    }
  },
```

**Comment by phuclh** [comment]
@kaleidografik Thank you so much, it works!!! 👯
