### ISSUE TITLE
<sub> and <sup> stick in front of modal

### ISSUE THREAD

**Issue by mokhosh** [tailwindcss/tailwindcss#1527]
I have a `sub` element on my page, and when I create a modal that is a `relative` div with `z-50` the `sub` still sticks in front of it. I even tried `z-index: 99999999999;` in the dev tools, no luck.

When I remove `position: relative` from `sub` styles it goes behind.

I know you're hard resetting browser styles, but this is a problem.

**Comment by tlgreg** [comment]
Stacking context can be hard to deal with, for modals usually it's best if they are used at the end of the document.

Tailwindcss uses the fairly widely adopted `normalize.css` as a base (+SUIT and some of its own).

This rule is also part of `normalize.css` from pretty much the beginning (8+ years ago), not sure tailwindcss should change this behavior.

**Comment by mokhosh** [comment]
Well my modal is part of a component that has to be put before the `sub` element.

Who ever is putting `position` on simple static elements that should not be positioned is wrong, no matter who they are and for how long they have been doing it. Bad hack.

**Comment by adamwathan** [comment]
Can you share a demo that reproduces the issue? It sounds like it would be fixable by adding a position and a z-index so want to understand why that's not working.

Either way not going to change this rule in Tailwind because we don't want to deviate from normalize.
