### ISSUE TITLE
[Feature Proposal] Limit Tailwind to ID or Class

### ISSUE THREAD

**Issue by cihantas** [tailwindcss/tailwindcss#1529]
Hello everyone,

We'd like to use Tailwind in a widget that will be included in the sites of our customers, kinda like Intercom. To avoid style leaking we increase specificity by prefixing all classes with our id e.g. `#our-widget .opacity-25` using Tailwinds `important` config option. This however does not apply to `@tailwind base`. It would be great if we could optionally include the base classes.

**Comment by cihantas** [comment]
Solved using `postcss-prepend-selector`.

**Comment by handplant** [comment]
@cihantas I have exactly the same problem with my vue app. But I can't get it to work with the npm package `postcss-prepend-selector` either. The Tailwind stuff is not wrapped in the selector. Do you have another tip for me? Thanks

postcss.config:
```
module.exports = {
  plugins: [
    require('postcss-prepend-selector')( { selector: '.helloworld' } ),
    require("postcss-import"),
    require("tailwindcss"),
    require("postcss-nested"),
    require("autoprefixer"),
  ]
}
```
