### ISSUE TITLE
Getting rid of class="..."

### ISSUE THREAD

**Issue by michaeljakob** [tailwindcss/tailwindcss#1530]
I love tailwind, however, the most annoying thing is still to constantly write `class="..."` so many times. Maybe this is hugely off-topic, but might also be slightly disruptive:

Isn't there a way to make tailwind work without the class attribute? I'm thinking:

`<h1 bg-white rounded-lg p-6>hey there!</h2>`

**Comment by adamwathan** [comment]
No plans to change this sorry, little too unconventional IMO.
