### ISSUE TITLE
Search doesn't redirect to anchor when needed

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#155]
Hey @maxiloc, I found another bug here:

<img width="514" alt="capture d ecran 2017-11-08 a 15 48 37" src="https://user-images.githubusercontent.com/1854141/32555177-5b7d6554-c49c-11e7-80b5-958993b7ef57.png">

When I click on `Naming`, I'm redirected to the right page but the anchor isn't correct.

In this case I am redirected to 
```
https://tailwindcss.com/docs/colors/#app
```
but should be
```
https://tailwindcss.com/docs/colors/#naming
```

It's the same thing everywhere else, hope you'll fix that :)

**Comment by MichaelDeBoey** [comment]
CC @maxiloc

**Comment by maxiloc** [comment]
Yes the anchors are generated via css. I enabled javascript rendering. All good now.

**Comment by reinink** [comment]
On fire! 🔥 

Thanks again!
