### ISSUE TITLE
Add PurgeCSS comments to tailwind.css

### ISSUE THREAD

**Issue by pspeter3** [tailwindcss/tailwindcss#1551]
I often end up having a single css file for Tailwind projects with the below contents. It would be nice if the `tailwind.css` file could include those comments by default. That way I can just import `"tailwind/tailwind.css"` in my code and not need the CSS file.

```css
/* purgecss start ignore */
@tailwind  base;
@tailwind  components;
/* purgecss end ignore */

@tailwind  utilities;
```

**Comment by taylorbryant** [comment]
https://github.com/tailwindcss/tailwindcss/pull/1639

**Comment by pspeter3** [comment]
Yeah, I think this is made redundant by #1639
