### ISSUE TITLE
How to transpile tailwindcss classes into plain css ?

### ISSUE THREAD

**Issue by MenaiAla** [tailwindcss/tailwindcss#1552]
I'm using [express-vue](https://github.com/express-vue/express-vue) in my project, this is a rendering engine for vue.js components that requires only normal css styles. I want to design the component using Tailwindcss classes then transpile or convert the file into normal css.
Example 
.button {
@apply mx-auto;
}

Become :
.button {
margin-left:auto,
margin-right:auto:
}

Or other solution to use Tailwindcss as normal css file?

**Comment by jgraham44** [comment]
This looks like an issue with express-vue as described [here](https://github.com/express-vue/express-vue#css-inside-componentsviews). 

You should be able to just set up a [gulp task](https://github.com/postcss/gulp-postcss) to compile your components and then include the output in your project.
