### ISSUE TITLE
Just a small problem 

### ISSUE THREAD

**Issue by warcraft14115** [tailwindcss/tailwindcss#1554]
Hi :) Look like `sm:clear-none` not work :) I don't know how to add it in config file. But I think someone will need it.

**Comment by ahinkle** [comment]
Do you have a full example of how you are using it?

**Comment by warcraft14115** [comment]
I think no, I add css manual over style.css. It's work ok :D

**Comment by ahinkle** [comment]
Please provide a _full_ code example of how you are using it. It seems to be working fine, otherwise.

**Comment by florianbouvot** [comment]
@warcraft14115 `clear-none` are documented but is missing from current release.

Will be ok in a futur release, see #1413 PR.

Right now, you can add this:

```
@responsive {
    .clear-none {
        clear: none;
    }
}
```

**Comment by warcraft14115** [comment]
@florianbouvot  Thank you :D

**Comment by warcraft14115** [comment]
@florianbouvot I got a problem with tailwindcss-animatecss :s 
I tried to use purge css, it worked fine with tailwind 
But look like it not work with above plugin :s I don't know why. 
CSS down from 85k lines to 2k (4kb) , but that still not maxium optimize :D Something wrong with purgecss config or from tailwind,right ?

**Comment by florianbouvot** [comment]
@warcraft14115 I never use this plugin, but I think you need to refer to PurgeCss docs (whitelist, ...) : https://purgecss.com

**Comment by florianbouvot** [comment]
@warcraft14115 and this one two : https://tailwindcss.com/docs/controlling-file-size

**Comment by adamwathan** [comment]
This was added in v1.3, left out accidentally originally 👍
