### ISSUE TITLE
Feature Request: Define different color for border-t, border-r, border-b, border-l

### ISSUE THREAD

**Issue by masihjahangiri** [tailwindcss/tailwindcss#1555]
I try to write this tailwindcss class but found out that tailwind not support it!
```html
<div className="border border-gray-200 border-t-8 border-t-gray-900">test</div>
```

**Comment by ahinkle** [comment]
This has been opened and addressed many times. Please see https://github.com/tailwindcss/tailwindcss/pull/560#issuecomment-503222143.
