### ISSUE TITLE
Feature request: text styles

### ISSUE THREAD

**Issue by benface** [tailwindcss/tailwindcss#156]
It would be nice if, in addition to fonts, text sizes, font weights, line heights, letter spacings, and text colors, we could define "text styles" (aka "character styles" or "paragraph styles") which could combine any of those properties.

The way I see it working, it would be possible to use names representing values defined in the config, like this:

```
textStyles: {
    'h1': {
        'font': 'serif',
        'textSize': '3xl',
        'fontWeight': 'bold',
    },
},
```

...or we could use values directly (which are not necessarily used anywhere else in the config):

```
textStyles: {
    'h1': {
        'font': ['Constantia', 'Lucida Bright', 'Lucidabright'],
        'textSize': '1.875rem',
        'fontWeight': 700,
    },
},
```

All properties are optional and the ones that aren't defined simply inherit as per CSS. The above would generate a `style-h1` class, and maybe it could be possible to override some of its properties like this:

```
<h1 class="style-h1 font-light">Title</h1>
```

Thoughts?

**Comment by reinink** [comment]
Hey there @benface! Thanks for your interest in Tailwind CSS! Generally we have tried to not mix more than one CSS property into each utility. It only happens in maybe one or two places in the whole framework, in very [unique situations](https://github.com/tailwindcss/tailwindcss/blob/05b5bbd741f2e4c9c6ae1f316bda9fb187bf65b4/src/generators/floats.js#L13-L16).

Generally when you start mixing utilities, what you're really doing is creating components. I think this is a great use-case for some `.style-h{x}` as components. For example:

```less
@responsive {
  .style-h1 { @apply .font-serif .text-3xl .font-bold }
  .style-h2 { @apply .font-serif .text-2xl .font-bold }
  .style-h3 { @apply .font-serif .text-xl .font-bold }
  .style-h4 { @apply .font-serif .text-xl }
}
```

You can read more about extracting components [here](https://tailwindcss.com/docs/extracting-components).

I hope that makes sense! Good luck! 💪🏻

**Comment by benface** [comment]
Makes perfect sense! Thank you!
