### ISSUE TITLE
[Bug] `xl 2xl 3xl` font-size is error

### ISSUE THREAD

**Issue by LIAOTOW** [tailwindcss/tailwindcss#1569]
`xl` font-size right is 1.25rem, but is 1.2857142857142858rem
`2xl` font-size right is 1.5rem, but is 1.4285714285714286rem
![image](https://user-images.githubusercontent.com/22748955/79313138-779b9a00-7f32-11ea-8c4e-54ce20ab5ed2.png)
![image](https://user-images.githubusercontent.com/22748955/79313160-7ec2a800-7f32-11ea-9639-0f724d709486.png)

**Comment by LIAOTOW** [comment]
my base.scss 
![image](https://user-images.githubusercontent.com/22748955/79313552-158f6480-7f33-11ea-917a-c740c1445e54.png)

**Comment by florianbouvot** [comment]
@LIAOTOW I don't know why, but take a look at:

- `font-size: 16px;` on html cause an accessibility issue: remove it or use 100% instead to allow user settings
- duplicate rules on html and boby : font-family and antialiased  added via @apply + declaration
- font-family can be customize in `tailwind.config.js`

**Comment by LIAOTOW** [comment]
thanks you,  `postcss.config.js - tailwindcss` should is empty:  `plugins: tailwindcss: {}`, my be  external modules's tailwind.config.js path
