### ISSUE TITLE
@tailwindcss/ui messes my colors! 

### ISSUE THREAD

**Issue by gabrilator** [tailwindcss/tailwindcss#1572]
Hey! Loving Tailwind so much I had to purchase tailwind UI. 

Been trying to add the @tailwindcss/ui  extension but  it's messing with my existing Tailwind color classes. My tailwind.config.js file is as follows: 

`module.exports = {
  plugins: [
    require('@tailwindcss/ui'),
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: '4rem'
      },
      inset: {
        '0': 0,
        '1/2': '50%',
        '1/4': '25%',
        '1/8': '12.5%',
        '3/5': '60%',
        '1/5': '20%'
      },
      }
    }
  },
}`

Any idea where I'm messing up the config? 

Keep up the amazing work !!!

**Comment by filipesmedeiros** [comment]
I think you probably need to provide a bit more info about where it's messing up the colors. Is it the default palette?

**Comment by adamwathan** [comment]
Hey @gabrilator, Tailwind UI adds a whole new color palette as documented here:

https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind

Is that what you're seeing perhaps? If you'd like to keep using the old color palette, you can do so like this:

```js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    colors: defaultTheme.colors,
    extend: {
      container: { center: true, padding: '4rem' },
      inset: { '0': 0, '1/2': '50%', '1/4': '25%', '1/8': '12.5%', '3/5': '60%', '1/5': '20%' },
    },
  },
  plugins: [require('@tailwindcss/ui')],
}
```

Note that this will mean that when you copy a Tailwind UI component into your project it's not going to look quite the same as it does in the preview, but if you want to use a different color palette that's to be expected anyways, you'll just have to adjust the colors of the components you're using to fit your own palette.

**Comment by gabrilator** [comment]
Thanks @adamwathan , I didn't know about the new palette! 

Keep it up :)
