### ISSUE TITLE
[Feature] Can we enable utilities and variants instead of disabling?

### ISSUE THREAD

**Issue by filipesmedeiros** [tailwindcss/tailwindcss#1574]
Hey!

Is there a way to enable variants and plugins? Instead of disabling? So I could do something like

```javascript
module.exports = {
    corePlugins: {
        float: true
    }
}
```

And all other plugins get purged from the final build.

Use case: very small website, I'm using very little of TailwindCSS (but love it), and PurgeCSS doesn't seem to work with some SASS features I'm using.

Thanks!

**Comment by tlgreg** [comment]
The feature exist.
Docs: https://tailwindcss.com/docs/configuration#core-plugins
```js
module.exports = {
  corePlugins: ['float'],
}
```

**Comment by filipesmedeiros** [comment]
Oops, I wish that was on the "Reduce file size" page. Thanks!
