### ISSUE TITLE
Displaying a background image

### ISSUE THREAD

**Issue by sebastien-metzger** [tailwindcss/tailwindcss#1575]
Hello,

This is the first time that I use Gridsome and I have chosen Tailwind as a CSS framework. I am trying to display a background image with the following code but the image is not found:
```
<section
            id="hero"
            class="bg-no-repeat bg-center w-full h-24"
            style="background-image: url('~@/assets/images/hero-left.jpg');"
        ></section>
```

My assets are located in src directory (project_root/src/assets/images). What am I doing wrong?

Have a great day.
Best regards,

**Comment by jgraham44** [comment]
I believe the problem is how Gridsome compiles the src of the images. Your best bet is to add it to a css class using the relative path and then add the class to your component/html

**Comment by sebastien-metzger** [comment]
Thank you @jgraham44 !

I am using the current solution:

```
<template>
        <section
            id="hero"
            class="bg-hero py-40 bg-cover bg-no-repeat bg-center flex justify-center"
        ></section>
</template>
<style>
.bg-hero {
        background-image: url("~@/assets/images/hero-background.jpg");
    }
</style>
```

I must use "~@" and I think it is related to Webpack.

Have a great day!
