### ISSUE TITLE
Ability to filter generated variants

### ISSUE THREAD

**Issue by makenosound** [tailwindcss/tailwindcss#1581]
Hello! I’ve used Tailwindcss on a couple of different projects now, and one thing I’ve wondered each time if there’s a method for filtering _out_ rules that will be generated by a variant context.

For example, I’d love to be able to generate `responsive` variants for _some_ of the defined colours, but not for all of them. At the moment I don’t think there’s a way to do that easily.

Is there an existing way to do that? Or is it a feature that would be _possible_ to implement?

Thanks!

**Comment by tlgreg** [comment]
No, there is no way for that atm, can only toggle variants on a per-plugin level.
And I don't think it would be possible without a bigger rewrite.
Currently, the usual workflow is to use purgecss to remove the unused css instead.

**Comment by adamwathan** [comment]
Yeah unfortunately no plans to support any finer level of granularity than we currently do.
