### ISSUE TITLE
Proposal for additional color configuration format

### ISSUE THREAD

**Issue by drKnoxy** [tailwindcss/tailwindcss#1585]
First off, big fan, love the library!

My feature request is an alternative way to structure the colors is config. I'm importing the colors from Invision and transforming the shape to match tailwind.

colors.gray['100'] 

The annoying part is that you can't sort keys in an object, and apparently insertion order isn't obeyed when (I'm guessing) the keys look like numbers with a leading 0.
```
gray = {
"100":"#eee",
"200":"#222",
"050":"#fefefe",
}

out ={}
Object.keys(gray).sort().forEach(k => out[k] = gray[k])
// Badly sorted still
```

I propose that config accept something like 
```
colors: [
{key: "100", value:"#333"}
]
```

**Comment by andrewbrey** [comment]
@drKnoxy I think you _might_ be dealing with the fact that numbers are sorted lexicographically in javascript by default, and you need to provide a comparator to the `sort()` method if you want it to sort numerically - have you tried something like this https://stackoverflow.com/a/1063027 ?

**Comment by drKnoxy** [comment]
@andrewbrey jeeez, TY

**Comment by drKnoxy** [comment]
Yeah!
The sort order in the config file dictates the sort in the generated css. I haven't hit any bugs related to this yet though, just one of those idiosyncrasies of JS

Here are the steps I'm currently going through:
1. colors are uploaded to invision in the correct shade-scale (lightest to darkest)
  gray-050, gray-070, gray-100, gray-200, gray-300
1. colors are pulled from invisions json api
1. colors are transformed into tailwind's object format

tailwind wants a format like
```
{ gray: { "050": '...', '100': '...', '200': '...', '300': '...' } }
```
so that it can produce
```
.bg-gray-050
.bg-gray-100
.bg-gray-200
.bg-gray-300
```

but I don't believe we can create an object sorted like that. (see codesandbox in previous comment)

**Comment by adamwathan** [comment]
Am I right that you aren't actually having any problems at the moment then? The only reason CSS order matters is if you are trying to do something like `<div class="bg-gray-50 bg-gray-400">`, and I can't see how it would ever be possible to make the CSS order support the exact needs of your UI in that type of situation every single time. It's also very unlikely that sorting from lightest to darkest would align with how you want the overrides to actually apply.

Why does it matter that the colors are in a specific order when the output is generated?

**Comment by drKnoxy** [comment]
I think you are totally right, i didnt take the time to think through what the conflicts in usage might look like.

Thanks for taking the time!
