### ISSUE TITLE
tailwind.com website not opening up.

### ISSUE THREAD

**Issue by abhinav098** [tailwindcss/tailwindcss#1588]
I'm trying to load tailwind: https://tailwindcss.com/

but the website is not loading up. What's the issue ?

**Comment by narwy** [comment]
The website loads fine, looks like an issue on your end.

**Comment by abhinav098** [comment]
Yeah, thanks for confirming, It's now working fine, yesterday it was not loading. You can close this issue.

**Comment by florianbouvot** [comment]
@abhinav098 I think you can close it to 😀

**Comment by abhishek00678** [comment]
when i click onny live preview its is not loading nor any componet loading i dont understand what the issue is
