### ISSUE TITLE
Tailwindcss v1.2.0 problem with margin

### ISSUE THREAD

**Issue by NM97** [tailwindcss/tailwindcss#1589]
I have a problem. I added a class to the div parameter ml-auto. Unfortunately I don't go for the effect on the website.
`<div class="ml-auto">`
Parameter e.g. ml-6 works but 'auto' does not work. I have a version installed v1.2.0
I attach the tailwind.config.js file.
[tailwind.config.txt](https://github.com/tailwindcss/tailwindcss/files/4497296/tailwind.config.txt)

**Comment by florianbouvot** [comment]
@NM97 what effect did you expect?

<div> is a block level element that take full width by default, so you need to add a width or a flexbox container or ... to obtain a result with `ml-auto`

I think you need to learn more about CSS 😉
