### ISSUE TITLE
Docs - wrong installation commands

### ISSUE THREAD

**Issue by Mikilll94** [tailwindcss/tailwindcss#1590]
![image](https://user-images.githubusercontent.com/17653648/79688343-04ee2f80-824e-11ea-84f9-058acee56762.png)

The installation command is wrong because tailwindcss should be installed as a dev dependency.

The correct commands are:

```
# Using npm
npm install tailwindcss --save-dev

# Using Yarn
yarn add -D tailwindcss
```

I.e. in the upgrade guide (https://tailwindcss.com/docs/upgrading-to-v1/#1-update-tailwind) the commands are correct.

**Comment by adamwathan** [comment]
It doesn't matter if you install it as a dev dependency or a regular dependency, it won't end up in your client bundle either way.

These days I personally prefer using regular dependencies for anything needed for building the production code (Tailwind is needed for this), and dev dependencies for tools used during development, like Prettier, Jest, etc.
