### ISSUE TITLE
Slash substitute for Pug

### ISSUE THREAD

**Issue by vannyvann** [tailwindcss/tailwindcss#1595]
Hello, amazing people!

I had some issues with colon and slash in Pug templates.
I believe Tailwind and Pug were born to be together. But...

Anyway, I found the way to change the "separator" for display option (aka colon in md:py-2), thanks or that, tbh btw!

But the slashes still make problems, like in "w-1/2" or whatever. 
How about adding some "divider" option, or something like that, so I still can enjoy TWCSS?

10x for your work, stay amazing each RC!

**Comment by adamwathan** [comment]
Hey @vannyvann! You can actually configure this already by just editing the properties in the `width` section of your config:

```js
// tailwind.config.js
module.exports = {
  theme: {
    width: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1_2': '50%',
      '1_3': '33.333333%',
      '2_3': '66.666667%',
      '1_4': '25%',
      '2_4': '50%',
      '3_4': '75%',
      '1_5': '20%',
      '2_5': '40%',
      '3_5': '60%',
      '4_5': '80%',
      '1_6': '16.666667%',
      '2_6': '33.333333%',
      '3_6': '50%',
      '4_6': '66.666667%',
      '5_6': '83.333333%',
      '1_12': '8.333333%',
      '2_12': '16.666667%',
      '3_12': '25%',
      '4_12': '33.333333%',
      '5_12': '41.666667%',
      '6_12': '50%',
      '7_12': '58.333333%',
      '8_12': '66.666667%',
      '9_12': '75%',
      '10_12': '83.333333%',
      '11_12': '91.666667%',
      full: '100%',
      screen: '100vw',
    }),
  },
}
```

No plans to introduce a configuration option for this right now unfortunately.

**Comment by vannyvann** [comment]
Great! That would do the trick.
Thanks a lot!

**Comment by tlgreg** [comment]
Slashes are used inside the config only, so it can be also overridden.
They are used in two plugins currently, `width` and `translate`.
In the default config these look like this:
https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L392-L423
https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L566-L573
```js
module.exports = {
  theme: {
    width: {
      '1of2': '50%',
    },
  },
}
```

Related older issue: #785 

Programmatic replacement is a bit trickier as you would have to resolve the config to change the keys.
Because of this, it's not really possible as a plugin but can work as an extra node utility to resolve the config.
Created a working example on codesandbox:
https://codesandbox.io/s/blue-frost-kzw86?file=/replaceFractionDivider.js

**Comment by nomadoda** [comment]
> Programmatic replacement is a bit trickier as you would have to resolve the config to change the keys.
> Because of this, it's not really possible as a plugin but can work as an extra node utility to resolve the config.
> Created a working example on codesandbox:
> https://codesandbox.io/s/blue-frost-kzw86?file=/replaceFractionDivider.js

This is great! The issue I encountered with the other approach was that I couldn't find a good way to include negative spacings.

**Comment by xxSkyy** [comment]
> Programmatic replacement is a bit trickier as you would have to resolve the config to change the keys.
> Because of this, it's not really possible as a plugin but can work as an extra node utility to resolve the config.
> Created a working example on codesandbox:
> https://codesandbox.io/s/blue-frost-kzw86?file=/replaceFractionDivider.js

Great fix! But is it possible to create divider with adding substitused not replacing? It'll make things much smoother to test in actual project and also smooth transition

**Comment by simonmaass** [comment]
has there been any new insights regarging pug and tailwind working smooth together?

**Comment by nomadoda** [comment]
> has there been any new insights regarging pug and tailwind working smooth together?

@simonmaass  Seems like the codesandbox does not exist anymore. Here is [a gist](https://gist.github.com/nomadoda/21a0afc0d270f46e6b7c227e2ceab38d) with my take on it. Then add it like this:

```js
const config = {
  theme: {
    // ...
  },
};

module.exports = replaceFractionDivider("_", config, [
  "width",
  "translate",
  "inset",
  "padding",
  "margin",
]);
```
