### ISSUE TITLE
issue with divide-x and flex

### ISSUE THREAD

**Issue by threecrowco** [tailwindcss/tailwindcss#1596]
Here's what I'm running into with .divide-x

```html
<ul class="flex text-2xl divide-x-8">
        <li>one</li>
        <li>two</li>
        <li>three</li>
        <li>four</li>
        <li>five</li>
    </ul>
```

returns

<img width="679" alt="ul-flex_with_lis" src="https://user-images.githubusercontent.com/53721001/79828543-8507b880-8366-11ea-85c0-0d82665436b8.png">

---

```html
<div class="flex text-2xl divide-x-8">
        <a href="#">one</a>
        <a href="#">two</a>
        <a href="#">three</a>
        <a href="#">four</a>
        <a href="#">five</a>
    </div>
```

returns

<img width="592" alt="div-flex_with_a-hrefs" src="https://user-images.githubusercontent.com/53721001/79828630-b7191a80-8366-11ea-8cef-d80d10ec2842.png">

**Comment by adamwathan** [comment]
Thanks, fixed in v1.3.3 👍
