### ISSUE TITLE
`space` utilities missing `responsive` variant by default?

### ISSUE THREAD

**Issue by achaphiv** [tailwindcss/tailwindcss#1597]
v1.3.1

Can't use `md:space-x-2`.

https://unpkg.com/tailwindcss@1.3.1/dist/tailwind.css

I assume `defaultConfig.stub.js` is supposed to have:

```
  variants: {
    space: ['responsive'],
  },
```

Perhaps same thing for `divide`?

**Comment by pandroid** [comment]
Have you tried

` variants: {
    stack: ['responsive'],
  },`

Adam used this in the video.

**Comment by achaphiv** [comment]
It was renamed away from `stack`.

Plugin even looks for `variants('space')`:

https://github.com/tailwindcss/tailwindcss/blob/5b3f8b5461a4e2a0a7eb6169985d37581f609ad5/src/plugins/space.js#L35

Just looks a mistake.

Release notes say:

> All of these utilities include responsive variants by default, and their values and variants can be customized using the space, divideWidth, and divideColor configuration keys respectively.

But they're clearly not in the CDN stylesheet.

**Comment by adamwathan** [comment]
🤦 Just fixed in 1.3.2, thanks for catching.
