### ISSUE TITLE
Some classes have no effect after adding Tailwind.css to a Vue.js project

### ISSUE THREAD

**Issue by paupaulaz** [tailwindcss/tailwindcss#1609]
I am trying to add Tailwind.css to a Vue.js project. There are a lot of resources on how to do this, most of them following the same path as [this video][1]. To make sure I was in the same conditions as in the video, I created a Vue app from scratch, using `vue-cli` with the default presets. After this step, I did the following :

 - `npm install tailwind.css`
 - create `src/styles/tailwind.css`
 - adding the following to the css file :
>     @tailwind base;
>     
>     @tailwind components;
>     
>     @tailwind utilities;

 - call `npx tailwind init` to create a `tailwind.config.js` file at the root of the project
 - create `postcss.config.js` at the root of the project, and add the following to this file:

>    module.exports = {
>      plugins: [require("tailwindcss"), require("autoprefixer")],
>    };

 - add a custom color to the `tailwind.config.js` file :

> module.exports = {   theme: {
>     colors: {
>       "awesome-color": "#56b890",
>     },
>     extend: {},   },   variants: {},   plugins: [], };

- adding a simple `<p>` element to the `HelloWorld.vue` component generated by `vue-cli`
- trying to style it using `tailwind` classes

Finally, here is the problem : I can apply some classes like `bg-awesome-color` or `text-xl` and have them render properly, but a lot other classes won't work.

For instance, removing those classes and trying instead `bg-black`, `bg-orange-500`, or `text-orange-500` has strictly no effet. Did I do something wrong ? Would that be a problem of compatibility bewteen Vue.js and Tailwind.css ?

I do not know if this is related, by I also noticed that after adding Tailwind.css, the Vue logo, that used to be centered in the original `vue-cli` template, was now aligned left in the page.

Thank you very much for any help !

[1]: https://www.youtube.com/watch?v=J5CUrUSCuO0

**Comment by adamwathan** [comment]
You overrode all of the default colors in your config file when you did this:

```js
module.exports = {
  theme: {
    colors: {
      "awesome-color": "#56b890",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
};
```

Use the `extend` feature if you want to add new colors:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        "awesome-color": "#56b890",
      },
    },
  },
  variants: {},
  plugins: [],
};
```

Hope that helps!

**Comment by paupaulaz** [comment]
Indeed, thank you so much !
