### ISSUE TITLE
rtl mode

### ISSUE THREAD

**Issue by vahidalvandi** [tailwindcss/tailwindcss#1613]
hello , how i can use tailwindcss in rtl language like persian ?

**Comment by adamwathan** [comment]
Check out the previous discussion here:

https://github.com/tailwindcss/discuss/issues/64

**Comment by lijoantony** [comment]
https://www.npmjs.com/package/tailwindcss-rtl

**Comment by vahidalvandi** [comment]
please add RTL in core tailwindcss

**Comment by soheilhassanjani** [comment]
https://www.npmjs.com/package/rtl-tailwindcss
