### ISSUE TITLE
[Proposal] 'child' variant 

### ISSUE THREAD

**Issue by muzafferdede** [tailwindcss/tailwindcss#1618]
Hi,

I was thinking if there is a possibility to achieve such a way to define child element's style on parent as : 

```html
<ul class="child:text-gray-900 lg:child:text-gray-500 bg-white child:bg-black">
  <li>Lorem ipsum dolor sit amet</li>
  <li>Lorem ipsum dolor sit amet</li>
  <li>Lorem ipsum dolor sit amet</li>
  <li>Lorem ipsum dolor sit amet</li>
</ul>

```
and we can enable it as 

```js
textColor: ['responsive', 'hover', 'focus', 'active', 'group-hover','child'],
backgroundColor: ['responsive', 'hover', 'focus', 'active', 'group-hover','child'],
```

It will be very helpful for `Single source of truth` class usages on DOM. 

Thanks.

**Comment by benface** [comment]
Hey @muzafferdede check out my [`tailwindcss-children` plugin](https://github.com/benface/tailwindcss-children).

**Comment by muzafferdede** [comment]
> Hey @muzafferdede check out my [`tailwindcss-children` plugin](https://github.com/benface/tailwindcss-children).

Yeah, this is indeed does what I mentioned.
