### ISSUE TITLE
How to fix vscode code error with the @apply mixins

### ISSUE THREAD

**Issue by MattixNow** [tailwindcss/tailwindcss#1619]
Hey i tried to use the `@apply` mixins in my code but i cannot use multiple class next to the previous. How can i fix that ?
![image](https://user-images.githubusercontent.com/32040951/80261284-4c2f5280-868a-11ea-840e-db01e5823bd0.png)
On a nuxtjs project

**Comment by Apostolique** [comment]
Install the [language-postcss](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss) extension, then add this to your vscode config:

```json
"files.associations": {
    "*.css": "postcss"
}
```

**Comment by MattixNow** [comment]
Vscode remove color code highlight with postcss syntax

Mattèo Gauthier
tel : 07 81 71 73 66
mattèo.dev <https://xn--matto-7ra.dev/>


Le sam. 25 avr. 2020 à 02:49, Adam Wathan <notifications@github.com> a
écrit :

**Comment by Ostendorf** [comment]
I've been looking a few days for the perfect solution now, but have not found it. 
I'm using Visual Studio Code, NuxtJS (Vue.js) and Tailwind with SCSS.

Setting lang to postcss is not a perfect solution. It does work for the syntax highlighting, but it removes/disables the SCSS linting checks done by Vetur (VS Code plugin).

The second style in the `@apply` always breaks it. Using just 1 keeps it ok (but then why use Tailwind).

Right now i've settled for VS Code + Vetur plugin and disabled the linting in the vscode settings:
```json
"vetur.validation.style": false,
```

Then in `.vue` files you can use the proper lang:
```html
<style lang="scss" scoped>
```
It then still does highlighting, but sadly doesn't check for errors.

If anyone has a way to use syntax highlighting and linting/validation in a vue file with SCSS and Tailwind, please let me know 🙂

**Comment by martinrojas** [comment]
The closest thing I have seen to a solution seems by installing another plugin. https://www.meidev.co/blog/visual-studio-code-css-linting-with-tailwind/

but this can't be the right answer can't be. Where is the lint config file that vs code uses and its causing the error
