### ISSUE TITLE
Last Child does not work as per example in documentation

### ISSUE THREAD

**Issue by icithis** [tailwindcss/tailwindcss#1651]
The example is located here:

https://tailwindcss.com/docs/pseudo-class-variants/#last-child-v1-1-0

You can see the broken functionality here using the latest CDN resource:

https://jsfiddle.net/FoomFries/vgse0k2b/2/

**Comment by adamwathan** [comment]
The CDN build doesn't include last-child variants for anything out of the box. You have to enable it for the utilities you want it for in your `tailwind.config.js` file 👍 

![image](https://user-images.githubusercontent.com/4323180/80616077-75dfd500-8a0e-11ea-9725-eb31d8dce993.png)

**Comment by icithis** [comment]
Ah, I had missed that statement. Enabling them on my installation via the variants in the tailwind.config.js resolved the issue. Thanks!
