### ISSUE TITLE
Invisible items are still accounted for in .space-* utilities

### ISSUE THREAD

**Issue by Francismori7** [tailwindcss/tailwindcss#1657]
Here's the code:

```
<form action="" class="space-y-6">
    @csrf
    
    <div>1st input</div>
    <div>2nd input</div>
</form>
```

Laravel changed the @csrf for a input[type=hidden] field. It is still used to add margin-top to the "1st input".

**Comment by robmcfadden** [comment]
Wrapping only the items you want to be spaced with their own div might make the most sense here.

```
<form action="">
    @csrf

    <div class="space-y-6">
        <div>1st input</div>
        <div>2nd input</div>
    </div>
</form>
```

**Comment by brandonpittman** [comment]
Awesome.

**Comment by adamwathan** [comment]
This is just an accepted limitation, it's not realistic to make these classes totally bullet proof under all circumstances, for example if you have this markup you get the same issue and it's pretty hard to work around sensibly with CSS alone:

``html
<div class="space-y-6">
  <div class="md:hidden">...</div>
  <div>...</div>
  <div>...</div>
</div>
```

The `space`/`divide` utilities are never going to be absolutely flawless silver bullet solutions I'm afraid, but they are very useful 90% of the time.
