### ISSUE TITLE
Version 1.4 breaks on npm run build

### ISSUE THREAD

**Issue by jenstornell** [tailwindcss/tailwindcss#1664]
I did not get the impression that version 1.4 is a breaking change? If it's not, there may be a bug?

I run `npm run build` just like always (from your Youtube video). I get this.

```
npm run build

> doBlog@1.0.0 build D:\projects\libraries\doBlog
> postcss assets/css/src/tailwind.css -o assets/css/dist/tailwind.css

D:\projects\libraries\doBlog\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doBlog@1.0.0 build: `postcss assets/css/src/tailwind.css -o assets/css/dist/tailwind.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the doBlog@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jenst\AppData\Roaming\npm-cache\_logs\2020-04-30T07_33_00_206Z-debug.log
```

## Possible reason

My guess is that the purge option is not optional but required, which breaks when the config file is not changed to support it?

**Comment by jenstornell** [comment]
This was probably not related to Tailwind at all. First I updated with `npm update`. After that it stopped working.

I had Node 9 installed and the current version is 12. That seems to be the cause of this problem.

I found the solution here where they had a similar problem: https://github.com/ColorlibHQ/AdminLTE/issues/2631

**Comment by adamwathan** [comment]
This should have worked anyways honestly — we test against Node 8, 10, and 12. There were a few releases where we mistakenly broke Node 8 support (1.3.0 through 1.3.4) but 1.4.0 should definitely be Node 8 compatible. Glad you got it fixed, I suspect another solution would have been to delete node_modules and re-install.

**Comment by jenstornell** [comment]
@adamwathan I did a whole lot of things, including deleting `node_modules`, rolled back to Tailwind `1.3` and so on. I even reverted all settings and styles, but it was still broken. Therefor it was not really related to Tailwind in the first place.

The problem seems to appear when I had the latest version of `fs-extra` (when I updated all node modules) in combination of an old Node version.
