### ISSUE TITLE
Tailwind not working with vue

### ISSUE THREAD

**Issue by whytepeter** [tailwindcss/tailwindcss#1666]
i installed tailwindcss into a vuejs SPA did all the setup 
create a assets/css/tailwind.css and added the necessary base styles
imported it in the main.js file
create a postcss.config.js file and copied the required configuration from the official documentation

but the tailwind styles don't apply to my markups
inside the tailwind.css
`@tailwind base;

@tailwind components;

@tailwind utilities;
`

inside the postcss.config.js
`module.exports = {
  plugins: [
    // ...
    require("tailwindcss"),
    require("autoprefixer"),
    // ...
  ],
}
`

inside the main.js file
`import Vue from "vue"
import App from "./App.vue"
import "./registerServiceWorker"
import router from "./router"
import store from "./store"
import axios from "axios"
import "./assets/css/tailwind.css"
import firebase from "firebase/app"
import "firebase/firestore"
import "firebase/auth"`

The package.json file
`"dependencies": {
    "autoprefixer": "^9.7.6",
    "axios": "^0.19.2",
    "core-js": "^3.6.4",
    "firebase": "^7.14.2",
    "register-service-worker": "^1.7.1",
    "tailwindcss": "^1.4.0",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6",
    "vuex": "^3.1.3"
  },`
I don't know what am doing wrong

**Comment by adamwathan** [comment]
I'm not sure if you can import your styles into `main.js`, usually you do it in `App.vue`.
