### ISSUE TITLE
[Doc] Linf of installation for CDN still refers to 1.0 version

### ISSUE THREAD

**Issue by ASmallCookie** [tailwindcss/tailwindcss#1671]
Hello

The installation link for cdn still refers to version 1.0. 
It **should use the following link instead** in order to always have the latest version, because at the moment this leads to confusion. If someone could change that. 

[https://unpkg.com/tailwindcss/dist/tailwind.min.css](https://unpkg.com/tailwindcss/dist/tailwind.min.css)

![tailwind-issue](https://user-images.githubusercontent.com/42717232/80717108-bf0c5380-8af8-11ea-8ae2-6f27194865a6.png)

**Comment by adamwathan** [comment]
This is intentional so that sites/demos using the CDN don't accidentally break when we tag 2.0 some time in the future. We made this mistake with 0.x and all of the Codepens and stuff that used the versionless CDN URL broke when we released 1.0.
