### ISSUE TITLE
Turning off divideWidth in corePlugins config still generates CSS

### ISSUE THREAD

**Issue by pandroid** [tailwindcss/tailwindcss#1685]
I turned off divideWith, divideOpacity and divideColor in the config but still get CSS 

Configuration
`corePlugins: {
    divideWith: false,
    divideOpacity: false,
    divideColor: false,}`

CSS Output
`.divide-y-4 > :not(template) ~ :not(template) {
  --divide-y-reverse: 0;
  border-top-width: calc(4px * calc(1 - var(--divide-y-reverse)));
  border-bottom-width: calc(4px * var(--divide-y-reverse));
}
...`

**Comment by adamwathan** [comment]
Looks like you have a typo in your config, it should be `divideWidth` not `divideWith`.

**Comment by pandroid** [comment]
Thank you, Adam for your quick response. You're right, it was a typo. Sorry.
