### ISSUE TITLE
[Feature proposal] Namespaced class names

### ISSUE THREAD

**Issue by zkwbbr** [tailwindcss/tailwindcss#1689]
Since Tailwind are mostly utility class, it would nice be if there's a namespaced version available (alongside with the usuall classes). E.g., `tw-m-1` or `tw-p-1`. This way it might just be possible to use Tailwind with other CSS frameworks like Bootstrap or MaterializeCSS.

**Comment by adamwathan** [comment]
Already got you covered friend 🍻

https://tailwindcss.com/docs/configuration/#prefix

**Comment by zkwbbr** [comment]
@adamwathan  Awesome.

**Comment by designbyadrian** [comment]
@adamwathan Not all heroes wear capes!
