### ISSUE TITLE
divide-y with border-r on child changes color

### ISSUE THREAD

**Issue by tanthammar** [tailwindcss/tailwindcss#1693]
"@tailwindcss/ui": "^0.3.0",
"tailwindcss": "^1.4.4",

-  I have an `ul` with dividers for the `li` children. 
- I use Alpinejs to add a **`border-r`** and `border-color` when an `li` is clicked.
- When I click on an `li` the `active` (w border-r and color) class is applied.

**Problem**

The `li` changes it's **`border-t`** which none of the classes should change.

```html
<ul class="divide-y divide-gray-300">
    <template x-for="(panel, index) in panels" :key="index">
        <li :class="{ 'active': tab === panel.name }" x-on:click="tab = panel.name" class="vtab" x-text="panel.label" />
    </template>
</ul>
```

Here are the classes
```css
li.vtab {
  @apply p-2;
  @apply text-gray-700 text-xs tracking-wider uppercase;
}
li.vtab.active {
  @apply border-r-4 border-gray-800;
}
li.vtab:hover {
    @apply bg-gray-100;
}
```

<img width="403" alt="tabs" src="https://user-images.githubusercontent.com/21239634/80918636-49a5ba80-8d66-11ea-9aa9-b087d30e5966.png">

**Comment by hkan** [comment]
`border-{color}` utilities change the color for all the borders of the applied element. `divide-*` utilities work by literally adding borders to child elements. Thus the problem you are having is the expected behavior.

Since you are using custom utilities, you can work around the issue though. Try this:

    // instead of this:
    li.vtab.active {
      @apply border-r-4 border-gray-800;
    }

    // do this:
    li.vtab.active {
      @apply border-r-4;
      border-right-color: theme('colors.gray-800');
    }

**Comment by tanthammar** [comment]
Perfect! Thank you :)
