### ISSUE TITLE
space-x and space-y not working using flex-row-reverse and flex-col-reverse

### ISSUE THREAD

**Issue by richardthombs** [tailwindcss/tailwindcss#1698]
I think the space-x and space-y classes are broken when used in reversed flexboxes. See how the  spacing is wrong on the 2nd and 4th blocks in the screenshot below?

Example here: https://jsbin.com/boyeyepeto/edit?html,output

![image](https://user-images.githubusercontent.com/1511599/80952991-91722380-8df2-11ea-9813-5260758c3627.png)

**Comment by adamwathan** [comment]
Use the reverse modifiers:

https://tailwindcss.com/docs/space/#reversing-children-order

**Comment by richardthombs** [comment]
Doh, thank you @adamwathan !
