### ISSUE TITLE
Add coreplugin 'transform' to whitelist gives error

### ISSUE THREAD

**Issue by JanaVanMaele** [tailwindcss/tailwindcss#1699]
As in the documentattion described you can whitelist coreplugins. One of this coreplugins is 'transform', but when I add to my array of coreplugins I get following error:

TypeError: plugins[pluginName] is not a function
    at pluginNames.map.pluginName (/Users/janavanmaele/Sites/Yesplan-app/node_modules/tailwindcss/lib/util/configurePlugins.js:12:59)

I tried to add 'translate' as well and also this one fails to compile.

**Comment by adamwathan** [comment]
Can you share your Tailwind config file or a link to a GitHub repo that reproduces the issue? I need a lot more context to help and a reproduction is by far the most useful thing.

**Comment by JanaVanMaele** [comment]
Fixed. Apparently I was running some tailwindcss versions behind. Updating to 1.4.4 fixed the issue.
