### ISSUE TITLE
Wrong class names on the documenation

### ISSUE THREAD

**Issue by scanadi** [tailwindcss/tailwindcss#1709]
Hello ! 

I noticed worng class names in the documentation for the Divide Opacity

they are listed as .border-opacity

https://tailwindcss.com/docs/divide-opacity/#app

![image](https://user-images.githubusercontent.com/1336058/81045922-892fec00-8eb7-11ea-99b6-4c57d3e9a786.png)

**Comment by adamwathan** [comment]
Fixed, thanks!
