### ISSUE TITLE
TWs PurgeCSS Not Purging `.components` when Unused

### ISSUE THREAD

**Issue by jhauraw** [tailwindcss/tailwindcss#1725]
The docs indicate that TW's Components will be purged if not used in project, but when building local CSS (no `.container` class in project), Components remain.

Setup v1.4.4 NODE_ENV=production:
```
// tailwind.config.js
module.exports = {
  purge: [
    '// snip',
  ]
}
```

Docs conceptual example shows:
```js
/* Start purging... */
@tailwind  components;
/* Stop purging. */
```

Docs link:
https://tailwindcss.com/docs/controlling-file-size#purgecss-options

So not sure which one is the intended behavior, but if we can vote, I would vote that Components get purged just like Utilities.

Thanks for this great project and the hard work 👍

**Comment by izznatsir** [comment]
it's not
`/* Start purging... */
@tailwind  components;
/* Stop purging. */`

but, it is:
`/* purgecss start ignore */
@tailwind  base;
@tailwind  components;
/* purgecss end ignore */`

which means base and components will not be purged even when the class is not being used.

**Comment by jhauraw** [comment]
@izznatsir that was not the case when I made this Issue. @adamwathan made some changes to the docs right after I posted the issue which aligned the docs with the behavior. I was hoping he would decide to purge components with base which makes more sense to me. You can see the commit here (lines 93 and 102). Not sure why he didn't update this issue at the same time.

https://github.com/tailwindcss/docs/commit/b773c2253c77b1dad87ad38d2f09b071fb32291d#diff-713d5e494f5f7bf76cb67bd850e29dc5L102

**Comment by adamwathan** [comment]
The main reason I decided not to purge components by default is because in my own projects I very often have components like this:

```less
.markdown {
  @apply text-lg text-grey-darkest leading-normal;
  & > * + *,  & li + li, & li > p + p {
    @apply mt-6;
  }
  & strong {
    @apply text-black font-bold;
  }
  & a {
    @apply text-black font-semibold;
  }
  & strong a {
    @apply font-bold;
  }
  & h2 {
    @apply leading-tight text-xl font-bold text-black mb-2 mt-10;
  }
  & h3 {
    @apply leading-tight text-lg font-bold text-black mt-8 -mb-2;
  }
  & code {
    @apply font-mono text-sm inline bg-grey-lighter px-1;
  }
  & pre code {
    @apply block bg-black p-4 rounded;
  }
  & blockquote {
    @apply border-l-4 border-grey-light pl-4 italic;
  }
  & ul, & ol {
    @apply pl-5;
    @screen sm {
      @apply pl-10;
    }
  }
}
```

Since the actual source files these styles are generally targeting are markdown files, these styles are easy to accidentally purge because PurgeCSS sees `## My heading` instead of `<h2>My heading</h2>` and deletes the `h2` styles because it doesn't think they are needed.

We can add more modes if we want though, so you can purge both components and utilities, just need to think of an API that feels right.

Maybe this?

```
module.exports = {
  purge: {
    mode: ['utilities', 'components'],
    content: [...]
  }
}
```

**Comment by jhauraw** [comment]
@adamwathan ah-ha. Your example made clear what I wasn't understanding from the docs. Is this correct?: Tailwind's built-in purge routine won't purge tailwind/components, NOR anything *between* that and tailwind/utilities in a CSS entry point file?

Put another way, when the docs talk about tailwind's built-in purging and components, it means tw's built-in purge skips over everything *between* tw/comp and tw/util inside the entry point? So the purge for user added CSS is entry point file location based, rather than explicit imports.

**Comment by alexdilley** [comment]
@jhauraw you could consider [disabling the `.container` class](https://tailwindcss.com/docs/container/#disabling) as an alternative to purging its non-usage.

**Comment by jhauraw** [comment]
@alexdilley hi yes good idea. That's what I did last week when I saw the new capability to do it: (marketempower/axiom:91e6189)

**Comment by jhauraw** [comment]
@alexdilley hi yes good idea. That's what I did last week when I saw the new capability to do it: (https://github.com/marketempower/axiom/commit/91e6189be4b9c00ca5664e97290d2487468e9ff0)

**Comment by Rotario** [comment]
I think this should be added to the [docs](https://tailwindcss.com/docs/guides/vue-3-vite). It's a simple and obvious fix, but I spent hours messing around thinking config files/paths were wrong because the docs made me think it couldn't possibly be the NODE_ENV variable.
Is it possible to open a PR with the Docs?
