### ISSUE TITLE
Redesign the site?

### ISSUE THREAD

**Issue by jenstornell** [tailwindcss/tailwindcss#1750]
https://tailwindcss.com/ - I like the site. It's very functional and looks fine, but I think it could look much better, with a few changes.

I've also seen this site https://tailwindui.com/components and I think it looks great. So what did you do with `tailwindui` that you did not with `tailwindcss`?

**Here is what I think**

1. Nicer waves in the logo. You already have that on `tailwindui`. No gradients needed on them. To me it's like comparing a logo from 2016 to a logo from 2020, kind of like that.
1. `tailwindcss` looks a bit too foggy (for my taste). On `tailwindui` you have really cleaned it up and have a great color palette. Not too much fuzzy gray there. Clean, sharp and out of the fog.

I'm not sure you plan a redesign for tailwindcss or not, but I think you can improve it a lot with just a few fixes here and there.

I hope I did not offend you with this post.

**Comment by estevanmaito** [comment]
I don't mean to answer your questions (as I'm not in charge of anything), but to show a different point of view.

> So what did you do with tailwindui that you did not with tailwindcss

Tailwind UI is a product, it's website only job is to sell. It has to convince you that their price is worth what you will receive.
Tailwind CSS, the documentation website, well, it's a documentation. It has to be clear, inobstrusive. In my opinion, a documentation selling point is: "this may not seem easy, but you can find everything you need with one click".

About the _foggy_, I agree with you, but from a different perspective: it is completely inaccessible.

Category titles use `text-gray-500` over a white background. It results in a constrast ratio of 2.26, while the minimum should be 4.5 (AA) or 7.0 (AAA).  `text-gray-600` would result in a contrast ratio of 4.02 and still fail. `text-gray-700` would result in both AA and AAA passing, with 7.53.

Subcategories fail too. They are using `text-gray-600`, resulting in 4.02. `text-gray-700` would pass AA with 6.14 but fail AAA. `text-gray-800` would pass both tests with a CR of 9.79 and also still be a step above the gray scale of the category titles if implemented with the previous solution.

I think this could be another issue.

**Comment by benji014628** [comment]
i noticed that too lol

**Comment by adamwathan** [comment]
A full redesign/rebuild of the docs site is on the roadmap but not a huge priority right now. Tailwind UI looks better because we designed it more recently, new stuff always looks better than old stuff, heh. Thanks for the suggestions, going to close since already something we're planning on.
