### ISSUE TITLE
PurgeCSS feature is removing unexpected classes

### ISSUE THREAD

**Issue by Aferz** [tailwindcss/tailwindcss#1757]
Hello @adamwathan 

First of all, thank you for this awesome CSS "framework". Totally awesome and your efforts to maintain it are outstanding. Such amazing quality.

Now the issue:

version **1.4.6**:

I've changed my PurgeCSS config from `postcss.config.js` to the new `purge` attribute. I just copied what I had, **literally**, and it **almost** worked. I've found these classes are being removed without explanation (They are used statically in my vue templates):

`fixed`, `scale-95` (and all its variants, `scale-100`, etc ...)

An example:

```html
<transition
  enter-class="opacity-0 translate-y-0 scale-90"
  enter-active-class="ease-out duration-300 delay-200"
  enter-to-class="opacity-100 translate-y-0 scale-100"
  leave-class="opacity-100 translate-y-0 scale-100"
  leave-active-class="ease-in duration-200"
  leave-to-class="opacity-0 translate-y-0 scale-90"
>
  <div
    v-show="open"
    class="fixed z-50 transform transition"
  >
    <slot />
  </div>
</transition>
```

I'm struggling to understand why because I'm using the classes and I just copied from one file to another...

Anyone is experiencing the same issue?

Thank you guys!

**Comment by adamwathan** [comment]
Hey! Can you share your Tailwind config? Even better would be a GitHub project that reproduces the issue.

**Comment by Aferz** [comment]
Argh,

I'd a typo in one of my paths, and PurgeCSS just ignore the mistyped paths and don't give you a warning.

**Be careful with what you type in your `content` attribute, future issuers!**

Sorry for wasting your time.
