### ISSUE TITLE
Allow `.purge.options` to be a function

### ISSUE THREAD

**Issue by knowler** [tailwindcss/tailwindcss#1758]
Currently, PurgeCSS options are evaluated even if they aren’t being used. I have a rather heavy duty whitelisting function happening which is slowing my development build (even though purging isn’t happening). Allowing, `.purge.options` to be a function that is called only when PurgeCSS runs could fix this, but I’m sure there might be other solutions.

**Comment by estevanmaito** [comment]
You could watch for env variables like `NODE_ENV` and just run your function if it's a production environment, eg:

In `tailwind.config.js`

```js
const isProd = process.env.NODE_ENV === 'production'

module.exports = {
  purge: {
    enabled: true,
    content: ['./**/*.html'],
    options: {
      whitelist: isProd ? ['bg-indigo-500'] : null,
    },
  },
  theme: {},
  ...
```

In this naive example `bg-indigo-500` would only be available in production, but it could be a function instead.

**Comment by knowler** [comment]
I think that’s a better solution and what I ended up doing. Thanks @estevanmaito!
