### ISSUE TITLE
Colors not shown anymore within VS Code

### ISSUE THREAD

**Issue by MartijnHarmenzon** [tailwindcss/tailwindcss#1770]
I believe since Tailwind 1.4.x, colors are not shown anymore by color highlighters/pickers within VS Code. Is anyone else experiencing this issue? Might it have to do with the class bg-opacity? Same is with text colors. I am using the VS Code packages Tailwind CSS IntelliSense and Color Highlight.

![image](https://user-images.githubusercontent.com/23123158/81907149-9a6bad80-95c7-11ea-8050-819107bb042a.png)

**Comment by estevanmaito** [comment]
It's an issue with the extension, Tailwind CSS IntelliSense, not the library.

It's been already pointed here https://github.com/bradlc/vscode-tailwindcss/issues/113 and solved (although not yet released).

**Comment by MartijnHarmenzon** [comment]
Thanks @estevanmaito.
