### ISSUE TITLE
Tailwind Not Found when deploying to Heroku

### ISSUE THREAD

**Issue by jetro4u** [tailwindcss/tailwindcss#1771]
I am having challenge deploying my React App to Heroku. I used and declare Tailwindcss in my devDependencies. When I tried to deploy to Heroku, I got the error in the bash that Tailwind is not found. My Package.son script looks like:

```
"scripts": {
        "start": "yarn run tailwind && react-scripts start",
        "build": "yarn run tailwind && yarn run purge-tailwind && cross-env GENERATE_SOURCEMAP=false react-scripts build",
        "tailwind": "tailwind build ./src/styles/tailwind-config.css -c ./tailwind.config.js -o ./src/styles/tailwind.css",
        "purge-tailwind": "node ./purge-tailwindcss.js",
        "test": "react-scripts test --env=node",
        "eject": "react-scripts eject",
        "build-docs": "find ./src/app/main/documentation/material-ui-components \\( -name '*.ts' -o -name '*.tsx' \\) -type f -delete && babel-node --presets @babel/preset-env src/app/main/documentation/material-ui-components/build.js",
        "analyze": "yarn run tailwind && yarn run purge-tailwind && react-scripts build && source-map-explorer 'build/static/js/*.js' --html analyze-result.html",
        "pnpify-sdk": "yarn pnpify --sdk",
        "lint": "eslint"
    },

```

**Comment by estevanmaito** [comment]
Could you share the complete error message?

**Comment by cjfloss** [comment]
Whithout seeing the log message, I can give you this guess.
Heroku runs on production environment so "devDependencies" are not installed.
To run tailwind commands you should put tailwindcss on the "Dependencies" part of your packages.json.

**Comment by cjfloss** [comment]
Expanding on my previous answer, here is what [Heroku's documentation says](https://devcenter.heroku.com/articles/nodejs-support#package-installation)

---
By default, Heroku will install all dependencies listed in package.json under dependencies and devDependencies.

After running the installation and build steps Heroku will strip out the packages declared under devDependencies before deploying the application.

**Comment by jetro4u** [comment]
Ok. Thanks. I'll look into it
