### ISSUE TITLE
We're hiring a developer to join the Tailwind team!

### ISSUE THREAD

**Issue by adamwathan** [tailwindcss/tailwindcss#1779]
Hey everyone! 👋 

Steve and I are hiring a full-stack developer to join the Tailwind team and help us with existing tools and products (like Tailwind CSS and Tailwind UI), as well as brand project ideas like official Tailwind UI React and Vue libraries.

It's a full-time remote position open to anyone who can overlap ~4 hours per day with the EST timezone, with a salary of $115,000 – $135,000 USD.

[&rarr; **Read the full job posting**](https://jobs.tailwindui.com/full-stack-developer)

If that sounds like something you'd be interested in, we'd love for you to apply ❤️

**Comment by diazabdulm** [comment]
Is this still open?

**Comment by pumano** [comment]
@adamwathan I'm also interested.

**Comment by paulocuambe** [comment]
@pumano and @diazabdulm the job is closed. He provided a link with all the details...

**Comment by pumano** [comment]
@adamwathan thanks
