### ISSUE TITLE
Cleanup old/merged branches

### ISSUE THREAD

**Issue by MichaelDeBoey** [tailwindcss/tailwindcss#178]
The following branches are all merged into `master` (except `improve-flexbox-search`, but that one's fixed on the Agolia side, see [#170 (comment)](https://github.com/tailwindcss/tailwindcss/pull/170#issuecomment-343325749)), so I guess they can be deleted?
Just keeping the repo a bit cleaner I think 🙂

- [`add-message-after-tailwind-init`](https://github.com/tailwindcss/tailwindcss/tree/add-message-after-tailwind-init)
- [`agolia`](https://github.com/tailwindcss/tailwindcss/tree/agolia)
- [`fix-path-issues`](https://github.com/tailwindcss/tailwindcss/tree/fix-path-issues)
- [`improve-flexbox-search`](https://github.com/tailwindcss/tailwindcss/tree/improve-flexbox-search)
- [`psren-fix-issue-18`](https://github.com/tailwindcss/tailwindcss/tree/psren-fix-issue-18)

**Comment by adamwathan** [comment]
Done, don't need to create issues for this sort of thing though, we clean up that stuff periodically already.

**Comment by MichaelDeBoey** [comment]
Just wanted to help keep the repo a bit cleaner that's all 🙂

Keep up the great work @adamwathan! 🙂

**Comment by reinink** [comment]
We appreciate it @MichaelDeBoey! Thanks for your interest in this project! 🕺
