### ISSUE TITLE
text-opacity does not work for inherited colors

### ISSUE THREAD

**Issue by dpeek** [tailwindcss/tailwindcss#1780]
Not sure if this is by design or simply a limitation of CSS variables, but the following:

```html
<div class="text-black">
    <div class="text-opacity-50">text-color inherited</div>
  </div>
  <div class="text-black text-opacity-50">text-color inline</div>
```

Renders like this:

<img width="170" alt="image" src="https://user-images.githubusercontent.com/128329/82051448-364b0580-96fd-11ea-8119-aa81f6ef2805.png">

Had me scratching my head for a bit – which is unusual since tailwind normally works exactly the way I want it to :) Awesome project!

**Comment by estevanmaito** [comment]
It's a [CSS custom properties definition](https://www.w3.org/TR/css-variables-1/#example-942ce4d7), that Tailwind uses to evaluate colors.

> It is important to note that custom properties resolve any var() functions in their values at computed-value time, **which occurs before the value is inherited**.

So, in your case:

1. `text-black` resolves to `color: rgba(155,44,44,var(--text-opacity));`
2. `--text-opacity` is evaluated and probably set to 1 (default).
3. `text-opacity-50` resolves to `--text-opacity: 0.5;`, but at this time, it's useless.

The solution is exactly your second example, apply the color **and** the opacity right in the element.

**Comment by frederikhors** [comment]
Same problem here.

**Comment by dpeek** [comment]
@estevanmaito thanks for the detailed explanation. Should probably mention this limitation in the docs as it’s not consistent with other utils in tailwind.

**Comment by estevanmaito** [comment]
@dpeek  What do you think would be a useful message in the docs that if you had seen before, would help you with this issue?

Right now, the **Usage** text on [Text Opacity](https://tailwindcss.com/docs/text-opacity#usage) says:

> Control the opacity of an element's text color using the .text-opacity-{amount} utilities.

Would appending something like this be useful? _This utility is not inherited, so you should use it directly on the target element(s)._

It's probably the case for other utilities that use custom properties also.

**Comment by dpeek** [comment]
My confusion isn't that you have to use opacity on the element, but the fact you need to specify a colour utility on the same element as well. So, maybe something like:

"This utility should be used as a modifier to the `text-color` utilities, and must be defined on the same element as the color to function."

**Comment by estevanmaito** [comment]
> you need to specify a colour utility on the same element as well

Yeah, I forgot that.

Your warning sounds better. Mine would confuse people, as this example is inheriting but works perfectly.

```html
<div class="text-black text-opacity-50">
  <div>text-color inherited</div>
  <div>text-color inherited</div>
</div>
```

If approved, I think it should be issued in the [docs ](https://github.com/tailwindcss/docs)repo. Are you interested in implementing this? If not, I could do it.

**Comment by adamwathan** [comment]
Merged the docs PR, thanks!

**Comment by frederikhors** [comment]
Is this missing in docs for v3, or am I wrong?
