### ISSUE TITLE
divide-x creates useless blank space

### ISSUE THREAD

**Issue by frederikhors** [tailwindcss/tailwindcss#1784]
Can I ask you why in this example it gives me blank space after "Github" and "LinkedIn" links?

REPL: https://codepen.io/fredhors/pen/vYNVPRo

```
<div class="divide-x-4 divide-blue-500">
   <a class="bg-red-500" href="#">Github</a>
   <a class="bg-red-500" href="#">LinkedIn</a>
   <a class="bg-red-500" href="#">Something Else</a>
</div>
```

![image](https://user-images.githubusercontent.com/41120635/82148652-0f9fe280-9855-11ea-933c-6c9c92c7527d.png)

**Comment by adamwathan** [comment]
That's just the whitespace in between your links and it's present even if you don't use the divide utilities at all:

https://jsfiddle.net/gwf1pzuv/2/

To remove it you'd have to remove the whitespace from your markup or use flexbox:

```html
<div class="divide-x-4 divide-blue-500">
    <a class="bg-red-500" href="#">Github</a><!--
 --><a class="bg-red-500" href="#">LinkedIn</a><!--
 --><a class="bg-red-500" href="#">Something Else</a>
</div>
```

```html
<div class="divide-x-4 divide-blue-500 flex">
  <a class="bg-red-500" href="#">Github</a>
  <a class="bg-red-500" href="#">LinkedIn</a>
  <a class="bg-red-500" href="#">Something Else</a>
</div>
```
