### ISSUE TITLE
Importing .scss file with @apply not working.

### ISSUE THREAD

**Issue by sonicparke** [tailwindcss/tailwindcss#1787]
Hi,

I'm trying to add tailwind to an angular/cli project and it works great except one thing. When I try to use `@apply` in `app.component.scss` the apply isn't being built. I've got a repo [here](https://github.com/sonicparke/tailwind-angular).

Am I doing something wrong or is this not supported?

Thanks!

**Comment by estevanmaito** [comment]
Your webpack config is just loading this file: `test: /tailwind\.scss$/,`

It should be testing every sass/scss file: `test: /\.s[ac]ss$/i,`

**Comment by sonicparke** [comment]
> Your webpack config is just loading this file: `test: /tailwind\.scss$/,`
> 
> It should be testing every sass/scss file: `test: /\.s[ac]ss$/i,`

Damn. Thanks! Never even thought to check that.
