### ISSUE TITLE
Add a link to GitHub from the Docs

### ISSUE THREAD

**Issue by coliff** [tailwindcss/tailwindcss#179]
Would be useful to have a link to his repo from the Docs
https://tailwindcss.com/docs/

**Comment by MichaelDeBoey** [comment]
If you click the version number underneath the logo (top right in the navigation), you'll be redirected to the [releases page](https://github.com/tailwindcss/tailwindcss/releases) on this repo 🙂

**Comment by adamwathan** [comment]
Yeah we need to redesign the docs a bit in general; lots of stuff it doesn't really accommodate yet :/ I'm going to at least add a little GitHub icon under the search for now.

**Comment by coliff** [comment]
oh right, that's quite hidden - didn't know that was a link.
