### ISSUE TITLE
Prefix + border class not working

### ISSUE THREAD

**Issue by kb1995** [tailwindcss/tailwindcss#1794]
I added a "tw-" prefix, and it's working for all classes expect for "border" class

For example:

"tw-border" class is not working, but "border" class is working.

It's fine for all other classes. As far as I can see, no other selectors influence my code.

**Comment by estevanmaito** [comment]
Could you share more info? What version of Tailwind are you using, build step that produced this code, how could we reproduce this? Your `tailwind.config.js` file could also be helpful.

You can look inside the generated CSS if there are more classes that were not prefixed, so we can find a relation.

**Comment by kb1995** [comment]
@estevanmaito I was being stupid - Monday evenings...

I am using Bootstrap within my project together with Tailwind, which caused the confusion.
