### ISSUE TITLE
Is it intentional that `theme()` doesn't throw when property doesn't exist?

### ISSUE THREAD

**Issue by jquense** [tailwindcss/tailwindcss#1797]
This seems like maybe a bug, or at least an undocumented design choice. I was expecting `theme` to provide safety rails against typos or unexpected theme breakage by throwing an error if you try and get something that doesn't exist from the config. It doesn't tho, which is all very css but seems like an unnecessary footgun. Wondering if it's a bug to be fixed or some thoughts on why it fails silently

thanks!

**Comment by adamwathan** [comment]
Could definitely make it throw when someone asks for a key that doesn't exist 👍 Would accept a PR for it for sure.

**Comment by adamwathan** [comment]
Closing this since we can handle the rest of the conversation in the PR 👍
