### ISSUE TITLE
Set custom environment variable for using purge option

### ISSUE THREAD

**Issue by anyuzx** [tailwindcss/tailwindcss#1803]
Currently, in the documentation, it says that when using purge option in tailwind.config.js, CSS will be purged when `NODE_ENV` is `production`. I am wondering is it possible to define a custom environment variable for purge to be executed? I can do it if I manually set up purgecss. Just wondering is there an option when using it within tailwindcss. Thx.

**Comment by estevanmaito** [comment]
Did you try https://tailwindcss.com/docs/controlling-file-size/#enabling-manually ?

**Comment by anyuzx** [comment]
@ahmadabuaysheh @estevanmaito Thanks. I can do this but I believe I will lose the ability to enable purge automatically depending on the environment variable. I tried this,

```js
purge: {
  enabled: ((MY_ENV_VAR === 'production') ? true : false),
  content: ...
}
```

This gives MY_ENV_VAR not defined error which I believe is because environment variable is not exposed to tailwind.config.js

**Comment by anyuzx** [comment]
Instead of doing `MY_ENV_VAR ===`, `process.env.MY_ENV_VAR ===` will work.

**Comment by Hrishikesh-K** [comment]
Hey, I am doing the same thing for my config and it's working. But now, I had to access the config file in JavaScript, so following the guide from the official documentation, I imported the file, but I get `process is not defined` in browser's console.  It works fine if I manually set the value to true or false, but I am unable to use it with environment variable.

**Comment by CandysMan** [comment]
tailwind.config.js file look like but it still output 3.81Mb of file so how to set node env
`module.exports = {
	purge: {
		enabled: false,
		content: ["./src/**/*.html"],
	},
	darkMode: false, // or 'media' or 'class'
	theme: {
		extend: {},
	},
	variants: {
		extend: {},
	},
	plugins: [],
};
`
build cmd for tailwind css output file
`"build:css": "tailwindcss build src/styles.css -o dist/styles.css"`

postcss.config.js file
`module.exports = {
	plugins: {
		tailwindcss: {},
		autoprefixer: {},
	},
};
`
