### ISSUE TITLE
[Website Search feature] flex-shrink

### ISSUE THREAD

**Issue by rowild** [tailwindcss/tailwindcss#1810]
I just wanted to report that, when searching for a feature in the tailwindcss website, "flex-shrink" will not be listed as a suggestion when searching for "flex". This is a bit confusing, because "flex-grow" does appear as a suggestion. 

I am ok with that, but I thought I report it anyway, maybe you want to do sth about it.

Thank you so much for tailwind!!!

**Comment by estevanmaito** [comment]
If you just type "flex" it will start trying to find the best occurrences for a **word** that contains "flex" (flexbox, flexible, flex). If you add a space, then it understands that you're looking for this word **plus** something (flex grow, flex shrink, etc).

Google works almost the same way (except it shows more results).

![search](https://user-images.githubusercontent.com/8527573/82674103-31181a00-9c19-11ea-9366-5634362318d6.png)

*also, this is a docs issue https://github.com/tailwindcss/docs

**Comment by rowild** [comment]
Ah, I understand. Wasn't aware of that! Thank you!
And also thank you for pointing me to the docs! Next time there :-)
