### ISSUE TITLE
Unnecessary escape character

### ISSUE THREAD

**Issue by frederikhors** [tailwindcss/tailwindcss#1814]
Unnecessary escape character: \[. (eslint: no-useless-escape)

in:

`const innerMatches = content.match(/[^<>"'`\s.(){}\[\]#=%]*[^<>"'`\s.(){}\[\]#=%:]/g) || []`

here: https://github.com/tailwindcss/tailwindcss/blob/99a5fea06d85f218b01842c0d7abe8e6eee0f969/src/lib/purgeUnusedStyles.js#L89

**Comment by estevanmaito** [comment]
It's probably being catched by your local `eslint` (or editor config), because if you look at `.eslintignore`, the `lib` folder is ignored:

```
/lib
/docs
/__tests__/fixtures/cli-utils.js
/stubs/*
```

**Comment by frederikhors** [comment]
Yes, but I think we can remove that escapes, right? I will PR now.

**Comment by estevanmaito** [comment]
I deleted my last comment because it was misleading as the ignored `lib` is the one outside `src`.

But my point is still that it's your local configuration giving this error. I don't get it here and running `npm run style`, there is no error logged also.

**Comment by frederikhors** [comment]
@estevanmaito 

https://eslint.org/docs/rules/no-useless-escape

**Comment by estevanmaito** [comment]
I get it. My point is: why isn't Tailwind build raising this?

It's not the RegEx that should be fixed, it's the plugin that is not working the way it should. If eslint was working properly, this error would've been raised, and who knows how many others?
