### ISSUE TITLE
npm run build is returning errors

### ISSUE THREAD

**Issue by ryusufu** [tailwindcss/tailwindcss#1820]
**Hey, guys pls help me.
I'm getting errors after running npm run build, I can't seem to figure it out for 5 days. here's the github link incase it would be useful https://github.com/ryusufu/haske-landing.git
here's the errors**

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\RILWAN\Desktop\A\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\RILWAN\Desktop\A\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RILWAN\AppData\Roaming\npm-cache\_logs\2020-05-25T20_37_47_126Z-debug.log
**_the complete log is below_**

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\RILWAN\Desktop\A\package.json'
5 verbose cwd C:\Users\RILWAN\Desktop\A\Tailwind\Haske
6 verbose Windows_NT 10.0.18363
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 verbose node v12.14.1
9 verbose npm  v6.13.4
10 error code ENOENT
11 error syscall open
12 error path C:\Users\RILWAN\Desktop\A\package.json
13 error errno -4058
14 error enoent ENOENT: no such file or directory, open 'C:\Users\RILWAN\Desktop\A\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by estevanmaito** [comment]
there is no `build` script inside your `package.json`

**Comment by ryusufu** [comment]
> there is no `build` script inside your `package.json`

could you help me on how to add it?

**Comment by ryusufu** [comment]
I added "build": "npm run build" to the script but still same error

**Comment by estevanmaito** [comment]
Please, read the instructions in the readme inside your project: https://github.com/ryusufu/haske-landing

All the instructions you need are already there, you just need to follow the steps.

**Comment by ryusufu** [comment]
I now have the optimized css but I can't get it to host on netlify.com

**Comment by mateuszmatyszkowicz** [comment]
@ryusufu What error log did you get from netlify?

**Comment by ryusufu** [comment]
1:26:05 PM: Build ready to start
1:26:07 PM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
1:26:07 PM: build-image tag: v3.3.14
1:26:07 PM: buildbot version: 578c7628507b646d2c2478c57933187c689f36ec
1:26:07 PM: Fetching cached dependencies
1:26:07 PM: Failed to fetch cache, continuing with build
1:26:07 PM: Starting to prepare the repo for build
1:26:08 PM: No cached dependencies found. Cloning fresh repo
1:26:08 PM: git clone https://github.com/ryusufu/haske-landing
1:26:08 PM: Preparing Git Reference refs/heads/master
1:26:10 PM: Starting build script
1:26:10 PM: Installing dependencies
1:26:11 PM: v10.20.1 is already installed.
1:26:12 PM: Now using node v10.20.1 (npm v6.14.4)
1:26:12 PM: Started restoring cached build plugins
1:26:12 PM: Finished restoring cached build plugins
1:26:12 PM: Attempting ruby version 2.6.2, read from environment
1:26:13 PM: Using ruby version 2.6.2
1:26:13 PM: Using PHP version 5.6
1:26:13 PM: 5.2 is already installed.
1:26:13 PM: Using Swift version 5.2
1:26:13 PM: Started restoring cached node modules
1:26:13 PM: Finished restoring cached node modules
1:26:14 PM: Installing NPM modules using NPM version 6.14.4
1:26:22 PM: npm WARN repo No repository field.
1:26:22 PM: npm WARN repo No license field.
1:26:22 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
1:26:22 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1:26:22 PM: added 549 packages from 336 contributors and audited 553 packages in 7.711s
1:26:22 PM: 26 packages are looking for funding
1:26:22 PM:   run `npm fund` for details
1:26:22 PM: found 2 low severity vulnerabilities
1:26:22 PM:   run `npm audit fix` to fix them, or `npm audit` for details
1:26:23 PM: NPM modules installed
1:26:23 PM: Started restoring cached go cache
1:26:23 PM: Finished restoring cached go cache
1:26:23 PM: go version go1.12 linux/amd64
1:26:23 PM: go version go1.12 linux/amd64
1:26:23 PM: Installing missing commands
1:26:23 PM: Verify run directory
1:26:25 PM: ​
1:26:25 PM: ┌─────────────────────────────┐
1:26:25 PM: │        Netlify Build        │
1:26:25 PM: └─────────────────────────────┘
1:26:25 PM: ​
1:26:25 PM: ❯ Version
1:26:25 PM:   @netlify/build 1.0.11
1:26:25 PM: ​
1:26:25 PM: ❯ Flags
1:26:25 PM:   mode: buildbot
1:26:25 PM: ​
1:26:25 PM: ❯ Current directory
1:26:25 PM:   /opt/build/repo
1:26:25 PM: ​
1:26:25 PM: ❯ Config file
1:26:25 PM:   No config file was defined: using default values.
1:26:25 PM: ​
1:26:25 PM: ❯ Context
1:26:25 PM:   production
1:26:25 PM: ​
1:26:25 PM: ┌────────────────────────────────┐
1:26:25 PM: │ 1. Build command from settings │
1:26:25 PM: └────────────────────────────────┘
1:26:25 PM: ​
1:26:25 PM: $ npm run build
1:26:25 PM: npm
1:26:25 PM:  ERR!
1:26:25 PM:  missing script: build
1:26:25 PM: npm ERR! A complete log of this run can be found in:
1:26:25 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-05-31T12_26_25_695Z-debug.log
1:26:25 PM: ​
1:26:25 PM: ┌─────────────────────────────┐
1:26:25 PM: │   "build.command" failed    │
1:26:25 PM: └─────────────────────────────┘
1:26:25 PM: ​
1:26:25 PM:   Error message
1:26:25 PM:   Command failed with exit code 1: npm run build
1:26:25 PM: ​
1:26:25 PM:   Error location
1:26:25 PM:   In Build command from settings:
1:26:25 PM:   npm run build
1:26:25 PM: ​
1:26:25 PM:   Resolved config
1:26:25 PM:   build:
1:26:25 PM:     command: npm run build
1:26:25 PM:     publish: /opt/build/repo
1:26:25 PM: Caching artifacts
1:26:25 PM: Started saving node modules
1:26:25 PM: Finished saving node modules
1:26:25 PM: Started saving build plugins
1:26:25 PM: Finished saving build plugins
1:26:25 PM: Started saving pip cache
1:26:26 PM: Finished saving pip cache
1:26:26 PM: Started saving emacs cask dependencies
1:26:26 PM: Finished saving emacs cask dependencies
1:26:26 PM: Started saving maven dependencies
1:26:26 PM: Finished saving maven dependencies
1:26:26 PM: Started saving boot dependencies
1:26:26 PM: Finished saving boot dependencies
1:26:26 PM: Started saving go dependencies
1:26:26 PM: Finished saving go dependencies
1:26:28 PM: Error running command: Build script returned non-zero exit code: 1
1:26:28 PM: Failing build: Failed to build site
1:26:28 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
1:26:28 PM: Finished processing build request in 21.564365757s

**Comment by mateuszmatyszkowicz** [comment]
Let's start with the configuration at netlify. Netlify allow you to choose Build Command which runs your application, so to make sure how it looks in your app. I review your project and I assume that you do not have a `build` script which is required in default netlify configuration, instead of that you have had `production` named. So based on that, you could simply change script name from `production` to `build` or the second solution go to netlify Deploy and Build settings and change you Build Command to `yarn run production`.  Here are some more info https://docs.netlify.com/configure-builds/get-started/#basic-build-settings

**Comment by ryusufu** [comment]
Still getting errors after running yarn run production or npm run production.
I think the error is in the script like you've already said, but I couldn't pinpoint the problem.

2:44:18 PM: Build ready to start
2:44:20 PM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
2:44:20 PM: build-image tag: v3.3.14
2:44:20 PM: buildbot version: 578c7628507b646d2c2478c57933187c689f36ec
2:44:20 PM: Fetching cached dependencies
2:44:20 PM: Failed to fetch cache, continuing with build
2:44:20 PM: Starting to prepare the repo for build
2:44:20 PM: No cached dependencies found. Cloning fresh repo
2:44:20 PM: git clone https://github.com/ryusufu/haske-landing
2:44:21 PM: Preparing Git Reference refs/heads/master
2:44:22 PM: Starting build script
2:44:22 PM: Installing dependencies
2:44:24 PM: v10.20.1 is already installed.
2:44:24 PM: Now using node v10.20.1 (npm v6.14.4)
2:44:24 PM: Started restoring cached build plugins
2:44:24 PM: Finished restoring cached build plugins
2:44:24 PM: Attempting ruby version 2.6.2, read from environment
2:44:26 PM: Using ruby version 2.6.2
2:44:26 PM: Using PHP version 5.6
2:44:26 PM: 5.2 is already installed.
2:44:26 PM: Using Swift version 5.2
2:44:26 PM: Started restoring cached node modules
2:44:26 PM: Finished restoring cached node modules
2:44:26 PM: Installing NPM modules using NPM version 6.14.4
2:44:34 PM: npm
2:44:34 PM: WARN repo No repository field.
2:44:34 PM: npm WARN repo No license field.
2:44:34 PM: npm WARN
2:44:34 PM: optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
2:44:34 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:44:34 PM: added 549 packages from 336 contributors and audited 553 packages in 7.26s
2:44:35 PM: 26 packages are looking for funding
2:44:35 PM:   run `npm fund` for details
2:44:35 PM: found 2 low severity vulnerabilities
2:44:35 PM:   run `npm audit fix` to fix them, or `npm audit` for details
2:44:35 PM: NPM modules installed
2:44:35 PM: Started restoring cached go cache
2:44:35 PM: Finished restoring cached go cache
2:44:35 PM: go version go1.12 linux/amd64
2:44:35 PM: go version go1.12 linux/amd64
2:44:35 PM: Installing missing commands
2:44:35 PM: Verify run directory
2:44:37 PM: ​
2:44:37 PM: ┌─────────────────────────────┐
2:44:37 PM: │        Netlify Build        │
2:44:37 PM: └─────────────────────────────┘
2:44:37 PM: ​
2:44:37 PM: ❯ Version
2:44:37 PM:   @netlify/build 1.0.11
2:44:37 PM: ​
2:44:37 PM: ❯ Flags
2:44:37 PM:   mode: buildbot
2:44:37 PM: ​
2:44:37 PM: ❯ Current directory
2:44:37 PM:   /opt/build/repo
2:44:37 PM: ​
2:44:37 PM: ❯ Config file
2:44:37 PM:   No config file was defined: using default values.
2:44:37 PM: ​
2:44:37 PM: ❯ Context
2:44:37 PM:   production
2:44:37 PM: ​
2:44:37 PM: ┌────────────────────────────────┐
2:44:37 PM: │ 1. Build command from settings │
2:44:37 PM: └────────────────────────────────┘
2:44:37 PM: ​
2:44:37 PM: $ yarn run production
2:44:37 PM: bash: yarn: command not found
2:44:37 PM: ​
2:44:37 PM: ┌─────────────────────────────┐
2:44:37 PM: │   "build.command" failed    │
2:44:37 PM: └─────────────────────────────┘
2:44:37 PM: ​
2:44:37 PM:   Error message
2:44:37 PM:   Command failed with exit code 127: yarn run production
2:44:37 PM: ​
2:44:37 PM:   Error location
2:44:37 PM:   In Build command from settings:
2:44:37 PM:   yarn run production
2:44:37 PM: ​
2:44:37 PM:   Resolved config
2:44:37 PM:   build:
2:44:37 PM:     command: yarn run production
2:44:37 PM:     publish: /opt/build/repo
2:44:37 PM: Caching artifacts
2:44:37 PM: Started saving node modules
2:44:37 PM: Finished saving node modules
2:44:37 PM: Started saving build plugins
2:44:37 PM: Finished saving build plugins
2:44:37 PM: Started saving pip cache
2:44:37 PM: Finished saving pip cache
2:44:37 PM: Started saving emacs cask dependencies
2:44:37 PM: Finished saving emacs cask dependencies
2:44:37 PM: Started saving maven dependencies
2:44:37 PM: Finished saving maven dependencies
2:44:37 PM: Started saving boot dependencies
2:44:37 PM: Finished saving boot dependencies
2:44:37 PM: Started saving go dependencies
2:44:37 PM: Finished saving go dependencies
2:44:40 PM: Error running command: Build script returned non-zero exit code: 1
2:44:40 PM: Failing build: Failed to build site
2:44:40 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
2:44:40 PM: Finished processing build request in 20.213283036s

**Comment by mateuszmatyszkowicz** [comment]
@ryusufu I manage to investigate it deeply, mainly issue lays in https://community.netlify.com/t/support-guide-frequently-encountered-problems-during-builds/213 point **11**.
Solution 1: remove from .gitignore line: `yarn.lock` then commit it. Remember to add yarn.lock to your commit as well.
Then netlify will know to install yarn on your behalf.
Solution 2: (**I did not test it**) add `yarn` as a dependency to `package.json`

**Comment by adamwathan** [comment]
Closing since this isn't anything actionable on the Tailwind side but of course feel free to keep helping OP out here if you like 👍
