### ISSUE TITLE
Use calc () in config?

### ISSUE THREAD

**Issue by QJan84** [tailwindcss/tailwindcss#1821]
Hi!

Maybe it has already been discussed but I am trying to create a fluid typography.
So far this works well:

	body {
		font-size: calc(1rem + 0.15vw);
		line-height: calc(1.4em + 0.2vw);
	}

In the `tailwind.config.js` I tried the following:

	fontSize: {
		"xs-fluid": "calc(0.75rem + 0.15vw)",
		"sm-fluid": "calc(0.8rem + 0.15vw)",
		"base-fluid": "calc(1rem + 0.15vw)",
		"lg-fluid": "calc(1.125rem + 0.15vw)",
		"xl-fluid": "calc(1.3rem + 0.15vw)"
	},

The result:

	.text-base-fluid {
		font-size: 1.25rem; // should be calc(1rem + 0.15vw)
	}

Unfortunately, calc () is compiled. What can I do to get calc () in the class?

**Comment by adamwathan** [comment]
Can you share your PostCSS configuration? This shouldn't happen out of the box so I'm guessing maybe you are using postcss-preset-env or postcss-calc which would be the culprit.

**Comment by QJan84** [comment]
Sure, of course!
Maybe it's because of cssnano?

Here is my config:

`gulp-postcss` & `postcss-custom-properties`

	.pipe(
		$.postcss([
			$.tailwindcss(),
			$.autoprefixer(),
			$.cssnano({
				discardComments: {
					removeAll: true,
				},
				discardDuplicates: true,
				discardEmpty: true,
				minifyFontValues: true,
				minifySelectors: true,
			}),
			$.postcssCustomProperties({
				importFrom: pkg.paths.dist.css + pkg.vars.siteCssName,
			}),
		])
	)

**Comment by QJan84** [comment]
Adding `calc: false` fixed the problem. ;-)

**Comment by langdon0003** [comment]
> Adding `calc: false` fixed the problem. ;-)

Hello @QJan84 , I hit same problem like you did now. Could you help me more details on where to put `calc: false`. Many thanks.

**Comment by VeArnold** [comment]
Same question as well...
