### ISSUE TITLE
Small doc improvement

### ISSUE THREAD

**Issue by tiagomatosweb** [tailwindcss/tailwindcss#1829]
Just wanted to point this out.
On these doc sections 

- https://tailwindcss.com/docs/pseudo-class-variants/#odd-child-v1-1-0
- https://tailwindcss.com/docs/pseudo-class-variants/#even-child-v1-1-0

It shows examples using bg color but the variants configurations show borderWith.

I believe it could benefit more readers if we had a match in this section such as bg color as an example as well as configuration variants.

Cheers

**Comment by estevanmaito** [comment]
It makes sense. For the reader in a hurry or inattentive, that may just copy both examples, it could save some time.

**Comment by tiagomatosweb** [comment]
Oh Sorry, I didn't realise that there was a repo for the docs.
Cheers
