### ISSUE TITLE
Space utility overrides the margin of the child element

### ISSUE THREAD

**Issue by scanadi** [tailwindcss/tailwindcss#1841]
Personally i think that margin on a child element should overide the space utility margin.

Currently this will not work

So for example 
![image](https://user-images.githubusercontent.com/1336058/83130110-198bd600-a0de-11ea-84c3-f3a01a97b0d8.png)

Any sugeestions ?

**Comment by estevanmaito** [comment]
This behavior is explained in the PR: https://github.com/tailwindcss/tailwindcss/pull/1584

> It unfortunately comes at the cost of increased specificity (0, 1, 2 instead of 0, 1, 0) which means you cannot override the styles applied by these classes with simpler utilities.

> Even if you do run into this, you can always revert to the "old way" and not use these new classes at all in those situations.

So, in your case, the solution would be to use a margin on every element, then you could adjust for special cases.

**Comment by scanadi** [comment]
Ok thanks
