### ISSUE TITLE
It is recommended to remove the button outline

### ISSUE THREAD

**Issue by baojiawei** [tailwindcss/tailwindcss#1851]
I found that the buttons in the website introduction all have an outline attribute. I think this attribute should be set to none by default and return the setting permission to the developer. Because this attribute behaves differently in various browsers

![outline](https://user-images.githubusercontent.com/10663964/83231080-7e6a2d80-a1bd-11ea-88c2-47c6eb55e89e.jpg)

**Comment by estevanmaito** [comment]
It would be great if you could present a source to your assertion in the title.

IMO, accessibility should be the default (as it is), and developers can make the choice to turn their websites inaccessible, by removing the default styling.

You could solve the different behavior in browsers with your own style, like `focus:outline-none focus:shadow-outline`

**Comment by baojiawei** [comment]
Thank you for your answer, I will close this issure
