### ISSUE TITLE
Docs: divide- examples are failed

### ISSUE THREAD

**Issue by RomainMazB** [tailwindcss/tailwindcss#1864]
Hi,
Just to report, in the new `divide-` documentation: 90% of the examples are failed:
![Capture d’écran de 2020-05-31 22-15-38](https://user-images.githubusercontent.com/53976837/83361803-63014d00-a38c-11ea-8d46-e5db7111cbe7.png)

It's simple enough though but I had to report :)

**Comment by estevanmaito** [comment]
Please, post in the Docs repo instead: https://github.com/tailwindcss/docs

**Comment by RomainMazB** [comment]
Sorry, didn't know about the docs repo!
