### ISSUE TITLE
Ditch `.npmignore` in favor of `files` option in `package.json`

### ISSUE THREAD

**Issue by MartijnCuppens** [tailwindcss/tailwindcss#1867]
Currently the `.github` folder, `.editorconfig`, `.eslintignore`, and `.eslintrc.json` are published on npm.

Instead of blacklisting the files you don't want to publish, it's easier to whitelist the ones you do want to be published. You can do this with the [`files` option](https://docs.npmjs.com/files/package.json#files)

**Comment by adamwathan** [comment]
This is definitely a good idea and would accept a PR that set this up for sure 👍  Thanks @MartijnCuppens!
