### ISSUE TITLE
Built-in purgeCSS not purging plugins classes?

### ISSUE THREAD

**Issue by pavelloz** [tailwindcss/tailwindcss#1870]
Hello,

I'm migrating my Tailwind 1.4.6 [boilerplate](https://github.com/pavelloz/webpack-tailwindcss-purgecss) from postcss-purgecss to just Tailwind but i noticed, that output is couple times bigger.

I'm using `"@tailwindcss/custom-forms": "^0.2.1"` and it seems like it was purged by postcss, and now every class is included no matter if its used or not.

Before migration:
```
  ⚠️  Tailwind is not purging unused styles because no template paths have been provided.
      If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
      removing unused styles, set `purge: false` in your Tailwind config file to silence
      this warning.
   
      https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
Version: webpack 4.43.0
Time: 4269ms
             Asset       Size  Chunks                         Chunk Names
         js/app.js   2.43 KiB       0  [emitted]              app
```

After migration:

```
Version: webpack 4.43.0
Time: 2721ms
                    Asset       Size  Chunks                         Chunk Names
              css/app.css   7.29 KiB       0  [emitted]              app
```

HTML evidently does not need any class from the plugin (I include it because i need it often enough to make it part of boilerplate):
```
<body class="antialiased font-sans leading-normal h-screen">
  <div class="flex justify-center items-center mt-6">
    <h2 class="text-5xl font-semibold">
      Hello world!
    </h2>
  </div>

  <div class="w-2/3 max-w-2xl mx-auto mt-6">
  </div>
```

My purgeing patterns are pretty simple:
```
  purge: [
    './src/**/*.html',
    './src/**/*.liquid',
    './src/js/**/*.js',
  ],
```

This is how my migration looked like in commits: https://github.com/pavelloz/webpack-tailwindcss-purgecss/pull/3

---

So the question is: is this intentional and if yes, should it be the case?

**Comment by adamwathan** [comment]
This is by design and documented here:

https://tailwindcss.com/docs/controlling-file-size/#removing-all-unused-styles

Use `mode: ‘all’` if you want to purge everything and not just purge utility styles 👍🏻
