### ISSUE TITLE
Providing a default tracking with Font Size

### ISSUE THREAD

**Issue by valtism** [tailwindcss/tailwindcss#1874]
Hi there!

I'd like to extend the font-size configuration to also include an optional spec for tracking / letter-spacing. 

Right now, we can specify a default line-height like so:

```
sm: ['14px', '20px'],
base: ['16px', '24px'],
lg: ['20px', '28px'],
xl: ['24px', '32px'],
```

I would like to extend this to support tracking like so:

```
sm: ['14px', '20px', '0.01em'],
base: ['16px', '24px', '0'],
lg: ['20px', '28px', '-0.02em'],
xl: ['24px', '32px', '-0.024em'],
```

Does this align with the goals of the framework? Seems like it's not to big of a change and isn't breaking.

**Comment by adamwathan** [comment]
I like this idea and commented on the PR, going to close this as an issue and lets continue the discussion in the PR instead 👍
