### ISSUE TITLE
Customizing z-index doesn't generate the css rules

### ISSUE THREAD

**Issue by mrassili** [tailwindcss/tailwindcss#1875]
Hello 👋 

I am building a chrome extension and using tailwind via postcss, I noticed a weird issue with z-index, custom values that I add to the config weren't applied and when I checked the output css, I couldn't find them for some reason, I do however find custom value for other classes like colors

tailwind config
```js
module.exports = {
  purge: ["./src/content-scripts/index.js"],
  important: "#popup__5cXrO",
  theme: {
    extend: {
      spacing: {
        "14px": "14px",
        "4px": "4px",
        "6px": "6px",
        "9px": "9px",
        "11px": "11px",
      },
      borderRadius: {
        "16px": "16px",
        "12px": "12px",
        "26px": "26px",
      },
      colors: {
        black: "#18191F",
        "orange-s": "#FFBD12",
        "orange-d": "#F95A2C",
        "blue-s": "#1947E6",
      },
      fontSize: {
        "13px": "13px",
        "21px": "21px",
      },
      borderWidth: {
        "6": "6px",
      },
      transitionDuration: {
        400: "400ms",
      },
      inset: {
        full: "100%",
        1: "1rem",
      },
      zIndex: {
        "9999": "9999",
      },
    },
  },
  variants: {
    boxShadow: ["responsive", "hover", "focus", "focus-within"],
  },
  plugins: [],
};
```

and I apply it like this
```js
class="z-9999 w-full fixed top-1 right-1 shadow-xl new-event-form bg-white max-w-sm border-2 border-black p-5 rounded-16px border-b-6"

```

Maybe there's something specific to z-index that I missed, because the styles are generated for everything else!?

**Comment by mrassili** [comment]
if you think this has to do with PostCSS I'll be happy to move it ;)

**Comment by estevanmaito** [comment]
Could you share more of your setup? PostCSS config, the content of `./src/content-scripts/index.js` that is being passed to `purge`, the command you ran to generate CSS, things that could help me reproduce it.

Because I copied your `tailwind.config.js` and executed in my project and it generated the `z-9999` class. Not only that, but I put your code in the tests that run for Tailwind, and it was also correctly generated.

**Comment by mrassili** [comment]
Hello Estevan

Thanks for taking the time to look into it

I can share my config 
```js
module.exports = {
  plugins: [require("tailwindcss"), require("autoprefixer")],
};
```

the content script contains this
```js
document.body.insertAdjacentHTML(
  `afterbegin`,
  `
<div
id="popup__5cXrO"
        class="z-9999 w-full fixed top-1 right-1 shadow-xl new-event-form bg-white max-w-sm border-2 border-black p-5 rounded-16px border-b-6"
      >
        <header class="flex mb-5 pl-1 items-center justify-between">
          <span class="text-2xl text-black font-extrabold">New Event!</span>
          <button
            class="duration-400 bg-white border-2 border-b-4 rounded-full border-black focus:outline-none focus:shadow-outline"
          >
            <svg..... rest of HTML tree
```

Every single class works but the z-9999 🤔
I removed purge alltogether and still it doesn't generate the z-index class

the command I used is `"build": "npm run clean && parcel src/manifest.json"` it uses `https://github.com/kevincharm/parcel-plugin-web-extension` nothing too crazy

I can add you to the repo if you'd like?

**Comment by estevanmaito** [comment]
> I can add you to the repo if you'd like?

If it would not be a problem for you, I could try to reproduce locally.

**Comment by mrassili** [comment]
now also inset custom classes stopped working 🤯 
anyways I sent you an invite

**Comment by estevanmaito** [comment]
Do I need to install something else than Parcel to build the project?

Because running any of the build scripts result in:

```css
/* TODO injected css is overriden */
body {
  font-family: "Montserrat", sans-serif;
  color: #18191f;
}

@tailwind base;
@tailwind utilities;


/*# sourceMappingURL=/index.css.map */
```

It doesn't even get touched. I'm not familiar with Parcel, but there's an open issue with PostCSS https://github.com/parcel-bundler/parcel/issues/2120

**Comment by mrassili** [comment]
> Do I need to install something else than Parcel to build the project?
> 
> Because running any of the build scripts result in:
> 
> ```css
> /* TODO injected css is overriden */
> body {
>   font-family: "Montserrat", sans-serif;
>   color: #18191f;
> }
> 
> @tailwind base;
> @tailwind utilities;
> 
> 
> /*# sourceMappingURL=/index.css.map */
> ```
> 
> It doesn't even get touched. I'm not familiar with Parcel, but there's an open issue with PostCSS [parcel-bundler/parcel#2120](https://github.com/parcel-bundler/parcel/issues/2120)

sorry I didn't write any documentation yet :/
I believe you only need parcel

the resulting css is weird tbh, haven't run into this issue before. are you running parcel 1.12.4?

**Comment by mrassili** [comment]
okay turned it was just parcel keeping an old build cache, had to remove `.cache/` to see additional classes generated 😏 
You can close this

**Comment by kkdima** [comment]
> okay turned it was just parcel keeping an old build cache, had to remove `.cache/` to see additional classes generated 😏
> You can close this

Where did you find the .cache/ folder?

**Comment by estevanmaito** [comment]
@kkdima 

https://parceljs.org/cli.html#cache-directory

### Cache directory
Default: ".cache"

Available in: serve, watch, build

parcel build entry.js --cache-dir build/cache
