### ISSUE TITLE
Font-weight issue in Firefox

### ISSUE THREAD

**Issue by maaajo** [tailwindcss/tailwindcss#1879]
Hi!

Here is the screenshot of official docs when opened with Firefox Developer 78.0b2:

![obraz](https://user-images.githubusercontent.com/36929127/83742650-fa4ef480-a659-11ea-95cf-ed8a3d2b6c74.png)

The same is happening for me in my project even if I'm using custom fonts:

```
@tailwind base;

@import url('https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@700&family=Work+Sans:wght@400;500;600&display=swap');

@tailwind components;
@tailwind utilities;
```
Screenshot from Firefox:

![obraz](https://user-images.githubusercontent.com/36929127/83742871-3bdf9f80-a65a-11ea-97bf-6b1666acf283.png)

Screenshot from Chrome:

![obraz](https://user-images.githubusercontent.com/36929127/83742943-5285f680-a65a-11ea-8dd2-daf9acfd663d.png)

When refreshing the page in Firefox I can see for a second that the font-weight is being applied and after that any font-weight is being erased somehow,

Appreciate your help!

**Comment by adamwathan** [comment]
Is this on Windows by any chance? Can't seem to reproduce on macOS but either way I don't think there's anything we can do here if the browser is just ignoring font-weight declarations. Chrome had a bug like this last month so I wonder if there's something similar happening here.

**Comment by maaajo** [comment]
Hi @adamwathan !

Thanks for replying. Yes indeed this is happening on Windows. Can you perhaps think of anything that could be causing that?

**Comment by estevanmaito** [comment]
Firefox 76, Windows

![Screenshot_2020-06-04 Font Weight - Tailwind CSS](https://user-images.githubusercontent.com/8527573/83768627-6713c000-a655-11ea-9fa7-9d43a3514767.png)

Firefox 77.0.1, Windows (current supported version)

![Screenshot_2020-06-04 Font Weight - Tailwind CSS(1)](https://user-images.githubusercontent.com/8527573/83768663-7266eb80-a655-11ea-9beb-3425d2d43c4f.png)

Firefox 78.0b2, Windows (Beta)

![Screenshot_2020-06-04 Font Weight - Tailwind CSS](https://user-images.githubusercontent.com/8527573/83769858-c0c8ba00-a656-11ea-87fd-a07184cf3c2a.png)

Even though Firefox 78 is set to be released on [2020-06-30](https://wiki.mozilla.org/Release_Management/Calendar) and is still in beta (things could change until there), it looks like you have something going on with your system. Did you try a clean installation of Firefox?

You can also inspect what fonts are being loaded from the Dev Tools > Inspector > Fonts (5th option in the Rules, Layout... panel)

**Comment by maaajo** [comment]
@estevanmaito 

Here is screenshot from the fonts panel:

![obraz](https://user-images.githubusercontent.com/36929127/83772519-c1c41080-a683-11ea-904a-2e23d4231ffa.png)

I'm trying to use here Work Sans with font-weight 600 which is actually imported but never applied.

What is more interesting is that when I will try to import each Work Sans style in separate link tag, then it suddenly works. Strange.

**Comment by maaajo** [comment]
Reinstalling firefox helped here, thanks for your suggestion @estevanmaito !

**Comment by ahmadmobaraki** [comment]
I had the same issue, this thread helped me find out it was because I had been changed the default font size in Firefox appearance settings to 18px, once I reverted it back to 16px, the problem solved.
