### ISSUE TITLE
More height utilities to cover 25vh, 50vh and 75vh

### ISSUE THREAD

**Issue by jferrettiboke** [tailwindcss/tailwindcss#191]
I am missing a few utilities. My proposal would look as follows.

### Height

| Class | Properties | Description |
| --- | --- | --- |
| .h-screen-1/2 | height: 50vh; | Set the element's height to 50vh. |
| .h-screen-1/4 | height: 25vh; | Set the element's height to 25vh. |
| .h-screen-3/4 | height: 75vh; | Set the element's height to 75vh. |

### Min-Height

| Class | Properties | Description |
| --- | --- | --- |
| .min-h-screen-1/2 | min-height: 50vh; | Set the element's minimum height to 50vh. |
| .min-h-screen-1/4 | min-height: 25vh; | Set the element's minimum height to 25vh. |
| .min-h-screen-3/4 | min-height: 75vh; | Set the element's minimum height to 75vh. |

### Max-Height

| Class | Properties | Description |
| --- | --- | --- |
| .max-h-screen-1/2 | max-height: 50vh; | Set the element's maximum height to 50vh. |
| .max-h-screen-1/4 | max-height: 25vh; | Set the element's maximum height to 25vh. |
| .max-h-screen-3/4 | max-height: 75vh; | Set the element's maximum height to 75vh. |

**Comment by adamwathan** [comment]
Hey @jferrettiboke! We're going to pass on adding these to the default config file for now just because every new class we add is quite expensive in terms of file size, but there's nothing stopping you from adding these to your own config file 👍

**Comment by afkcodes** [comment]
@adamwathan as now the JIT enigne is on its way, can we have this utility classes? I don't know if this still makes sense. I just landed to tailwind land a day before so sorry if  this is irrelevant.

**Comment by fultonm** [comment]
@afkcodes Yes if you are using Tailwind JIT you can do things like
`max-h-[40vh]`

**Comment by HusanboyZafarov** [comment]
That's not working

**Comment by SAIPRANAY-GANGULA** [comment]
> That's not working

`h-screen max-h-[40vh]` will work!
