### ISSUE TITLE
npm ERR! request to https://registry.cnpmjs.org/tailwindcss failed

### ISSUE THREAD

**Issue by DanKamNdi** [tailwindcss/tailwindcss#1916]
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://registry.cnpmjs.org/tailwindcss failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.cnpmjs.org. i
s not in the cert's altnames: DNS:r.cnpmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     `C:\Users\Eddie\AppData\Roaming\npm-cache\_logs\2020-06-11T13_06_30_594Z-debug.log`

**Comment by adamwathan** [comment]
If you'd like to open an issue that actually describes your problem we can definitely help, but just copy and pasting an error isn't enough information for us to actually help.
