### ISSUE TITLE
Feature Proposal: Add items-normal and align-normal

### ISSUE THREAD

**Issue by manniL** [tailwindcss/tailwindcss#192]
Hey!

I've noticed that there are no utilities for a "normal" state for `align-items` and `align-self`

Styles that want to accomplish an output like `items-center md:items-normal` won't work currently.

That's the reason why "normal" utilities should be added. I'd create a PR for that if this feature is wanted.

**Comment by adamwathan** [comment]
Interesting I didn't even know about those values! The idea with the current set of utilities is that you'd just reset to the browser's default value to "undo" anything, so with `align-items` the default is [`items-stretch`](https://tailwindcss.com/docs/flexbox-align-items#stretch-default) and with `align-self` the default is [`self-auto`](https://tailwindcss.com/docs/flexbox-align-self#auto-default).

You can see on MDN that the initial/default/normal value for align-items is `stretch`, and for align-self it's `auto`:

https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
https://developer.mozilla.org/en-US/docs/Web/CSS/align-self

The `normal` value isn't actually the default state for either of them and appears to be quite complex:

![image](https://user-images.githubusercontent.com/4323180/32700712-e1d4244c-c796-11e7-8c03-020eee3d2647.png)

Is that actually what you want or does the current system accomplish what you need?

**Comment by devcircus** [comment]
"normal" doesn't seem to be a flexbox specific property value. It looks like this is best handled in a custom way.

**Comment by manniL** [comment]
I've used `items-stretch` and `self-auto` in those scenarios, but I thought it might be useful to have a normal helper as well.

Though I understand that they won't be needed that often, so introducing them could be done as a separate utility by people needing them :)

**Comment by adamwathan** [comment]
Gonna close this unless there's a really compelling reason to add these; sounds like what we currently have solves this for most situations. Thanks though @manniL!
