### ISSUE TITLE
DOCS: Use npx in examples

### ISSUE THREAD

**Issue by aparajita** [tailwindcss/tailwindcss#193]
Currently any examples in the docs that want to execute the `tailwind` binary look like this:

```sh
./node_modules/.bin/tailwind build
```

This is kind of old school since `npx` came out. If the user has `npm` v5.3 or later, or installs `npx` directly, it's so much better:

```sh
npx tailwind build
```

Not sure how you want to document the dependency on `npx`. Once you decide that, I'll be happy to make a PR with the changes.

**Comment by DanielRuf** [comment]
Not everyone uses npx. Also just running `tailwind build` should also work.

**Comment by aparajita** [comment]
`tailwind build` doesn't work unless it's installed globally.

It's true that not everyone **has** npx, but I think you would have a hard time finding someone who has it available and would rather type `./node_modules/.bin/tailwind` vs `npx tailwind` every time.

So shouldn't the npx syntax be offered as an option for those who have it?

**Comment by DanielRuf** [comment]
Afaik npm looks for local binaries.

**Comment by DanielRuf** [comment]
Seehttps://github.com/DanielRuf/slides/blob/master/package.json and https://github.com/DanielRuf/webpack-starter/blob/master/package.json

**Comment by DanielRuf** [comment]
Imho this is the only way to provide the binary without requiring more.

Think about projects where people work directly with the binaries and do not have a full npm / yarn setup with scripts.

So far this makes it clear that there is a binary and where you can find it.
Frameworks should allow entrylevel developers to work with it.
npx is optional and also npm-run, npm scripts and installing the binary globally.

I know how it is for beginners as I do some support for Materialize.

Experienced developers will know what they can do from here. Exple setups / configs might be still usefull.

**Comment by DanielRuf** [comment]
Just for your information: I'm just a normal commenter / contributor, not part of the tailwind team.

Not that there are any misunderstandings about my role.
