### ISSUE TITLE
First / Last child for margin not working?

### ISSUE THREAD

**Issue by oknoorap** [tailwindcss/tailwindcss#1930]
I've been playing around with pseudo class, but it's seems margin won't be affected by pseudo class?

e.g
```
# working
first:border

# not working
first:mx-0
```

**Comment by robbyrice** [comment]
As per this page (https://tailwindcss.com/docs/pseudo-class-variants#first-child-v1-1-0) not all pseudo-class variants are enabled for all utilities. You'll want to follow the instructions on that page to enable to pseudo-variants that you want.

**Comment by estevanmaito** [comment]
Did you add `first` to the `margin` variant? Like

```js
// tailwind.config.js
module.exports = {
  variants: {
    // ...
   margin: ['responsive', 'hover', 'first'],
  }
}
```

**Comment by robbyrice** [comment]
@estevanmaito great minds think alike :smiley:

**Comment by oknoorap** [comment]
@estevanmaito Okay thanks it works, I've done that before,
it's my mistake here, it was caused by NextJS, react-refresh not finished to refresh the changes I made.

I'm closing this issue 😄 it should be in discussion.

**Comment by peach-inzn** [comment]
I can't get this to work in 2022 with v.3.1.4 of Tailwind. Were there any breaking changes regarding this?

**Comment by robbyrice** [comment]
I'm not sure if there were any breaking changes around this feature. Would you mind sharing what results you're expecting and what what exactly doesn't seem to be working? If you could share a repo showing what's not working that would greatly help in helping you out.

**Comment by gronagatan** [comment]
You want to select the direct children with the `>` combinator in addition to using the `:nth-child` psuedo class. The nth-child psuedo class *doesn't* automatically point at the children but rather asks if the currently selected object is the nth child. Perhaps a bit confusing as the word "child" is part of the psuedo class 😛 
So.
In your case you need to put `& > :nth-child(3)` inside the square brackets.
Like so: 
```
<div class="text-red-400 last:text-blue-500 [&>:nth-child(3)]:font-extrabold">
...
```
this will first target all direct children of the div tag with the `>` and then match the one which is the 3rd child

playground link: https://play.tailwindcss.com/1tRLpoO1zC

**Comment by gronagatan** [comment]
The nth-child psuedo class doesn't automatically target the children. You need to additionally use the `>` combinator to target the direct children of the div. Perhaps a bit unintuitive as the psuedo class itself has the word "child" in it's name 😛 
So. You'll want something like this inside your square brackets:
```
& > :nth-child(X)
```
This would first target the direct children using the `>` combinator and then match the X:th child using the "nth-child" psuedo class.
Your code updated to have with different color and bold for last p-tag:
```
<div class="text-red-400 [&>:last-child]:text-blue-500 [&>:nth-child(3)]:font-extrabold">
  <p>1</p>
  <p>2</p>
  <p>3</p>
</div>
```

Playground link: https://play.tailwindcss.com/9pGwUY7QKe

**Comment by Dealerpriest** [comment]
You want to select the direct children with the `>` combinator in addition to using the `:nth-child` psuedo class. The nth-child psuedo class *doesn't* automatically point at the children but rather asks if the currently selected object is the nth child. Perhaps a bit confusing as the word "child" is part of the psuedo class 😛 
So.
In your case you need to put `& > :nth-child(3)` inside the square brackets.
Like so: 
```
<div class="text-red-400 last:text-blue-500 [&>:nth-child(3)]:font-extrabold">
...
```
this will first target all direct children of the div tag with the `>` and then match the one which is the 3rd child

playground link: https://play.tailwindcss.com/1tRLpoO1zC

**Comment by mehdad-hussain** [comment]
@Dealerpriest Thanks a lot, I figured it out later, but thanks any way for your time and this good explanation.

**Comment by adilaben** [comment]
@Dealerpriest Thanks a lot!
