### ISSUE TITLE
Feature request: Rounded underlines

### ISSUE THREAD

**Issue by JamesTheHacker** [tailwindcss/tailwindcss#1936]
I propose a feature request to allow for rounded underlines. Currently there is no way to do this with tailwind, but I think it's something a lot of people would find handy. Example: 
 https://jsfiddle.net/toqL0agq/1/

![image](https://user-images.githubusercontent.com/19844560/85184626-4ddf5600-b288-11ea-946d-42f624053f91.png)

I don't mind implementing this if it's something that would be seen as beneficial to Tailwind.

Thoughts?

**Comment by robbyrice** [comment]
I've tweaked your example to show what this would look like using Tailwind classes. Basically it involves styling an empty div to make it look like the underline. Here's a link to the forked jsfiddle https://jsfiddle.net/tcjL2w6o/1/ and here is the code.

```html
<div class="w-2/3 mx-auto">
  <h2 class="text-xl font-semibold pb-1">Title</h2>
  <div class="h-2 bg-green-500 rounded-md"></div>
  <p class="pt-4 pb-10">Text</p>
  <h2 class="text-xl font-semibold pb-1">Long title this is a very long title, spanning multiple lines.</h2>
  <div class="h-2 bg-green-500 rounded-md"></div>
</div>
```

**Comment by JamesTheHacker** [comment]
Tailwind to the rescue! Nice solution thanks @robbyrice

**Comment by robbyrice** [comment]
Glad to help!
