### ISSUE TITLE
Darken & Lighten feature for tailwind

### ISSUE THREAD

**Issue by ubheamar** [tailwindcss/tailwindcss#1938]
Hey Adam,
Thanks for a tailwind I am using it one of my projects .can you make the tutorial for theme configuration light & dark theme.
also, I was trying to do something link this
 primary: darken('var(--color-primary)'),
postcss was throwing error --color-primary, not color
is there any method which can generate darken & lighten color based on the primary color. 
Again thanks for tailwind. Keep it up

-->

**Comment by jzabala** [comment]
Hi @ubheamar 

This feature has already been solved by the community through plugins. Check this one for example: https://github.com/innocenzi/tailwindcss-theming

I hope that helps 🙂

**Comment by ubheamar** [comment]
Hey @jzabala Thanks.
;)  i was trying to avoid another plugin i guess i have to use this theme plugin
