### ISSUE TITLE
Automated testing for pseudo states (hover, focus etc)

### ISSUE THREAD

**Issue by yellow1912** [tailwindcss/tailwindcss#1940]
Hi,

Thank you for the great framework. We heavily use it at our work.

There is one thing that I'm not sure how to do properly right now: we have a custom automated script to test the layout, and it's quite difficult to simulate the pseudo-states such as hovered, focused, etc. I was thinking that in the development mode, we could generate extra classes such as hover, focus etc to simulate the elements pseudo-states just for testing purpose.

For example, if I have something like this:

```
<form>
  <input class="bg-gray-200 hover:bg-white hover:border-gray-300 focus:outline-none focus:bg-white focus:shadow-outline focus:border-gray-300 ...">
  <button class="bg-teal-500 hover:bg-teal-600 focus:outline-none focus:shadow-outline ...">
    Sign Up
  </button>
</form>
```

To test the hover code, I can simply add hovered class like this:
```
<form>
  <input class="bg-gray-200 hover:bg-white hovered hover:border-gray-300 focus:outline-none focus:bg-white focus:shadow-outline focus:border-gray-300 ...">
  <button class="bg-teal-500 hover:bg-teal-600 focus:outline-none focus:shadow-outline ...">
    Sign Up
  </button>
</form>
```

Perhaps there is some better way to get around this, I would love to know how you do it.

**Comment by estevanmaito** [comment]
Maybe this can help: https://stackoverflow.com/questions/11495535/why-doesnt-getcomputedstyle-work-with-pseudo-classes-like-hover/11495671#11495671

---

Not the answer to your question, but my opinion on this testing approach.

I don't see the point on testing external libraries code. Tailwind is already tested, so you don't need to bother testing if it will work or not.

IMO, snapshot testing would be enough, just to make sure nobody breaks things or introduce unwanted styles.

**Comment by yellow1912** [comment]
Hello Eatevan,

When you mentioned snapshot testing, do you mean just checking the presence
of the classes or taking actual screenshots? I can see your point of not
testing tailwindcss, at the same time I wonder how tailwind actually runs
tests on these pseudo cases? Another possible usage of this is to automate
the screenshot process to take proofs of work.

**Comment by estevanmaito** [comment]
Snapshot testing as just checking that the code is there.

Beyond Tailwind and thinking just about testing CSS behavior, in this case `hover`. What will this test tell you? Are you doing this to feel safe that `hover` actually works? Because if that is the case, you'll just waste your time and your test will be useless.

You'll just test in your closed environment, probably using some headless browser. What is the guarantee that this code will perform the same in Safari, Firefox, Chrome, Opera, Brave, etc. etc. in different version of each one?

**Comment by yellow1912** [comment]
I'm sorry for the late reply. This can be useful in 2 ways:
1. Build a web builder (like webflow or grapejs): you may decide to let the users style by state of the elements (e.g hovered) and want to show a preview. There is no easy way (no way) to do that with tailwind as of now. You cannot ask the users to hover over the element just to see that. 
2. Automatic testing: this is not to test if tailwind works, it's to test if the HTML is properly built. During the test we automatically capture screenshot as well to show as proofs later.

**Comment by adamwathan** [comment]
No plans to bake something like this in to Tailwind at the moment sorry, just feels a bit out of scope. Thanks for understanding  🙏

**Comment by kevinvalk** [comment]
If anyone ever stumbles on this, you can now easily add this using a plugin to generate classes to toggle certain states.
```javascript
plugin(({ addVariant }) => {
	if (process.env.NODE_ENV === 'production') {
		return;
	}
	for (const state of ['active', 'hover', 'focus', 'focus-within', 'focus-visible', 'target', 'visited']) {
		addVariant(state, [`&:${state}`, `&.pseudo-${state}`]);
	}
}),
```

Bonus if you are using https://www.npmjs.com/package/eslint-plugin-tailwindcss (and https://github.com/tailwindlabs/tailwindcss-intellisense). If you want to make sure developers do not end up using these classes (as they are only used in testing/development you can adjust eslint rules to whitelist them in certain scenarios.

```javascript
{
	files: ['*.story.vue'],
	rules: {
		'tailwindcss/no-custom-classname': [
			'warn',
			{
				whitelist: [
					'active',
					'hover',
					'focus',
					'focus-within',
					'focus-visible',
					'target',
					'visited',
				].map((state) => `pseudo-${state}`),
			},
		],
	},
},
```

**Comment by rChaoz** [comment]
The solution above works great, but not with `group-hover`, `peer-hover` or similar. Instead, I found this [postcss plugin](https://www.npmjs.com/package/postcss-pseudo-classes) that seems to do exactly what I want.

Instead of modifying Tailwind's behaviour, it takes Tailwind's output and replaces every occurence of `something: hover` with `something:hover, something.\:hover` so you can use `:hover` as a pseudo-class.
