### ISSUE TITLE
2 issues report

### ISSUE THREAD

**Issue by nsursock** [tailwindcss/tailwindcss#1947]
Hello,

Casper (the default theme for Ghost) is so fast that a page almost loads in 1 second (1.3 sec on 4G to be precise). At the moment I'm using the Liebling theme which works fine with Tailwind. But if I want to use Casper to have a superfast website, I can't because Tailwind and Casper don't interact correctly.

Another bug I found was that some speedtest website (yellowlab.tools) indicates that Tailwind loads twice with Liebling but Casper loads it only once though. So the speedtest tool is alright. And that may be contribute to the slowness of my site with Liebling (2.7 seconds on 4G, 5.5 on 3G).

Please:
1/ Make Tailwind work effortlessly with Casper
2/ Tell us if it's normal Tailwind loads twice on YellowLab.tools

**Comment by nsursock** [comment]
Here is my website just in case: https://soundsirius.digitalpress.blog/

**Comment by estevanmaito** [comment]
I feel like you're new with web development, but now it's starting to feel like you're trolling people around here.

You asked this question: [Page with Tailwind CSS returns error on Google Pagespeed](https://github.com/tailwindcss/tailwindcss/discussions/1912)

Which I answered you.

Then you created another question, asking the same thing: [Tailwind CSS has slowed down my blog by 10 points on Pagespeed Mobile](https://github.com/tailwindcss/tailwindcss/discussions/1927)

Which you answered to the proposed solutions:

> **Sadly I don't have much time**: I'm working alone on my music blog. I need a simple copy/paste solution with only a few tweaks.

Then you asked another question: [Small bug on my FAQ accordion pag](https://github.com/tailwindcss/tailwindcss/discussions/1933)

And now this.

There's nothing wrong with asking questions, and there's no stupid question, but looks like you're just looking for somebody to solve your problems (_sadly you don't have enough time, but everybody else has?_) and are not really into solving the problems yourself, even when people actually put time into understanding your demand and propose a solution.

It's just disrespectful.

**Comment by nsursock** [comment]
Sorry I didn't mean to harass you. I'm under a lot of stress at the moment and that may be why you think I'm trolling. I want my website to look good and also be fast (a reasonable request :)

**Comment by adamwathan** [comment]
This sounds like it's configuration error on your end and not anything we can do anything about in Tailwind.
