### ISSUE TITLE
purge whitelist with regex

### ISSUE THREAD

**Issue by vortechron** [tailwindcss/tailwindcss#1962]
how to allow this:?

```
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  purge: {
    content: [
      './resources/views/**/*.blade.php',
    ],
    options: {
      whitelist: [
        'grid-cols-*',
        'max-w-*',
      ],
    }
  }
}
```

instead of 

```
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  purge: {
    content: [
      './resources/views/**/*.blade.php',
    ],
    options: {
      whitelist: [
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-7',
        'grid-cols-8',
        'grid-cols-9',
        'grid-cols-10',
        'grid-cols-11',
        'grid-cols-12',
        'max-w-xs',
        'max-w-sm',
        'max-w-md',
        'max-w-lg',
        'max-w-xl',
        'max-w-2xl',
        'max-w-3xl',
        'max-w-4xl',
        'max-w-5xl',
        'max-w-6xl',
        'max-w-full',
      ],
    }
  }
}
```

**Comment by lihbr** [comment]
Hi @vortechron, thanks for reaching out!

Tailwind `purge.options` key allow you to pass options directly to PurgeCSS, therefore you should be able to take advantage of the [`whitelistPatterns`](https://purgecss.com/whitelisting.html#patterns) options to achieve what you want this way:
```javascript
{
  purge: {
    options: {
      whitelistPatterns: [
        /^grid-cols-.*/,
        /^max-w-.*/
      ]
    }
  }
  /* ... */
}
```
Let me know how it goes!

**Comment by vortechron** [comment]
yep, it worked! @lihbr thanks man 🤙

**Comment by andyatflocc** [comment]
Looks like the option has changed to safelist (instead of whiteListPatterns). See https://purgecss.com/configuration.html#options

**Comment by ilpet** [comment]
Any tips on why this isn't working @andyatflocc @lihbr 

`
module.exports = {
  mode: 'jit',
  purge: {
    content: [
      './resources/views/**/*.blade.php',
      './resources/ts/**/*.{js,jsx,ts,tsx,vue}',
    ],
    options: {
      safelist: [/^col-span-.*/]
    }
  },
  ...
}
`

**Comment by ilpet** [comment]
Never mind, it was because of JIT mode. So turn that off if you wish to use regex safelisting.

**Comment by Disane87** [comment]
> Never mind, it was because of JIT mode. So turn that off if you wish to use regex safelisting.

thanks, I got stuck at this two evenings. You deserve a cookie for this!

**Comment by shivasaisagar18** [comment]
Thanks the great info!!

But still its not working for my run-time classes 

Example:
Clasess: grid-cols-[1fr_2fr_2fr], grid-cols-[1fr_1.5fr_2fr]
RegExp: /grid-cols-.*/

**Comment by eschiendorfer** [comment]
I hade the same issue. I am still on Tailwind 2. But for me this is working:
```
purge: {
    content : [
      "../../../../../**/*.tpl",
      "../../../../../**/*.js",
    ],
    options: {
      safelist: [
        /^[\w:]*grid-cols-/
      ]
    }
  }
```
