### ISSUE TITLE
implementation of md:container would be helpfull

### ISSUE THREAD

**Issue by M00nD3v** [tailwindcss/tailwindcss#1964]
Hey guys, whilst working with tailwindcss a came across this issue/missing feature:

implementation of the .container with screen-size conditional prefixes like md:container to enable the `.container` class only on screens bigger than that corresponding screen size.

Now I've implemented this with `md:max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl` which is not that obvious and intuitive as implementing it with the screen prefixes on other classes.

Nevertheless, thanks for the awesome tailwindcss.

Cheers.

**Comment by royvanv** [comment]
You can customize the max widths in the config. Unfortunately it is not documented (I'll create a PR for it).

```js
module.exports = {
    theme: {
        extend: {
            container: {
                screens: {
                    xs: '100%',
                    xl: '1280px',
                },
            },
        },
    },
};
```

**Comment by M00nD3v** [comment]
But wouldn’t it be awesome, if the responsive prefixes (sm:, md:, etc.) would work with the container class?

**Comment by Apostolique** [comment]
It doesn't really make sense since it's not a utility but a component. Container defines multiple breakpoints. More info: <https://tailwindcss.com/docs/container>.

**Comment by ryangjchandler** [comment]
> But wouldn’t it be awesome, if the responsive prefixes (sm:, md:, etc.) would work with the container class?

The syntax you're proposing is actually valid syntax and would be considered a breaking change. I think you'd be looking for something like `container-md` as opposed to `md:container`. The latter is saying only apply the `.container` styles on screen sizes md & greater.

**Comment by browner12** [comment]
for reference #1520
