### ISSUE TITLE
display: block; and vertical-align: middle; somewhere in the Tailwind are useless together

### ISSUE THREAD

**Issue by DeltaKilo** [tailwindcss/tailwindcss#1966]
> Note that vertical-align only applies to inline, inline-block and table-cell elements: you can't use it to vertically align block-level elements.
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

I don't know where it's happening, but it's compiled to:
`audio,canvas,embed,iframe,img,object,svg,video {
    display: block;
    vertical-align: middle
}
`
While I think it is a breaking change, since someone can make <img> tag inline-block and then assume that it has `vertical-align: middle;` I feel this blunder should be fixed in the next major version.

**Comment by adamwathan** [comment]
This is by design, see: https://github.com/jensimmons/cssremedy/issues/14

That lint error is dumb.
