### ISSUE TITLE
Add border-collapse

### ISSUE THREAD

**Issue by zachleigh** [tailwindcss/tailwindcss#197]
It would be nice to have a `border-collapse` class that sets `border-collapse: collapse`. Might be useful to also have the opposite `border-separate`. Not sure if you would want this in the borderStyle file or in a separate file, maybe borderCollapse.js.

**Comment by adamwathan** [comment]
Definitely! We have plans for a whole `tables` module which will include these sorts of styles, would actually love a PR to get that started if you're up for it.

**Comment by zachleigh** [comment]
I'll try to find some time this week or over the weekend. If anybody else can get to it earlier than that, be my guest :)

**Comment by garygreen** [comment]
By default Bootstrap adds these in their normalize:

```
border-collapse: collapse;
border-spacing: 0;
```

**Comment by reinink** [comment]
Yep, let's add this as a default style, and add a couple utilities for this. I've put a PR together for this: #489

**Comment by adamwathan** [comment]
#489 is merged and will be in a release today 👍
