### ISSUE TITLE
Rotate classes not working

### ISSUE THREAD

**Issue by corstian** [tailwindcss/tailwindcss#1970]
I have not been able to get the `rotate-*` classes using the `--transform-rotate` property working. Alternatively, applying `transform: rotate(-90deg)` style in the same situation works great.

**Comment by estevanmaito** [comment]
I don't know if I understood you right, but this is the correct way to use the `rotate` utilities:

```html
<img class="transform rotate-90">
```

You must use, in the same element, the properties `transform` and the desired rotation, [see docs for more](https://tailwindcss.com/docs/rotate/#app). `--transform-rotate` is the CSS property that will be added by the class `rotate-*`

If this is not your case, consider adding more info, like the code you've tried, the results, config, browser, etc

**Comment by corstian** [comment]
@estevanmaito My bad. Thanks for clarifying :)

**Comment by thesmart** [comment]
I also had this issue and came to file a bug. Just wanted to post that it didn't seem obvious that two classes are required, but reasonable. <3

**Comment by OliverLSanz** [comment]
I also had this issue. I would like to note that the documentation examples do not include the "transform" class at all. See here: https://tailwindcss.com/docs/rotate#app

**Comment by minemos** [comment]
Same here.
When using with state or props, rotate not working
```js
<div className={`transform rotate-[${props.dir}deg] ease-in-out`}>
```

**Comment by RobinMalfait** [comment]
@minemos Tailwind is a build-time tool, not a runtime tool. We don't execute your code, so you can't use dynamic classes like that: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by iKnowMagic** [comment]
The rotate class is not working for me in Tailwind Play. Please see an example of this at: https://play.tailwindcss.com/iJzMlxqXbh

Many thanks.

@RobinMalfait

**Comment by Fatima-Bibi** [comment]
i am trying to apply counterclockwise rotation in tailwind as -rotate-180 and its not working

**Comment by edcijn** [comment]
Try adding an `absolute` on your styles, ie "absolute rotate-180"

**Comment by pramodjodhani** [comment]
In my case `@tailwind base;` wasn't included to the CSS file.
