### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by doubleungoodkitsune** [tailwindcss/tailwindcss#1971]
It's recommended to use a code of conduct, [New World Code](https://github.com/doubleungoodkitsune/newworldcode) is an excellent choice for fostering inclusiveness!

**Comment by adamwathan** [comment]
Have had one for years:

https://github.com/tailwindcss/tailwindcss/blob/master/.github/CODE_OF_CONDUCT.md
