### ISSUE TITLE
Slash and colon in classnames gives me problems. 

### ISSUE THREAD

**Issue by Montago** [tailwindcss/tailwindcss#1973]
Slash and Colon is not good/normal practice in classnames 
https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors

In my case, i have some validator / antixss plugin somewhere that strips slashes from classnames. 

but it's also not normal practice to use these characters which needs escaping !

I propose to use a different approach with double hyphen instead of colon and then get rid of slash by renaming and simplyfying the fractions.. 

how about only dealing with 12th's and drop the 3rds, 4ths and 6ths ? 
then only care about the numerator:
w-f1 = 1/12
w-f2 = 2/12
w-f3 = 3/12
w-f4 = 4/12
etc.

**Comment by adamwathan** [comment]
No plans to change this as it would be an enormous breaking change, but you can configure all this stuff to be whatever you want in your own projects 👍🏻 use the “separator” option and override the width utilities under “theme” for example.

**Comment by Montago** [comment]
> No plans to change this as it would be an enormous breaking change, but you can configure all this stuff to be whatever you want in your own projects 👍🏻 use the “separator” option and override the width utilities under “theme” for example.

hi, thanks. 

I know it's much easier to fix these kind of problems per solution instead of fixing it in the framework. 

but wouldn't you agree that there are way too many width properties to choose from ? 

the output css suffers from this - also since you dont combine those with equal value...

**Comment by AndyOGo** [comment]
If there are tests which show clearly that this is a big problem, then I would favor a breaking change and a major release of the framework.
