### ISSUE TITLE
Fix style command in contribution guide not working

### ISSUE THREAD

**Issue by royvanv** [tailwindcss/tailwindcss#1976]
The `--fix` parameter in the `style` script does not work on the [contribution guide](https://github.com/tailwindcss/tailwindcss/blob/master/.github/CONTRIBUTING.md). It needs an extra `--` between the command and the arguments, as stated in the [npm docs](https://docs.npmjs.com/cli/run-script):

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:
> 
> `npm run test -- --grep="pattern"`

The correct command would be `npm run style -- --fix`.

**Comment by adamwathan** [comment]
Fixed thanks.
