### ISSUE TITLE
Accessing theme(...) in theme.extend.colors

### ISSUE THREAD

**Issue by ExpDev07** [tailwindcss/tailwindcss#1977]
Hey, I'm trying to access a `theme` property inside my extended colors so I don't have to maintain a duplicate of the primary color. See below:

```javascript
module.exports = {
    theme: {
        extend: {
            colors: {
                primary: theme => theme('colors.indigo.600'),
                indigo: {
                    900: '#191e38',
                    800: '#2f365f',
                    600: '#5661b3',
                    500: '#6574cd',
                    400: '#7886d7',
                    300: '#b2b7ff',
                    100: '#e6e8ff',
                },
            },
        },
    },
    variants: {},
    plugins: [],
};
```

However, this does not work? 

**EDIT:**
I am using Laravel Mix and compiling with SCSS, if that's of any relevance.

**Comment by adamwathan** [comment]
A color can't be a function, you have to make the whole `colors` key a function:

```
module.exports = {
    theme: {
        extend: {
            colors: theme => ({
                primary: theme('colors.indigo.600'),
                indigo: {
                    900: '#191e38',
                    800: '#2f365f',
                    600: '#5661b3',
                    500: '#6574cd',
                    400: '#7886d7',
                    300: '#b2b7ff',
                    100: '#e6e8ff',
                },
            }),
        },
    },
    variants: {},
    plugins: [],
};
```

**Comment by ExpDev07** [comment]
@adamwathan Thanks for such a quick response! Your solution is what I attempted initially, but was left with a stacktrace like:

```
ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
RangeError: Maximum call stack size exceeded
```

I am using Laravel Mix and compiling with SCSS, if that's of any relevance.

**Comment by adamwathan** [comment]
Sorry my mistake, you can't actually do what you're trying to do because it results in infinite recursion. Colors can't be calculated without looking at the colors value, and it just falls over as a result.

Best solution is put your colors in a variable at the top of your config:

```js
const colorPalette = {
  indigo: {
      900: '#191e38',
      800: '#2f365f',
      600: '#5661b3',
      500: '#6574cd',
      400: '#7886d7',
      300: '#b2b7ff',
      100: '#e6e8ff',
  },
}

module.exports = {
  theme: {
      extend: {
          colors: {
            ...colorPalette,
            primary: colorPalette.indigo[600],
          }
      },
  },
  variants: {},
  plugins: [],
};
```

**Comment by akashooo** [comment]
fsdfsd

**Comment by akashooo** [comment]
/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')

module.exports = {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],

    theme: {
        extend: {
            colors: {
                primary: colors.indigo,
                indigo: {
                    900: '#191e38',
                    800: '#2f365f',
                    600: '#5661b3',
                    500: '#6574cd',
                    400: '#7886d7',
                    300: '#b2b7ff',
                    100: '#e6e8ff'
                }
            }
        }
    }
}

//then access like this text-primary-50|100...900
