### ISSUE TITLE
Feature proposal -Support for leveraging the tailwind config attributes in javascript?

### ISSUE THREAD

**Issue by ar-stackrox** [tailwindcss/tailwindcss#198]
@adamwathan I am not sure if this falls out of scope for the project, or if this is something that is easily implemented, but I showed my UI team Tailwind (they were really impressed!) and they asked how they could access these variables (primarily colors) in Javascript for when working in something like d3 visualizations or even HTML canvas. If there was an example you could quickly write up or add to the docs, I'd really appreciate it. We're so close on a complete design system, but the config javascript integration is still a question mark.

**Comment by reinink** [comment]
Hey there @ar-stackrox, great question! This is possible, as long as you are not using this line in your config:

```js
// var defaultConfig = require('tailwindcss').defaultConfig()
```

If you're already using a module bundling tool like browserify or webpack, you can get access to your tailwind config like any other JS dependency you would import. For example:

```js
window.Tailwind = require('path/to/your/tailwind/config')
```

There's no reason that you couldn't import your Tailwind config into Vue or React components either.

We're still working on a solution to allow you to import a config file that references Tailwind's default config.

Hope that helps!

**Comment by pxwee5** [comment]
Just want to report that I got `Cannot assign to read only property 'exports' of object '` from the console when I do 
```
import config from '../tailwind.js'
// or
const config = require('../tailwind.js')
```

Apparently you cannot use `import` together with `module.export`. Requiring the default config works though.
