### ISSUE TITLE
Feature request: Add more list style types

### ISSUE THREAD

**Issue by its-tayo** [tailwindcss/tailwindcss#1986]
Hi, Tailwind currently supports three list style types (.list-none, .list-disc, .list-decimal). It will be nice to provide classes for circle, square and roman numerals. Can I open a PR to add this, please?

**Comment by Apostolique** [comment]
You can add it to your own config. There's a note about that in the docs: <https://tailwindcss.com/docs/list-style-type/#customizing>.

**Comment by its-tayo** [comment]
@Apostolique I completely missed that tbh. Thanks for pointing it out. Closing this now.
