### ISSUE TITLE
Feature request: hover target

### ISSUE THREAD

**Issue by LucasLeandro1204** [tailwindcss/tailwindcss#199]
Hey, it would be cool to have a class like __hover:target__, then we can do something like this:

```html
<li class="hover:dropdown:flex">
  Dropdown
  <ul class="hidden dropdown">
    <!-- content -->
  </ul>
</li>
```

Yes, I can handle this situation with javascript, but why not with css (maybe I'm just wrong and that's the idea)?

I can't think in a good default target class.

**Comment by keithmancuso** [comment]
I agree, not sure that’s the best syntax really but the idea is really important.

We had talked internally about this a lot and what if it were just as simple so if there’s an <a> tag around something with hover it triggers those hovers.


So basically this should work as expected in that if you hover anywhere over the all all the hovers fire, but currently to get the h3 hover to fire you have to hover directly over the h3.  This is common ux for things like cards

`
<a href=“#”>
<div classs=“bg-red hover:bg-blue”>
<img src=“”/>
<h3 class=“text-blue hover:text-red”></h3>
</div>
</a>
`


Seems like on the css side you could just wrap all the hovers in a parents as well so if right now its

`
a::hover hover\:text-red  {
background-color:red
}
`

**Comment by tlgreg** [comment]
For me this kind of action is still feel like best suited for a component.

It would also duplicate hover utility selectors. Though if module options land that might not be as big of an issue.

If it's considered another question is where should the property utility actually be defined, on the hovered element (as in the opening example) or on the target element? For me it actually feels better on the target element, not on the hover parent.

**Comment by keithmancuso** [comment]
yea i think the underlining issue is theres no way currently to have the hover on a parent affect any of the children without writing your own custom css which feel a bit like a bummer.

I agree tho that the way im proposing its about putting the classes on the things that are changing (the children) but initiating the hover from the parent

**Comment by adamwathan** [comment]
I think this is an interesting idea overall and it would be cool to solve with utilities, but I am not sure I see a path to solving it that doesn't add a ton of extra weight to the framework.

Here's an example of the sort of thing we're talking about for anyone interested:

https://jsfiddle.net/pgdzpryv/11/

Happy to entertain ideas on how we could do this in a lightweight way, but going to close for now as we don't have plans to implement it as it stands and don't see it as a bug.
