### ISSUE TITLE
Tailwindcss Couldn’t resolve Tailwind class name: grid when I use v1.4.6 grid utilities with tailwind.macro v1.0.0-alpha.10 

### ISSUE THREAD

**Issue by subodha** [tailwindcss/tailwindcss#1993]
Anyone else trying to use tailwindcss v1.4.6 grid utilities with tailwind.macro v1.0.0-alpha.10 and getting
`Error: Couldn’t resolve Tailwind class name: grid`

_Originally posted by @jeremyswann in https://github.com/tailwindcss/tailwindcss/issues/446#issuecomment-595009382_

**Comment by estevanmaito** [comment]
Did you consider the comment next to the one you cited https://github.com/tailwindcss/tailwindcss/issues/446#issuecomment-595241583?

**Comment by adamwathan** [comment]
tailwind.macro is not an official project and not really maintained currently. The issue here is just that it hasn't been updated to match new Tailwind features. Best to discuss the issue on that repo 👍
