### ISSUE TITLE
Initial utility classes for absolute positioning

### ISSUE THREAD

**Issue by sanderjson** [tailwindcss/tailwindcss#1994]
Feature request: utility class -initial for absolute positioning

top-0
top-auto
top-initial
etc...

**Comment by estevanmaito** [comment]
What would `top-initial` apply in this case?

Because the CSS spec defines that the initial value of a position coordinate is `auto`

https://drafts.csswg.org/css-position-3/#insets

If you just want to set `top` to its initial value, `top-auto` does the trick.

**Comment by adamwathan** [comment]
Yep `top-auto` does what you need 👍
