### ISSUE TITLE
Tag sup appears over the dropdown menus

### ISSUE THREAD

**Issue by antonkomarev** [tailwindcss/tailwindcss#1995]
Because `<sup>` has `position: relative;` style rule - it appears on top of the dropdown lists with `z-0` (default in Tailwind UI). It could be fixed by adding `z-index: -1` to `sup`.

![Screenshot from 2020-07-02 00-09-50](https://user-images.githubusercontent.com/1849174/86291894-693b5100-bbf8-11ea-97ed-fd28eb603e98.png)

**Comment by adamwathan** [comment]
This comes from Normalize.css and is something we likely won't be changing sorry 😞  See discussion here:

https://github.com/tailwindcss/tailwindcss/discussions/1527
