### ISSUE TITLE
Discrepency Between Theme Function Documentation and Results

### ISSUE THREAD

**Issue by thecodeclimber** [tailwindcss/tailwindcss#1997]
In the [theme function documentation](https://tailwindcss.com/docs/functions-and-directives#theme), it says to reference color values using dot notation.  I.e., like this: 

```
.btn-blue {
  background-color: theme('colors.blue.500');
}
```

Not like this:

```
.btn-blue {
  background-color: theme('colors.blue-500');
}
```

However, for me it works the exact opposite.  `blue-500` works.  `blue.500` does not work. 

Not sure why, but thought you might like to know.

**Comment by adamwathan** [comment]
The docs are correct when your colors are defined as a big nested object (the default). Have you by any chance overridden the default colors with an object that looks like this?

```js
module.exports = {
  theme: {
    colors: {
      // ...
      'blue-500': '#0000ff',
    }
  }
}
```

**Comment by adamwathan** [comment]
Here is an example where you can see it is working as expected (check the CSS tab and look at the source and compiled CSS):

https://tailwind.run/9d54jQ

**Comment by thecodeclimber** [comment]
Yes, I did override the colors -- exactly as you guessed :).  

Thanks for clarifying this.
