### ISSUE TITLE
Tailwind build failing when called on css file in child folder

### ISSUE THREAD

**Issue by erikc96** [tailwindcss/tailwindcss#2004]
Hi,

Experiencing a weird issue, not sure if the issue is mine or not. 

When I run 'tailwind build src/tailwind.css,' I get this error:

`
🚀 Building... src/tailwind.css

   🚫 SyntaxError: Unexpected token (7:8)
    at _class.pp$4.raise (/Users/craigoej/Projects/renter-mentor/node_modules/acorn-node/node_modules/acorn/dist/acorn.js:2927:15)
`

When I cd into my 'src' folder and run 'tailwind build ./tailwind.css', I get no error and it builds correctly.

**Comment by adamwathan** [comment]
Can you create a simple project that reproduces the issue? We got a lot of issues that require me to manually recreate someone's project from scratch and I unfortunately just don't have time for that so things end up going unfixed. If you can provide something I can clone and start troubleshooting with right away it's much easier for me to find time to diagnose and fix the issue.

**Comment by erikc96** [comment]
It was a configuration error on my part, sorry!

**Comment by antongorodezkiy** [comment]
Thank you @erikc96 
I was surprised that the trace is not relevant to the issue reason.
In my case `tailwind.config.js` was corrupted (one `}` was commented out) during the git merge, I didn't notice that and searched for the issue in the application code and dependencies update.

**Comment by SebSwan** [comment]
webpack compilation failed due to application.scss , with the error " mdist/acorn.js:2927:15"

i deleted the `tailwind.config.js`
and recreate it with the command line
npx tailwindcss init --full

it did the job
