### ISSUE TITLE
Svelte rollup example

### ISSUE THREAD

**Issue by quantuminformation** [tailwindcss/tailwindcss#2005]
Would be nice if there was an official example of how to set TW up with Svelte + rollup. There's a few tutorials scattered around the web but they're bit out of date.

**Comment by sid3r** [comment]
It's easy don't need an official example, here's a recent article on how to do it:

https://dev.to/sarioglu/using-svelte-with-tailwindcss-a-better-approach-47ph

and here's the code: 
https://github.com/sarioglu/svelte-tailwindcss-template

**Comment by quantuminformation** [comment]
Yeah I tried that one but purge css wasn't working for me.

**Comment by quantuminformation** [comment]
Did it work for you?

**Comment by sid3r** [comment]
Sorry, not yet, I'll give it a try and see.

**Comment by sid3r** [comment]
@quantuminformation it works fine with me, be sure _@fullhuman/postcss-purgecss_ is added, here's the _postcss.config.js_

```
const purgecss = require('@fullhuman/postcss-purgecss')({
  content: ['./src/**/*.svelte', './src/**/*.html'],
  whitelistPatterns: [/svelte-/],
  defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
})

module.exports = {
  plugins: [
    require('tailwindcss'),
    ...(!process.env.ROLLUP_WATCH ? [purgecss] : [])
  ]
}
```

**Comment by adamwathan** [comment]
We have some examples here although they are mostly community contributed (and take a look at the open PRs for more):

https://github.com/tailwindcss/setup-examples/

Closing because probably better to discuss this on that repo.

**Comment by quantuminformation** [comment]
thanks all

**Comment by quantuminformation** [comment]
I ended up going with Svite https://www.youtube.com/watch?v=ryYhiCd2fqw
