### ISSUE TITLE
`@apply` cannot be used with .form-select

### ISSUE THREAD

**Issue by cbernard** [tailwindcss/tailwindcss#2006]
Hello,

I'm getting an error when I'm trying to compile my CSS, I'm getting : _`@apply` cannot be used with .form-select because .form-select is included in multiple rulesets._

here's my _forms.scss file
`/** Search form */
.acf-form {
  @apply bg-white;
}

select {
  @apply mt-1 form-select block w-full py-2 px-3 py-0 border border-gray-300 bg-white rounded-md shadow-sm transition duration-150 ease-in-out;

  @screen sm {
    @apply text-sm leading-5;
  }

  &:focus {
    @apply outline-none shadow-outline-blue border-blue-300;
  }
}
`

I'm not using this form-select class anywhere else.

Thanks in advance for your help !

**Comment by estevanmaito** [comment]
I think this issue belongs to https://github.com/tailwindcss/custom-forms

**Comment by adamwathan** [comment]
Same general issue as here:

https://github.com/tailwindcss/tailwindcss/issues/1599#issuecomment-618531722

`.form-select` is a complex class that includes focus states and stuff, so `@apply` doesn't work with it. Might be something we support one day but right now `@apply` is limited to simple utility classes only.
