### ISSUE TITLE
Conflict divide and regular border

### ISSUE THREAD

**Issue by afuno** [tailwindcss/tailwindcss#2007]
Initially, I implemented a simple list:

```html
<div class="divide-y-1 divide-gray">
  <div></div>
  <div></div>
  <div></div>
</div>
```

Then I needed some children to add a border to the left:

```html
<div class="divide-y-1 divide-gray">
  <div></div>
  <div class="border-l-4 border-primary"></div>
  <div></div>
</div>
```

And at this stage a conflict arises. The regular border is overridden by divide.

<img width="256" alt="Снимок экрана 2020-07-07 в 18 52 51" src="https://user-images.githubusercontent.com/2853419/86808000-1c85c900-c083-11ea-8cd6-3e0e996bb9e9.png">

**Comment by adamwathan** [comment]
Yeah just an unfortunate limitation you have to work around sadly. I'd use an extra element:

```html
<div class="divide-y-1 divide-gray">
  <div></div>
  <div>
    <div class="border-l-4 border-primary"></div>
  </div>
  <div></div>
</div>
```

**Comment by afuno** [comment]
@adamwathan Okay. Thanks for the answer ;)

**Comment by jlarmstrongiv** [comment]
Note to self:  You can override and force the border with the [important modifier](https://tailwindcss.com/docs/configuration#important)

**Comment by sloan58** [comment]
> Note to self: You can override and force the border with the [important modifier](https://tailwindcss.com/docs/configuration#important)

Yes!  And be sure to put the modifier in the right place:

Right: `dark:!bg-blue-500`

Wrong: `!dark:bg-blue-500`

**Comment by Tanosimboangy** [comment]
Having a border-bottom also is another option if having a border-bottom on the last element is okay.
