### ISSUE TITLE
Linked SVG Colors

### ISSUE THREAD

**Issue by scottzirkel** [tailwindcss/tailwindcss#201]
Following the examples, it's easy enough to use the text color to change an inline SVG, but what about linked ones? Some I have are too long to effectively use inline. I've tried putting the text color on the `img` tag as well as the `svg` tag in the file itself, but neither work. Any ideas?

**Comment by adamwathan** [comment]
Hey @scottzirkel! Unfortunately it's not possible to style SVGs that are linked through `img` tags; only inline SVG can be properly styled with CSS.

Here's a good article on it:

https://css-tricks.com/using-svg/

Your best bet for styling non-inline SVG is to embed the styling information into the SVG itself unfortunately.

**Comment by scottzirkel** [comment]
Bummer, but kinda what I figured. Thought maybe you were smart enough to figure a way around that. Guess not.

**Comment by reinink** [comment]
Alas, @adamwathan is only a mere human. 😂

**Comment by MichaelDeBoey** [comment]
@scottzirkel A more readable way would be to use a blade partial, Vue component, ... and pass the `class`es into the partial. 🙂
But that would not help with plain html ofcourse. 😕

**Comment by scottzirkel** [comment]
I was so focused on getting the design done, I didn't even think about breaking the blade apart yet. Thanks @MichaelDeBoey!

**Comment by MichaelDeBoey** [comment]
You're welcome @scottzirkel 🙂
Got the trick from @adamwathan in one of his 'Building @kitetail' streams 🙂
