### ISSUE TITLE
space-x-* does not work in RTL direction

### ISSUE THREAD

**Issue by chalist** [tailwindcss/tailwindcss#2017]
![image](https://user-images.githubusercontent.com/1072154/87267390-d1cddc00-c4dc-11ea-9e30-28edbb6d2534.png)

**Comment by chalist** [comment]
I fix this by doing this:
```
.space-x-4 > :not(template) ~ :not(template) {
    --space-x-reverse: 0 !important;
    margin-right: calc(1rem * var(--space-x-reverse)) !important;
    margin-left: calc(1rem * calc(1 - var(--space-x-reverse))) !important;
}
```

But I would like to know, there is a way to make space without depends on direction?

**Comment by chalist** [comment]
https://github.com/chalist/tailwindcss/commit/2066fa20324d1c90169360764215dbd5382378fd

**Comment by chalist** [comment]
https://github.com/tailwindcss/tailwindcss/pull/2020

**Comment by royvanv** [comment]
See https://github.com/tailwindcss/discuss/issues/64#issuecomment-532801714

**Comment by hsul4n** [comment]
Just use [tailwindcss-dir](https://github.com/RonMelkhior/tailwindcss-dir) and add space variant to `tailwind.config.js`
```js
variants: {
  space: ['responsive', 'direction'],
},
```

**Comment by mohamed-ibrahem** [comment]
@hsul4n Not working! still, the margin in the last item and none in the first 😟

**Comment by chalist** [comment]
> @hsul4n Not working! still, the margin in the last item and none in the first one

I fixed this problem by this code:

```[dir="rtl"] {
    .space-x-4 > :not(template) ~ :not(template) {
        --space-x-reverse: 0 !important;
        margin-left: calc(1rem * var(--space-x-reverse)) !important;
        margin-right: calc(1rem * calc(1 - var(--space-x-reverse))) !important;
    }
}
```

**Comment by mohamed-ibrahem** [comment]
@chalist good trick.
But I think the following way is much easier

```
variants: {
  space: ['responsive', 'direction'],
},
```
then you can do something like
```space-x-6 rtl:space-x-reverse``` ✌✌

Saves much time, isn't it?

**Comment by chalist** [comment]
yes sure. But you wrote not working. This is because I write that comment :D

**Comment by mohamed-ibrahem** [comment]
> yes sure. But you wrote not working. This is because I write that comment :D

Thank you 👍

**Comment by hsul4n** [comment]
Sorry @mohamed-ibrahem, I always add style utilities to variants property but looks like this doesn't work with `space` utility 😅, so I would suggest using `reverse` with RTL direction.

Here's example
```css
<div class="flex space-x-4 rtl:space-x-reverse">
  <div>1</div>
  <div>2</div>
  <div>3</div>
</div>
```

**Comment by Nefcanto** [comment]
@hsul4n your solution was the best one. Worked for me. Thank you.

**Comment by essaJ** [comment]
> ```css
> <div class="flex space-x-4 rtl:space-x-reverse">
> ```

it work for me thank you,

**Comment by stifler97** [comment]
For 2021 and tailwind v2 i used only this and works
`class='space-x-6 space-x-reverse'`
