### ISSUE TITLE
.prose not working in 1.5.0

### ISSUE THREAD

**Issue by benji014628** [tailwindcss/tailwindcss#2034]
### Describe the problem:
I installed and configured the @tailwindcss/typography plugin in v1.4.6 and after installing v1.5.0 '.prose' styles not showing in HTML elements

**Comment by adamwathan** [comment]
Have you installed and configured the `@tailwindcss/typography` plugin? It's not included in v1.5.0 out of the box. Please provide a GitHub repo that reproduces your issue.

**Comment by benji014628** [comment]
> Have you installed and configured the `@tailwindcss/typography` plugin? It's not included in v1.5.0 out of the box. Please provide a GitHub repo that reproduces your issue.

https://github.com/benji014628 view code

**Comment by adamwathan** [comment]
Confirmed, the 0.1.4 version of the typography plugin breaks under 1.5.0. If you upgrade to @tailwindcss/typography v0.2.0 it will work but I should tag a 1.5.1 that tries to handle this more gracefully because it's kind of a breaking change if I don't 🤦‍♂️ Thanks for the report.
