### ISSUE TITLE
@apply directive do not work when used inside a class with the same name

### ISSUE THREAD

**Issue by kamal** [tailwindcss/tailwindcss#2036]
### Describe the problem:

`@apply` directive does not expand to the correct CSS when it is being used inside a class with the same name as the directive.

When developing against a live reloading local Storybook instance, the output of the `.shadow` is invalid and gets marked as invalid CSS (like it was recursively applied).

```css
.shadow {
  @apply shadow: ;
}
```

When building a compiled version of the css, the output is correct.

#### CSS

```css
.shadow {
  @apply shadow;
}
```

#### Webpack
Rule for CSS uses `[style-loader, css-loader with importLoaders: 1, postcss-loader]`

#### postcss.config.js

```js
let plugins = {
  "postcss-import": {},
  "postcss-nested": {},
  tailwindcss: {},
  "postcss-preset-env": { stage: 0, browsers: "last 2 versions" },
};

module.exports = { plugins };
```

**Comment by adamwathan** [comment]
What's the expected output here? This looks like it should be an error.

**Comment by kamal** [comment]
The expected output is the default shadow `0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)`.

**Comment by adamwathan** [comment]
It applies against all the CSS in your entire project so that you can `@apply` your own custom classes. I don't think we can/will do much here other than maybe throw an explicit error but as it stands this is undefined behavior for sure.

**Comment by kamal** [comment]
@adamwathan thanks for the explanation. it is curious though that when i create a compiled css, it is able to resolve it correctly. FWIW i am using CSS modules where the classname isn't likely to remain `.shadow`. Does `@apply` run before or after css module class renaming?

**Comment by adamwathan** [comment]
We don't do any CSS module stuff in Tailwind so when that runs really is up to how you've configured your own stuff, unfortunately I just don't really know anything about CSS modules.

Going to close this as not really a bug, just undefined behavior. Trying to apply a class to itself isn't something we have any plans to support.
