### ISSUE TITLE
Feature: target individual corners when rounding

### ISSUE THREAD

**Issue by egyptik** [tailwindcss/tailwindcss#204]
Hey guys,

Looks like there are no options yet to target individual corners with `rounded`.

Would it help if I make a PR to add the following?:

`.rounded-tl` - top left
`.rounded-tr` - top right
`.rounded-bl` - bottom left
`.rounded-br` - bottom right

**Comment by MichaelDeBoey** [comment]
There's already a PR for this: #188 🙂
This will be available in `0.2` 🙂

**Comment by reinink** [comment]
Hey there @egyptik! We've actually got a PR (#188) in the works already to add this to the next (breaking release). It's part of a PR to change "rounded" to "radius", which we are actually still debating. 😀

Should be out within the next few days. 👍

**Comment by egyptik** [comment]
Ah okay missed that, sorry. Great! 😄
