### ISSUE TITLE
Setting Padding to 0 at larger breakpoints does not override setting at smaller breakpoint

### ISSUE THREAD

**Issue by chenware** [tailwindcss/tailwindcss#2042]
### Describe the problem:

On an element, if I set `md:pl-2` then set `lg:pl-0`, the latter class never works at the expected breakpoint, though `lg:pl-1` does.

**Comment by adamwathan** [comment]
Can you recreate on CodePen or JSFiddle? This definitely works so must be another little detail.

**Comment by chenware** [comment]
Hm, yeah this works in [codepen](https://codepen.io/chenware/pen/ZEQmZEN) via the CDN. Will look into it further.

**Comment by tobyselway** [comment]
Sorry to bring up an old issue, but did you find the cause for this in your project?
I have the same problem. Only happens in my project, works fine on tailwind play.

Using Laravel Mix inside Laravel project with Vue.js 3.

tailwind.config.js is as follows:

```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    darkMode: 'class',

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
```

Dependencies in package.json:
```
    "devDependencies": {
        "@tailwindcss/forms": "^0.4.0",
        "@vue/compiler-sfc": "^3.2.29",
        "autoprefixer": "^10.4.0",
        "laravel-mix": "^6.0.6",
        "postcss": "^8.4.4",
        "postcss-import": "^14.0.1",
        "tailwindcss": "^3.0.0",
        "vue-loader": "^16.8.3"
    },
    "dependencies": {
        "@headlessui/vue": "^1.4.3",
        "acorn": "^8.7.0",
        "laravel-echo": "^1.11.3",
        "vue": "^3.2.22",
        "vue-router": "^4.0.12"
    }
```

Happens with m-0, ml-0, mr-0, mb-0, mt-0, mx-0, my-0, p-0, pl-0, pr-0, pb-0, pt-0, px-0, and py-0, but only when the class is at a larger breakpoint, overriding some over value (> 0) from a lower breakpoint.

Happens always, no matter if compiling for dev, prod, or using hot-reloading.

Examples:
`px-4 md:px-0` behaves as `px-4`
`px-0 md:px-4` works fine
`md:px-2 lg:px-0` behaves as `md:px-2`

**Comment by anguspmitchell** [comment]
I'm having the same issue
`px-2 lg:px-0` behaves as if `px-2` at all screen sizes

**Comment by Kerwood** [comment]
> I'm having the same issue `px-2 lg:px-0` behaves as if `px-2` at all screen sizes

Having exactly the same issue.. Did anyone figure it out ?

**Comment by anguspmitchell** [comment]
@Kerwood in my case, the problem was that I was using another library (Buefy) that also had a `px-2`. I discovered this issue by following the links to style files in the Chrome CSS explorer. I solved it by prefixing tailwind classes, eg `tw-px-2`. The prefix is a Tailwind setting that is configurable.

**Comment by Kerwood** [comment]
@anguspmitchell  Ah yes... I can see that Bulma is in the way in my case. Thanks.

**Comment by rspauwen** [comment]
@tobyselway did you solve your issue?
