### ISSUE TITLE
Plugin generated classes are not purged with Next.js

### ISSUE THREAD

**Issue by meoyawn** [tailwindcss/tailwindcss#2045]
### Describe the problem:

When using Tailwind in Next.js, plugin generated classes are not purged

For example adding

```js
require('@tailwindcss/typography')
```

to `plugins` and never using `prose` creates 1256 occurrences of `prose` in the production CSS

tailwindcss 1.4.1 generates a 5.6 kB document
tailwindcss 1.5.1 generates a 12.5 kB document

`purge.mode: 'all'` reduces the size down to 5.3 kB, but still leaves some of the unused `prose` classes

### Link to a minimal reproduction:

repo: https://github.com/adelnizamutdinov/nextjs-tailwind-purge
live: https://next-tailwind-purge.vercel.app/

**Comment by estevanmaito** [comment]
`prose` extends `components` and you are ignoring that specific line, so `purge` won't do it's job there:

`/styles/index.css`

```js
/* purgecss start ignore */
@tailwind  base;
@tailwind  components;
/* purgecss end ignore */

@tailwind  utilities;
```

Remove the ignore comments and it will run as expected.

**Comment by adamwathan** [comment]
Yep you have to purge the `components` layer as well if you want to purge those classes. Just be careful you aren't "over-purging" accidentally, especially easy if you are working with markdown as your source templates won't contain actual strings like `h1` or `h2` so Purge will remove those.

**Comment by meoyawn** [comment]
Hi @adamwathan @estevanmaito thank you for taking a look!

I removed the ignore comments https://github.com/meoyawn/nextjs-tailwind-purge/commit/579031753263b58cfd8626cc065efbaccdf240dc and there's still 1276 occurences of `prose` in production css

Live: https://next-tailwind-purge.vercel.app/

**Comment by adamwathan** [comment]
Looks like you are using the built-in PurgeCSS integration, follow the instructions in our documentation to purge all styles instead of just utility styles:

https://tailwindcss.com/docs/controlling-file-size/#removing-all-unused-styles

**Comment by meoyawn** [comment]
thank you @adamwathan 

combination of:

```css
/* purgecss start ignore */
@tailwind  base;
/* purgecss end ignore */

@tailwind  components;

@tailwind  utilities;
```

and 

```js
purge: {
  mode: 'all'
}
```

helped me achieve what I need
