### ISSUE TITLE
.prose-xl seems to behave differently to .prose

### ISSUE THREAD

**Issue by jensamunch** [tailwindcss/tailwindcss#2058]
This code
```
<div class="flex-1 prose mt-10 md:mt-0 text-sm "> {{ .Content }} </div>
```

Generates this:
![image](https://user-images.githubusercontent.com/1650140/88082340-95078200-cb79-11ea-9e4a-903c7dce65fa.png)

This code
```
<div class="flex-1 prose-xl mt-10 md:mt-0 text-sm "> {{ .Content }} </div>
```
Generates this:
![image](https://user-images.githubusercontent.com/1650140/88082413-a81a5200-cb79-11ea-98d3-51f8e4cbec13.png)

Am I missing something here? Why is <h1> not bold and why bullet-points not working?

**Comment by estevanmaito** [comment]
This issue belongs to https://github.com/tailwindcss/typography

But, this is how you solve it: https://github.com/tailwindcss/typography#size-modifiers

> Size modifiers are designed to be used with the multi-class modifier pattern and must be used in conjunction with the base prose class:

**Comment by jensamunch** [comment]
Answering my own question - you need to use both .prose and .prose-lg...should have been:

```
<div class="flex-1 prose prose-xl mt-10 md:mt-0 text-sm "> {{ .Content }} </div>
```
