### ISSUE TITLE
Colon classes can't be found

### ISSUE THREAD

**Issue by faustbrian** [tailwindcss/tailwindcss#208]
I am experiencing a weird issue while trying to use tailwind classes that contain colons like the responsive and hover ones. The upcoming snippet is followed by an exception when building the less files.

```css
@tailwind preflight;
@tailwind utilities;

.btn {
    @apply .no-underline .text-sm .px-3 .py-3 .leading-none .border .rounded .border-white .text-white .md\:flex-initial .hover\:text-primary .hover\:bg-white .mr-2 .md\:mr-0;
}
```

```sh
ERROR in ./resources/assets/css/app.less
Module build failed: ModuleBuildError: Module build failed: Syntax Error

(2:4) No .md\\\:flex-initial class found.

  1 | .btn {
> 2 |     @apply .no-underline .text-sm .px-3 .py-3 .leading-none .border .rounded .border-white .text-white .md\:flex-initial .hover\:text-primary .hover\:bg-white .mr-2 .md\:mr-0;
    |    ^
  3 | }
```

The problem I am experiencing is that it says that the class can't be found which I guess is caused by the fact that the tailwind css isn't compiled and included yet because if I manually copy over those classes I am trying to use from tailwind directly into my source before my `.btn`declaration the error no longer occurs.

What is so weird about that issue is that only classes that contain colon throw this error any not any other ones. Any idea what I might be doing wrong?

**Comment by elpete** [comment]
You can’t use the prefixed classes directly in `apply`. Instead, target the pseudo-selector or media query directly. 

See here in the docs: https://tailwindcss.com/docs/extracting-components

**Comment by faustbrian** [comment]
Ah, thanks! Bummer, would have been so much nicer to use the prefixed ones directly.

**Comment by adamwathan** [comment]
Hey @faustbrian, like @elpete mentioned we don't currently support `@apply`ing classes that contain responsive or state prefixes. It's described in more detail in the `@apply` documentation:

https://tailwindcss.com/docs/functions-and-directives#apply

It would be nice to support this eventually but it's a surprisingly difficult technical challenge.

**Comment by adamwathan** [comment]
For what it's worth I was literally submitting a PR to provide better error messaging around this at the same time you opened this issue 😄 

https://github.com/tailwindcss/tailwindcss/pull/209

**Comment by saraMElsanan** [comment]
> Hey @faustbrian, like @elpete mentioned we don't currently support `@apply`ing classes that contain responsive or state prefixes. It's described in more detail in the `@apply` documentation:
> 
> https://tailwindcss.com/docs/functions-and-directives#apply
> 
> It would be nice to support this eventually but it's a surprisingly difficult technical challenge.

I have kinda similar problem , I know it's not an issue in Tailwind , but I really need help 
I'm new to Tailwind plugins , I made a plugin to custom the scollbar using theme colors , any way 
my problem is the `::-webkit-scrollbar-thumb`
`[`.${e(`scrollbar-thumb-${element.name}\:\:-webkit-scrollbar-thumb`)}`]: {
	'background': element.color,
}`
with or with out the escape char , I still get this result
 ` '.scrollbar-track-teal-200\\:\\:-webkit-scrollbar-track': { background: '#b2f5ea' }` 
I just want to remove these backslashes , Also I know If I cut `::-webkit-scrollbar-thumb` and paste it out side `${e()}` It will work perfectly but I will Loose the privilege of using variants option
 `variants: ['responsive', 'hover']` 
Can You HELP me
