### ISSUE TITLE
Fixed background image problem

### ISSUE THREAD

**Issue by Jamipietila** [tailwindcss/tailwindcss#217]
Hi! It seems that tailwind breaks fixed background image. 

Here's my css:

```
body {
  background: url('/img/site-bg.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```
If I add it to my scss file (laravel mix), after "npm run dev" css is:

```
body {
  min-height: 100%;
  background-color: #222b2f;
  background-image: url('/img/site-bg.jpg');
  background-position: 60% 50%;
  background-repeat: no-repeat;
  background-size: cover;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
}
```

It seems that `background-attachment: fixed` is removed and `background-position` is also different. Any ideas how to fix it?

**Comment by adamwathan** [comment]
Can you share a public repo that demonstrates this? These are the only styles Tailwind applies to the body element anywhere in the codebase:

```
body {
  margin: 0;
}
```

**Comment by Jamipietila** [comment]
You are absolutely correct, for some reason I had 2 folders, css and sass and I've been debugging wrong file past hour lol :D Sorry to bother...
