### ISSUE TITLE
There is no mx-auto anymore in v0.2.0

### ISSUE THREAD

**Issue by mhamlet** [tailwindcss/tailwindcss#218]
After upgrading Tailwind to version 0.2.0, I have found that there is no `.mx-auto` class anymore.

As you can see in screenshot bellow, searching in compiled CSS have no results.

![screenshot from 2017-11-18 22-08-08](https://user-images.githubusercontent.com/1281731/32983410-8e99ee30-ccad-11e7-8d61-d37977b98b35.png)

**Comment by m1guelpf** [comment]
@mhamlet According to the upgrade guide, you have to manually add it to the config.

**Comment by mhamlet** [comment]
Yes, that is. Thank you.

**Comment by MichaelDeBoey** [comment]
Ref: https://github.com/tailwindcss/tailwindcss/releases#auto-is-no-longer-a-hard-coded-margin-value
