### ISSUE TITLE
Feature request: expose function to loop through [colors, fonts, text-sizes, etc.]

### ISSUE THREAD

**Issue by ar-stackrox** [tailwindcss/tailwindcss#219]
Hi @adamwathan, maybe you can help me. I'm trying to do some tricky things relating to theming 
and CSS custom properties and I haven't found a way to add a fallback to the color classes generated by tailwind.

I thought if I could loop through the `var colors {}` like how tailwind does (but maybe in the CSS), I could maybe generate text-color and bg-color classes that have an @supports and a fallback color.

Then when tailwind allows disabling components, I could just turn those off and use my custom functions tied to the tailwind config.

I can show you my code, which is working great, but a little elaborate. The only thing that's missing is adding a sensible fallback for each color in the colors object. If you have any ideas that don't involve this approach, I'd be very appreciative.

Thanks so much!

**Comment by ar-stackrox** [comment]
Thanks @adamwathan . Right, there is probably no need for a preprocessor if the plugin system can modify the tailwind generators themselves. For example, if I edit backgroundColors.js, I can probably achieve what I need in a sensible way. Of course, I don't want to edit anything in the node_modules folder.

In your example, would a browser like IE11 ignore the 2nd statement? I am not sure if it would for mine because my system is using something like this:

```
background-color: hsl(var(--primary), var(--s-40), var(--l-90));
```
Since HSL is valid in IE11, I'm not sure if it would be ignored by the browser, and show me blue as the desired fallback. I'd have to test it when I have time.


But I think the end goal is to achieve the following, for things like grid and future properties you don't want clashing with fallbacks - 

```
.bg-primary {
	background-color: hsl(230, 40%, 90%);
}

@supports (--custom: property) {
    .bg-primary {
      background-color: hsl(var(--primary), var(--s-40), var(--l-90));
    }
}
```

I can share the whole system later today when I have time to explain it :)

**Comment by ar-stackrox** [comment]
One thing I want to clarify - If your example above works with my implementation, that would solve my current case and I'll have a fallback value.

I understand `@supports` may make more sense for custom components that have tailwind utilities classes `applied` to them, since it's a more complex and nuanced scenario.

But I'll give you one example for where looping through and conditionals is helpful. With Tailwind, I am reading the colors config in my sass. Then I created a mixin to iterate through the background color scale classes `(bg-primary-100, bg-primary-200, all the way to 900).`

Then, depending on the weight class (100-300), I `@apply` a text-black or text-white (400-900) color, so there are some sensible defaults tied to the background color. These can still be overwritten with Tailwind text color utility classes, as my sass is generated before I import `tailwind utilities`.

I could avoid all the sass work perhaps through this plugin system, but it would need conditional logic. Right now if you look at my dev tools, you'll see 

```
//sass generated css, based of a loop through the tailwind colors
.bg-primary-700 {
COLOR: white; //@apply text-white;
}

//tailwind-generated CSS
.bg-primary-700 {
BACKGROUND-COLOR: blue;
}
```

Ideally, these could be spit out in a single class by tailwind, as the default behavior for background classes based on a conditional where I determine (or using something like a contrast calculator function) the proper white text or black text value. It would save on having to type text-white on everything, but still allow for overrides with tailwind utility classes.

**Comment by adamwathan** [comment]
Yeah got it; I don't think this is something we are going to bake into the framework any time soon (the ability to hook into utility definitions and modify them through some config or something).

I think the best way for you to implement this on your own project would be to write a PostCSS plugin that looks for background color classes and adds the extra declaration. Maybe not something you've done before but best recommendation I have given I don't plan to add features to Tailwind itself to make this sort of thing easier.

It's totally fine for you to write a custom plugin that takes your existing Tailwind config as a parameter for example:

```
// ...
{
  postCss: [
    require('custom-bg-color-plugin')(require('./tailwind.js')),
    require('tailwindcss')('./tailwind.js'),
  ]
}
```

Once we have our own plugin system fleshed out, you should also be able to write your own plugin for this and disable the normal background color utilities.

Going to close this for now since we don't intend to add the functionality in the issue title, but hopefully the plugin system will make this sort of thing easier.
