### ISSUE TITLE
/dist folder empty on unpkg

### ISSUE THREAD

**Issue by LasseRafn** [tailwindcss/tailwindcss#220]
Previous versions of Tailwind would have `dist/tailwind.min.css` on unpkg ([see example](https://unpkg.com/tailwindcss@0.2.0/dist/tailwind.min.css))

However latest version (0.2.1) [does not](https://unpkg.com/tailwindcss@0.2.1/dist/tailwind.min.css).

I'm not certain if this is intended or not, but I just wanted to let you know 👍

**Comment by adamwathan** [comment]
Annoying! Seems like it's due to the version of NPM I'm using on my laptop vs. my iMac where I normally publish them from :/ Will have this fixed ASAP.

**Comment by adamwathan** [comment]
Fixed! Thanks.
