### ISSUE TITLE
is a converter in the works?

### ISSUE THREAD

**Issue by vesper8** [tailwindcss/tailwindcss#223]
I was thinking about this and thought it should be possible to make a converter for old websites 

so that 

```
<style>
h1 {
    color:#FFF;
}
</style>

<h1>Hello</h1>
```

becomes

```
<h1 class="text-white">Hello</h1>
```

It wouldn't have to be perfect but it would be great for anyone that wants to convert a big old website to this.. could save lots of time and should help adoption rate of this awesome project. 

Thoughts? Any idea on why this wouldn't be easy/possible?

**Comment by browner12** [comment]
good luck, sir.

**Comment by vesper8** [comment]
This is not quite the same but could be used for inspiration https://github.com/awssat/tailwindo

**Comment by adamwathan** [comment]
We don't have any plans to do anything like this officially (sounds super hard and just generally out of scope) so gonna close this. Cool idea though!
