### ISSUE TITLE
Add pre-defined table styles

### ISSUE THREAD

**Issue by excellentingenuity** [tailwindcss/tailwindcss#227]
Could some nice pre-defined table styles be generated like "stripped" or "lined" that would allow a dev using tailwinds to just put the utility classes on a table and have a pre-set table?

**Comment by MichaelDeBoey** [comment]
I think this sort of things are great for the plugin's the team is going to support, but not for the core. 🙂

**Comment by adamwathan** [comment]
Yeah no plans to add these sorts of component-style classes to core right now, but like @MichaelDeBoey said they will be a good fit for the extension system we hope to ship in the coming weeks.

It's possible we revisit this down the road as a core thing one day, but going to close this for now as it's not on the roadmap.
