### ISSUE TITLE
.appearance-none missing -webkit and -moz

### ISSUE THREAD

**Issue by Gypson** [tailwindcss/tailwindcss#23]
I don't know if i missed something with my setup but I am getting

.appearance-none {
  appearance: none;
}

When i look at the tailwind docs

.appearance-none {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}

**Comment by adamwathan** [comment]
Hey @Gypson! `appearance` is not supported without vendor prefixes in any browser right now, so you'll want to make sure you include [Autoprefixer](https://github.com/postcss/autoprefixer) at the end of your PostCSS build chain. We should definitely do a better job documenting that in the installation instructions.

What's your setup like right now?

**Comment by Gypson** [comment]
Thanks @adamwathan for the response, for some reason Autoprefixer was not working in Laravel Mix but I have fixed that.  Tailwind has been great so far.

**Comment by adamwathan** [comment]
Awesome, glad to hear it!

**Comment by odalysadam** [comment]
Hello! 
Two years later I've run into this, wondering if I missed something or if it's just not a tailwind feature. Just a friendly reminder. 
Much love

**Comment by emiliosh** [comment]
> for some reason Autoprefi

Sorry, how did you solve it?, looks like I had a similar problem, because its not working in my case.  Using Laravel 8, tailwind, etc.

**Comment by VottusCode** [comment]
> > for some reason Autoprefi
> 
> Sorry, how did you solve it?, looks like I had a similar problem, because its not working in my case. Using Laravel 8, tailwind, etc.
> 
> My package.json
> 
> ```
> {
>     "private": true,
>     "scripts": {
>         "dev": "npm run development",
>         "development": "mix",
>         "watch": "mix watch",
>         "watch-poll": "mix watch -- --watch-options-poll=1000",
>         "hot": "mix watch --hot",
>         "prod": "npm run production",
>         "production": "mix --production"
>     },
>     "devDependencies": {
>         "@tailwindcss/forms": "^0.3.1",
>         "@tailwindcss/typography": "^0.4.0",
>         "alpinejs": "^3.0.6",
>         "axios": "^0.21",
>         "laravel-mix": "^6.0.6",
>         "lodash": "^4.17.19",
>         "postcss": "^8.1.14",
>         "postcss-import": "^14.0.1",
>         "tailwindcss": "^2.2.2"
>     },
>     "dependencies": {
>         "@popperjs/core": "^2.10.2",
>         "filepond": "^4.30.3",
>         "flatpickr": "^4.6.9"
>     }
> }
> ```
> 
> tailwind.config.js
> 
> ```
> const defaultTheme = require('tailwindcss/defaultTheme');
> 
> module.exports = {
>     mode: 'jit',
>     presets: [
>         require('./vendor/ph7jack/wireui/tailwind.config.js')
>     ],
>     purge: [
>         './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
>         './vendor/laravel/jetstream/**/*.blade.php',
>         './storage/framework/views/*.php',
>         './resources/views/**/*.blade.php',
>         './vendor/ph7jack/wireui/resources/**/*.blade.php',
>         './vendor/ph7jack/wireui/ts/**/*.ts',
>         './vendor/ph7jack/wireui/src/View/**/*.php',
>         './vendor/power-components/livewire-powergrid/resources/views/**/*.blade.php',
>         './vendor/power-components/livewire-powergrid/src/Themes/Tailwind.php',
>     ],
> 
>     theme: {
>         extend: {
>             fontFamily: {
>                 sans: ['Nunito', ...defaultTheme.fontFamily.sans],
>             },
>         },
>     },
> 
>     plugins: [
>         require('@tailwindcss/forms')({
>             strategy: 'class',
>         }),
>         require('@tailwindcss/typography')
>     ],
> };
> ```
> 
> webpack.mix.js
> 
> ```
> const mix = require('laravel-mix');
> 
> /*
>  |--------------------------------------------------------------------------
>  | Mix Asset Management
>  |--------------------------------------------------------------------------
>  |
>  | Mix provides a clean, fluent API for defining some Webpack build steps
>  | for your Laravel applications. By default, we are compiling the CSS
>  | file for the application as well as bundling up all the JS files.
>  |
>  */
> 
> mix.js('resources/js/app.js', 'public/js')
>     .postCss('resources/css/app.css', 'public/css', [
>         require('postcss-import'),
>         require('tailwindcss'),
>     ]);
> 
> if (mix.inProduction()) {
>     mix.version();
> }
> ```

Under require('tailwindcss'), make sure to also have require('autoprefixer').

You need the autoprefixer package installed of course.
