### ISSUE TITLE
Idea: Implement upgrade notes

### ISSUE THREAD

**Issue by Tjoosten** [tailwindcss/tailwindcss#245]
Hi, 

First of all. Thanks for the love that you guys putting into this. But i have an idea. To add some doc page. For upgrade older tailwindcss versions. To the latest version by example.

**Comment by MichaelDeBoey** [comment]
For `v0.2.0` there was an [update guide](https://github.com/tailwindcss/tailwindcss/releases/tag/v0.2.0#upgrade-guide-breaking-changes), so I'm pretty sure there will be for all new breaking changes releases 🙂

**Comment by adamwathan** [comment]
Yeah we'd like to add this to the actual documentation eventually but for now just using the release notes for each GitHub release.

**Comment by adamwathan** [comment]
Going to close this as we do provide upgrade notes.
