### ISSUE TITLE
Disable Container module

### ISSUE THREAD

**Issue by gabormeszoly** [tailwindcss/tailwindcss#256]
Hi,
Can I ignore the container class output in tailwind.js?
Thanks, Gabor

**Comment by adamwathan** [comment]
Right now it's not possible to disable the container module but we're planning to make it possible soon. In the mean time, just choose a different class name for your own container and don't use the
 `.container` clas 👍

**Comment by gabormeszoly** [comment]
Thanks @adamwathan

**Comment by adamwathan** [comment]
This will be possible in 0.5 which is being released today 👍 

All you'll need to do is remove it from the `plugins` list in your config file:

```diff
   module.exports = {
     // ...
     plugins: [
-      require('tailwindcss/plugins/container')(),
     ],
     // ...
   }
```

**Comment by MickL** [comment]
tailwind.config:

```ts
export default <Partial<Config>>{
  corePlugins: {
    container: false,
  },
};
```

**Comment by KCTWLSK** [comment]
> ```ts
>   corePlugins: {
>     container: false,
>   },
> ```

this definitely saved my day, thank you 🙌🙌🙌

**Comment by KCTWLSK** [comment]
> tailwind.config:
> 
> ```ts
> export default <Partial<Config>>{
>   corePlugins: {
>     container: false,
>   },
> };
> ```

@MickL 
this definitely saved my day, thank you 🙌🙌🙌

**Comment by Reeska** [comment]
Is there a way in Tailwind v4 as corePlugins property is not longer supported ?

**Comment by Reeska** [comment]
I found this way to disable `max-width` setted by tailwind : 
```css
/* tailwind.css */
@utility container {
  max-width: unset;
}
```
