### ISSUE TITLE
No node_modules/.bin/tailwind created on homestead

### ISSUE THREAD

**Issue by jbardnz** [tailwindcss/tailwindcss#259]
Hey there,

I have a Laravel install that I run on homestead (Windows 10 is base OS).

I am running:
node v8.9.1
npm 5.5.1

I installed tailwind with `yarn add tailwindcss --dev --no-bin-links`

Everything seemed to install correctly however I can't run `./node_modules/.bin/tailwind init [filename]`

When I look in `node_modules` their is no `.bin` folder.

**Comment by tlgreg** [comment]
Maybe the `--no-bin-links` flag?

**Comment by jbardnz** [comment]
It's not possible to install dependencies without the `--no-bin-links` flag on Homestead on Windows due to the lack of symlink support.

**Comment by tlgreg** [comment]
Without the bins created, you could run the node script directly:
`node ./node_modules/tailwindcss/lib/cli.js init [filename]`

**Comment by adamwathan** [comment]
Yeah using `--no-bin-links` means the bin links of course aren't created, so you can't use the Tailwind CLI tool the way it's documented. What @tlgreg suggested will work though 👍
