### ISSUE TITLE
[Feature Request] Add option to allow 'prefixes' to tailwind's classes.

### ISSUE THREAD

**Issue by classicmike** [tailwindcss/tailwindcss#266]
Hi,

Your framework is very interesting as it will allow people to quickly add css using Utility classes to quickly build UI and the feature of then being able to create abstractions when we have them figured out, seems like a nice win.

One thing I would like to suggest is the possibility to add the option of a 'prefix' in front of all classes used by tailwind.

From my perspective, I'm in the process of wanting to rewrite my company's pattern library and am looking for a base framework to start off with. Our developers are working on frontend which may either come from this pattern library or this new base framework and the use of a prefix would then allow other developers if the need to debug our UI to quickly determine where a particular css style originates from. Example:

If there was the option to allow a prefix before the class name you could possibly use ```tw-``` infront of the class names you have already. So
```
<div class="tw-px-2 pattern-lib-section pattern-lib-section--lg">
</div>
```
Is much more helpful in determining the source of particular bits of code than
```
<div class="px-2 pattern-lib-section pattern-lib-section--lg">
</div>
```
Now I get there may be some other CSS developers who cringe at the verbosity of class names, but my opinion of that matter is that I value self-documenting classes at the cost of verbosity more than anything else when it comes to writing CSS. 

So why not have the best of both worlds by allowing config to determine whether or not to allow the prefix to be added during the compilation phase.

Look forward to seeing more developments with this framework.

Thanks.

**Comment by tlgreg** [comment]
Prefix was added in 0.2.0.
[log](https://github.com/tailwindcss/tailwindcss/releases/tag/v0.2.0)
[docs](https://tailwindcss.com/docs/configuration/#prefix)

**Comment by adamwathan** [comment]
Yep this has been supported for a couple of weeks now, closing!

**Comment by gordicaleksa** [comment]
Is it possible to add a prefix to tailwind's base class? It's messing up my Chrome extension, and the prefix only applies to the classes I'm explicitly setting in my React components?
