### ISSUE TITLE
Request: Background repeat

### ISSUE THREAD

**Issue by mikeroosa** [tailwindcss/tailwindcss#267]
Wondering if there were any plans to incorporate the background-repeat options. I'd be willing to implement this if there is interest.

repeat
repeat-x
repeat-y
no-repeat
space
round

**Comment by adamwathan** [comment]
Hey @mikeroosa! Actually just merged a PR for this the other day, will be included in the next release 👍 

https://github.com/tailwindcss/tailwindcss/pull/255

We decided to just include the basic repeat options and not space/round for now to keep file size down; every little bit adds up if we're not careful.

**Comment by mikeroosa** [comment]
Ok, excellent.

**Comment by adamwathan** [comment]
This is now included in 0.3 👍
