### ISSUE TITLE
Request: background blend mode

### ISSUE THREAD

**Issue by mikeroosa** [tailwindcss/tailwindcss#268]
Wondering if there were any plans to incorporate the background-blend-mode options. I'd be willing to implement this if there is interest.

normal
multiply
screen
overlay
darken
lighten
color-dodge
saturation
color
luminosity

**Comment by ar-stackrox** [comment]
Yes, this would be cool!

**Comment by tlgreg** [comment]
No IE or Edge support, maybe as a plugin?

**Comment by ar-stackrox** [comment]
Yes, I think like CSS Grid layout or anything supported by evergreen browsers (Edge support is likely coming), it should be an optional plugin. I don't know if it makes sense for Tailwind to be opinionated about which feature sets are included. The choice and burden should be on the developer. I personally don't want to feel restricted by IE11 until 2025...

![image](https://user-images.githubusercontent.com/28272783/33510758-04fb53a4-d6c5-11e7-81a9-df6c068fe5c2.png)

![image](https://user-images.githubusercontent.com/28272783/33510788-987b51f6-d6c5-11e7-86ee-eecf653f3260.png)

**Comment by tlgreg** [comment]
Not sure what @adamwathan and @reinink are planning for these type of features.
Earlier was mentioned that they may be separate packages for the time being, but now that modules can be disabled in 0.3 (*or possibly could be opt-in*) what's the current plan?

**Comment by adamwathan** [comment]
Yeah now that we can make things disabled by default I’m more comfortable
adding features like this to core. That way at least all the people using
them have a consistent API instead of pulling in a bunch of plugins.

**Comment by hacknug** [comment]
I've just published a plugin that adds utilities to use `background-blend-mode` as well as `mix-blend-mode` and `isolation`: https://github.com/hacknug/tailwindcss-blend-mode
