### ISSUE TITLE
Documentation: Grid should be an example, not a style

### ISSUE THREAD

**Issue by shai126** [tailwindcss/tailwindcss#273]
It seems to me that the _styles_ section of the documentation is for learning about all the available utilities, and then _examples_ shows how you can _compose multiple utilities_ to make cool stuff.

I've now seen a couple of developers get confused when they try to figure out _grids_—and can't get their head around what's special about the `md:w-1/3` class that makes it suitable for grids, and what other "grid utilities" are available.

I wonder whether this is a result of _grid_ being listed in the _styles_ section of the docs. **Shouldn't _grid_ be categorized under _examples_? It just composes flex, sizing and responsive utilities – it's no more a part of Tailwind than buttons or alerts are.**

Or, if not, a note in the grid docs to explain that it's just comprised of whatever flex and sizing and responsive utilities you want to use.

**Comment by adamwathan** [comment]
Yep improving this has been on my radar for a while but just no time to do it yet. Definitely want to move it to examples and change all of the examples to look like all the other code examples in the docs; the grid docs were actually one of the very first things I quickly hacked out before we had any patterns in place for how we were going to do things.

I'll see if I can improve this today.
