### ISSUE TITLE
Feature Proposal: List utilities

### ISSUE THREAD

**Issue by manniL** [tailwindcss/tailwindcss#275]
Hey again!

I'm currently using tailwind together with reveal.js for creating presentation slides. Therefore I needed a different list style and noticed that there are no helpers for `list-style-type`. Only a `list-reset` class is available currently.

As with my former proposals, I'd work on this feature if you guys would agree on implementing it.

**Comment by benface** [comment]
That's really great @hacknug. I personally think this should be part of the core. @adamwathan Would you be interested in a PR, or is this plugin-land?

**Comment by adamwathan** [comment]
Added for 1.0: #761
