### ISSUE TITLE
Proposal: Replace "var" with "let"/"const" in default config

### ISSUE THREAD

**Issue by manniL** [tailwindcss/tailwindcss#281]
To support modern JavaScript (ES6/ES2015) standard, it would be good to change the variable declarations from `var` to `const`/`let` in the tailwind default config.

**Comment by adamwathan** [comment]
I left it as `var` initially just because I wasn't sure exactly which versions of Node support `const`/`let`, but looking now it looks like its a non-issue, so would happily accept a PR for it 👍
