### ISSUE TITLE
[Bug Report] Long tables don't expand using Safari

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/tailwindcss#285]
Hi @adamwathan et al: I noticed today when browsing the doc page, that long tables have an "expansion" feature, however, they don't expand when clicking on the down arrow in Safari or Chrome.

![not-expanding](https://user-images.githubusercontent.com/1791050/33520532-a31fba8c-d771-11e7-9690-89bd6a0bf0fb.gif)

Am I doing something wrong? Keep up all the hard work!

**Comment by adamwathan** [comment]
Hey Mike! They aren’t expandable, just scrollable. It’s proving very
difficult to make it clear that you can scroll them 😫

**Comment by mikebronner** [comment]
@adam, thanks for the clarification! Perhaps you would consider leaving them expanded by default? I believe in documentation it is quite important to be able to quickly glance over information without having to act on it (the page scrolls already). Thanks though! (I completely understand trying to make the page more concise, and not carry on and on.) :)

**Comment by adamwathan** [comment]
The main problem is on pages like background colors where it’s so long that
it’s not obvious that there’s anything extra on the page after the table,
and the docs that are hidden down there are important :/

**Comment by mikebronner** [comment]
Yea, tricky for sure! What if you change the cursor to indicate scrolling on hover over the table? If the table is at the top, show the down array, if the table is at the bottom show the up array, and otherwise show the up/down arrow cursor?

**Comment by tlgreg** [comment]
I think an expand/collapse button would be the best under long tables like this. Be it scrollable by default but can be expanded by toggling the `max-h-sm` on the table container.
