### ISSUE TITLE
[Feature Request] Option to @apply without !important when important mode is on.

### ISSUE THREAD

**Issue by jackmcdade** [tailwindcss/tailwindcss#299]
Hey there, we chatted about this on Twitter a few days ago and I would love a way to do this. The use case is that I often create a `.content` class to scope a lot of typography rules into for written content, while leaving the rest of the global defaults in tact. When I do this, I lose the ability to override with utilities.

Turning important on works but then i can't @apply anything because that importance is inherited.

**Comment by jackmcdade** [comment]
I tried to work on a PR but came up short - this particular type of project isn't quite my forte -- just couldn't find a good testing/debug setup.

I chatted with @adamwathan about this and it seems like the best course of action would probably be to simply remove `!important` when applying the AtRules in `substituteClassApplyAtRules{}`. It should be _something_ like this: <https://gist.github.com/georgecrawford/acb44cae777f5d0378d1db001acefacd>, but I couldn't seem to manipulate the data correctly. Or maybe my test set up was faulty. Either way, maybe this will help jump start something.

**Comment by psren** [comment]
```!important```
all
the things BIIIIIIIIITCCCCCCHHHH


![600px-rambo08bow-2](https://user-images.githubusercontent.com/1016798/33790448-8870f5d4-dc80-11e7-8f14-c7d3d9c27629.jpg)


Sorry, just kidding.


I love ```!important``` for all utilities.
IMO don't use ```@apply```. Just use regular css if it should be overwritten,
IMO utilities should always be ```!important```. Wheater ```@apply```ed or not :-)

**Comment by adamwathan** [comment]
This will be in 0.4 which I may release today 👍
