### ISSUE TITLE
Bug: Navbar not collapsing

### ISSUE THREAD

**Issue by marktopper** [tailwindcss/tailwindcss#300]
The navbar is not collapsing.
https://tailwindcss.com/docs/examples/navigation/#responsive-header

When I make my screen width smaller, it shows the burger menu icon, but it always shows the menu both before and after clicking the burger menu icon.

**Comment by sorinr** [comment]
Hi,

Just add `sm:hidden` in here: `<div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto sm:hidden">`

**Comment by marktopper** [comment]
Thanks @sorinr.
Then I can just toggle it using Javascript.

**Comment by sorinr** [comment]
@marktopper  yep

**Comment by adamwathan** [comment]
Yeah the example shows it expanded because showing it closed seemed boring; seemed more useful to show the open state vs. just hiding the content and not showing you how it would look when you open it.

**Comment by abhishekashyap** [comment]
You can do it in vanilla JS simply by,

```html
<div id="toggle-navbar" class="block lg:hidden">Toggle button</div>
<div id="nav-items" class="w-full hidden flex-grow lg:flex lg:items-center lg:w-auto">
<a>...</a>
<a>...</a>
<a>...</a>
</div>
```


```js
 document.addEventListener("DOMContentLoaded", () => {
      document.getElementById("toggle-navbar").addEventListener("click", () => {
        const element = document.getElementById("nav-items");
        if (element.classList.contains("block")) {
          element.classList.remove("block");
          element.classList.add("hidden");
        } else {
          element.classList.remove("hidden");
          element.classList.add("block");
        }
      });
    });
```
