### ISSUE TITLE
[Docs Feature Request] Quick code copy btn

### ISSUE THREAD

**Issue by sorinr** [tailwindcss/tailwindcss#302]
Hi there,

I find very usefull to have a "quick copy"  btn in the docs->examples ,and not only, for quick copy/paste of example code that i want to test.

**Comment by adamwathan** [comment]
Agree would be nice, bit of a low priority though since we have so much documentation still to write. Happy to accept a PR for it if someone wants to put together a really polished solution; would rather keep it as is than implemented something half baked though.

**Comment by heavysumo** [comment]
After reading this I noticed how many times I copied by selecting so put together a pull request (https://github.com/tailwindcss/tailwindcss/pull/311) that automatically adds a copy button for all prism syntax highlighted elements.

Currently looks like:
![image](https://user-images.githubusercontent.com/10924328/33944995-ac6030de-e015-11e7-88b3-aa6d2bb85f58.png)

Hope this does the trick but if not just let me know how/if it can be improved.

**Comment by adamwathan** [comment]
Closing this since the docs have moved to a separate repo, still would like to add this feature eventually though.
