### ISSUE TITLE
[Feature Request] Animations

### ISSUE THREAD

**Issue by marktopper** [tailwindcss/tailwindcss#304]
Hey 👋.

Well, I need animations as a utility to become able to easily have multiple animations on the same element.

I currently have built up the CSS manually, which is not that easy to maintain.
So was wondering if there would be support for animations.

I am able to build this myself and make a pull request here if you like.
However just not sure how to add a utility JS file to the system.

**Comment by d8vjork** [comment]
I think it will be a huge change adding animations, maybe you can use some other frameworks like Animate.css

**Comment by marktopper** [comment]
You are properly right.

**Comment by adamwathan** [comment]
Yeah unfortunately designing animations like what Animate.css does is not a strength I personally have, so I definitely recommend using a separate library like that for this sort of thing:

https://daneden.github.io/animate.css/

We might look into adding simple *transitions* as an optional module down the road but not animations.
