### ISSUE TITLE
Docs is missing margin auto utilities

### ISSUE THREAD

**Issue by pedroborges** [tailwindcss/tailwindcss#31]
Margin `auto` utilities are not documented yet. There's only one mention on the **Container** section.

Since the `auto` doesn't apply to other spacing utilities I'm not so sure how you want to present that info, otherwise I would have submitted a PR.

**Comment by reinink** [comment]
Yeah good point, we'll have to add this to our TODO list! Thanks @pedroborges.

**Comment by reinink** [comment]
Fixed: 1622d4b6943b3c9f406887424335c308ed852f4f

![image](https://user-images.githubusercontent.com/882133/32305112-d867fcda-bf49-11e7-902a-4b72cd8cb9ad.png)

This will help our friend @jackmcdade as well.
