### ISSUE TITLE
[Feature Proposal] Pointer Events utilities

### ISSUE THREAD

**Issue by hacknug** [tailwindcss/tailwindcss#316]
I haven't found any discussion about adding pointer-events utilities to Tailwind so I'm opening the issue to hear your thoughts on this. I know it's probably something most people won't use in every website but it'd be something useful to have around.

Maybe it would make sense to have it disabled by default?

**Comment by adamwathan** [comment]
We have a few actually by default:

https://tailwindcss.com/docs/pointer-events

**Comment by hacknug** [comment]
I missed that. Sorry!
