### ISSUE TITLE
[Feature Proposal] Object-Fit and Object-Position utilities

### ISSUE THREAD

**Issue by hacknug** [tailwindcss/tailwindcss#317]
I haven't found any discussion about adding object-fit and object-position utilities to Tailwind so I'm opening the issue to hear your thoughts on this. I know it's probably something most people won't use in every website but it'd be something useful to have around.

Support for this feature is not excellent and I always provide a [fallback](https://codepen.io/hack_nug/pen/KvjzZJ) via `@supports not` so I'm not sure if it would make any sense to add this. Maybe if it was disabled by default?

**Comment by rathesDot** [comment]
Support for `object-fit` and `object-position` isn't that poor ...https://caniuse.com/#search=object-fit
I think it is something that should be added ... And as you said, one can disable it in their config, if they don't need it ...

**Comment by manniL** [comment]
Won't happen because both properties aren't supported by IE 11 (see #143)

**Comment by rathesDot** [comment]
Not sure if thats the best way to go, cause new features won't land on IE anymore, just on Edge.

**Comment by aparajita** [comment]
IE 11 === IE 6

It's abandoned tech which to some degree is holding back the whole state of the web, just like IE 6 did for years.

**Comment by adamwathan** [comment]
We'll add these soon but probably disable them by default in the default config file. Happy to look at a PR for getting it started.

**Comment by MichaelDeBoey** [comment]
Gave it a shot in #347 🙂

**Comment by MichaelDeBoey** [comment]
This one's re-done in #500 🙂
