### ISSUE TITLE
Proposed Feature: A few transparent colors

### ISSUE THREAD

**Issue by marflow** [tailwindcss/tailwindcss#319]
Anybody else would find it useful to add a few transparent "colors" using rgba? 
Maybe in steps like opacity, white-75, white-50, white-25, and for black as well.
Easy enough to add yourself, but if it would be of use for many.

**Comment by hacknug** [comment]
This is something that I've only needed for some websites so I think it might make sense to add it as a plugin once we can extend core's functionality. Just my two cents.

**Comment by adamwathan** [comment]
Hey @marflow! This has come up before so, check out the discussion here: https://github.com/tailwindcss/tailwindcss/pull/114

Thanks!
