### ISSUE TITLE
README images are not loaded

### ISSUE THREAD

**Issue by bad33ndj3** [tailwindcss/tailwindcss#321]
The images in your `readme` are not loading, thought you might like to know. :)

![image](https://user-images.githubusercontent.com/9072952/34107734-960d7d3c-e3fd-11e7-9b72-c7a21e175d58.png)

**Comment by adamwathan** [comment]
Yeah this happens once in a while with the service we use that provides them; you'll see the same issue on other repos using the same service like Vue for example:

https://github.com/vuejs/vue

They're dynamically generated every time you visit the page so when there's an outage with the service they stop working. They'll fix themselves eventually 🙂
