### ISSUE TITLE
Add background-size: auto

### ISSUE THREAD

**Issue by hacknug** [tailwindcss/tailwindcss#323]
I'm working on a website that has a `background-size: contain` image on mobile but on desktop it should be `background-size: auto`.

With the classes Tailwind provides by default, there's no way to accomplish that so I think it would be a good idea to add `.bg-auto` so we can at least reset the value in bigger breakpoints.

I also think it might even be a better idea to allow users to set their own background-sizes on their config files. Probably not the most common use-case but doing so would allow us to keep both current values by default without having to add auto in there. (making the compiled file a little bigger).

**Comment by adamwathan** [comment]
I think moving these values to the config file is totally reasonable, and including `auto` by default sounds good to me as well. Happy to look at a PR for this.

**Comment by hacknug** [comment]
Will try to open a PR with the changes later.

**Comment by vieko** [comment]
Using tailwindcss with my current project and loving every minute of it. Anyways, it is a project that requires some background-image finessing. Currently doing the following:

`.bg-size-initial {
  background-size: initial;
}
.bg-size-cover {
  background-size: cover;
}
.bg-size-contain {
  background-size: contain;
}
.bg-no-repeat {
  background-repeat: no-repeat;
}
.bg-pos-t {
  background-position-y: 0;
}
.bg-pos-r {
  background-position-x: 100%;
}
.bg-pos-b {
  background-position-y: 100%;
}
.bg-pos-l {
  background-position-x: 0;
}
.bg-pos-y-center {
  background-position-y: 50%;
}
.bg-pos-x-center {
  background-position-x: 50%;
}
.bg-pos-center {
  background-position: center;
}`

Would it make sense to add to tailwind @adamwathan ?

**Comment by aparajita** [comment]
@vieko Please read the docs a little more carefully. They are searchable.  😄 

https://tailwindcss.com/docs/background-size
https://tailwindcss.com/docs/background-position
https://tailwindcss.com/docs/background-repeat

**Comment by vieko** [comment]
aaaah silly me :) thanks man.
