### ISSUE TITLE
[Feature Proposal] Using config in CSS comments

### ISSUE THREAD

**Issue by florenthobein** [tailwindcss/tailwindcss#324]
It may be a very specific request, I was simply wondering if the `config('...')` function could be made available even in a CSS comment, so configuration vars could be inserted in comments.

Use case: I'm using comments to generate a style guideline, and it doesn't play well with TW for now...

Thanks again for your great work 🙏

PS: if it doesn't imply a big refactoring, I can even try a PR if you give me some pointers 👀

**Comment by adamwathan** [comment]
Unfortunately this would be a lot of work, as right now we just leverage the [`postcss-functions`](https://github.com/andyjansson/postcss-functions) plugin to define the config function.

Can you show me an example of how you'd like to use it in a comment? Depending on what you're doing there might be another way to tackle it.

**Comment by florenthobein** [comment]
Oh I see. Then I doubt there is a workaround.

It's simple, I'm creating a library builder using tailwind and  [LivingCSS](https://github.com/straker/livingcss), which reads the CSS comments to build a web styleguide.
With this tool, you can specify in your CSS comments HTML examples to illustrate ways of using it. You can find an example here: https://github.com/florenthobein/styleguide-one/blob/master/src/2-colors.css
See, for ex, line 16 I'm using `config('colors.palette1')` hoping to display in the resulting HTML the decimal code for this color. [Which, as you can see here, doesn't work](https://florenthobein.github.io/styleguide-one/#colors-color-palette).

There is also the possibility to import a HTML fixture instead of writing it in CSS, there may be a solution to be found in this direction, but then it's out of Tailwind's spectrum.

**Comment by florenthobein** [comment]
Nevermind then, I worked around this problem using HTML fixtures and [`gulp-html-replace`](https://www.npmjs.com/package/gulp-html-replace).
