### ISSUE TITLE
Does @apply in Tailwind conflict with @apply in postcss-cssnext?

### ISSUE THREAD

**Issue by 01ivr3** [tailwindcss/tailwindcss#325]
ref: cssnext feature [# custom properties set & @apply](http://cssnext.io/features/#custom-properties-set-apply)

Granted when using @apply with the current version of cssnext I'm getting the following warning 

`You are using @apply rule and custom property sets.
This feature won't be included in next the major release of postcss-cssnext.
This most likely won't get any more support from browser vendors as the spec is yet considered deprecated and alternative solutions are being discussed.`

Still, it might be a bit odd for Tailwind to reimplement this?

**Comment by adamwathan** [comment]
Ours is compatible with cssnext. Basically our plugin ignores custom property sets that are included in an `@apply` call and leaves them there for cssnext to process.

So if you have this code:

```
.foo {
  @apply .text-red .text-blue --some-property-set;
}
```

It will compile to this:

```
.foo {
}
```

**Comment by GAYATHIRI31** [comment]
Unknown at rule @tailwind
How to resolve this issue. It's occurred while configuring the tailwind.

**Comment by evawanini** [comment]
> Unknown at rule @tailwind How to resolve this issue. It's occurred while configuring the tailwind.

Soultion: Install PostCSS Language Support extension in your VSCode editor. 
Method 1: Launch the editor. Go to extensions. Search for this particular extension and install it. 
Method 2: Run this in your terminal: ext install csstools.postcss

**Comment by petr-stupka** [comment]
Edit `.vscode/settings.json` in your project

```json
"files.associations": {
  "*.css": "tailwindcss"
}
```

**Comment by jcita** [comment]
@petr-stupka  working

**Comment by akinsanmi60** [comment]
@petr-stupka Best solution

**Comment by creative2113** [comment]
@petr-stupka working well
