### ISSUE TITLE
Extracting utility patterns idea

### ISSUE THREAD

**Issue by gabormeszoly** [tailwindcss/tailwindcss#327]
[Extracting utility patterns](https://tailwindcss.com/docs/extracting-components#extracting-utility-patterns-with-apply) without generate any utility class. Tailwind just a reference.
```
module.exports = {
  // ...

  modules: {
    // ...
    flexbox: reference,
    // ...
  },

  // ...
}
```

**Comment by adamwathan** [comment]
We've talked about this in other issues/PRs in the past, here's one worth starting at:

https://github.com/tailwindcss/tailwindcss/pull/169#issuecomment-343549111

In general we aren't interested in going out of our way to support this workflow, but it might become possible eventually as we solve related problems like supporting `@apply` in scoped style blocks like you might see in a Vue component or similar.
