### ISSUE TITLE
Prefix only certain classes

### ISSUE THREAD

**Issue by garygreen** [tailwindcss/tailwindcss#330]
Following on from the recent addition to the `prefix` option where you can specify a prefix for all classes - it would be nice to be able to list what classes should be prefixed:

```
prefix: {
   'container': 'tw-'
},
```

Reason for this suggestion is because the main reason why you use the prefix option is to avoid collisions with whatever framework e.g. Bootstrap that you are using. It seems wasteful to prefix every single classname when there is probably only a 5% collision of names with your current framework.

This will help reduce size of your output CSS and simplify the classnames you need to type.

Another idea, maybe some kind of "mutator" function that will be called when classes are being added to your CSS?

```js
tailwind.addTransformer(function(css) {
    if (css.selector == '.container') {
        css.selector = 'tw-container';
    }

    return css;
});
```

**Comment by adamwathan** [comment]
Interesting idea; I don't think I want to go so far as to introduce anything crazy like "transformers" or anything, but I wouldn't be opposed to allowing the `prefix` configuration option to be a function for folks who want to do more complex stuff.

For example:

```js
{
  // ...
  // 
  options: {
    prefix: function (selector) {
      if (selector == '.container') {
        return '.tw-container';
      }

      return selector;    
    },
    important: false,
    separator: ':',
  },
  
  // ...
}
```

Would be a pretty simple PR I think.

**Comment by aparajita** [comment]
Wasn’t this closed by #367?

**Comment by adamwathan** [comment]
Closed by #367

**Comment by rologit85** [comment]
@adamwathan have you implemented this? I only want to know cause prefixing as a default while converting an existing Bootstrap project is pretty exhausting.

**Comment by K-Thompson** [comment]
See [this discussion for a fix](https://github.com/tailwindlabs/tailwindcss/discussions/10151).

**Comment by ampedweb** [comment]
Yep. I missed these last few comments, and again was just trying to prefix `.container` specifically as this is the only conflict I can see with our current CSS.
