### ISSUE TITLE
@apply issue with mx-auto

### ISSUE THREAD

**Issue by aaronmoodie** [tailwindcss/tailwindcss#332]
I just updated to v0.4.0, and am now getting an error on with `@apply` and `.mx-auto`

```
`@apply` cannot be used with `.mx-auto` because `.mx-auto` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.mx-auto` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

The class I'm using it on is as so

```
.page > * {
  @apply .max-w-md .mx-auto .px-9;
}
```
which is below both `@tailwind preflight` and `@tailwind utilities`

I've also tried just using the `.mx-auto` class in the html, yet that doesn't seem to be working either.

**Comment by devcircus** [comment]
See the [upgrade notes](https://github.com/tailwindcss/tailwindcss/releases#auto-is-no-longer-a-hard-coded-margin-value). You'll need to add auto to the tail windows config.
