### ISSUE TITLE
Installation Error: CLI Utility issues

### ISSUE THREAD

**Issue by Wilby1976** [tailwindcss/tailwindcss#34]
In Installation Step 2 I try to use the utility to create the tailwind.js config file I receive an error.  I later discovered that I get this error whenever trying to use the utility.

![screen shot 2017-11-01 at 4 19 37 pm](https://user-images.githubusercontent.com/4195010/32295722-82dabb96-bf20-11e7-98a9-4c0fd5148b6f.png)

**Comment by SmashBrando** [comment]
@Wilby1976 I had this issue as well and found my version of Node.js was out of date. Currently v8.9.0 is working for me.

**Comment by Wilby1976** [comment]
That was exactly the issue. Thanks @SmashBrando!
