### ISSUE TITLE
`@apply` cannot be used with `.sans` because `.sans` either cannot be found, 

### ISSUE THREAD

**Issue by bantawa04** [tailwindcss/tailwindcss#349]
Dear Adam,
                   I'm learning tailwind css through your video on [rebuilding laravel.io](https://www.youtube.com/watch?v=ZrRRMBaz5Z0) from YouTube and encountered this error point to the line:
` 473 | button,
  474 | [role=button] {
> 475 |   @apply .sans;
      |   ^
  476 |   cursor: pointer;
  477 | }`

with error message:
**(475:3) `@apply` cannot be used with `.sans` because `.sans` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.sans` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.**

Are things working differently since you had done that video ?

I installed tailwind via laravel-frontend-present and using LESS for  pre-processing.

**Comment by sgraewe** [comment]
Hey,

the class is called ".font-sans".

https://tailwindcss.com/docs/fonts

**Comment by sgraewe** [comment]
You have to use existing class names.
Read https://tailwindcss.com/docs/colors for all available colors.
For dark, maybe try .text-grey-dark or .text-grey-darker

**Comment by bantawa04** [comment]
Thanks
