### ISSUE TITLE
Why does tailwindcss depend on mousetrap?

### ISSUE THREAD

**Issue by satyago** [tailwindcss/tailwindcss#351]
Can't find it is used anywhere in the codebase so a bit curious how it got there? ;)

**Comment by adamwathan** [comment]
Ah it should be a dev dependency; we use it for the documentation site
which is the same repo. I’ll move it.

**Comment by satyago** [comment]
No problem at all - I know the plugin and used it in the past but was unsure how it got into my node_modules.

Good day to you Adam !
Busy guy :) 👍
