### ISSUE TITLE
negative margin with responsivity doesn't seem to be working

### ISSUE THREAD

**Issue by denjaland** [tailwindcss/tailwindcss#356]
Hi,

We have a sidebar navigation.  BAsically on md and up, it should always have a width of 70px at the left side; when hovered, it expands to 280px

On sm devices however, I want the sidebar to be gone entirely, so that user has to click the infamous hamburger icon to get it displayed.

My sidebar navigation has the following classes applied:

```
<div class="w-280px sm:-ml-280px md:-ml-210px">...</div>
```
The issue is that the sidebar is ALWAYS shown at a full with of 280px.
When I remove the sm: prefix, it correctly slides to the left so that it's invisible (width of 280px minus 280px negative margin), so I'm sure my -ml-280px class is correctly working.  Same goes for -ml-210px...  These classes are simply not correctly applied when the responsitivity prefixes are being added...

Any thoughts?

**Comment by adamwathan** [comment]
What does the dev tools inspector show? Do the classes exist, or have you maybe removed the `responsive` key from your negative margin modules configuration by mistake?

It works as expected in this fiddle:

https://jsfiddle.net/adamwathan/8vvkadzb/

![neg-margin-sidebar](https://user-images.githubusercontent.com/4323180/34990184-2210df80-fa93-11e7-886e-960cb636290b.gif)

**Comment by adamwathan** [comment]
Can you share a gist with your config file and your compiled CSS?

**Comment by denjaland** [comment]
okay.
1/ I started from version 0.2 or something where you didn't already have the modules settings.  So I just published a new tailwind.js file, and copied that bit from it, and pasted it in my existing (the modules part) --> is there anything else I might need to check?

The gist is available from <script src="https://gist.github.com/denjaland/ab33579705ed40a845b17d05d9e8157d.js"></script>

**Comment by denjaland** [comment]
seriously - nevermind.
I test my mobile using the chrome developer tools, and at the bottom left, I can click a mobile icon, and then select phone types.  It goes wrong there.

When I just narrow my screen, it works correctly.

I'm going to check on my actual phone after deploy...

**Comment by denjaland** [comment]
sigh - doesn't work on my phone either - guessing it has to do with how iphone does my handling of hover...  I'm conditionally adding these classes based on a hover event which I pick up in VueJs, and then keep a boolean that tells me whether the menu should be shown or not...

```
<div class="h-full absolute bg-nav flex flex-col transition-ease overflow-hidden z-50 w-280px"
                 :class="{
                    'sm:-ml-280px md:-ml-210px': !nav.hovered && !nav.pinned,
                    'shadow-lg': nav.hovered && !nav.pinned
                 }"
                 v-on:mouseenter="nav.hovered = true"
                 v-on:mouseleave="nav.hovered = false">
...
</div>
```
basically, vuejs adds the `sm:-ml-280px md:-ml-210px` classes if the menu isn't either hovered, and isn't pinned...

So not a tailwindcss issue then.  My apologies.

**Comment by adamwathan** [comment]
No problem! Yeah hover is never going to be nice to deal with on mobile since of course it's not really possible; I know Safari tries to be smart about applying hover styles on touch but I would never expect it to be reliable. Better to have it open/close on a real click on mobile I think.

**Comment by denjaland** [comment]
I agree, and I was adding the hamburger icon for my small devices.
I just want to keep the hover functionality working when larger than sm ;-)
As I see it now, I need to either get rid of the hover on md and up...  You never rely on hover to automatically show menu when you hover the sidebar?

**Comment by adamwathan** [comment]
Hmm I'm not sure I'm understanding what you're trying to do I guess. If you want the negative margin applied on mobile you'll have to use a non-prefixed class for that right? Adding `sm:-ml-280px` will never change how it looks on mobile, so if you want negative margins on mobile when the menu is closed you need to be adding the regular `-ml-280px` class since `sm:...` is only applied at 576px and above.

**Comment by denjaland** [comment]
okay - that just answered my question.  I just did that incorrectly.  I had sm: for mobile; md for anything above.  I should just not prefix for mobile, and apply sm: for anything above

Thanks!
