### ISSUE TITLE
[Feature proposal] Alternative to @apply

### ISSUE THREAD

**Issue by aparajita** [tailwindcss/tailwindcss#357]
Now that `@apply` is actually part of the emerging new [CSS spec](http://tabatkins.github.io/specs/css-apply-rule/), the tailwind `@apply` syntax is causing problems because it doesn't comply with the spec. Here's an example from WebStorm:

<img width="274" alt="screen shot 2018-01-16 at 3 15 20 pm" src="https://user-images.githubusercontent.com/22218/35017169-8a36711e-fad0-11e7-9613-5054df7e137b.png">

It would be good if we could use an alternative directive that isn't in use by CSS. Any number of names could be used, but to be absolutely future-proof one possibility would be `@tailwind apply`.

**Comment by luizbills** [comment]
`@compose`
`@include`
`@extends` +1
`@implement`
...

**Comment by aparajita** [comment]
I've got a backward-compatible PR ready for whatever syntax you might choose.

**Comment by aparajita** [comment]
Another possible syntax that would definitely be future-proof would be `@tailwind apply <class list>`.

**Comment by adamwathan** [comment]
Tailwind is actually [intentionally compatible with the proposed @apply rule](https://github.com/tailwindcss/tailwindcss/blob/master/src/lib/substituteClassApplyAtRules.js#L42-L51), but even so, that proposal is not actually coming, it's [considered deprecated](https://github.com/pascalduez/postcss-apply#web-platform-status) and [alternative solutions](http://tabatkins.github.io/specs/css-shadow-parts/) are being discussed instead.

Changing the name of this directive won't affect the highlighting you see in WebStorm; I can guarantee you'd see those same errors if you typed something that did follow the spec, like:

```css
.foo {
  @apply --foo-styles;
}
```

No intent to change this right now, thanks!

**Comment by aparajita** [comment]
> Tailwind is actually intentionally compatible with the proposed `@apply` rule

Maybe that was your intention, but it isn't compatible. The grammar specifically states:

```
@apply = @apply <custom-property-name>

The <custom-property-name> production corresponds to this:
it’s defined as any valid identifier that starts with two dashes.
```

So Tailwind's syntax is incompatible, because the class names begin with a dot.

> Changing the name of this directive won't affect the highlighting you see in WebStorm; I can guarantee you'd see those same errors if you typed something that did follow the spec

Actually, no and no. WebStorm **does** parse `@apply` according to the spec:

<img width="276" alt="screen shot 2018-01-16 at 5 45 41 pm" src="https://user-images.githubusercontent.com/22218/35021398-8db7a172-fae5-11e7-853d-3206c415bd83.png">

And WebStorm allows me to ignore unknown directives, in which case it doesn't try parsing and doesn't generate an error.

<img width="269" alt="screen shot 2018-01-16 at 5 49 56 pm" src="https://user-images.githubusercontent.com/22218/35021435-b90b1480-fae5-11e7-985c-da7899a7edbb.png">

Oh well, I guess we'll have to wait for you to implement one of the proposed alternatives. Thanks for creating tailwind (and the screencasts), it's a fantastic piece of work.

**Comment by aparajita** [comment]
> Tailwind is actually intentionally compatible with the proposed `@apply` rule

Maybe that was your intention, but it isn't compatible. The grammar specifically states:

```
@apply = @apply <custom-property-name>

The <custom-property-name> production corresponds to this:
it’s defined as any valid identifier that starts with two dashes.
```

So Tailwind's syntax is incompatible, because the class names do not begin with two dashes.

> Changing the name of this directive won't affect the highlighting you see in WebStorm; I can guarantee you'd see those same errors if you typed something that did follow the spec

Actually, no and no. WebStorm **does** parse `@apply` according to the spec:

<img width="276" alt="screen shot 2018-01-16 at 5 45 41 pm" src="https://user-images.githubusercontent.com/22218/35021398-8db7a172-fae5-11e7-853d-3206c415bd83.png">

And WebStorm allows me to ignore unknown directives, in which case it doesn't try parsing and doesn't generate an error.

<img width="269" alt="screen shot 2018-01-16 at 5 49 56 pm" src="https://user-images.githubusercontent.com/22218/35021435-b90b1480-fae5-11e7-985c-da7899a7edbb.png">

Oh well, I guess we'll have to wait for you to implement one of the proposed alternatives. Thanks for creating tailwind (and the screencasts), it's a fantastic piece of work!

**Comment by adamwathan** [comment]
Welp sorry for the overly confident "guarantee" comment, my mistake! 😳

> Maybe that was your intention, but it isn't compatible. The grammar specifically states...

It is compatible in the sense that your code will compile and function as expected. Try running this through cssnext for example:

```
:root {
  --foo-styles: { color: red; }
}

.foo {
  @apply --foo-styles .bg-red;
}
```

WebStorm might consider it a syntax error but that doesn't make it incompatible in my eyes; PostCSS parses it fine and the code compiles into what you'd want.

That said I'm not entirely opposed to changing it, I just haven't seen an alternative that I think is an improvement. Personally I would rather this problem be solved via a WebStorm plugin for Tailwind syntax like others have done for VS Code for example.

**Comment by joshmanders** [comment]
+1 on changing to:

```css
a {
  @bananasandwich .no-underline;
}
```

**Comment by aparajita** [comment]
> I just haven't seen an alternative that I think is an improvement. 

Someone much wiser than me once wrote in [the very source file that handles @apply](https://github.com/tailwindcss/tailwindcss/blob/b8df829de97820b36651762018605348f993411e/src/lib/substituteClassApplyAtRules.js#L47):

```
   * We might consider renaming this at-rule.
```

I agree. 😄

> PostCSS parses it fine 

PostCSS doesn't parse at-rules. It is only parsing '@apply' and then passing everything that comes after to a handler. So it isn't parsing the CSS spec per se. On the other hand, VS Code's built in CSS parser **does** choke on the Tailwind @apply syntax.

> Personally I would rather this problem be solved via a WebStorm plugin for Tailwind syntax like others have done for VS Code

It's much easier in the various editors to ignore unknown at-rules than it is to get them to ignore invalid syntax for known at-rules.

In the case of VS Code, are you talking about [this?](https://codeburst.io/tailwind-css-intellisense-in-visual-studio-code-9782375ec121). On closer examination, this isn't a fix for @apply. It's just turning off the **real** CSS parsing built in to VS Code in favor of stylelint, which is built on PostCSS, which doesn't parse what comes after at-rules at all. So Tailwind is getting a free pass in the case of @apply.

Given all of this — and your own source code comment! — I think there's a fairly compelling case that actual CSS parsers consider the Tailwind @apply syntax broken and it's worth exploring an alternative. As I said before, I already modified the code to **add** an alternative name (existing code won't break), so all you have to do is come up with a new name. 😄 

@joshmanders Adam has spent an incredible amount of time and thought into creating and supporting an incredible framework. We are trying to have a thoughtful discussion about this problem. More constructive comments would be greatly appreciated.

**Comment by adamwathan** [comment]
Not renaming it to a worse name, and `@apply` isn't real CSS anyways; WebStorm chose to add code to their editor to lint the syntax of a draft feature that has since been deprecated and was never supported anywhere. `@apply` as outlined in that spec is actually being removed in the next version of cssnext; it's never coming to browsers.

Really, WebStorm should remove their code that lints it and instead treat it as an unrecognized at-rule, because it's not real and never will be.

**Comment by aparajita** [comment]
VS Code is also guilty unfortunately. I guess we'll have to wait for the code editors to be updated. I'll file a bug report with WebStorm.

**Comment by joshmanders** [comment]
> @joshmanders Adam has spent an incredible amount of time and thought into creating and supporting an incredible framework. We are trying to have a thoughtful discussion about this problem. More constructive comments would be greatly appreciated.

Clearly you don't follow Adam that much.

**Comment by curtisblackwell** [comment]
> Personally I would rather this problem be solved via a WebStorm plugin for Tailwind syntax like others have done for VS Code for example.

@adamwathan I'm not seeing anything for VS Code but an extension for docs lookup. If you have a link for a VS Code syntax, could you please share?

**Comment by adamwathan** [comment]
Maybe there's not one, I dunno. I personally use the PostCSS highlighting plugins available for most editors which are less strict about this sort of thing.
