### ISSUE TITLE
dezalgo ENOENT npm install error FIX

### ISSUE THREAD

**Issue by 1415926535** [tailwindcss/tailwindcss#359]
This is a FIX not a bug, issue or suggestion. Delete this (and/or tell me where to share help on errors) if I'm breaking protocol but I started getting this error installing TWCSS via npm today. When googling "dezalgo" there are others currently having this issue but unrelated to TWCSS but involving "dezalgo". See [here](https://github.com/npm/npm/issues/19304#issuecomment-358384940)

Ubuntu 16.04
Laravel 5.5 fresh install

I was installing TWCSS fine yesterday and even this AM. Rolling npm back to LTS fixed it for me. I was on `npm 5.6`. I have no idea what broke my npm. I did `sudo apt update` and upgrade today but I do that every day. It's the only thing I can think of that broke my junk.

Fix was found [here](https://github.com/nodejs/node/issues/13492#issuecomment-306719416) 

RUN THIS `npm i npm@4 -g`

TO FIX THIS
 `1058 verbose stack Error: ENOENT: no such file or directory, rename 'C:\dev\projects\acme\node_modules\npm\node_modules\dezalgo' -> 'C:\dev\projects\acme\node_modules\npm\node_modules\.dezalgo.DELETE'
1059 verbose cwd C:\dev\projects\acme
1060 verbose Windows_NT 10.0.16299
1061 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jarjar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
1062 verbose node v8.9.1
1063 verbose npm  v5.6.0
1064 error path C:\dev\projects\acme\node_modules\npm\node_modules\dezalgo
1065 error code ENOENT
1066 error errno -4058
1067 error syscall rename
1068 error enoent ENOENT: no such file or directory, rename 'C:\dev\projects\acme\node_modules\npm\node_modules\dezalgo' -> 'C:\dev\projects\acme\node_modules\npm\node_modules\.dezalgo.DELETE'
1069 error enoent This is related to npm not being able to find a file.
1070 verbose exit [ -4058, true ]`

**Comment by adamwathan** [comment]
Thanks for the info; closing this as not an issue but glad it'll show up in Google searches for those who run into similar problems.

**Comment by justinbarkhuff** [comment]
Ran into something similar, but was able to fix it without rolling back npm. Fixed mine by deleting both the `node_modules` directory and the `package-lock.json` file, then running `npm install`.

**Comment by erikmueller** [comment]
I also found the `npm4` problem. Removing local `npm` from you `node_modules` and `npm i`ing again also fixes the issue (9 out of 10) and does not force you to downgrade it globally. See  https://github.com/npm/npm/issues/17444#issuecomment-362559375

**Comment by isaadabbasi** [comment]
I also had this issue, Solved by downgrading npm from 5.6 to 5.2.

**Comment by r4m** [comment]
Solved downgrading npm from 5.6 o 5.2 too.

**Comment by harmandeep-singh** [comment]
i also had this issue while trying to build an electron app on windows , i resolve this issue by  installing dezalgo

`npm i dezalgo`

hope this help some one :)

**Comment by lavkesh1608** [comment]
**Solved** Since i am running latest versions of ionic framework , so i solved this issue by upgrading npm to latest version  :

**Comment by CamilaQueiroz** [comment]
Thanksssssss!

**Comment by Tassfighter** [comment]
Nothing above worked for me .
I had to delete the package-lock.json
