### ISSUE TITLE
Get styles as JS object from CSS class names

### ISSUE THREAD

**Issue by jferrettiboke** [tailwindcss/tailwindcss#360]
Hi all!

It would be nice if Tailwind could provide a way to get all the style properties from CSS classes. It would be very useful for CSS-in-JS.

Writing CSS-in-JS is very useful to make universal components across targets, regardless of Platform. If Tailwind is a "A Utility-First CSS Framework for Rapid UI Development", IMO, it should provide easier ways to avoid wasting time when writing CSS-in-JS.

According to my proposal, Tailwind would mean not only for web, also for iOS and Android (React Native), [Sketch ](https://github.com/airbnb/react-sketchapp) and many more platforms.

Instead of this:

```js
const tailwind = require('./tailwind');

const styles = {
  color: tailwind.colors.grey,
  marginTop: tailwind.margin[4],
  marginBottom: tailwind.margin[4],
};

/*
{
  color: '#b8c2cc',
  marginBottom: '1rem',
  marginTop: '1rem',
}
*/
```

This:

```js
const myTailwindConfig = require('./tailwind');
const { getStylesFromClasses } = require('tailwind')(myTailwindConfig);

const styles = getStylesFromClasses('text-grey my-4');

/*
{
  color: '#b8c2cc',
  marginBottom: '1rem',
  marginTop: '1rem',
}
*/
```

**Comment by adamwathan** [comment]
This is a neat idea but no plans to implement right now. If this was developed by someone as a separate project that can get styles from any class list given a CSS tree that contains those classes, I would be open to layering something on top of it that's baked into Tailwind, but no plans to develop this ourselves any time soon.

**Comment by jferrettiboke** [comment]
I understood your viewpoint, @adamwathan. I was thinking a little bit more and I have another approach to bring to the table and it could be easier to implement on Tailwind.

Basically it is as simple as add `.js` as the output file extension, instead of `.css`. That will mean that the output will be a JS object.

```
./node_modules/.bin/tailwind build styles.css [-c ./tailwind.js] [-o ./output.css]
```

Internally, Tailwind can convert the current output (the CSS) into a JS object with the help of [`native-css` library](https://github.com/raphamorim/native-css) and create a `.js` output file based on the output file extension.

So, for example, this:

```css
/* More stuff here... */

.sm\:text-red-darkest {
  color: #3b0d0c;
}

/* More stuff here... */
```

Will be convert to this:

```js
/* More stuff here... */

"sm__text_red_darkest": {
  "color": "#3b0d0c"
},

/* More stuff here... */
```

Having this option is really good and does not compromise to Tailwind to big changes at all. So, do you agree on this? This means that Tailwind will generate a CSS output file but it will be also able to generate a JS output file to be imported if desired for CSS-in-JS.

**Comment by farskid** [comment]
@adamwathan I'm keen to work on this tool. What are the good starting points I should look into?

**Comment by ianhernandez** [comment]
I'm working on a tailwind ui editor tool and a similar problem popped up for me. 

I found this repo from @siddharthkp https://github.com/ui-devtools/tailwind-utils 

Just wanted to get some visibility on this as I don't think his repo includes the last v3 updates. cc: @farskid

**Comment by Izaanaami** [comment]
> I'm working on a tailwind ui editor tool and a similar problem popped up for me.
> 
> I found this repo from @siddharthkp https://github.com/ui-devtools/tailwind-utils
> 
> Just wanted to get some visibility on this as I don't think his repo includes the last v3 updates. cc: @farskid Wondering if there's a path where things can be less harcoded or less redundant.

this is exactly what I needed. I have an application that needs to update tailwind classes, and sometimes new classes should overwrite some of old classes, so I needed a package to check each class css property.
thank you very much @ianhernandez
