### ISSUE TITLE
[Feature proposal] New module to handle first/last child spacing

### ISSUE THREAD

**Issue by aparajita** [tailwindcss/tailwindcss#369]
This is related to #277.

A very common use case is to handle margins/padding on all but the first/last child, as @sebastiandedeyne [mentioned](https://github.com/tailwindcss/tailwindcss/issues/277#issuecomment-359450119). I'd like to propose a similar concept to #277 but in a more focused form that is orthogonal to the existing utilities: `spaced-{direction}-{size}`.

So `spaced-r-4` would put `mr-4` margin on all but the last child. `spaced-ml-4` would leave margin off the first child. And so on. This would only need to go on the parent element, no need to override a child.

For example, say I'm building a horizontal list of links in a navbar:

### html
```html
<ul class="flex justify-end list-reset spaced-r-4">
  <li class="navbar-link">
    <a class="no-underline text-black" href="about.html">About</a>
  </li>
  <li class="navbar-link">
    <a class="no-underline text-black" href="contact.html">Contact</a>
  </li>
  <li class="navbar-link">
    <a class="no-underline text-black" href="login.html">Login</a>
  </li>
</ul>
```

### css
```css
.navbar-link {
  @apply .inline-block .px-3 .py-2 .font-normal .text-base .text-black
}
```

### Tailwind config
```js
  /*
  |-----------------------------------------------------------------------------
  | Spacer                                  https://tailwindcss.com/docs/spacer
  |-----------------------------------------------------------------------------
  |
  | Here is where you define your spacer utility sizes. These can be
  | percentage based, pixels, rems, or any other units. By default we
  | provide a sensible rem based numeric scale plus a couple other
  | common use-cases like "1px". You can, of course, modify these
  | values as needed.
  |
  | Class name: .spaced-{side}-{size}
  |
  */

  spacer: {
    auto: 'auto',
    px: '1px',
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem'
  },
```

The generated CSS for something like `spaced-r-4` is simply:

```css
.spaced-r-4 > * {
  margin-right: 1rem;
}

.spaced-r-4 > *:last-child {
  margin-right: 0;
}
```

If you think it would be worth supporting padding as well, then the type would be added along with the side, e.g. `spaced-mr-4`.

I'm happy to make a PR for this if you think it's worth pursuing.

**Comment by hacknug** [comment]
I think this would fit better as at-rules since I usually find myself writing this kinds of things outside my config file. I like the idea of introducing something like spacing to be able to share the same spacing values between margins (both positive and negative) and paddings (à la Tachyons) but I'm not sure most people would want this if it hasn't been yet discussed or PR'd (not sure about this though).

Also not sure if you made a mistake here or I simply don't understand how toggling between first/last would work: _So `.spaced-r-4` would put `.mr-4` margin **on all but the last child**. `.spaced-ml-4` would leave margin **off the first child**._

Just my two cents. Looking forward to everyone else's opinion on this. Somewhat related to this (media queries and pseudo selectors) #313 #355.

**Comment by aparajita** [comment]
> I think this would fit better as at-rules since I usually find myself writing this kinds of things outside my config file

The config file defines the available spacing, the same way margin and padding is defined. There will be a set of defaults that mirror the margins. Unless the defaults don't cover your needs, you won't have to configure anything.

> So .spaced-r-4 would put .mr-4 margin on all but the last child. .spaced-l-4 would leave margin off the first child.

Correct. If you're stacking vertically, `spaced-b-4` would leave margin off the last child, `spaced-t-4` the first child.

**Comment by denjaland** [comment]
Interesting thought.  I find myself constantly adding conditional classes in VueJS.

**Comment by hacknug** [comment]
> The config file defines the available spacing, the same way margin and padding is defined. There will be a set of defaults that mirror the margins. Unless the defaults don't cover your needs, you won't have to configure anything.

What I meant is that I don't see why should we add this and _only_ use it to add margins to child elements. I feel this would be much more useful as at-rules to use with pseudo-selectors to `@apply` _any_ class to those elements.

Together with `@responsive` we would be able to create all kinds of things that would only apply to some breakpoints which imho is one of the main issues Tailwind should try to tackle next.

> Correct. If you're stacking vertically, spaced-b-4 would leave margin off the last child, spaced-t-4 the first child.

Again, I still don't understand how `spaced-b-4` and `spaced-t-4` indicate they would exclude their first/last child respectively. The only difference between each other is the `b`/`t` part of the class name which to me stand for `bottom`/`top` and don't tell me anything about targeting the first/last child.

I would probably go for something more like `.child-not-last:mr-8` or `.child-not-first:mr-8` in this case but what I'd really like to be able to do is create all kinds of classes for every pseudo selector in a standardized way.

**Comment by aparajita** [comment]
I agree, a more universal solution would be better.

**Comment by adamwathan** [comment]
I think the most "Tailwind" way to handle this would be adding new prefixes for targeting children like @hacknug mentioned. I'd probably want it to work like this:

```html
<div class="children:mb-4 last-child:mb-0">
  ...
</div>
```

I'm still trying to get over my fear of bloating the living hell out of the CSS so I'm hesitant to add this right now, but I do like the idea. The main question I have with this stuff is how it all plays with other state variants. Do we need to support `hover:children:mb-4` for example? Gets tricky to decide how far to go.

Regarding the `spaced-b-4` style approach; I think if I was going to create classes like that in a project they'd look like this:

```css
.spaced-y-4 {
  margin-bottom: 1rem;
  &:last-child {
    margin-bottom: 0;
  }
}

.spaced-x-4 {
  margin-right: 1rem;
  &:last-child {
    margin-right: 0;
  }
}
```

...instead of having specific versions for top, bottom, left, and right. Seems like just an implementation detail of what you're really trying to do which is either "space these items vertically" or "space these items horizontally".

**Comment by aparajita** [comment]
> <div class="children:mb-4 last-child:mb-0">

Hmm... if you're going to use a general `children` prefix, then you would want to handle things like the common case of nth-child(2) for alternating row colors. And for spaced children in a container, 99% of the time the first/last child will be 0, in which case this solution isn't very DRY. So to cover the most common cases, in addition to the general `children/last-child` mechanism, how about:

```
all-but-last-child
all-but-first-child
every-other-child
```

Seems to me that's how you think about the problem: "I want to apply a right margin to all but the last child of this container."

Of course we could compose these ourselves, but these are extremely common use cases.

> Do we need to support hover:children:mb-4 for example?

Can't see much use case for this, since `children:` is primarily aimed at layout, and I can't think of a case where I would want hovering to change layout. 

> I'm still trying to get over my fear of bloating the living hell out of the CSS

It's the nature of the system you built that there are going to be massive numbers of generated rules that aren't used. But so what? Just make PurgeCSS part of Tailwind. I can't see how anyone in their right mind wouldn't want to use PurgeCSS, considering it takes build sizes down by 20x or more.

Features/functionality are **way** more important than generated file size if PurgeCSS is part of the equation.

**Comment by aparajita** [comment]
@adamwathan If you're still interested in the children/last-child prefixes, I can put together a PR next week.

**Comment by benface** [comment]
Thought on this: the Flexbox Level 2 Spec will bring Grid’s `gap` properties to Flexbox, which will make this problem much easier to solve: https://github.com/w3c/csswg-drafts/issues/592. When we’ll see this in browsers is anybody’s guess, but I’m pretty excited about it.

**Comment by benface** [comment]
@aparajita What happened? Why did you remove all your issues/comments from this repo?
