### ISSUE TITLE
Border Spacing

### ISSUE THREAD

**Issue by jkniest** [tailwindcss/tailwindcss#380]
Hey,

I just wanted to ask if something related to "border-spacing" is planed?

The default table layout does include `border-spacing: 2px` which is kind of annoying since I wanted to add a bottom border after the table head.

With border-spacing 2:
![bildschirmfoto 2018-02-09 um 23 37 21](https://user-images.githubusercontent.com/15618191/36053507-34513eb6-0df2-11e8-9f3a-3c17e96d8c89.png)

With border-spacing 0:
![bildschirmfoto 2018-02-09 um 23 37 51](https://user-images.githubusercontent.com/15618191/36053530-46238176-0df2-11e8-8101-390743bca782.png)

See also: https://www.w3schools.com/cssref/pr_border-spacing.asp

Have a nice day,
Jordan

**Comment by minthemiddle** [comment]
+1

Default Border Spacing is a problem.
You cannot add a continuous background color to tables because of this.

See http://jsbin.com/soxeqat/edit?html,output

**Comment by adamwathan** [comment]
We're planning to add some table related utilities in the near future but in the mean time you can easily add your own utilities:

https://tailwindcss.com/docs/adding-new-utilities

**Comment by adamwathan** [comment]
Looking at getting some of this stuff added soon but quick question, do you actually want `border-spacing: 0` or do you just need `border-collapse: collapse`? It would be nice to avoid adding another scale to the config file for border spacing if people really just care about removing border spacing altogether.

**Comment by minthemiddle** [comment]
For the continuous background color problem, `border-collapse: collapse` would be enough of a solution. See: http://jsbin.com/culebiluca/2

**Comment by jkniest** [comment]
@adamwathan Yeah border-collapse: collapse should be enough. I didn't knew about this css "command".

**Comment by adamwathan** [comment]
We have border collapse utilities now as of v0.6.0 👍

**Comment by OD91** [comment]
I have a case with a table, with:

-  a right border of the first column
-  and a border of the table head (first row or th tag)

These borders are supposed to be sticky when scrolling on the x- and y-axis. This case just works with `border-separate` but here the default is `border-spacing: 2px`. For a cleaner look I would need a `border-spacing: 0px`...

Any progress regarding the question above? **"Are there any plans to add support for changing border-spacing"**

**Comment by epitaphmike** [comment]
Seem like adding your own utility is your best bet for now. With JIT enabled, it'll be nice to see this added to the core library
@adamwathan 
 
```
@layer utilities {
  .border-spacing-0 {
    border-spacing: 0;
  }
}
```

**Comment by dspacejs** [comment]
I'm also in need of this. I think this should be included in Tailwind's stock utilities.

**Comment by reinink** [comment]
Hey all, just letting you know that we've officially added `border-spacing` utilities to Tailwind CSS, thanks to the work of @JuanM04. This will be part of the upcoming `v3.1.0` release, but if you want to use it right away, you can use an [insiders release](https://www.npmjs.com/package/tailwindcss?activeTab=versions).
