### ISSUE TITLE
[Feature Proposal] Element Focus Outline Removal

### ISSUE THREAD

**Issue by davidpiesse** [tailwindcss/tailwindcss#385]
**Proposal:**
Add a new class "no-outline"
```css
.no-outline:focus {
  outline:0;
}
```
**Reasoning:**
When creating a button that is rounded you will potentially (browser dependent but happens in Chrome) get a blue ring around the button that does not line up with the buttons edge.
```html
<button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded-full">
  Button
</button>
```
![image](https://user-images.githubusercontent.com/800650/36262063-5000d84a-125e-11e8-94e7-9fd3dae082bc.png)
Clicking on it renders this:
![image](https://user-images.githubusercontent.com/800650/36262089-6100deba-125e-11e8-981a-2edd33a26c9e.png)

This happens on the Tailwind Docs site [here](https://tailwindcss.com/docs/examples/buttons/#pill) 

Similar to #56 

Happy to PR

**Comment by fedeTibaldo** [comment]
That's a minor side effect of a way bigger picture: keyboard interaction.
Every browser implements it somehow. Resetting `focus` styles would hurt accessibility imo

**Comment by davidpiesse** [comment]
This is why I suggested a new style that was specifically developer implemented rather than a general reset - just when they want it to be; such as rounded buttons.
I felt that no developer would want the weird blue outline to a rounded button and I really wanted to write no CSS 😆
