### ISSUE TITLE
[Feature Request] Provide a Tailwind docset for Dash

### ISSUE THREAD

**Issue by pryley** [tailwindcss/tailwindcss#386]
It would be really handy to have a Tailwind docset for Dash.

![monosnap 2018-02-15 20-38-01](https://user-images.githubusercontent.com/134939/36292621-4270d586-1290-11e8-87ef-776e4231c494.png)

Here is the Docset Generation Guide: https://kapeli.com/docsets

I imagine this could probably be scripted to generate on build.

**Comment by aparajita** [comment]
I tried. Turns out it isn’t straightforward. Because of the structure of the docs generating a decent index is difficult.

**Comment by adamwathan** [comment]
I'm planning to redo the docs site over the next couple of weeks, so any resources that talk about things I should consider to make it Dash-friendly would be great.

**Comment by aparajita** [comment]
@adamwathan Read the page @pryley linked to, it tells you everything you need to know. Generating a good index is the key thing. Take a look at [this](https://kapeli.com/docsets#fillsqlite) and [this](https://kapeli.com/docsets#tableofcontents) in particular. There are links to example scripts on that page.

**Comment by aparajita** [comment]
I'll have time next week to give another try at generating Dash docs and I'll let you know what issues came up.

**Comment by simensen** [comment]
It doesn't look like you *have* to change anything. You just need to be able to index the pieces of your existing HTML docs correctly. Looks like you can use your stock HTML/CSS/everything.

Resources:

 * https://kapeli.com/docsets (talks about how to create everything from scratch)
 * https://github.com/akirk/dash-phpunit (example docset for phpunit)
 * https://github.com/technosophos/dashing#readme (utility to help bootstrap a docset from HTML)

**Comment by adamwathan** [comment]
Going to close this since the docs have moved to their own repo:

https://github.com/tailwindcss/docs

I haven't had time to look into this at all and I don't personally use Dash so I'm not particularly motivated to invest the time into it myself, but welcome any work from the community to do it.

**Comment by axsuul** [comment]
There are now user-contributed Dash docs for Tailwind: https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Tailwind_CSS

**Comment by Igosuki** [comment]
@axsuul they rely on the old one page version of the site, it's obsolete now got to be recoded from scratch.
