### ISSUE TITLE
Disabling normalize.css?

### ISSUE THREAD

**Issue by mattkoch614** [tailwindcss/tailwindcss#398]
This may be a dumb question, but is there any way to disable some (or all?) of the ``normalize.css `` defaults we get with tailwind via configuration? 

I ask this because on a legacy project with super heavy use of old school inline styling, table formatting, and floats galore, dropping in tailwind causes some issues right out of the gate. One culprit seems to be the ``box-sizing`` property on the html element and before/after pseudo classes, but I'm sure there are others.

I was hoping to make a quick config file with some colors and fonts to match our branding, and start folding in the CSS piece by piece.

The project I'm working on here probably won't be completely redesigned, so it would be nice to have the power of something like tailwind peppered in.

If this isn't possible, please feel free to close this issue. That being said, I'd love to hear your thoughts!

**Comment by adamwathan** [comment]
Hey @mattkoch614, totally possible, just don't include `@tailwind preflight` in your CSS file 👍

**Comment by mattkoch614** [comment]
Oh man, I know it was a dumb question. Thanks @adamwathan!

**Comment by SeanRoberts** [comment]
After 1.0 it looks like this can be accomplished by removing `@tailwind base` instead.  Am I missing anything important by removing that line?

**Comment by hacknug** [comment]
@SeanRoberts that's correct 👍

**Comment by adamwathan** [comment]
@SeanRoberts not missing anything *super* important, but here's the docs page explaining what's there:

https://tailwindcss.com/docs/preflight/#app

**Comment by HimanshuBari21** [comment]
https://github.com/tailwindlabs/tailwindcss/issues/398#issuecomment-516811892

people coming for v4, please take this in consideration
