### ISSUE TITLE
[FEATURE] CSS variables

### ISSUE THREAD

**Issue by florenthobein** [tailwindcss/tailwindcss#399]
Did you already consider including the JS config variables in the generated lib, as css variables?

In my projects, I include the generated output of a configured tailwind as a css library, then extend it with targeted css, and I'd love to be able to make use of, say, colors as css variables.

Ex:

In Tailwind config:

```js
let colors = {
  ...
  'black': '#22292f',
  ...
}
```

would generate in the css:

```css
:root {
  --color-black: #22292f;
}
```

**Comment by SmashBrando** [comment]
See https://github.com/tailwindcss/tailwindcss/issues/260

At the current time it makes more sense to define the variables you'd like in your CSS.

**Comment by florenthobein** [comment]
Alright, so, the other way around. Thanks.

**Comment by adamwathan** [comment]
Yeah like mentioned in the other issue we don't have concrete plans to implement anything like this, but it could totally be done with another PostCSS plugin or even Tailwind's upcoming plugin system.

**Comment by omarkhatibco** [comment]
I made it as plugin 
https://github.com/omarkhatibco/tailwind-css-variables
