### ISSUE TITLE
[Feature Request] CLI option to explode config into files

### ISSUE THREAD

**Issue by jameslkingsley** [tailwindcss/tailwindcss#400]
One of the things I like to do is split the config into individual files for an easier workflow. I'm not sure how this would be implemented, a nudge in the right direction and I'll see what I can do.

Essentially instead of having one massive config file in the project root for example, it would split it into files such as `colors.js`, `margin.js`, `screens.js` etc. The CLI could let you do something like `./node_modules/.bin/tailwind init [filename] --explode` and perhaps another tool to explode an existing config like `./node_modules/.bin/tailwind explode [filename]`.

**Comment by adamwathan** [comment]
Interesting idea but no plans to implement right now sorry 😞 It would add some complexity to keeping `webpack watch` working properly and don't want to devote resources to that right now.
