### ISSUE TITLE
Feature Proposal: Docs generator for custom configuration

### ISSUE THREAD

**Issue by timkindberg** [tailwindcss/tailwindcss#403]
After a user has configured tailwind, there could be a way to generate documentation showing their specific configuration settings so they could upload to an internal site for devs in their company to have a reference.

The existing Tailwind doc site is already perfect, it would just need to be "templatized" so it could be populated with custom configs.

**Comment by ajmariduena** [comment]
It would be nice to generate some kind of visual guide base on Tailwind config file. Let me work on something, sharing this someday.

**Comment by adamwathan** [comment]
@samselikoff is actually working on something similar to this, not sure if he plans to open source it eventually but sort of been waiting to see what he comes up with before thinking too hard about this:

https://twitter.com/samselikoff/status/962417456315846656

(video demo in tweet)

This is definitely something I've wanted to be able to do from day 1 so we'll surely have a solution at some point.

**Comment by hacknug** [comment]
Link to the mentioned project's repo: https://github.com/embermap/ember-cli-tailwind

**Comment by samselikoff** [comment]
Would love to see this upstreamed eventually. Right now the styleguide needs to be aware of all the modules and their configured values, and be notified when any one of them change. In Ember CLI Tailwind, it knows the module locations (they're essentially hard-coded), and it uses the broccoli build pipeline to be notified of file changes.

One way to generalize this would be to have the Tailwind binary generate the styleguide from the module locations on disk. Then it would be up to the consumers (such as Ember CLI Tailwind) to re-run that binary whenever the files on disk change. In Ember's case that would be a broccoli watcher, in others it would be webpack, and so on.

The other thing is that I want to keep improving the UI of the styleguide, and I have some ideas for fairly complex features I'd like to see in it: histogram of how much different styles are used, etc. Right now the styleguide is built using Ember components, but if we wanted it to be packaged with Tailwind we'd need to think about the most portable way to do so. I'm not sure the answer here and perhaps the starting point is for Tailwind to expose the customized data in a nice way that different consumers can use to build different UIs.

**Comment by garygreen** [comment]
I've just published a package which can generate your own personalized style guide:

https://github.com/garygreen/tsg

This was heavily inspired by your work with the Ember Cli @samselikoff so props go out to you Sam for the inspiration 😄 

It's still a work in progress, but some things to note:

* Written in Vue
* Supports multiple tailwind configurations
* Not yet published to npm, so give it a spin by cloning locally

**Comment by adamwathan** [comment]
I think this is best tackled as a separate project so going to close this issue, it's a great idea though.
