### ISSUE TITLE
:hover taking precedence over :focus

### ISSUE THREAD

**Issue by Nartub600** [tailwindcss/tailwindcss#404]
This happened to me while using the utility for border colors. I added the `focus` variant to the `borderColors` module, then used it in an `input`:

`<input class="border border-white hover:border-grey-light focus:border-grey-dark" type="text" />`

It is expected that when the `input` is focused, `:focus` style is applied whether the mouse is hovering it or not, but `:hover` style is prevailing and `:focus` style can be seen only when `input` is focused and mouse is not hovering.

**Comment by ExCluSiv3** [comment]
See #379

**Comment by adamwathan** [comment]
I think we are going to change this, but closing this issue in favor of https://github.com/tailwindcss/tailwindcss/issues/392.
