### ISSUE TITLE
@apply .container;

### ISSUE THREAD

**Issue by ConsoleTVs** [tailwindcss/tailwindcss#407]
```
`@apply` cannot be used with .container because .container is included in multiple rulesets.
```

Is there a way to solve this or it must never be injected using apply?

**Comment by adamwathan** [comment]
Right now `@apply` is only designed to work for simple single-definition classes that aren't part of media queries and don't include any pseudo selectors.

Duplicate of https://github.com/tailwindcss/tailwindcss/issues/298.

**Comment by ConsoleTVs** [comment]
Sorry for the duplicate adam!
