### ISSUE TITLE
Missing classes on prod

### ISSUE THREAD

**Issue by marktopper** [tailwindcss/tailwindcss#409]
When I run `yarn run dev`, everything works perfectly.
But when running `yarn run prod` then the stylesheet does not include classes like `text-blue-lighter` and a lot of other classes.

Any ideas?

**Comment by adamwathan** [comment]
Can you share a repository that reproduces this? Are you using Purgecss or
similar?

**Comment by adamwathan** [comment]
Closing as it's more or less impossible this is a Tailwind issue and rather a build config issue. Happy to help troubleshoot still if you can provide a reproduction.
