### ISSUE TITLE
Word-Wrapping

### ISSUE THREAD

**Issue by hacknug** [tailwindcss/tailwindcss#411]
I'm aware we have `break-words` and `break-normal` but they don't allow us to insert line breaks when words overflow their parent container. Unfortunately they're not enough to make this work and I had to extend the class and add `word-break: break-all` too.

Demo showing the issue and how it looks when _fixed_: https://streamable.com/s/mr1hj/rpukfv

Some useful links:
- https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
- https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

Should this be included by default? Should we make a couple new classes to add support for `word-break`?

Also since `word-wrap` is not part of the standard and we now have `overflow-wrap`, should we change it and let Autoprefixer do its thing?

I'd also like to point out that searching for `break` and `word` on the docs doesn't show the page and it kinda makes it harder to find this kind of utilities. It would be great if we could also improve this.

**Comment by adamwathan** [comment]
Can you share a JSFiddle or Codepen that demonstrates the issue? Not sure I fully understand.

This demo just uses `break-words` and long text breaks as expected when it overflows:

https://codepen.io/anon/pen/RMNGWb

**Comment by hacknug** [comment]
You're right it work as expected when dealing with inline elements. The issue is it doesn't with `inline-block` elements.

Here's a fork of your pen demoing it: https://codepen.io/hack_nug/pen/NYPRpp?editors=1000

**Comment by adamwathan** [comment]
Ah got it! I'd be on board with a PR that adds a `.break-all` class.

**Comment by hacknug** [comment]
@milandimun it is although @robbinfellow started working on it on #571 and some issues arised. Maybe you can add your two cents to the PR's discussion
