### ISSUE TITLE
Importing webfonts from a URL doesn't work with LESS

### ISSUE THREAD

**Issue by bhulsman** [tailwindcss/tailwindcss#414]
I'm using TailwindCSS with LESS and Laravel Mix. Adding a web font from Google...

```
@import url('https://fonts.googleapis.com/css?family=Roboto');
```

... results in the following error:

```
ERROR in ./resources/assets/less/theme.less
Module build failed: ModuleBuildError: Module build failed:

@import url('https://fonts.googleapis.com/css?family=Roboto');
^
Can't resolve './https://fonts.googleapis.com/css?family=Roboto' in 'C:\Users\[...]\resources\assets\less'
      in C:\Users\[...]\resources\assets\less\theme.less (line 44, column 0)
    at runLoaders (C:\Users\[...]\node_modules\webpack\lib\NormalModule.js:195:19)
    at C:\Users\[...]\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\[...]\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\[...]\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ multi ./resources/assets/js/theme.js ./resources/assets/less/theme.less
```

Adding it before pre-flight, or after pre-flight, or after utilities doesn't matter. It results in the same error.

Is it possible to add fonts like this at all, and if so; how should I do that? The docs don't mention this and apparently nobody uses a web font like this, since I can't find anything about this issue.

**Comment by adamwathan** [comment]
Try marking the import as a CSS import so Less doesn't try to process it:

```less
@import (css) url('https://fonts.googleapis.com/css?family=Roboto');
```

This error is happening in Less, not in PostCSS so you'd be seeing it even if you weren't using Tailwind. Happy to help anyways :)

**Comment by bhulsman** [comment]
Thanks, that works!

However, in our pre-tailwind projects we used simply `@import url('https://code.cdn.mozilla.net/fonts/fira.css');` (just copied that from a project's source), and it works. So I'm not sure that's because of LESS, but might have to do with Laravel Mix then. Not sure, may test a few combinations when working on some older stuff.

**Comment by adamwathan** [comment]
Yeah I think it's a Mix thing; it's trying to resolve URLs by default I bet.
