### ISSUE TITLE
Support for m and p paired helpers?

### ISSUE THREAD

**Issue by jackmcdade** [tailwindcss/tailwindcss#42]
In our internal utility framework I've gotten quite used to enjoying `.p-2` and `.m-2` helpers that set both x and y axes identically. Any chance of bringing that in in?

**Comment by reinink** [comment]
You mean where doing `.p-2` would add a `0.5rem` (or whatever) padding to the entire element? Because that's how it works already...

**Comment by jackmcdade** [comment]
Ahh well look at that. It wasn't explicit in the docs so I assumed it wasn't present. I gotta look more carefully at the `{?optional}` pattern. Carry on!

**Comment by reinink** [comment]
![proceed](https://user-images.githubusercontent.com/882133/32301584-f0918dae-bf34-11e7-97f4-0b96a25b70c5.gif)
