### ISSUE TITLE
Tailwindcss.com Website Dark Theme

### ISSUE THREAD

**Issue by parlays** [tailwindcss/tailwindcss#424]
Hello Tailwind CSS,

Really cool CSS framework.  Thank you guys so much!

I know this is an uneccessary request, but it would be great if tailwindcss.com had a dark theme.  The white background affects my eyes.  I like how Elixir Hexdocs site has a moon icon that changes it to a dark theme.  The moon icon is next to the hamburger icon on the top left:
https://hexdocs.pm/elixir/Enum.html

Please consider adding a dark theme for the documentation.  Thank you all! :+1: 

Naji

**Comment by taylorbryant** [comment]
I recommend using something like Stylish or Stylebot for this. Chris Coyier wrote [a great article](http://mediatemple.net/blog/tips/bend-websites-css-will-stylish-stylebot/) on using these tools.

**Comment by parlays** [comment]
Thanks.  I've used Stylish in the past and it was a bit of a pain, but Tailwind makes it easy to use.  I just added some new styles.  Here is what I used:
.bg-white{background-color:#27252C}
.markdown>:not(pre):not(h1):not(h2):not(h3):not(h4)>code, .markdown>pre, pre.markdown{background-color:#292929;}
.bg-grey-lightest{background-color:#292929;}
.border-grey-light{border-color:#3a3a3a;}
.markdown>pre, pre.markdown{border-color:#3a3a3a;}
.markdown>blockquote>p, .markdown>p, p.markdown{color:#B4B4B4;}
.text-grey-darkest{color:#999;}
.border-grey-lighter{border-color:#3a3a3a;}
.bg-grey-lighter{background-color:#2a2a2a;}
::-webkit-input-placeholder {color: #aaa;}
::-webkit-scrollbar {width: 6px;background-color: #222;}
::-webkit-scrollbar-thumb {background-color: #2f2f2f;}
.markdown>p code, .markdown>ul li code, p.markdown code.markdown{color:#B08FE1;}
.text-purple-dark{color:#B08FE1;}
.text-blue-dark {color: #97C4E9;}
.token.important, .token.regex, .token.variable {color: #F4B84D;}
code[class*=language-], pre[class*=language-]{color:#ddd;}
.token.cdata, .token.comment, .token.doctype, .token.prolog{color:#aaa;}
*, :after, :before {border: 0 solid #3a3a3a;}
.token.atrule, .token.attr-value, .token.keyword {color: #B799E2;}
.token.boolean, .token.constant, .token.number, .token.property, .token.symbol, .token.tag {color: #81AED2;}
.markdown>a, .markdown>p a, a.markdown {color: #72ABDC;}
.markdown>h4, h4.markdown {color: #d2d2d2;}
.markdown>h3, h3.markdown {color: #e2e2e2;}
.markdown>h1, h1.markdown {color: #e2e2e2;}
.markdown>h2, h2.markdown {color: #e2e2e2;}
.text-grey-dark {color: #CF7F83;}
.token.string {color: #B592E5;}
.token.function {color: #E88297;}
.token.punctuation{color: #666;}
.language-css .token.string, .style .token.string, .token.entity, .token.operator, .token.url {background:none;}

thanks!

**Comment by adamwathan** [comment]
No plans to invest time into this unfortunately at the moment, best discussed on [the docs repo](https://github.com/tailwindcss/docs) anyways.

**Comment by parlays** [comment]
All good.  The stylish tool works well.  Thanks for Tailwind!

**Comment by quick007** [comment]
Finally added 👏
