### ISSUE TITLE
Setting outline: none! important; in preflight is too aggressive.

### ISSUE THREAD

**Issue by AleksejDix** [tailwindcss/tailwindcss#427]
I have hard times working around this lines of code. 

I struggle allot with focus management in my App. `!important` overrides my focus styles.
So i have to make them important too with higher specificity.

My suggestion would be to remove this lines from the preflight or make them optional.

https://github.com/tailwindcss/tailwindcss/blame/e1f3286141db27ac6d2d304d3730f152dd6e43de/css/preflight.css#L522

**Comment by adamwathan** [comment]
Interesting! What's your use case for applying focus styles to elements that are essentially unfocusable (`tabindex="-1"`), are you manually focusing those elements with JS in certain situations but don't want them keyboard accessible by default?

Not opposed to removing this at all, just want to understand the context better 👍

**Comment by AleksejDix** [comment]
okey let me explain:

 I have a AJAX Form and on submit i move focus to success or fail message on the top of the form. (requirements...) The whole page slides to this section and needs to be :focused with css.

I use `role="alert"` and everything works fine but when i focus the element there is no focusring.
