### ISSUE TITLE
Inconsistent border and margin/padding

### ISSUE THREAD

**Issue by TomS-** [tailwindcss/tailwindcss#430]
I believe that there should be a look at consistency with borders. For example `.mb-2` and `.pb-2` however for borders its `border-b-2` I would expect it to be `borderb-2`. 

Is there any reason for this?

**Comment by adamwathan** [comment]
Utilities made up of words that are abbreviated down to a single letter have no delimiters, but utilities that contain complete words use a dash delimiter. Goal was just to be as terse as possible while still making things look nice and be readable when there are words that are meant to be read.

**Comment by TomS-** [comment]
@adamwathan Got it! thanks.
