### ISSUE TITLE
Plugin and Laravel Mix

### ISSUE THREAD

**Issue by jpscharf** [tailwindcss/tailwindcss#432]
When running `npm run watch` and webpack is triggered, utilities provided by a plugin are not included in the css output.

Currenty I must run `npm run dev` or manually call tailwind `npx tailwind build resources/assets/css/app.css -c tailwind.js -o public/css/app.css`.

**Comment by adamwathan** [comment]
Hmm I can't replicate this, can you upload a repo that reproduces it?

**Comment by jpscharf** [comment]
I tried to duplicate the issue in a new repo, and it worked without any issue. Restarting `npm run watch` seems to have fixed it.
