### ISSUE TITLE
@tailwindcss npm org

### ISSUE THREAD

**Issue by aparajita** [tailwindcss/tailwindcss#433]
With the advent of plugins, there will be an inevitable explosion of npm packages with "tailwind" or "tailwindcss" at the beginning of the name.

I recommend creating an npm org for tailwind and moving the existing repos to that org, so we can easily distinguish official packages (@tailwindcss/repo) from third party packages (tailwindcss-repo).

**Comment by adamwathan** [comment]
Already claimed that organization last October 👍 I plan to keep Tailwind itself as just `tailwindcss` but any official packages we put out will definitely be scoped under that organization.

**Comment by MichaelDeBoey** [comment]
@adamwathan You can add the package to the repo, but keep it in the global slope, as long as you don't set the '@tailwindcss' scope in the package name in `package.json`
