### ISSUE TITLE
[Feature proposal] pins reset

### ISSUE THREAD

**Issue by illycz** [tailwindcss/tailwindcss#437]
For responsive variants would be useful `.pin-t-none`, `.pin-r-none`, `.pin-b-none`, `.pin-l-none`.

**Comment by adamwathan** [comment]
Usually I just use `pin-none` for this and then re-apply any I need to stick around:

`<div class="pin-r pin-t sm:pin-none sm:pin-t">...</div>`

Does that work for your needs?

**Comment by illycz** [comment]
Yes, this works, but it's redundant...

**Comment by adamwathan** [comment]
Going to close this as no plans to implement. I'm pretty sure I'm going to add a new `offset` module eventually where we can have dedicated utilities like `top-0` instead of `pin-t`, so I think `top-auto` would fit better there than having `pin-t-none`.
