### ISSUE TITLE
Add overflow-x-hidden and overflow-y-hidden

### ISSUE THREAD

**Issue by benface** [tailwindcss/tailwindcss#439]
They're useful because sometimes you want `overflow-x-hidden overflow-y-auto` (the default `overflow-x` when `overflow-y` is set to `auto` is also `auto`).

**Comment by hacknug** [comment]
Yes! I just had to manually add these to a site I was working on yesterday. I guess @adamwathan will be okay with a PR that includes this as well as tests for them (probably a PR for the docs too).

@benface do you wanna take care of it or should I open the PR myself?

**Comment by adamwathan** [comment]
I think these should be in the framework 👍 Happy to look at a PR!
