### ISSUE TITLE
[Feature Proposal] More component examples

### ISSUE THREAD

**Issue by ryanmortier** [tailwindcss/tailwindcss#444]
I love the idea of Tailwind and utility-based CSS frameworks but one thing that is stopping me from embracing it is that I'm a backend developer who at the moment still relies on frameworks like Bootstrap to build internal corporate tools and other apps.

Bootstrap feels like it's getting stale, at least to me, and I would love to try something new like Tailwind but right now it's still intimidating to make the switch. I think adding more component examples to the point that you almost have a full collection comparable to other CSS frameworks would allow more developers to feel like they could take the leap.

If this is out of scope of this project then please feel free to close this issue. Thanks.

**Comment by adamwathan** [comment]
Hey @ryanmortier! Definitely hoping to add more component examples over time but it's more of a documentation issue than a bug/feature request with the actual framework, so do you mind starting a new issue over at https://github.com/tailwindcss/docs with any component examples that would be helpful for you to see added?

Going to close this one here but again feel free to continue the discussion on the docs repo 👍

**Comment by ryanmortier** [comment]
Sure, thank you.
