### ISSUE TITLE
Responsive on custom classes

### ISSUE THREAD

**Issue by antoninadert** [tailwindcss/tailwindcss#447]
Is it possible to use the responsive selector like `md:height-1` on custom classes that I would define in my CSS ?

If not then this issue would be a feature request. Do you think it is possible to prefix any custom class with `.sm` `.md` and so on, and so my class would apply the media query ?

**Comment by robindrost** [comment]
You can wrap your css in the responsive tag:

@responsive {
  Your css
}

**Comment by adamwathan** [comment]
Yep like @robindrost mentioned, docs are here:

https://tailwindcss.com/docs/adding-new-utilities#responsive-variants

**Comment by antoninadert** [comment]
Brilliant :) Thanks

**Comment by ITenthusiasm** [comment]
It seems that neither of the linked options are currently a thing, correct? Is there a new syntax for this now?

**Comment by andreichirkov** [comment]
> It seems that neither of the linked options are currently a thing, correct? Is there a new syntax for this now?

In docs I cant't understand how to add my RESPONSIVE class with different styles on every point (sm, lg)

After 1 hour this work for me:

`
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  .px-container {
    @screen sm {
      @apply px-4 bg-amber-700
    }

    @screen lg {
      @apply px-4 bg-green-400
    }
  }
}
`

So 'px-container' works fine, but autocomplete don't work in components
It's better than nothing

**Comment by nbelakovski** [comment]
From the v2->v3 migration guide

> Since all variants are now enabled by default, you no longer need to explicitly enable these for custom CSS using the @variants or @responsive directives.
>
> Instead, add any custom CSS to appropriate “layer” using the @layer directive:


https://v3.tailwindcss.com/docs/upgrade-guide#replace-variants-with-layer

Works for me in v3, haven't tried with v4.
