### ISSUE TITLE
Border on button

### ISSUE THREAD

**Issue by RafaelMLMacedo** [tailwindcss/tailwindcss#448]
Hi there,

First off all, thanks for the CSS utility framework 😄 it is the best!

Second off all, is it just me or the border is not showing on the `<button>` element?
```
<!-- This is outline button example on "https://tailwindcss.com/docs/examples/buttons"  -->
<button class="bg-transparent hover:bg-blue text-blue-dark font-semibold hover:text-white py-2 px-4 border border-blue hover:border-transparent rounded">
  Button
</button>
```
The weird part is that it shows on another element, like `<span>`

Does anyone has this issue on v0.5.2 ?

I'm using Laravel 5.6 and using .less with this configuration on mix in case it matters 😄 

```
mix.js('resources/assets/js/app.js', 'public/js')
    .less('resources/assets/less/app.less', 'public/css')
    .options({
        postCss: [
            tailwindcss('./tailwind.js')
        ]
    })
    .version();
```

**Comment by RafaelMLMacedo** [comment]
Is my question so dumb no one even bother to reply or I'm not explaining my error properly?

**Comment by adamwathan** [comment]
Hey sorry been very busy and haven't had time to go through the issues in a while.

The border in the documentation shows up for me:

![image](https://user-images.githubusercontent.com/4323180/38711644-e6d207c8-3e94-11e8-858a-195f44363604.png)

Are you saying when you visit the docs it doesn't show up? Or only in your own project? Do you have `@tailwind preflight` included in your CSS? Can you share a fiddle that reproduces the problem, or a GitHub repo?

**Comment by RafaelMLMacedo** [comment]
In the documentation yes, it show's, but not in my own project. I am using the
```
// app.less

@tailwind preflight;
@tailwind components;
@tailwind utilities;

button, [role = button] {
  //@apply .sans;
  cursor: pointer;
}
```

I don't know if I'm doing something wrong 😞

**Comment by RafaelMLMacedo** [comment]
I'm also using
```
// app.less

@import (less) "~normalize.css/normalize.css";
@import (less) "~suitcss-base/lib/base.css";
```

Do you see any pitfall I've might got myself into?

**Comment by adamwathan** [comment]
You don’t need Normalize or SuitCSS Base, both of those are already included in Preflight. I bet that’s what’s messing things up.

Also your custom button base styles should be moved; put them between preflight and components, base styles like that should be at the beginning of a stylesheet.

Can you post your whole CSS file?

**Comment by adamwathan** [comment]
Cool glad that solved it.
