### ISSUE TITLE
Integrating TailwindCSS with SailsJS

### ISSUE THREAD

**Issue by aidanayala** [tailwindcss/tailwindcss#451]
Has anyone had any success with integrating tailwind with SailsJS?

If so would you mind sharing your setup?

**Comment by adamwathan** [comment]
This SailsJS starter project seems to have PostCSS set up, maybe check it out for an example:

https://github.com/leedium/sailsjs-starter/blob/e1e1133571fe1172a3b70d97a3bcc6f7e612bd15/tasks/config/postcss.js

You'd just have to add `require('tailwindcss')('/path/to/your/tailwind/config.js')` before autoprefixer in the plugin list.

**Comment by timabell** [comment]
This question has  also  been asked here: https://stackoverflow.com/questions/59022022/how-do-i-setup-tailwind-css-with-sails-js (though no answers yet)
