### ISSUE TITLE
Why is 5 and 7 missing for margin, padding etc..?

### ISSUE THREAD

**Issue by morrislaptop** [tailwindcss/tailwindcss#454]

**Comment by taylorbryant** [comment]
Tailwind isn't necessarily meant to be a framework in the traditional sense like Bootstrap or Foundation. It's meant to be customized. Any values in the default configuration are just there to get you started.

You can add the 5 and 7 steps by throwing this in the definitions for margin, padding, etc.
```
'5': '1.25rem',
'7': '1.75rem',
```

You can read more about the configuration [here](https://tailwindcss.com/docs/configuration).

**Comment by morrislaptop** [comment]
Ok, seemed a bit odd. But the issue is here for anyone else wondering :)

**Comment by adamwathan** [comment]
Yeah same reason 15px, 17px, 19px, 21px, etc. are missing from the font scale; we tried to provide a reasonable set of constrained default values.

It seems a bit weird when you look at it in this case admittedly, but it would probably seem less weird if we extended the default scale with some more large values. It'd end up looking something like this:

```js
{
  // ...
  margin: {
    'auto': 'auto',
    'px': '1px',
    '0': '0',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '32': '8rem',
  },
}
```
