### ISSUE TITLE
Attempts to use any plugin causes the following error.

### ISSUE THREAD

**Issue by alanquigley** [tailwindcss/tailwindcss#455]
Wondering if anyone is having the same issue. Im running tailwind within a react storybook app. It uses webpack and post-css. Any attempt to use a plugin results in an error message.

`Module build failed: TypeError: node.clone is not a function`

Something involving this util.
node_modules/tailwindcss/lib/util/cloneNodes.js:15

**Comment by adamwathan** [comment]
Usually see that error on older versions of PostCSS; can you try explicitly bumping to the newest PostCSS version in your project?

**Comment by adamwathan** [comment]
Can basically promise you this is a PostCSS version problem so gonna close this.
