### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by AGhasemzadeh** [tailwindcss/tailwindcss#47]
Hello,
I like to have sidebar like TailWindCSS.
How can I have it?

**Comment by psren** [comment]
Just look at the source code. The tailwind-docs use tailwind and can show you how to add the sidebar.

**Comment by adamwathan** [comment]
Hey @AGhasemzadeh, this would be a great question for our more general discussion repo here:

https://github.com/tailwindcss/discuss

Happy to chime in with an example if you'll re-open the issue there!
