### ISSUE TITLE
Tailwind causes boxes displayed when copying and pasting content to MS Word

### ISSUE THREAD

**Issue by trbhoang** [tailwindcss/tailwindcss#471]
Just found out that Tailwind causes boxes displayed when copying and pasting content to MS Word.

![image](https://user-images.githubusercontent.com/60682/40352955-70cc6b12-5dda-11e8-8024-aedc8e5a2d7d.png)

Any suggestion to fix this? Thanks!

**Comment by adamwathan** [comment]
This is not a bug with the library, better off asking this question to MS Office support.
