### ISSUE TITLE
"strongest" instead of "darkest"

### ISSUE THREAD

**Issue by cssberries** [tailwindcss/tailwindcss#472]
I'm wondering if there is an option to configure/change the names of the text colours to be more abstract so the "-lightest" -> "-darkest" scale can be renamed to "weakest" -> "strongest"?
The use case is the dark themes where you may end up having a "text-darkest" class for actually white  text.

**Comment by adamwathan** [comment]
Totally! Just change the color names in your Tailwind config file:

https://tailwindcss.com/docs/colors/#customizing
