### ISSUE TITLE
:hover shadow

### ISSUE THREAD

**Issue by diomed** [tailwindcss/tailwindcss#473]
it would be most excellent if this would be possible

`<div class="max-w-sm rounded overflow-hidden shadow hover:shadow-md">`

**Comment by fedeTibaldo** [comment]
You can, but you need to customize the shadow's state variants.
Take a look at
https://tailwindcss.com/docs/shadows/#responsive-and-state-variants.
(PS. I don't remember how to style messages with markdown)

**Comment by diomed** [comment]
I see. Shouldn't this be something default, tho?

**Comment by fedeTibaldo** [comment]
I guess it depends on the use case. I don’t know what else to say

Sent from Mail for Windows 10

**Comment by adamwathan** [comment]
We intentionally keep the number of enabled variants low by default to avoid bloating the default build too much. We might make it a default down the road but for now you just need to enable it in your config file.
