### ISSUE TITLE
postcss cssnano plugin messes up zIndex mapping

### ISSUE THREAD

**Issue by LBrian** [tailwindcss/tailwindcss#474]
Hi guys,

I didn't have time yet to look into which part of `cssnano` optimisation breaks this exactly, just post this issue I encountered first. `zIndex` works perfectly before I added `cssnano` plugin into `postcss.config.js` when I added class `z-10` the compiled stylesheet is actually `z-10{z-index: 2}`. 

Below is my `postcss.config.js` and I tried to remove `preset: advanced` but not working, so I need to remove the whole plugin for the moment to make sure our production works properly.

```javascript
const glob = require('glob');
const path = require('path');
const tailwindcss = require('tailwindcss');
const appRoot = path.resolve(__dirname);

module.exports = ({ env }) => {
  const plugins = [
    tailwindcss(`${appRoot}/../../app/media/js/admin/stackla-tailwind.js`),
    require('autoprefixer')
  ];

  if (env !== 'development') {
    plugins.push(
      require('postcss-cleaner')({
        sources: glob
          .sync(`${appRoot}/../../app/media/js/admin/**/*.jsx`)
          .concat(
            glob.sync(`${appRoot}/../../app/media/js/claim/**/*.{js,jsx}`)
          )
      })
    );
    plugins.push(
      require('cssnano')({
        preset: 'advanced'
      })
    );
  }

  return { plugins };
};
```

**Comment by plesiecki** [comment]
@LBrian You should be able to disable zindex optimisation.
Check this out https://github.com/ben-eb/cssnano/blob/b0cf1d21d259e14c519c37d7d5f31f6eb72132ec/packages/cssnano/src/__tests__/presets.js#L74

**Comment by adamwathan** [comment]
Going to close this as definitely not a Tailwind issue, but more than welcome to continue the discussion to help figure out the cssnano settings you need to prevent this behavior.
