### ISSUE TITLE
Improving the cli

### ISSUE THREAD

**Issue by randohinn** [tailwindcss/tailwindcss#475]
I have a few proposals for the cli, which I'd be happy to tackle implementing as well over the course of the summer, if found useful by anyone. Since developers do tend to spend a lot of time on the command line anyways, especially if working with projects that have class generators etc (such as Laravel), it would be easy to have a way to add rules to the TW config straight from the command line as well. Ideally, to not break stuff, this should just add to the bottom of the respective array. Margins and paddings could be automatically predicted based on the default scale, to save typing if the scale has not been changed. 

For example:

```
R2-D2$:tailwind add:color
    Pick a name for your color (Usually 'colorName-shadeName') :
gorgeous-darkest
    Set a value for 'gorgeous-darkest': #5F4B8B

    Color 'gorgeous-darkest' added as #5F4B8B !
```

```
R2-D2$:tailwind add:margin
    Pick a margin name: 12
    Pick a margin value (3rem):
    Add negative too (no)?: yes
    Margin m-12 for 3rem added! Negative margin added!
```

And so on... Any ideas on this?

**Comment by adamwathan** [comment]
I think this could be a cool idea but I'd rather it be developed as a separate package, at least to start. Feel free to put something together and I'm happy to play with it and offer fedback.

**Comment by adamwathan** [comment]
Closing as "dealt with", not because I'm rejecting it :)
