### ISSUE TITLE
Angular (2-6+) `ng serve` support

### ISSUE THREAD

**Issue by tehpsalmist** [tailwindcss/tailwindcss#481]
Hi Adam et al., I would like to propose adding angular-cli support to the tailwind build process, so Angular developers can benefit from tailwind without disrupting their regular development flow using angular-cli.

I'm not sure yet what changes are necessary in the actual tailwind project, and it is possible that this might be better off living in a separate node_module.

I have jimmy-rigged a chokidar script that watches tailwind files and rebuilds tailwind when changes are saved. ([Check it out](https://stackoverflow.com/questions/47381149/angular-4-tailwindcss-setup/50558866#50558866)) Rebuilding tailwind to the global style sheet (`src/styles.css`) then prompts `ng serve` to re-run, which is the desired behavior, in my opinion.

Initially, I planned on simply packaging my script up with npm, so anyone could just install it and include the appropriate command in their `prestart` script or something. But, maybe there is a more convenient way to ship it along with the tailwindcss package. I will continue poking around on this topic, and I look forward to any feedback.

**Comment by tehpsalmist** [comment]
So, it turns out that turning my jimmy-rigged scripts into an npm module wasn't so bad! There is now a cli tool available for your tailwind + angular needs!
https://www.npmjs.com/package/ng-tailwindcss

**Comment by adamwathan** [comment]
Cool glad to hear you were able to put something together! I don't think there's really anything we could really do to make this better on our end; Angular just needs to start properly supporting PostCSS plugins :\
