### ISSUE TITLE
Seems hover pseudo classes are not working with using prefix

### ISSUE THREAD

**Issue by mfour-merickson** [tailwindcss/tailwindcss#482]
The following does not work

```
<a href="#" class="tw-hover:underline tw-no-underline">Test</a>
```

however, if I remove the `prefix` setting from my `tailwind.js` file and change markup as follows

```
<a href="#" class="hover:underline no-underline">Test</a>
```

It works as expected

**Comment by adamwathan** [comment]
The prefix is added before the base utility name, so `hover:tw-underline` 👍🏻

**Comment by mfour-merickson** [comment]
This was a typo in preparing this report, I babe indeed done `tw-hover:underline` in the actual code. I can supply an archive if you would like

**Comment by mfour-merickson** [comment]
![image](https://user-images.githubusercontent.com/31225533/40888329-7a59ec0c-670a-11e8-9277-f16e7045de6b.png)

**Comment by devcircus** [comment]
But that's what he is saying. ```tw-hover:underline``` is wrong. It should be ```hover:tw-underline```

**Comment by adamwathan** [comment]
Yep @devcircus is correct, you have the class name wrong.

This is explained with examples in the documentation:

https://tailwindcss.com/docs/configuration#prefix

**Comment by mfour-merickson** [comment]
Clayton

Ahhh, I see what you are saying. My bad 🤗
