### ISSUE TITLE
Issue with Google Map marker info windows caused by border-style: solid; on *

### ISSUE THREAD

**Issue by richardwiggins** [tailwindcss/tailwindcss#484]
There looks to be an issue with https://github.com/tailwindcss/tailwindcss/pull/116 that causes a gap with Google Map markers. I removed this and the gap disappeared.

![screen shot 2018-06-07 at 08 48 01](https://user-images.githubusercontent.com/940047/41107699-c926e9b2-6a6a-11e8-8e44-5d9097b28538.png)

**Comment by adamwathan** [comment]
The fix here is to add your own CSS that resets `border-style` back to `none` for the map and it's children, something like:

```css
#map * {
  border-style: none;
}
```

If we tried to fix this from the Tailwind side it would mean you could no longer add a border to an element just by adding the `border` class; instead you'd have to add `border-solid border`. I think writing an extra line of CSS just to undo this style for Google Maps is probably the better trade off.

If you'd prefer to choose the other side of that trade-off, just remove our `preflight` styles from your CSS and provide your own base styles instead 👍
