### ISSUE TITLE
[Feature proposal] -  add watch option to config

### ISSUE THREAD

**Issue by magicspon** [tailwindcss/tailwindcss#488]
Add option to config for watching external files.

example

`tailwind/backgrounds.js`
```
module.exports = {
	backgroundSize: {
		auto: 'auto',
		cover: 'cover',
		contain: 'contain'
	}
}
```

`tailwind.config`
```
const { backgroundSize } = require('./tailwind/backgrounds')

module.exports = {
    backgroundSize,
    
    options: {
      watch: 'tailwind/**.js'
    }
} 

```

Cheers

**Comment by serh11p** [comment]
One of the ways:
Add all tailwind.config.js dependencies( = require.js dependencies) here - https://github.com/tailwindcss/tailwindcss/blob/master/src/lib/registerConfigAsDependency.js#L9

@adamwathan What do you think?

**Comment by adamwathan** [comment]
Yeah that’s how I’d ideally like to do it but I haven’t been able to figure out a way to determine all of the dependencies of someone’s Tailwind config file. Would love a PR if anyone has an idea of how to do it.

**Comment by serh11p** [comment]
> Yeah that’s how I’d ideally like to do it but I haven’t been able to figure out a way to determine all of the dependencies of someone’s Tailwind config file. Would love a PR if anyone has an idea of how to do it.
> […](#)
> On Aug 10, 2019, 10:35 AM -0400, Serhii Pashchenko ***@***.***>, wrote: One of the ways: Add all tailwind.config.js dependencies( = require.js dependencies) here - https://github.com/tailwindcss/tailwindcss/blob/master/src/lib/registerConfigAsDependency.js#L9 @adamwathan What do you think? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Cool. I'll try to found a solution 🤔

**Comment by serh11p** [comment]
@adamwathan , I opened PR.

**Comment by adamwathan** [comment]
This is just going to work automatically from now on so closing 👍
