### ISSUE TITLE
CLI version out of sync

### ISSUE THREAD

**Issue by aaemnnosttv** [tailwindcss/tailwindcss#49]
Hey guys, really exciting to see this thing finally released! Congrats!

I noticed the tailwind CLI version doesn't match the version of the package installed.

```
➜  tailwindtest npm list --depth=0
tailwindtest@1.0.0 /Users/aaemnnosttv/Code/tailwindtest
└── tailwindcss@0.1.2

➜  tailwindtest node_modules/.bin/tailwind -V
0.1.0
```

I realize this is due to being hardcoded in the CLI but not sure how this is normally handled for node CLI apps. Perhaps it should just be written to a file at build-time that the CLI refers to?

**Comment by adamwathan** [comment]
I always screw this up 😩 #60 fixes this for good hopefully.
