### ISSUE TITLE
focus: Not Working

### ISSUE THREAD

**Issue by zreiss** [tailwindcss/tailwindcss#492]
Focus is not working:

here is my input example:
`<input class="bg-purple text-white focus:bg-white focus:text-black rounded py-2 px-3 w-full" placeholder="focus: works?">`

https://codepen.io/zr/pen/LrjBGv

**Comment by zreiss** [comment]
sorry now I noticed 

By default, focus variants are not generated for any utilities.
You can customize this in the modules section of your configuration file

**Comment by AimanFariz** [comment]
> sorry now I noticed
> 
> By default, focus variants are not generated for any utilities. You can customize this in the modules section of your configuration file

How?

**Comment by sytpb** [comment]
how?
