### ISSUE TITLE
[Feature Proposal] Add important: variant option

### ISSUE THREAD

**Issue by jameslkingsley** [tailwindcss/tailwindcss#493]
Quite often I find I need to use a class with `!important` set however it seems overkill to create/modify a non-Tailwind class just for something as small as text color for example.

Eg. I would be changing the `btn` class like this currently:
```css
.btn {
    @apply .bg-primary;

    &:not(.text-danger) {
        @apply .text-white;
    }
}
```

```html
<button class="btn text-danger">Delete</button>
```

Would be ideal if you could just do it like this:
```css
.btn {
    @apply .text-white .bg-primary;
}
```

```html
<button class="btn important:text-danger">Delete</button>
```

You might ask why not just create `btn-{color}` variants? Well that also gets pretty tedious when you have a lot of colors.

This variant could be implemented the same way the `focus` and `hover` ones are implemented, where you can choose which utilities to generate for.

**Comment by jameslkingsley** [comment]
My `app.scss` looks like this, is the `button` import in the wrong place then?

```css
@tailwind preflight;

@tailwind components;

@import "button";

@tailwind utilities;
```

**Comment by benface** [comment]
No, it’s perfect! It should just work, no `important` needed.

**Comment by jameslkingsley** [comment]
Ohhh I needed `options: { important: true }` for it to work. Thanks!

**Comment by adamwathan** [comment]
You shouldn't even need that option actually; when two rules have the same specificity, whatever is defined last wins:

https://jsfiddle.net/wje8os9x/2/

**Comment by chasegiunta** [comment]
@adamwathan not sure where you got that idea...

**Comment by chasegiunta** [comment]
@adamwathan I'd like to address this again to see if it's a possibility. I've found myself a few times now having to use inline styles to override a vue component's wrapper classes.

If I had a `btn` component:
```
<template>
  <div class="p-3 text-white bg-blue">
    <slot />
  </div>
</template>
```
 rather than doing 
`<btn style="background-color: red">Read More</btn>`

it'd be nice if we could just do`<btn class="bg-red!">Read More</btn>`

**Comment by jakedowns** [comment]
just stumbled on this thread and @chasegiunta's npm package: https://github.com/chasegiunta/tailwindcss-important

**Comment by kunwei-kooboo** [comment]
@chasegiunta yes, have the same problem with you. It is better to use `<btn class="bg-red!">Read More</btn>` than config  `{ important: true }` roughly. 
@adamwathan is this will be considered in the future ?

> @adamwathan I'd like to address this again to see if it's a possibility. I've found myself a few times now having to use inline styles to override a vue component's wrapper classes.
> 
> If I had a `btn` component:
> 
> ```
> <template>
>   <div class="p-3 text-white bg-blue">
>     <slot />
>   </div>
> </template>
> ```
> 
> rather than doing
> `<btn style="background-color: red">Read More</btn>`
> 
> it'd be nice if we could just do`<btn class="bg-red!">Read More</btn>`

**Comment by kunwei-kooboo** [comment]
aha, just saw this: https://tailwindcss.com/docs/plugins/#complex-variants

**Comment by kunwei-kooboo** [comment]
> just stumbled on this thread and @chasegiunta's npm package: https://github.com/chasegiunta/tailwindcss-important

aha, just saw this: https://tailwindcss.com/docs/plugins/#complex-variants

**Comment by kissu** [comment]
Still not sure how to implement it, didn't achieved it with either `Complex variants` nor `chasegiunta/tailwindcss-important`'s package.

**Comment by chlorophyllkid** [comment]
@kissu After you add the plugin for complex variants to your `tailwind.config.js`, you also need to add the new variant to the property you want to use it on. (e.g. padding)

```
const plugin = require('tailwindcss/plugin')

module.exports = {
  variants: {
    padding: ['responsive', 'important'],
  },
  plugins: [
    plugin(function({ addVariant }) {
      addVariant('important', ({ container }) => {
        container.walkRules(rule => {
          rule.selector = `.\\!${rule.selector.slice(1)}`
          rule.walkDecls(decl => {
            decl.important = true
          })
        })
      })
    }),
  ],
}
```
This will generate classes like `!px-4` or `md:!px4`

**Comment by kissu** [comment]
I may have already tried that (don't remember exactly) but will definitely give it another try. Thank you very much @chlorophyllkid ! ♥

**Comment by chrise86** [comment]
> @kissu After you add the plugin for complex variants to your `tailwind.config.js`, you also need to add the new variant to the property you want to use it on. (e.g. padding)
> 
> ```
> const plugin = require('tailwindcss/plugin')
> 
> module.exports = {
>   variants: {
>     padding: ['responsive', 'important'],
>   },
>   plugins: [
>     plugin(function({ addVariant }) {
>       addVariant('important', ({ container }) => {
>         container.walkRules(rule => {
>           rule.selector = `.\\!${rule.selector.slice(1)}`
>           rule.walkDecls(decl => {
>             decl.important = true
>           })
>         })
>       })
>     }),
>   ],
> }
> ```
> 
> This will generate classes like `!px-4` or `md:!px-4`

This doesn't seem to work with other variants like `hover` or `dark`.

**Comment by parker-codes** [comment]
Tailwind JIT includes this out of the box, so you could do something like 
```html
<Heading size={3} class="!max-w-xl" />
```

**Comment by acro5piano** [comment]
Any way to implement `class="!max-w-xl"` without JIT?

**Comment by parker-codes** [comment]
@acro5piano Look at the comment a few above mine by chlorophyllkid.

**Comment by Szymon-dziewonski** [comment]
Yep @chlorophyllkid solution is really nice but doesnt work when combining other variants e.g `focus:!bg-white`
