### ISSUE TITLE
[Feature idea] Background images

### ISSUE THREAD

**Issue by Anachron** [tailwindcss/tailwindcss#511]
Hey guys!

I am pretty new so forgive me if this is a stupid idea or has already been discussed,- a quick search did return nothing.

How about adding a class for background-image? It would kind of act like a proxy.

Example:
`<div class="bg-img" data-bg="<some-url>.jpg"></div>`

Sorry for bad formatting,- typing this on mobile.

Have a great rest of the weekend!

**Comment by tlgreg** [comment]
The `attr()` css function can only be used in `content` property currently, so you can't set it with a custom attribute.
You can just use inline style for this or if its a repeating image then create custom class for it.

**Comment by Anachron** [comment]
Owh, I haven't checked the `attr()` support yet. Based on https://dev.w3.org/csswg/css-values/#attr-notation you are right,- I'll close this.

**Comment by adamwathan** [comment]
Yeah I would recommend just using inline styles for this sort of thing currently 👍 Didn't know about the `attr()` function, that's very cool! Looking forward to seeing that get better browser support!
