### ISSUE TITLE
purgecss-webpack-plugin Example

### ISSUE THREAD

**Issue by malinky** [tailwindcss/tailwindcss#514]
In the controlling file size docs I was unable to get the PurgeCss example working using either a PostCss mix or a Sass mix. However, when I used this Spatie package [laravel-mix-purgecss (https://github.com/spatie/laravel-mix-purgecss) it worked straight away.

I'm not sure if others have had any trouble but it might be worth mentioning the package in the docs as an alternative solution.

Thanks

**Comment by azdanov** [comment]
I've been playing around with Webpack, Tailwind and Purgecss.

Have a look here: https://github.com/azdanov/tailwind-starter

**Comment by adamwathan** [comment]
Gonna close this as not an issue with the framework, if anything a PR suggesting any improvements to the docs if there's a mistake would be great 👍 

https://github.com/tailwindcss/docs

**Comment by brandonpittman** [comment]
Same issue. Spent an hour trying to make the example from the docs work. Spatie package sorted me out in 2 minutes.

**Comment by adamwathan** [comment]
Seems like it was a change in Mix 2.1 that caused it to stop working, trying to find out how you're supposed to add Webpack plugins to Mix now... The Spatie package works and uses a different class-based Mix API for extending it (https://github.com/spatie/laravel-mix-purgecss/blob/master/src/index.js), but for the docs example that seems like overkill.

My current suspicion is that `mix.webpackConfig({ ... })` just doesn't work anymore at all, but hopefully that's not the case.

**Comment by bradlc** [comment]
For what it’s worth I just tried it with a fresh Laravel installation (Mix 2.1.11) and the example in the docs works absolutely fine.

**Comment by adamwathan** [comment]
So did I and it didn't work at all 😅

**Comment by adamwathan** [comment]
Link to a repo that reproduces it not working for me:

https://github.com/adamwathan/mix-purgetest

**Comment by bradlc** [comment]
Ah, okay. The difference I didn’t have any JS. Your example didn’t work for me, but if I remove `.js('resources/assets/js/app.js', 'public/js')` it does.

**Comment by adamwathan** [comment]
Now that's really bizarre 🤔
