### ISSUE TITLE
.no-underline doesn't work on <abbr> elements

### ISSUE THREAD

**Issue by teddybradford** [tailwindcss/tailwindcss#515]
In the preflight there's a rule for `abbr[title]` which overrides `.no-underline` class because of the attribute selector, making it impossible to override the text decoration style with default Tailwind.

**Comment by objectmastery** [comment]
As a workaround for now, you can put this after your `@tailwind utilities` declaration:

```css
abbr.no-underline {
  @apply no-underline;
}
```

**Comment by nternetinspired** [comment]
That rule comes with [Normalize](https://github.com/necolas/normalize.css/blob/master/normalize.css#L74) so you may want to consider not using the preflight styles.

**Comment by tehpsalmist** [comment]
This could probably be closed, then, right?

**Comment by adamwathan** [comment]
I don't think we want to mess with Normalize, so probably not going to make any changes to make this work differently out of the box.

Instead I'd recommend a) enabling the `important` option so utilities will always override other styles:

https://tailwindcss.com/docs/configuration#important

... b) adding an extra rule like `abbr.no-underline` like mentioned above, or c) not using `preflight` and instead providing your own base styles.

**Comment by hamstu** [comment]
I had the same issue, but @iadcode's solution caused a 'circular dependency' error for some reason. I found this worked for me though:

```css
abbr[title].no-underline {
  text-decoration: none;
}
```
