### ISSUE TITLE
"grey" should be "gray"

### ISSUE THREAD

**Issue by pedzed** [tailwindcss/tailwindcss#521]
"grey" colors — or "colours" if you are British — should be "gray", because US English is the universally accepted language of the web. At the very least, there should be an alias in place that people can refer to `gray`.

I'm not American, but I find it unreasonable to have everything but Tailwind in US English.

**Comment by jasonlbeggs** [comment]
That's the beauty of Tailwind. Everything can be customized to whatever you want! If you want to change all the `grey`s to `gray`, you can do that in your config file.

**Comment by dwightwatson** [comment]
I'd prefer to see Tailwind adopt the American spelling out of the box as well.

As a user of Australian English this has thrown me off a number of times already. I know it's an easy thing to customise, but I think consistency with other web-based tech using US English would be preferable.

**Comment by adamwathan** [comment]
Will probably change this at some point, I agree should go full 🇺🇸 .

**Comment by yordis** [comment]
I knew I wasn't crazy typing grey for some reason 🤣I never understood why I kept typing grey instead gray before but now I do ( I thought it was a misspelling 🙃)

**Comment by devcircus** [comment]
This wasn't on accident. I remember it actually being talked about somewhere before it was used. I've a started spelling it "grey" outside web development because of using it in tailwind.

**Comment by donnysim** [comment]
Well, there is a `filter: grayscale(100%)`, not `greyscale` so I'm for the gray spelling :3

**Comment by pedzed** [comment]
What I notice is that those who give a thumbs down do not bother to clarify their reasoning. 

The only thing I can think of is what I already mentioned implicitly: backwards compatibility. According to @jasonlbeggs this should not be a problem though: you can easily revert the fix by customizing it.

**Comment by GeoffSelby** [comment]
What about us Americans that have always spelled it as grey instead of gray? 🤣

**Comment by dwightwatson** [comment]
I don’t think it’s fine to assume that everyone will be using PurgeCSS, but the other issue with having both is that they might be used interchangeably by accident, duplicating the classes.

**Comment by adamwathan** [comment]
I ran this poll on Twitter but unfortunately can't guarantee that only Americans responded 😅

https://twitter.com/adamwathan/status/1045684872801484800

CSS actually defines both `grey` and `gray` variants:

![image](https://user-images.githubusercontent.com/4323180/47272202-d8f8dc00-d5cd-11e8-9ab9-fa54b7ed89c2.png)

I'm partial to "grey" personally but don't care that much, so I'm prepared to be convinced to change it in a future release. Not *too* worried about it breaking anything because most users will have their own Tailwind config file with the colors defined with the original spelling anyways, so nothing would actually break for them.

**Comment by laurencei** [comment]
I just had another thought;

We already do `text-center` - and "Center" is American English. Whereas "Centre" is British English.

So for consistency - it would seem logical for American English to be the standard if we are using that style elsewhere.

**Comment by nternetinspired** [comment]
I'm a Brit, but CSS is generally en-US (`: center;` `: capitalize;`, etc.), so I think there's a clear argument to changing to US English just to make Tailwind _closer to CSS_.

**Comment by caneco** [comment]
Just a random thought on this matter…

Why not add some option in the configuration for the spelling of choice?

```javascript
options: {
  prefix: '',
  important: false,
  separator: ':',
  english: 'american', // or 'british'
},```

**Comment by nfq** [comment]
I don't know, I think being dogmatic about this is bad. Consistency is good sure, but what character? I for one (being of British decent) always use British spelling in my docs, and usually American English for 'things' in code. But why be stubborn about it?

**Comment by adamwathan** [comment]
Switched this for 1.0 🇺🇸 My main motivation is that there's a new `gray()` function coming in CSS, so best to stick with the same spelling the platform uses.

**Comment by tehpsalmist** [comment]
'murica.
