### ISSUE TITLE
Tracking/leading naming consistency

### ISSUE THREAD

**Issue by dwightwatson** [tailwindcss/tailwindcss#522]
I was wondering if you'd be open to renaming the larger variants of the tracking/leading utilities to match. It's caught me up a couple of times where I had expected `tracking-loose` to work and had to end up reaching for the docs.

![image](https://user-images.githubusercontent.com/1100408/42863377-458f5f24-8aa6-11e8-829c-51b0470c6c58.png)

![image](https://user-images.githubusercontent.com/1100408/42863382-49ec3272-8aa6-11e8-9b13-43ccb529278d.png)

I think `loose` would be preferable to `wide` for two reasons:
* It works better as a description in both horizontal and vertical directions.
* It sounds more like the opposite of `tight`.

**Comment by adamwathan** [comment]
You can change this in your config file if you like 👍 Going to keep them as-is in the default configuration at the moment though, as "wide letter-spacing" and "tight letter-spacing" is the generally accepted language in typography.

Can see examples on Wikipedia here:

https://en.wikipedia.org/wiki/Letter-spacing
