### ISSUE TITLE
[Bug] using tailwind with Gatsby, path and/or cache issues?

### ISSUE THREAD

**Issue by TomPichaud** [tailwindcss/tailwindcss#524]
Hello there,

I've been playing with Tailwind & Gatsby, I had no issues at all, until I decided to change the default Colors. I wasn't able to get it working easily.

To reproduce this issue we'll use this repo: https://github.com/jlengstorf/gatsby-tailwind-demo
1 - `yarn install`
2- `yarn develop`

You can see the expected purple UI.

BUG 1 - Reverse the purple colors by the green for example, `yarn develop`

You can still see the purple UI.

- Erase **.cache** and **/public**, `yarn develop` = still purple UI

- Erase **.cache**, **/public** and **/node_modules**, `yarn install`, `yarn develop` = yeah green UI !

So every time you change a variable, you need to go trough the all **clean** install / develop process.

BUT because there is a but... `yarn build` `yarn serve` = green UI !

BUG 2 - Move the tailwind.js and .css into a folder, change the appropriate pathways in the other files

- Impossible to make the green UI to appear, purple only.

Please help, I've been struggling for days to locate this bug.

My thought is that it must come from the way tailwind load the config js, but then again I'm not sure, or a webpack config...

**Comment by idrisakmal** [comment]
Hey @TomPichaud , how do you finally solve the config being cached issue? I too, have to delete everything and run the project again to get the config to reflect
