### ISSUE TITLE
Normalize.css 8.0.0

### ISSUE THREAD

**Issue by gregorywolanski** [tailwindcss/tailwindcss#525]
I love Tailwind CSS! Great job. Thank you.

Tailwind uses normalize.css 7.0.0. Version 8.0.0 is now available. Does Tailwind use 7.0.0 for some very specific reason?

I would create a pull request with an update, but normalize.css is outside `package.json` – it functions as a part of `css/preflight.css`. Is there any reason for that? :)

If “yes”, I’m genuinely interested in the details.

If “no”, I can take care of it.

**Comment by davidDuymelinck** [comment]
My interpretation of the preflight file is that you use it if you want as little trouble as possible to get started.

If you want to use another version of normalize.css, I suggest you add postcss-normalize to your project. And put the tailwind specific styles of preflight.css in your css file. Maybe you don't need all of them depending on the postcss-normalize browser configuration.

**Comment by gregorywolanski** [comment]
> My interpretation of the preflight file is that you use it if you want as little trouble as possible to get started.

I agree David and that’s the reason why I think we should keep normalize.css up to date. :)

**Comment by tlgreg** [comment]
It's actually suitcss/base, which includes normalize.css.
Tailwind also slightly modifies that without overriding with higher specificity selectors, mostly borders, list styles and outline I think.

So for the dependency to be imported instead of forked those modifications would need to be separate declarations.

**Comment by adamwathan** [comment]
Happy to accept a PR for updating to Normalize 8.0.0 👍🏻
