### ISSUE TITLE
Request for config example when using postcss-loader

### ISSUE THREAD

**Issue by brandonpittman** [tailwindcss/tailwindcss#529]
I'm using Vue-cli 3 and out of the box, it sets up a PostCSS config using the object syntax

```javascript
plugins: {
  autoprefixer: {}
}
```

What would be the object to pass to Tailwind in this case?

**Comment by tzurbaev** [comment]
You can replace it with the old syntax if it's ok for you:

```js
module.exports = {
    plugins: [
        require('tailwindcss')('./tailwind.js'),
        require('autoprefixer')(),
    ]
}
```

**Comment by brandonpittman** [comment]
@tzurbaev I already know that.

**Comment by adamwathan** [comment]
Just put the path to your config file:

```js
plugins: {
  tailwindcss: "./tailwind.js",
  autoprefixer: {}
}
```

Example from a Vue CLI 3 project: https://github.com/adamwathan/vue-cli3-tailwind/blob/master/package.json#L33-L39

**Comment by brandonpittman** [comment]
@adamwathan Thank you very much!
