### ISSUE TITLE
Tailwind strips all units from css when value is 0

### ISSUE THREAD

**Issue by aerni90** [tailwindcss/tailwindcss#532]
I encountered an issue, where Tailwind strips all units from the compiled css, when the value of any key is `0`. Take this example for instance:

**Original css**
```.section { max-width: 0px; }```

**Compiled css**
```.section { max-width: 0; }```

First I though it might be a problem with my Laravel Mix setup, libsass, PostCss or other plugins. To find the cause of this issue, I systematically disabled everything in my setup and worked my way through until I encountered the issue again. I found out, that the issue only happens, when I activate the Tailwind PostCss Plugin.

I'm using some advanced Sass Mixin to calculate font-sizes, max-width etc. based on the viewport. Now the problem is, that calc doesn't support numbers without a unit.

**This doesn't work**
```.section { max-width: calc(60vw + 0); }```

**This works**
```.section { max-width: calc(60vw + 0px); }```

Is this stripped down `0` without a unit intended or a bug? Is there a way to fix it?

**Comment by adamwathan** [comment]
Fixed and tagged! Update to 0.6.5 and you should be good.
