### ISSUE TITLE
Production CSS size 300+kb

### ISSUE THREAD

**Issue by besrabasant** [tailwindcss/tailwindcss#536]
I am fan of `tailwindcss`... A great tool.

I am facing an issue while build for production.

My Production build size is `311 kb`. 

Where as in the [docs](https://tailwindcss.com/docs/controlling-file-size), it says

> Using the default configuration, Tailwind CSS comes in at 36.4kb minified and gzipped.

Why is it so?

I am also using PurgeCSS in my **webpack-mix** configuration.

**Comment by adamwathan** [comment]
Can you share your project publicly? PurgeCSS definitely isn't doing anything if you are still ending up with 311kb.

**Comment by adamwathan** [comment]
For what it's worth, here's our default build prebuilt and minified:

https://unpkg.com/tailwindcss@0.6.5/dist/tailwind.min.css

It's 292kb raw, but only 49.8kb gzipped, or 24.6kb when compressed with [brotli](https://en.wikipedia.org/wiki/Brotli).

**Comment by besrabasant** [comment]
@adamwathan 

Here's the link to the [project](https://github.com/besrabasant/tailwind-issue) 

**Steps to reproduce**
 - `cd web/app/themes/yellowstudio`
 - run `npm install && npm run production`

**Comment by knowler** [comment]
@besrabasant

[Your packages show `laravel-mix-purgecss`](https://github.com/besrabasant/tailwind-issue/blob/38d62505a6bd3df5aca2ebd846ea35788c13e685/web/app/themes/yellowstudio/package.json#L16), but the `webpack.mix.js` uses `purgecss-webpack-plugin` (and `glob-all`) — which arent's in the `package.json`. You need to use one or another. I tested it for either case and they both work. Final CSS size is 3.23 kB.

**Comment by adamwathan** [comment]
Yep @knowler is right, if you are using the `laravel-mix-purgecss` package you need to follow their instructions to set it up instead of the instructions in our docs.

PR'd the change for you:

https://github.com/besrabasant/tailwind-issue/pull/1

**Comment by besrabasant** [comment]
Thanks @knowler .

the reason for not using `laravel-mix-purgecss` is that, It messes up my styling on production. 

Strips out some of the **extracted component classes**.
