### ISSUE TITLE
Using PostCss Cli to process tailwindCss

### ISSUE THREAD

**Issue by rooney1989315** [tailwindcss/tailwindcss#538]
Hi I am using PostCss Cli to process the tailwindCss and I got an issue when I run `postcss ./main.css -o src/index.css`

Here is my `main.css`
```
@import "tailwindcss/preflight.css";
@import "tailwindcss/components.css";
@import "tailwindcss/utilities.css";
```
Here is my `postcss.config.js`
```javascript
var tailwindcss = require('tailwindcss');

module.exports = {
  plugins: [
    tailwindcss('./tailwind.config.js'),
    require('postcss-import')
  ]
}
```
And the result I got which is in `src/index.css` is 
```
@tailwind preflight;
@tailwind components;
@tailwind utilities;

```

which I do not think is the correct one, can anyone please tell me anything I can do?
Sorry I am new to PostCss

**Comment by tlgreg** [comment]
Process with `postcss-import` first.

**Comment by rooney1989315** [comment]
@tlgreg thank you so much !!!!! thank for ur time and help.
