### ISSUE TITLE
Make authoring colors easier

### ISSUE THREAD

**Issue by MartinMuzatko** [tailwindcss/tailwindcss#539]
Hey there.
I'd love to ask for a feature, to make authoring colors easier.
Earlier in LESS/SASS projects, I would simply use `$color-primary-dark = darken($color-primary, 20%)`
But in tailwind, we could make use of color libraries.

Tailwind already makes customizing the utilities very easy. Colors are taken from google material design if I'm not mistaken, they do a bit more with colors than just adjusting the lightness - they also change saturation and hue per lightness or darkness level. It would be nice to be able to require tools from tailwind to make this authoring easier. Especially if you have a different base-tone of a color and want tailwind to generate the variants.

Example:
```js
let baseColors = [
    'grey': '#b8c2cc',
    'red': '#e3342f',
    'orange': '#f6993f',
    'yellow': '#ffed4a',
    'green': '#38c172',
    'teal': '#4dc0b5',
    'blue': '#2263A4',
    'indigo': '#6574cd',
    'purple': '#9561e2',
    'pink': '#f66d9b',
]

let colors = baseColors.map(tailwind.colorUtils.createTonesFromBase)
```
Your thoughts are very much appreciated.

Otherwise, I found a little tool that helps with generating a palette, but utilizing a UI tool to compose my colors in my project that I can develop from virtually anywhere without an internet connection, does not really appeal to me: https://github.com/tailwindcss/discuss/issues/128

**Comment by hacknug** [comment]
You could use the `color-mod()` function to generate colors in such way with a custom plugin for Tailwind. `postcss-preset-env` will take care of turning that into plain old CSS: https://preset-env.cssdb.org/features#color-mod-function

**Comment by MartinMuzatko** [comment]
@hacknug I'm not sure this will solve the problem. Tailwind generates all its classes from these colors. 
I'd love to still be able to use `bg-yellow-darker` and make the color be generated from the yellow base tone I set.

**Comment by hacknug** [comment]
You could make your plugin generate classes for backgrounds and borders as well.

**Comment by MartinMuzatko** [comment]
Why wouldn't I just change the colors that tailwindcss uses then? :S I don't get your reasoning.

**Comment by adamwathan** [comment]
The tricky thing here is we didn't use any algorithms or functions to come up with our color palette — me and Steve did it all by hand and by eye, comparing shades across colors trying to keep things balanced. We couldn't come up with a reliable way to "math" it that produced results that were as nice as what we just did by eye.

So not sure what to suggest to make coming up with your own colors easier, it wasn't easy for us either 😅

**Comment by hacknug** [comment]
@MartinMuzatko So you can reuse whatever logic is inside your plugin for all of your projects and other people can use it too 😃

**Comment by ky-is** [comment]
I've been experimenting with this too. Tailwind's built-in colors are really nice. But I typically use just a primary and maybe a secondary color, and don't want to tweak each variant individually (not quite that much of a designer sadly..). And the default greys can be a little blue depending on what they're paired with.

So based off the ideas of https://github.com/adevade/color-scheme-generator, I built a helper function that generates an entire color palette for me, provided a single theme color (though you can use it for multiple colors too). Not sure it's exactly what you're looking for, but it might come in handy.

https://github.com/ky-is/tailwind-color-palette

**Comment by adamwathan** [comment]
Going to close this as sort of out of scope of Tailwind itself, but would encourage people to explore creating separate tools to generate color palettes if you're interested in that problem 👍
