### ISSUE TITLE
Improve IE compatibility for flex-1 utility

### ISSUE THREAD

**Issue by scottbedard** [tailwindcss/tailwindcss#549]
IE has trouble understanding our `flex-1` utility, perhaps we should avoid using the `flex: 1` shorthand and be more explicit. After some digging, I wound up on [this stackoverflow page](https://stackoverflow.com/questions/37386244/what-does-flex-1-mean) and am now overwriting my `flex-1` class with the following...

```css
flex: 1 1 0;
```

FWIW, Edge seems to handle the existing utility just fine.

**Comment by objectmastery** [comment]
This sounds like [Flexbug #6](https://github.com/philipwalton/flexbugs#flexbug-6).

Speaking of Flexbugs however, the above flex definition you're now using might cause [Flexbug #4](https://github.com/philipwalton/flexbugs#flexbug-4), which you could solve by using this:
```css
flex: 1 1 0%;
```

There's also luisrudge/postcss-flexbugs-fixes which fixes both #4 and #6. You could just wack that into your PostCSS config after Tailwind.

**Comment by scottbedard** [comment]
Ah, thank you for the info, I always forget about that awesome repo. Would there be any downside to having our `flex-1` utility written this way out of the box? It seems like a bit of a gotcha to use the shorthand, and then leaving it up to the user to apply this fix. If the maintainers oppose this change though, no worries, go ahead and close this issue.

**Comment by adamwathan** [comment]
Would totally accept a PR for this change 👍🏻
