### ISSUE TITLE
Tailwind cli is not processing css

### ISSUE THREAD

**Issue by ansarizafar** [tailwindcss/tailwindcss#552]
I am using tailwincss ver 0.6.5 and node ver10.7.0. I have followed the installation guide and trying to process my css with tailwind cli but cli is not processing my css just outputting my own css file as it is. I am using these steps.
./node_modules/.bin/tailwind init tailwind.js
I am using the sample css from the guide with tailwind directives to create my css file tailwind.css
then using the following command to process my css.
./node_modules/.bin/tailwind build tailwind.css -c tailwind.js -o devstyles.css

tailwind build command is just copying tailwind.css to devstyles.css and not processing tailwind.css to generate styles.

**Comment by adamwathan** [comment]
I've just created a repository to try and replicate this but can't:

https://github.com/adamwathan/tailwind-cli-test

When I run `./node_modules/.bin/tailwind build tailwind.css -c tailwind.js -o devstyles.css` from the root of that project, `devstyles.css` is created with all the replaced CSS like you see in the committed file.

Can you share a repository that reproduces the issue so I can try and troubleshoot what's different?

**Comment by ansarizafar** [comment]
Cli was working fine in the past, may be not working with Node v 10. Here is the repo https://github.com/ansarizafar/tailwindcss

**Comment by adamwathan** [comment]
Ah ok I see the issue, you are trying to use `postcss-import` as well. The Tailwind CLI doesn't pick up your postcss.config.js file or anything like that, it *only* does Tailwind's processing.

If you want to use full-blown PostCSS and include other plugins and stuff, you need to use a proper build tool that supports PostCSS like Webpack, Gulp, etc.

**Comment by adamwathan** [comment]
Sent you a PR which shows you how to do what you want using `postcss-cli`:

https://github.com/ansarizafar/tailwindcss/pull/1

**Comment by ansarizafar** [comment]
@adamwathan Thanks for the help. Its working now.
