### ISSUE TITLE
Set shadowLookup to on by default, and remove it from "experimental"

### ISSUE THREAD

**Issue by jakedohm** [tailwindcss/tailwindcss#556]
First of all, I'm so happy with Tailwind recently. I love the newer features, plugin system, and the choices made about configurability!

A bit of backstory: This morning I used the new create-nuxt-app CLI tool for Nuxt 2.0 applications to create a brand new Nuxt application. create-nuxt-app allows you to choose "Tailwind" as a CSS framework during the project setup, which installs and enables PostCSS and Tailwind, creates configuration files for both, and adds the auto-generated tailwind.css file to the project. This is awesome, as it means Tailwind works out of the box, with no extra configuration.

The only thing that _doesn't_ work, is using `@apply` within single file components, unless you add `@tailwind utilites` at the top of every SFC <style> block. This can be fixed by enabling `shadowLookup` in the "experiments" section of the Tailwind configuration file.

Unless there have been issues with shadowLookup, or it causes backward compatibility issues, it would be awesome for that feature to be enabled by default. It would make working with Tailwind and Vue SFCs even more trivial (and zero config if you're using create-nuxt-app).

**Comment by adamwathan** [comment]
Yeah I agree it's ready for production 👍 Will try and tag a new patch with it included today.

**Comment by adamwathan** [comment]
Done and released as v0.6.6 👍
