### ISSUE TITLE
[Maintenance proposal] Tailwind should follow SemVer

### ISSUE THREAD

**Issue by koresar** [tailwindcss/tailwindcss#557]
Hello.

In node.js and especially NPM the packages must follow [Semantic Versioning](https://semver.org/). However, Tailwind is released in a quite unique manner.

SemVer specs say:
* If version starts with `0` - the software is not yet production ready. Any breaking changes can happen at any time. The software should be considered **experimental**.
* If you release a new feature - change the second digit.

Recently the 0.6.6 was released with a new flag - `shadowLookup`. Subsequently, it should have been released as 0.7.0.

Also, AFAIK, Tailwind is production ready robust software. The version should be at least 1.0.0.

Proposal.

* Re-release Tailwind 0.6.6 as 1.0.0.
* Start doing SemVer compatible releases from now on.

**Comment by adamwathan** [comment]
Hey!

> If you release a new feature - change the second digit.

That only applies after 1.0, before 1.0 anything can happen in both minor and even patch releases.

Up until now we include new features in patch releases, and breaking changes in minor releases, so users can safely pin a requirement like `^0.6.6` and know that they won't receive any breaking changes until they opt-in to `^0.7.0`.

I want to tag 1.0 soon but there's at least one breaking change I already have planned and I'd like to get it out of the way before 1.0 so I don't have to tag 2.0 a few weeks later. We'll get to 1.0 soon enough though 👍🏻

**Comment by koresar** [comment]
I assume you don't like latest Chrome being **v70.x.y** too. :)

I understand the reasons. Thank you for taking time explaining.
