### ISSUE TITLE
No documentation on tailwind cli option

### ISSUE THREAD

**Issue by afzaalopera** [tailwindcss/tailwindcss#563]
i was trying to setup tailwind as mentioned in the docs but when i tried to control filesize by removing color palettes in my confuguration it never worked. Thats because its not documented.  I spent 2-3 hours on this shit.

**Comment by adamwathan** [comment]
You pass your config file to the CLI tool using the `-c` option as demonstrated in the documentation.

![aaa72a42-4adc-44a7-823f-65d7e20e5c57](https://user-images.githubusercontent.com/4323180/46262408-d7f0f500-c4ce-11e8-993e-f9233ddf808b.jpeg)

Also fucking relax 👍🏻
