### ISSUE TITLE
background-position: 50% 0

### ISSUE THREAD

**Issue by mkarkachov** [tailwindcss/tailwindcss#566]
Hi!

I did not find class for `background-position: 50% 0; ` and I did not find possibility to add custom background-position. I use this rule very often and it will be great to have class like .bg-center-x

**Comment by kylemilloy** [comment]
Use `.bqtop` which is equal to `background-position: top;` which is equal to `background-position: 50% 0;`

**Comment by mkarkachov** [comment]
@kylemilloy .bg-top works, thanks!
