### ISSUE TITLE
[Feature proposal] SASS like @extend 

### ISSUE THREAD

**Issue by CDNRocket** [tailwindcss/tailwindcss#574]
Should be nice to have a SASS like @extend feature.
Because @apply is just a mixin that generates redundant code.

**Comment by benface** [comment]
Please no:
https://webinista.com/updates/dont-use-extend-sass/
https://www.sitepoint.com/avoid-sass-extend/

**Comment by CDNRocket** [comment]
I totally agree, but tailwind is another thing, maybe we can implement it in a different way in conjunction with the configuration file? .. it's worth it?

**Comment by adamwathan** [comment]
No plans to build this in to Tailwind but you can absolutely use an existing PostCSS plugin for this like this one:

https://github.com/travco/postcss-extend
