### ISSUE TITLE
Algolia to the rescue? 

### ISSUE THREAD

**Issue by LukyVj** [tailwindcss/tailwindcss#58]
Hey guys! Awesome project you have here! 

I just noticed that your search isn't ready yet? Would you be interested to use our service to perform search on your documentation? 

We do have a product just for that! It's called [DocSearch](https://community.algolia.com/docsearch) and it's free :) 

It already has been adopted by [Bootstrap](https://getbootstrap.com/docs/4.0/getting-started), [Middleman](https://middlemanapp.com/basics/install/), [Facebook ( React )](reactjs.org), [Vue.js](https://vuejs.org/), [Laravel](https://laravel.com/docs/5.5) and a lot more! 

If you are interested, I can definitely set it up for you and send you a pull-request 😊 

Let me know what you think! 

Best,
Lucas.

**Comment by reinink** [comment]
Hey there @LukyVj! Yes, we'd love to use DocSearch. I already submitted a request for this right when the site launched a couple days ago, but I have not heard back yet. 😭

**Comment by LukyVj** [comment]
Okay, expect a PR really soon!

**Comment by reinink** [comment]
@LukyVj ❤️

**Comment by LukyVj** [comment]
It's on it's way! Last details to be fixed and we're good to send a PR! 

### SPOILER ⬇️
<details>

![](https://puu.sh/yg5QP/1812a27966.png)

</details>

**Comment by LukyVj** [comment]
Here you go! https://github.com/tailwindcss/tailwindcss/pull/120

**Comment by reinink** [comment]
This has now been implemented, thanks again @LukyVj!
