### ISSUE TITLE
0.7.0 with react: Unknown browser query dead

### ISSUE THREAD

**Issue by Strernd** [tailwindcss/tailwindcss#583]
I setup some tailwind react projects according to this guide: https://itnext.io/how-to-use-tailwind-css-with-react-16e9d478b8b
This worked great everytime with version 0.6.*
Since version 0.7.0 following the same setup led to following error:
`Building ... tailwind.src.css`
`BrowerslistError: Unknown browser query 'dead'`

**Comment by adamwathan** [comment]
Should be fixed in v0.7.1 👍 Needed to update our autoprefixer dependency.
