### ISSUE TITLE
Add CSS property names to module comment blocks

### ISSUE THREAD

**Issue by chrisrowe** [tailwindcss/tailwindcss#586]
When I want to jump to a specific section of my tailwind config file, I find myself searching for the css property, rather than the Tailwind version.

For example I'll search "font-size" when I really want to jump to "textSizes", it'd be great if within the comment block each module listed what real CSS property it represents.

``` css
/*
  Class name: .text-{size}
  CSS property: font-size
*/
```

**Comment by adamwathan** [comment]
Happy to accept a PR for this, I think it's a good idea 👍
