### ISSUE TITLE
Make generated CSS follow SUIT naming convention

### ISSUE THREAD

**Issue by transitorytammy** [tailwindcss/tailwindcss#595]
Is there a way currently to possibly fork and modify the current version of tailwindcss to be able to have the generated files return SUIT css.  

ie. `.text-grey` becomes `.textGrey`

https://suitcss.github.io/

**Comment by adamwathan** [comment]
Currently not possible to change the names generated, but you could disable all of Tailwind's built-in modules and use your own plugins to generate everything instead 👍 

If you wanted to do it in a fork, you'd just have to edit all the files in the `generators` folder.
