### ISSUE TITLE
How can I deepen the background color?

### ISSUE THREAD

**Issue by lilianjin** [tailwindcss/tailwindcss#599]
Hover deepen background color?
<img width="416" alt="wx20181215-200151 2x" src="https://user-images.githubusercontent.com/21023027/50042833-5576db00-00a4-11e9-8247-354be7761547.png">

**Comment by lilianjin** [comment]
If you configure a light color in the variable, tailwindcss will traverse both colors, which is obviously not a good method. I want to make the current color deeper when a color is in hover!

**Comment by adamwathan** [comment]
What do you mean by "traverse both colors"?

All you need to do is apply one color normally, and another color on hover:

```
<button class="bg-blue hover:bg-blue-dark ...">
```

What makes this "obviously not a good method"? What would you do with vanilla CSS that is any different than this?
