### ISSUE TITLE
Margin only for top/bottom

### ISSUE THREAD

**Issue by awgul** [tailwindcss/tailwindcss#601]
Hey,

It would be a good idea to be able to set what directions I need to margins/paddings.

I would need Tailwind mostly for top/bottom margins and not left/right.
And so with such a settings I could make the CSS size smaller.

Is that possible?

Best,
Tom

**Comment by zaknesler** [comment]
Have you tried using PurgeCSS? That will remove every class you are not using in your markup.

**Comment by awgul** [comment]
OK.
It's some idea.

**Comment by awgul** [comment]
Yes, But I had to use custom extractor for escaped selectors.
I used once unCSS but it was not perfect and so didn't believe in such tools.
But this PurgeCSS looks good.

**Comment by voidiker66** [comment]
Tailwind lets you choose what direction you want the margins and padding. You can already choose to only have margins top and bottom and not to define the left and right.

left: ml-4
right: mr-4
top: mt-4
bottom: mb-4
left and right: mx-4
top and bottom: my-4

source:
https://tailwindcss.com/docs/spacing

**Comment by adamwathan** [comment]
Not possible at the moment — if you wanted to do this for your own projects though you could write a plugin to replace the built-in margin module:

https://tailwindcss.com/docs/plugins

...and disable the built-in margin module in the `modules` section of your config.

No real plans to make the built-in module more customizable in this regard.

**Comment by awgul** [comment]
OK.
Thanks Adam.
