### ISSUE TITLE
Missing Styles if you extend the default colors object to define custom colors in tailwind.js

### ISSUE THREAD

**Issue by connecteev** [tailwindcss/tailwindcss#602]
If you try to extend the colors object AFTER the module.exports = {} block, like this:
Object.assign(colors, {
  'panelColor': '#3333ff',
});
You will find that the resulting tailwind.css file generated is MISSING the BASE styles for:
.text-panelColor {} 
.bg-panelColor {} 
and so on.

Though it does have styles like:
.hover\:bg-panelColor:hover {}
.focus\:bg-panelColor:focus {}
  .sm\:bg-panelColor {}
  .sm\:text-panelColor {}
  .md\:bg-panelColor {}
and so on

Note: tailwind.js has a definition of colors at the top:
let colors = {
  'transparent': 'transparent',
  'black': '#22292f',
...
}
It works fine (the generated css file contains styles like .bg-panelColor {} etc) if you DIRECTLY modify this object, which I don't want to do (to keep the "main" tailwindcss library untouched / "pure" if that makes sense). 
Any suggestions? Looks like a bug, doesn't it?

**Comment by connecteev** [comment]
Turns out this is a bug  if you use:
mix.options({
    purifyCss: true
});

**Comment by hacknug** [comment]
Not a bug. PurifyCss is supposed to remove all unused CSS from your stylesheets.

**Comment by adamwathan** [comment]
Yeah not a Tailwind bug as far as I can tell. If you want to strip unused styles, follow our instructions for using PurgeCSS, PurifyCSS doesn't work very well.

**Comment by devcircus** [comment]
If the styles are applied programmatically, they may need to be whitelisted in configuration.

**Comment by adamwathan** [comment]
Purify CSS just straight up doesn’t work very well, wouldn’t waste time on
it, just use Purge and follow the instructions for using it with Tailwind.
