### ISSUE TITLE
Fix / improve default system font

### ISSUE THREAD

**Issue by florianbouvot** [tailwindcss/tailwindcss#607]
After reading [this article from @mdo about system font at Github](http://markdotto.com/2018/02/07/github-system-fonts/), I think Tailwind could update default sans-serif font family to limit issue on some OS / devices.

Some related articles / issues:

* https://css-tricks.com/snippets/css/system-font-stack/
* https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L278

Thoughts ?

**Comment by hacknug** [comment]
Also relevant: https://preset-env.cssdb.org/features#system-ui-font-family

**Comment by adamwathan** [comment]
Using what Bootstrap uses, will keep doing that until there's a good reason to switch (like Bootstrap switching theirs, or discovering some problem that Bootstrap is slow to address.)
