### ISSUE TITLE
Add border-style double

### ISSUE THREAD

**Issue by PHPGuus** [tailwindcss/tailwindcss#611]
Hi there,

Would you object, if I file a PR that adds border-style "double", please?
"double" seems to be missing, but I don't know whether that was intentional (due to style :rofl:) or not.

Thank you.

Best regards,
Guus

**Comment by PHPGuus** [comment]
I understand that it may be confusing, simply adding border-b border-double as classes to an element will not, by default, provide the user with a double border. However setting border-b-4 (or something similar) will actually make the double border-style work properly, and this can be documented without problems.

**Comment by adamwathan** [comment]
Added 👍
