### ISSUE TITLE
Responsive border widths create wrong classes when size includes a dot

### ISSUE THREAD

**Issue by kristiansp** [tailwindcss/tailwindcss#613]
I seem to have come across a bug with border widths and responsive classes (possibly this also applies to other styles, but I haven't tested that).

I have a border width `0.25`. Using `border-b-0.25` works fine, but `sm:border-b-0.25` doesn't. I discovered that it seems to generate the class `.border-b-0\.sm\:25` instead of `.sm\:border-b-0\.25`.

If I rename the border width to `1/4` instead of `0.25`, it correctly creates the class `sm\:border-b-1\/4`.

**Comment by adamwathan** [comment]
Thanks for this, making a note for myself that this is due to a bug in postcss-selector-parser 3.1.1, and upgrading to 5.0.0 should hopefully fix it as long as we account for breaking changes.

**Comment by kristiansp** [comment]
Thanks for the prompt reply. I was wondering if the bug was somewhere else in the chain, happy you found it out. At least with another syntax it works like expected.
