### ISSUE TITLE
Using @apply inside Sass Mixins

### ISSUE THREAD

**Issue by saleem-hadad** [tailwindcss/tailwindcss#614]
Hi @adamwathan 
Thanks for this awesome project
I'm trying to generate some classes with the power of mixin and @apply

Let's say I've several buttons colors and I don't wont to write each one individually like this:

```scss
.button-red {
    @apply bg-red text-white;

    &:hover {
        @apply bg-red-dark;
    }
}

.button-blue {
    @apply bg-red text-white;

    &:hover {
        @apply bg-blue-dark;
    }
}
```

This will be a tedious process, instead, I'm trying to use this approach:

```scss
@mixin buttonColor($color) {
    @apply $color;

    &:hover {
        @apply $color + '-dark';
    }
}

.button-red { @include buttonColor('bg-red'); }
.button-blue { @include buttonColor('bg-blue'); }
```

I don't know if that even possible with scss mixin, do have any idea or suggestion similar what I'm trying to solve?

**Comment by florianbouvot** [comment]
@saleem-hadad you need to use sass interpolation like that:

```
@mixin buttonColor($color) {
  @apply #{$color};

  &:hover {
      @apply #{$color}-dark;
  }
}

.button-red { @include buttonColor('bg-red'); }
.button-blue { @include buttonColor('bg-blue'); }
```

**Comment by saleem-hadad** [comment]
awesome 😍

**Comment by kKen94** [comment]
I cannot use @each statement.
I try to use same mixin but appears this compilation error:

```
`@apply` cannot be used with `.bg-\#\{\$color\}-100` because `.bg-\#\{\$color\}-100` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.bg-\#\{\$color\}-100` exists, make sure that an
y `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```
This is my webpack postcss configuration
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loader: 'postcss-loader',
        options: {
          ident: 'postcss',
          syntax: 'postcss-scss',
          plugins: () => [
            require('postcss-import'),
            require('tailwindcss'),
            require('postcss-nested'),
            require('postcss-custom-properties'),
            require('autoprefixer'),
          ]
        }
      }
    ]
  }
};
```

**Comment by florianbouvot** [comment]
@kKen94 read this https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus

> The most important thing to understand about using Tailwind with a preprocessor is that preprocessors like Sass, Less, and Stylus run separately, before Tailwind. This means that you can't feed output from Tailwind's theme() function into a Sass color function for example, because the theme() function isn't actually evaluated until your Sass has been compiled to CSS and fed into PostCSS.

**Comment by kKen94** [comment]
Hi, thanks for your quick answer!
```
$colors: ('gray', 'red', 'orange', 'yellow', 'green', 'teal', 'blue', 'indigo', 'purple', 'pink');

@each $color in $colors {
  .btn-#{$color} {
    @apply px-4;
    @apply py-2;
    @apply border !important;
    @apply border-gray-200;
    @apply rounded;
    @apply bg-transparent;
    @apply text-#{$color}-500;
    transition: 300ms;
  }
}
```

I (think) followed every single step and every suggestion to install tailwind with sass (SCSS) preprocessor since I use Angular. And the strange thing is that !important, despite documentation, works normally, but variables interpolation doesn't.
Where I wrong?
