### ISSUE TITLE
Feature proposal: add option to switch [variant]:[class] to [class]:[variant]

### ISSUE THREAD

**Issue by adamkiss** [tailwindcss/tailwindcss#630]
Hey,

Thanks for making Tailwind.

I’d like to ask if it would be possible to add a configuration option to switch the order of variants and classes, e.g. instead of `hover:text-blue`, you could do something like `text-blue@hover` (When paired with custom separator).

I briefly looked at the source code and it seems possible, but I’m sure I haven’t groked the insides of the tailwind fully. 

Thank you for considering this.

**Comment by adamwathan** [comment]
Hey @adamkiss! Interesting idea but I don't think any plans to add this level of configurability to core right now. If you really wanted to you could create your own variants to replace the built in ones using the plugin system though:

https://tailwindcss.com/docs/plugins#adding-variants
