### ISSUE TITLE
@apply cannot be used with .white

### ISSUE THREAD

**Issue by dudedigital** [tailwindcss/tailwindcss#631]
So I am kind of going crazy here. I cannot get @apply to work. I've searched and read trying many different things mentioned around here.

**The error:**

> `@apply` cannot be used with `.white` because `.white` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.white` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

----

This seems straightforward and clear. Many things I've read say it's due to the imports and things must be inline.

webpack.mix.js
```
let mix = require('laravel-mix');
let tailwindcss = require('tailwindcss');
let atImport = require('postcss-import');

mix.js('src/main.js', 'dist/js')
    .sass('src/sass/main.scss', 'dist/css')
    .options({
        processCssUrls: false,
        postCss: [
            atImport(),
            tailwindcss('./tailwind.js')
        ],
    });
```
main.scss
```
@import '../tailwind-preflight.css';
@import '../tailwind-components.css';

@import "variables";
@import "mixins";
@import "badge";
@import "chips";
@import "components/the_top_nav";
@import "forms";
@import "transitions";

@import '../tailwind-utilities.css';
```

Each tailwind file simply contains `@tailwind` call.

_the_top_nav.scss
```
.the-top-nav-menu-toggle {
  @apply white;
}
```

Any help will be greatly appreciated.

**Comment by benface** [comment]
The obvious question: are you sure you have a `.white` selector in your CSS? Is it a custom utility?

**Comment by devcircus** [comment]
Maybe .text-white or .bg-white?

**Comment by dudedigital** [comment]
Sorry guys I just made some really silly assumptions. I should have been applying text-white. I also made the mistake of adding commas to the apply list. I clearly wasn't thinking.

**Comment by benface** [comment]
> I also made the mistake of adding commas to the apply list.

If you mean dot instead of comma (e.g. `@apply .white`), that actually works AFAIK.
