### ISSUE TITLE
Importing Tailwind config breaks on IE11 due to container plugin

### ISSUE THREAD

**Issue by TomDeSmet** [tailwindcss/tailwindcss#634]
I imported my Tailwind config file into a Vue component, but from the minute I did that, it breaks on IE11.
It works on Chrome though.

The issue lies with the container plugin that is enabled by default. If I disable this plugin, it works on IE11.

The error starts with the eval() function that is being generated by Webpack from that file (`node_modules/tailwindcss/lib/plugins/container.js`). I can't tell you more as my understanding off the inner workings of Tailwind and Webpack are limited.

**Comment by adamwathan** [comment]
Solved in Slack so closing, but here's the message I posted there for anyone else who finds this issue:

> I would recommend not importing your tailwind config file into your Vue components directly, because you are going to drag along unnecessary dependencies. For example, the container plugin uses lodash, so now your client bundle will contain lodash.
>
> A better idea is to extract all of the style information you want to reference out into a new file, and import that file into your tailwind config to reference, as well as into your Vue components.
>
> Keep this new file just simple plain data, don’t import any other dependencies.
