### ISSUE TITLE
Creating a new variant that applies atRule does not get proper responsive treatment

### ISSUE THREAD

**Issue by justinanastos** [tailwindcss/tailwindcss#641]
I am adding a new variant called `safe`. It will allow me to specify position, padding, and margins that will follow the suggestions in https://webkit.org/blog/7929/designing-websites-for-iphone-x/ regarding using `max()` values to make sure my page doesn't intrude in iPhone X safe areas.

The variant itself uses `@supports()`, which causes unexpected behavior in [`substituteResponsiveAtRules`](https://github.com/tailwindcss/tailwindcss/blob/master/src/lib/substituteResponsiveAtRules.js#L28):

https://github.com/tailwindcss/tailwindcss/blob/8b1b797b9f6873124f70f8c6e9d52d4c75681199/src/lib/substituteResponsiveAtRules.js#L27-L37

In the case I described above, when a variant creates it's own atRules, `responsiveRules` here will be an array of not just `Rule`s, but also `AtRule`s. Those require special processing to all be property prefixed with the responsive classname.

I'm going to send in a PR with tests that illustrate the problem.

---

Reproduction can be found at https://github.com/justinanastos/tailwindcss-nested-atrules

**Comment by justinanastos** [comment]
Please see a working reproduction at https://github.com/justinanastos/tailwindcss-nested-atrules

**Comment by adamwathan** [comment]
Thanks again for catching and fixing this!

**Comment by justinanastos** [comment]
You're very welcome @adamwathan! Thanks for the super quick attention. Keep up the good work!
