### ISSUE TITLE
[Feature Proposal] Cursor Utilities

### ISSUE THREAD

**Issue by NicolasGiuristante** [tailwindcss/tailwindcss#658]
Hello, simple request/proposition.

Adding a couple of "rarely used yet quite useful" additional utilities for the cursor rendering.

`.cursor-help` -> `cursor: help;`
`.cursor-resize-col` -> `cursor: col-resize;` **
`.cursor-resize-row` -> `cursor: row-resize;` **
`.cursor-grab` -> `cursor: grab;`
`.cursor-grabbing` -> `cursor: grabbing;`
`.cursor-none` -> `cursor: none;`

There are plenty more options but I think those would be useful, especially for dashboards and backends. Those listed above are compatible in very old browsers.

** Reasoning for swapping the resize: There are many more resize options; starting the class with resize as a "prefix" made more sense than their actual values.

**Comment by benface** [comment]
This plugin adds all of those and more: https://github.com/hacknug/tailwindcss-cursor-extended (it calls the resize ones `cursor-col-resize` and `cursor-row-resize`, though)

By the way, if you don't mind me being pedantic, those classes are called "utilities" and not "variants" in Tailwind vocabulary. The variants are the prefixes such as `sm:`, `md:`, `lg:`, `hover:`, etc.

**Comment by hacknug** [comment]
I feel like these should be in core even if you don’t need them 99% of the time. Maybe keeping todays defaults using a new variant `recommended` or similar could be the solution? 🤔

**Comment by hacknug** [comment]
Cursors are (will be) customizable as of #679. I guess we can close this now.
