### ISSUE TITLE
Feature proposal: support Sass placeholder selectors

### ISSUE THREAD

**Issue by DanielRuf** [tailwindcss/tailwindcss#659]
We would like to use Sass' `@extend` with placeholder selectors (`%`) to prevent that all the generated classes are in our stylesheets as this can be quite much code.

See http://thesassway.com/intermediate/understanding-placeholder-selectors

**Comment by adamwathan** [comment]
Hey Daniel! I'm assuming you are asking for this as an alternative to `@apply`? If so you might find this post interesting:

["Mixins are better for performance"](https://csswizardry.com/2016/02/mixins-better-for-performance/)

Basically copying the rules to multiple class definitions actually gzips better than trying to combine class declarations to avoid duplicating rules.

Using `@apply` (mixins) also has the huge benefit of not affecting your CSS source order, which can cause bugs in your design:

https://codepen.io/adamwathan/pen/aqOQOX

Personally I think using `@extend` in Sass is just generally a very bad idea for these two reasons so it's not something I intend to bake in to Tailwind in any way, but if you really want to use something like that with PostCSS there is the [postcss-extend](https://github.com/travco/postcss-extend) plugin which you could add to your own project 👍

**Comment by DanielRuf** [comment]
> Using @apply (mixins)

apply is abandoned and rejected from official CSS specs and not part of Sass.

**Comment by DanielRuf** [comment]
Well I saw no mixins here so this is still a valid feature proposal.

**Comment by DanielRuf** [comment]
Also the performance is not relevant for us as we compile only once and deliver only the generated CSS. Combining rules is totally ok on the clientside.

**Comment by DanielRuf** [comment]
Currently the general issue is that tailwind has no customizable class prefixes or definitions (% instead of .).

A pure Sass version with mixins instead if classes would be ideal / the best but would require a bigger rewrite.

**Comment by adamwathan** [comment]
> apply is abandoned and rejected from official CSS specs and not part of Sass.

`@apply` is a feature of Tailwind: https://tailwindcss.com/docs/extracting-components#extracting-utility-patterns-with-apply

> Also the performance is not relevant for us as we compile only once and deliver only the generated CSS.

I mean performance as in file size. Using `@extend` leads to bigger CSS files than using mixins, so they are slower for your customers to download.

> And gzip is not so much relevant anymore (Brotli).

The idea is the same, mixins compress better than extend using both gzip and Brotli.

> A pure Sass version with mixins instead if classes would be ideal / the best but would require a bigger rewrite.

Definitely not interested in this. The idea behind Tailwind is to style elements by applying utility classes in your HTML and only extract component-style classes to solve painful duplication problems. If you want to write CSS in a more traditional way using content-derived classes that are built with mixins or by extending Sass placeholders then Tailwind is probably not the right tool for your team.

**Comment by DanielRuf** [comment]
> @apply is a feature of Tailwind: 

I am aware of this but this will be never valid CSS as it was once proposed but is now rejected from the specs.

I'll check if we can do the generation once, split the generated files, generate mixins and placeholders and cleanup the final files from all utility classes as we only need them for composing the components without deliverjng all these utility classes to the clients.

Otherwise we can not apply BEM and other approaches and atomic design solutions like patternlab.

Do you know if there are some projects who do it like this and only use the classes for prototyping in the development process?

Our goal is to have a configurable outcome like we have in some parts of Magento 2 (Blank and Luma theme, thousands of variables) and Foundation Sites (very few prototyping mixins and classes).

**Comment by DanielRuf** [comment]
We'll try https://www.npmjs.com/package/postcss-classes-to-mixins (and other soltions).

I think this is the best approach in this case.

**Comment by brandontamm** [comment]
@DanielRuf - Are you using tailwindcss for magento2 theme development? I have been searching for any projects or anyone using this currently..

**Comment by DanielRuf** [comment]
> @DanielRuf - Are you using tailwindcss for magento2 theme development? I have been searching for any projects or anyone using this currently..

No, I was referring to the customization possibilities in Magento Luma due to the big list of Less variables there or like we have it in Foundation Sites.

**Comment by brandontamm** [comment]
I see. Thank you for getting back to me.
