### ISSUE TITLE
[Feature Proposal] Media query for IE

### ISSUE THREAD

**Issue by maymoon** [tailwindcss/tailwindcss#668]
Add an option to apply certain styles just for Internet Explorer.

There are a lot of cases when some site require css hacks only for IE, for example some extra padding or margin so it would be nice if we could have something like IE specific prefix for example

`.ie:mt-2 .ie:pt-4`

I was thinking to use it similar as you use any other media query for screen size, and even to combine it

`.ie:sm:mt-2`

It can be accomplished with the comment mentioned here https://stackoverflow.com/a/28419263/1421641

What do you think?

**Comment by OwenMelbz** [comment]
Would you not need a prefix for every version in this case?

Technically you can already do this if you use the @apply syntax just Incase that is of interest to you

**Comment by adamwathan** [comment]
Don't plan to build this into Tailwind directly but it's easily done with a [variant plugin](https://tailwindcss.com/docs/plugins/#adding-variants):

```js
module.exports = {
  // ...
  plugins: [
    function ({ postcss, addVariant }) {
      addVariant('ie', ({ container, separator }) => {
        const ieRule = postcss.atRule({
          name: 'media',
          params: 'all and (-ms-high-contrast: none), (-ms-high-contrast: active)'
        })
        ieRule.nodes = container.nodes
        container.nodes = [ieRule]
        ieRule.walkRules(rule => {
          rule.selector = `.ie${separator}${rule.selector.slice(1)}`
        })
      })
    }
  ],
}
```

This creates classes like `ie:mt-2`, and responsive versions like `sm:ie:mt-2`.
