### ISSUE TITLE
Utilizing postcss-normalize

### ISSUE THREAD

**Issue by vinkla** [tailwindcss/tailwindcss#684]
I recently read in the journal about updating preflight to use the `normalize.css` package.

> Update preflight to use normalize.css as a proper npm dependency, instead of manually maintaining a copy-and-pasted version like we do now - [Journal](https://adamwathan.me/journal/2019/02/11/plugin-base-styles-and-shared-theme-values/)

Have you considered using [`postcss-normalize`](https://github.com/csstools/postcss-normalize#readme) instead of shipping the entire `normalize.css` stylesheet letting the user decide which browsers to support?

> PostCSS Normalize lets you use the parts of `normalize.css` you need from your [`browserslist`](https://github.com/browserslist/browserslist#readme)

**Comment by adamwathan** [comment]
Yeah I'm open to looking into this more, when I looked briefly a few days ago I realize that postcss-normalize is actually using a different normalize.css under the hood than the one we are using:

https://github.com/csstools/normalize.css

...so I opted to just go the simple route for now so I didn't have to spend a ton of time digging into the differences. You'll notice that csstools/normalize.css is currently on version 9.0.1 and necolas/normalize.css is only on 8.0.1.

**Comment by vinkla** [comment]
Yeah you are right, I didn't notice the difference at first. It seems the biggest difference being the removal of `margin: 0` on the `<body>` element. Not sure if that could mess up any current applications running Tailwind. 

The difference between the two stylesheets: https://www.diffchecker.com/aV6tptG5

In any case, it would be great if we could ship less CSS and let the developer choose which browser versions to support.

**Comment by adamwathan** [comment]
Not going to pursue this right now, if anything leaning towards dropping normalize as a dependency altogether and maintaining our own reset.
