### ISSUE TITLE
Automatically calculate color shades

### ISSUE THREAD

**Issue by sasafister** [tailwindcss/tailwindcss#686]
I don't know what is approach to defining color shades, this ones are hardcoded

```
let colors = {
  'transparent': 'transparent',

  'black': '#22292f',
  'grey-darkest': '#3d4852',
  'grey-darker': '#606f7b',
  'grey-dark': '#8795a1',
  'grey': '#b8c2cc',
  'grey-light': '#dae1e7',
  'grey-lighter': '#f1f5f8',
  'grey-lightest': '#f8fafc',
  'white': '#ffffff',
}
```

I think that better approach is to define some predefined steps of shade for each defined color ('light', 'lighter', 'lightest', etc), so what I have in mind is something like this:
```
 [
    { 'red': '#e3342f'},
    { 'green': '#38c172'},
    { 'grey': '#b8c2cc'}
  ]
```
and all shades will be calculated automatically.

I already have solution for this, and I can open PR for that. Basically I just need to export helper function, and that's it. What do you think?

**Comment by tlgreg** [comment]
The colors were handpicked consciously instead. [#539 (comment)](https://github.com/tailwindcss/tailwindcss/issues/539#issuecomment-414838822)

But you can create your palette your way too by using a color package from npm.

**Comment by adamwathan** [comment]
Have never had good results with algorithmically generating colors no matter how hard I've tried so going to stick with handpicking them for now. We are working on an all-new color palette for v1.0, can see some in-progress stuff on Twitter:

https://twitter.com/steveschoger/status/1098985161146929153
