### ISSUE TITLE
preflight retains default input field padding

### ISSUE THREAD

**Issue by ion1** [tailwindcss/tailwindcss#709]
Browsers seem to default to having a padding of `1px` on input elements. Given that preflight removes the default border, it might also make sense to remove the default padding.

A demonstration of the default padding and screenshots from Chrome, Firefox and Edge: https://codepen.io/ion1/pen/morXor

![A screenshot of the demonstration on Chrome](https://user-images.githubusercontent.com/39660/53778585-f76ccd80-3f05-11e9-8a22-5dc32f7fa0ad.png)
![A screenshot of the demonstration on Firefox](https://user-images.githubusercontent.com/39660/53778687-49adee80-3f06-11e9-815a-70b9c3db3d60.png)
![A screenshot of the demonstration on Edge](https://user-images.githubusercontent.com/39660/53778720-63e7cc80-3f06-11e9-9f7f-240027b648f9.png)

```html
<input value="default">
<input class="zero" value="zero">
```

```css
input { border: 1px solid black; }
.zero { padding: 0; }
```

**Comment by adamwathan** [comment]
Remove the padding in our new base styles for 1.0 👍 Thanks!
