### ISSUE TITLE
[Feature Proposal] text-align-last

### ISSUE THREAD

**Issue by NicolasGiuristante** [tailwindcss/tailwindcss#717]
Hello, very quick proposal here:

`.text-justify-right` -> `text-align: justify;` `text-align-last: right;`
`.text-justify-center` -> `text-align: justify;` `text-align-last: center;`
`.text-justify-left` ~ `.text-justify`

Use case here:
![screen shot 2019-03-05 at 10 40 47 am copy](https://user-images.githubusercontent.com/12054707/53817575-c3100600-3f33-11e9-9012-96e6900e08a0.jpg)

**Comment by hacknug** [comment]
Plugin territory due to browser support and still being part of a Working Draft (CSS Text Module Level 3).

**Comment by adamwathan** [comment]
Hey @NicolasGiuristante thanks for the suggestion! I think I would implement it as just separate utilities (`text-last-right`, `text-last-center`, and `text-last-left`) which you would use in combination with `text-justify`.

I don't think I want to add this by default right this moment, but if there's enough demand for it to be in core I am not opposed to it 👍🏻

For now I would recommend adding it to your own projects using a little plugin, or using CSS as outlined in the docs:

https://tailwindcss.com/docs/adding-new-utilities

**Comment by kamihicouki** [comment]
Today I strongly felt that I wanted this class and I request to add it.

**Comment by hacknug** [comment]
Still unsupported by Safari even if this first WebKit bug was marked as `RESOLVED FIXED`:

- https://bugs.webkit.org/show_bug.cgi?id=76173
- https://bugs.webkit.org/show_bug.cgi?id=229083

Trying to use a vendor-prefixed version of the property does nothing and Autoprefixer only supports IE and Firefox prefixes iirc.

**Comment by NathanBnm** [comment]
Any chance to reopen this? This is an essential property when using justified text in order to avoid weird alignment for last line.

**Comment by mustafa0x** [comment]
Supported in Safari 16.

**Comment by aemrei** [comment]
You can use `[text-align-last:center]` or `[text-align-last:right]`... etc for now.

**Comment by nmrisrl11** [comment]
For those who still looking how to achieve this here you go...

Put this on your styling where you included the tailwind base, components and utilities.

```
@layer utilities{
    .TextAlignLast{
        text-align-last: center;
    }
}

```
and use it like this... `<p className="TextAlignLast">.....</p>`

**Comment by itrujnara** [comment]
This issue has been closed as completed; however, the feature doesn't seem to exist. I have checked caniuse, and it is now baseline with about 93% availability, so I see no reason against adding it.
