### ISSUE TITLE
[Feature Request] pin center helpers

### ISSUE THREAD

**Issue by acidjazz** [tailwindcss/tailwindcss#724]
I find these very helpful with tailwind mixed with `.fixed`/`.absolute`
```stylus
.pin-center
  top 50%
  left 50%
  transform translate(-50%)

.pin-center-x
  left 50%
  transform translateX(-50%)

.pin-center-y
  top 50%
  transform translateY(-50%)
```

**Comment by adamwathan** [comment]
Hey @acidjazz! Check out the previous discussion around a similar request here:

https://github.com/tailwindcss/tailwindcss/issues/415

TL;DR don't plan to add this but there are other ways you can solve this problem already using Flexbox.
