### ISSUE TITLE
[Feedback Requested] Better default form styles?

### ISSUE THREAD

**Issue by adamwathan** [tailwindcss/tailwindcss#762]
Out of the box, this is what a `select` looks like with Tailwind when you add no additional CSS:

![image](https://user-images.githubusercontent.com/4323180/54322406-6bc10400-45cb-11e9-9244-77bea6ee1487.png)

It's a slightly worse version of what you'd get with just user agent styles, because some of our existing base styles have side effects for form elements that you're basically expected to just not care about because you are going to style them yourself anyways.

What I'm wondering is this:

If I could come up with a way to make controls like this look "not awful" with a little bit of basic custom styling, and none of that styling was intrusive enough to feel like you had to fight it when layering on your own custom styles, would that be a better experience? Or is it totally pointless — maybe it's just fine that things look awful out of the box, they aren't supposed to look good.

**Comment by stefanbauer** [comment]
Actually, why caring about that? I guess these kinds of elements have to be customized anyway as form elements are hard to use out of the box. I think it only makes sense when they fit other inputs.

**Comment by ell10t** [comment]
Maybe it's worth considering optional defaults that can be toggled? I'm sure people moving from Bootstrap would appreciate it.

**Comment by sandren** [comment]
I think a good compromise would be to add a `.select-reset` pseudo-utility class that creates an aesthetically unopinionated as possible, but nevertheless cross-browser consistent style for `<select>` elements. This seems like a safer option than adding custom styles to Preflight and requiring that developers manually undo the styles if they want to fully customize the design for `<select>` elements.

**Comment by hacknug** [comment]
Tachyons has a couple `reset` classes to apply some of this opinionated styles. Maybe it would be worth considering adding a plugin for this, including `.list-reset`?

https://tachyons.io/docs/elements/forms/

**Comment by jstummbillig** [comment]
In favor of reasonable out-of-the-box-styling. 

I see strong relations to recent decision decisions and the niche that tailwind is advancing for itself. In my mind at least one of the following two is a major driver for anyone who reaches for tailwind over something else:

- You want to build quickly, and while you do not want the boostrap look, the material look, or, well, any kind of immediately discernible look, you are still happy when things work reasonably well out of the box in a non-imposing, transparent way.
- You do care about design and are likely to customize your form elements at some point down the line.

Since tailwind is touching the system defaults anyway, leaving the framework defaults in non-working condition seems to be strictly worse than providing reasonable defaults.

**Comment by adamwathan** [comment]
> leaving the framework defaults in non-working condition seems to be strictly worse than providing reasonable defaults.

This is 100% what I think too, thanks for your input! I'm going to play around with it next week and see what I can do, I definitely think there is a path to improving this at least a little bit without imposing any real design opinions. Ideally I can figure out a way to actually make it _easier_ to apply custom styles to form elements 🤔

**Comment by Lelectrolux** [comment]
I'm pretty sure I'd personnaly use the form reset everytime, but a more "customisable" way could be resets based on a `resetForm: true` in the tailwind config (theme even ?), or a separate `@resetForm`, like the `@preflight` one (it's `@base` now in 1.0.0 I think).


A good deal of the less "reseting" and more "harmonisation" could use some similar form of config, maybe...


But I realise I'm the douche asking for a whole new feature just before 1.0 ...

**Comment by helmut** [comment]
I use tailwind alongside a Vue based component library that provides form styling. I'd just like to add that you might just want to make sure that any additional styling provided by tailwind doesn't clash or perhaps it could be opt-in 'able.

**Comment by adamwathan** [comment]
I'm tackling this in a separate official plugin:

https://www.npmjs.com/package/@tailwindcss/custom-forms

...so I'm going to close this issue as I don't intend to do this in core, at least not any time soon.
