### ISSUE TITLE
[Feature Request] Transitions

### ISSUE THREAD

**Issue by PascalHesselink** [tailwindcss/tailwindcss#772]
Properties like `trans-slow`, `trans` and `trans-fast` should be available in the main package.

Slow:
`.trans-slow {
    transition: all .6s;
}`

Normal:
`.trans {
    transition: all .3s;
}`

Fast:
`.trans-fast {
    transition: all .1s;
}`

**Comment by adamwathan** [comment]
Closing as duplicate of #14, we will add these eventually, probably as an official plugin first and then eventually part of core.
