### ISSUE TITLE
Feature request: Non Mobile first approach switch

### ISSUE THREAD

**Issue by cizza** [tailwindcss/tailwindcss#778]
Hi there,

thank you for your great work on Tailwind. I'm using it in my cms I'm currently developing and I've hit quite an interesting situation, for which I don't think there is a solution at the moment.

Tailwind is mobile first approach by default, which is great, however I've just switched to non-mobile mobile approach creating my screen settings in the tailwind config file like this: 

screens: {
      'xl': {'min': '1200px'},
      'lg': {'max': '1199px'},
      'md': {'max': '991px'},
      'sm': {'max': '767px'},
      'xs': {'max': '576px'}
  }

and when I need, I simply use the @responsive directive to generate any required styles. 

The problem I'm facing is the order the styles are getting generated, for example:

@responsive { 
    .mr-10px { margin-right: 10px;  }
}

generates the responsive classes in correct order but the non responsive class is generated underneath the responsive ones, and therefore overriding the responsive classes. That's quite a problem. 

What I propose is a property in the custom tailwind config file: 

mobileFirst: true [true/false] - true by default

which would allow the user to switch the mobile first off, in which case the non responsive class would get generated above the responsive classes. 

I think it makes sense, because in the config file, we can actually control the order in which the responsive classes are generated, but we can't select to generate the non-responsive class above or below the rest. 

If I may ask for anyone responding to this thread, please refrain from proposing to use mobile first approach or to disapprove a validity of non mobile first approach. 

Thank you all!

**Comment by adamwathan** [comment]
Hey! I *think* you can work around this already by manually specifying
where the responsive classes should be generated using the `@tailwind
screens` directive:

```
@tailwind preflight;
@tailwind components;
@tailwind screens;
@tailwind utilities;
```

See if that helps 👍🏻

**Comment by cizza** [comment]
Hello Adam, 

thank you for your very fast response. 

I'm afraid that doesn't help. I just tried this approach and it looked very promising and logical, but the end result seems to be the same. To be on the same page, here is my tailwind scss import:

@tailwind preflight;
@tailwind components;
@tailwind screens;
@tailwind utilities;

@responsive {
    .ml-32px {
        margin-left: 32px;
    }
}

and this is the end result:

@media (min-width: 1200px) {
  .xl\:ml-32px {
    margin-left: 32px;
  }
}
@media (max-width: 1199px) {
  .lg\:ml-32px {
    margin-left: 32px;
  }
}
@media (max-width: 991px) {
  .md\:ml-32px {
    margin-left: 32px;
  }
}
@media (max-width: 767px) {
  .sm\:ml-32px {
    margin-left: 32px;
  }
}
@media (max-width: 576px) {
  .xs\:ml-32px {
    margin-left: 32px;
  }
}
.ml-32px {
  margin-left: 32px;
}

As you can see, the non responsive class is at the end, overriding the responsive classes. 

Thank you.

**Comment by adamwathan** [comment]
Can you show me a full example including your input and the desired output?
The default behaviour puts the responsive classes at the very end so if
that’s what you want I’m surprised there’s an issue there.

**Comment by cizza** [comment]
Hello Adam, 

I went back to the docs, to read them again and I guess the feature request is not required. Because the way the @responsive feature works - or should work, is absolutely sufficient. 

That leaves me scratching my head wondering, why does it not work on build. I will test this locally on a new empty project and will refer my findings to you. 

Thank you for your help so far.

**Comment by cizza** [comment]
Hello Adam,

I've installed a new laravel project and implemented Tailwind. My result is the same on this brand new laravel project. I will list all important settings I think relate to Tailwind in the screenshots. I didn't change anything on the laravel project, just removed everything to get as clean css output as possible.
![app_scss](https://user-images.githubusercontent.com/5670171/54498498-f29a1780-4910-11e9-9db0-b7436e9fce47.jpg)
![css_output](https://user-images.githubusercontent.com/5670171/54498500-f332ae00-4910-11e9-883f-55c6f6848ba3.jpg)
![packagejson](https://user-images.githubusercontent.com/5670171/54498501-f332ae00-4910-11e9-85ac-52b9aae7ef4e.jpg)
![tailwindjs](https://user-images.githubusercontent.com/5670171/54498502-f3cb4480-4910-11e9-9300-9ee2458655a2.jpg)
![webpackmix](https://user-images.githubusercontent.com/5670171/54498503-f3cb4480-4910-11e9-970e-c41f168dcc2f.jpg)

**Comment by adamwathan** [comment]
What output do you actually want, can you show me what you want Tailwind to
generate?

**Comment by cizza** [comment]
Yes, here is the desired output, non responsive class first:

![desired_output](https://user-images.githubusercontent.com/5670171/54498587-f37f7900-4911-11e9-93bf-6570da1ef018.jpg)

**Comment by cizza** [comment]
Am I missing here something, doing something wrong?

**Comment by adamwathan** [comment]
Cool well you should get that result automatically if you delete the
`@tailwind screens` directive. I’m just on my phone so can’t make any
example project but that’s the default behaviour.

**Comment by cizza** [comment]
Thank you Adam, 

that resolved the issue. Don't know how to thank you enough. I'll dive into the docs again to try to understand this better. I've checked the code but it's beyond me. 

I'll close down the issue.

Thank you for developing Tailwind, it's an amazing software, very useful, well thought through and very well written. 

You're quite an inspiration.

Good night.

**Comment by adamwathan** [comment]
Ah cool glad that is working for you! 🙌🏻 Thanks for the kind words, really appreciate it :)
