### ISSUE TITLE
How we can contribute ?

### ISSUE THREAD

**Issue by lefuturiste** [tailwindcss/tailwindcss#78]

**Comment by reinink** [comment]
Hey there @lefuturiste!

In addition to looking through open issues and offering help, the biggest area we need help with right now is improving the docs.

Thanks for your interest in Tailwind! 😍

**Comment by MichaelDeBoey** [comment]
This should be in the [tailwindcss/discuss](https://github.com/tailwindcss/discuss) repo instead 🙂

tailwindcss/discuss#7 has the same question 🙂
