### ISSUE TITLE
[Change Proposal] change w-1/2 to w-1of2

### ISSUE THREAD

**Issue by anhnhoktvn** [tailwindcss/tailwindcss#785]
Hi author, thanks for great library.

Could you consider changing the `w-1/2`, `w-1/3`, ... to `w-1of2`, `w-1of3`, ... or something else. Because I'm a fan of pug/jade , and the character `/` (and `:`) is not support by pug/jade (or emmet). I know I can customize the config file to remove them, however, I'm afraid that in the future, you can add more unsupported characters like this to the library. Therefore, please consider my option, I think there are more options to archive this without making pug/jade fans unhappy.

Thank you!

**Comment by devcircus** [comment]
Seems like a perfect case for a simple library that can be quickly pulled in on every project.

**Comment by d8vjork** [comment]
You can always change them from the config, as you'll do with the `:` separator on the responsive classes `md:w-1/2 lg:w-1/3`

**Comment by adamwathan** [comment]
Not planning to change this, welcome to change it in your own config though 👍

**Comment by AlexanderSopov** [comment]
> You can always change them from the config, as you'll do with the `:` separator on the responsive classes `md:w-1/2 lg:w-1/3`.
> 
> After all, this is the most powerful thing on Tailwind, you can always configure and rebuild your CSS that easy for adapt it to your specific case

Hey! I know how to change the colon (:) separator to something else, but I find no info on how to change the slashes?

**Comment by adamwathan** [comment]
@AlexanderSopov You would just change it in the `width` section of your config file:

```js
// tailwind.config.js
module.exports = {
  theme: {
    width: {
      '1of2': '50%',
      '1of4': '25%',
      // ...
    },
    // ...
  }
}
```

https://tailwindcss.com/docs/width#width-scale
