### ISSUE TITLE
Config modifying ignored

### ISSUE THREAD

**Issue by mohamedsabil83** [tailwindcss/tailwindcss#787]
I installed beta.3 version. Only core config build as CSS and ignoring all modification I make in the configuration file eg. **change color value**

**Comment by devcircus** [comment]
Just installed beta 3 and I’m able to extend without problems. Be sure you’re using the new configuration structure, including the "extend" property.

**Comment by mohamedsabil83** [comment]
I use **init** command for configuration file `./node_modules/.bin/tailwind init --full`
Can you give me a link for using extend?
FYI: I use **laravel-mix**

**Comment by devcircus** [comment]
Sure. Give me a few minutes to track it down. Adam is still working on the docs for 1.0. Should be released soon.

**Comment by devcircus** [comment]
Can't find it right now but just add an "extend" object inside the "theme" object and place your changes inside.
Sample tailwind.config.js
```js
module.exports = {
    theme: {
        extend: {
            fontFamily: {
                'lato': [
                    'lato',
                    'system-ui',
                    'BlinkMacSystemFont',
                    '-apple-system',
                    'Segoe UI',
                    'sans-serif',
                ],
            }
        },
    },
    variants: {
    // Some useful comment
    },
    plugins: [
    // Some useful comment
    ]
}
```

**Comment by mohamedsabil83** [comment]
I try it but also not work. The reason is **laravel-mix-tailwind** not support the beta version yet. When I try it without using **laravel-mix-tailwind** it's work like a charm.
