### ISSUE TITLE
Support for rollup js? 

### ISSUE THREAD

**Issue by jimsheen** [tailwindcss/tailwindcss#788]
Hi, 

Is there a way to compile tailwind js using rollup js? 
I am using the following postcss.config.js 👍 

```const tailwindcss = require('tailwindcss');

module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-preset-env')({
      stage: 1,
    }),
    require('postcss-nested'),
  	tailwindcss('./tailwind.js'),
    require('autoprefixer'),
  ],
};
```

and in rollup.config 
```
postcss({
  extensions: ['.css'],
  extract: true,
  modules: true,
  config: {
    path: './postcss.config.js'
  },
}),
```

When omitting the config.path it does not seem to want to compile tailwind js into css.
Or even including it straight into rollup.config.js

```
const tailwindcss = require('tailwindcss');

...
postcss({
  extensions: ['.css'],
  extract: true,
  modules: true,
  config: {
    path: './postcss.config.js'
  },
  plugins: [
    require('postcss-import'),
    require('postcss-preset-env')({
      stage: 1,
    }),
    require('postcss-nested'),
    tailwindcss('./tailwind.js'),
    require('autoprefixer'),
  ]
}),
```

**Comment by jimsheen** [comment]
Ah fixed it, the component i was building from wasn't including the css file D'OH

**Comment by ericdfields** [comment]
@jimsheen can you share how you're including the css? my rollup + postcss config looks right. I'm trying to do something like 

```
<style>
  @import './main.css';
	h1 {
		color: purple;
	}
</style>
```

but no luck

**Comment by B3Kay** [comment]
> Ah fixed it, the component i was building from wasn't including the css file D'OH

Can you share how you configed rollup for Tailwind?

**Comment by mfeineis** [comment]
This ticket is not the freshest but in case somebody wants to have a look at a working tailwindcss+rollupjs setup, I have one here https://github.com/mfeineis/tailwindcss-exploration

**Comment by tim-phillips** [comment]
@mfeineis, that repo comes back 404

**Comment by alisahindev** [comment]
> This ticket is not the freshest but in case somebody wants to have a look at a working tailwindcss+rollupjs setup, I have one here https://github.com/mfeineis/tailwindcss-exploration

not working link crashed

**Comment by GodBleak** [comment]
I have a working rollup + tailwind setup [here](https://gitlab.godbleak.dev/pub/solid/ssr-streaming-minimal). It's for Solid, but I imagine it will work for other frameworks.

**Comment by JasonMatthewsDev93** [comment]
> I have a working rollup + tailwind setup [here](https://gitlab.godbleak.dev/pub/solid/ssr-streaming-minimal). It's for [Solid](https://github.com/solidjs/solid), but I imagine it will work for other frameworks.

This is EXACTLY what I needed - after 2 days. You're truly doing the lords work! Works with create-react-app and the version of tailwind in the package.json

**Comment by SySagar** [comment]
I am trying to build my componet library using rollup. I can assure that my storybook is working fine and getting all styles from tailwind. However on bundling and using the button I can't see any stlyes applied. Althoug on inspecting the styles are written there.

My rollupConfig:
```
const resolve = require("@rollup/plugin-node-resolve");
const commonjs = require("@rollup/plugin-commonjs");
const typescript = require("@rollup/plugin-typescript");
const dts = require("rollup-plugin-dts");
const postcss = require("rollup-plugin-postcss");
const tailwindcss = require("tailwindcss")
const tailwindConfig = require("./tailwind.config")

const packageJson = require("./package.json");

module.exports = [
  {
    input: "src/index.ts",
    external: ['react-dom','css'],
    output: [
      {
        file: packageJson.main,
        format: "cjs",
        sourcemap: true,
      }
    ],
    plugins: [
      resolve(),
      commonjs(),
      typescript({ tsconfig: "./tsconfig.json" }),
      postcss({
        extract: 'tailwind.css', 
        extends:['.css'], 
        module:false,
        minimize: true,
        inject: {
          insertAt: 'top',
        },
        plugins: [
          tailwindcss(tailwindConfig),
          require('autoprefixer'), // Assuming you're using Autoprefixer
        ],
      }),
    ],
  },
  {
    input: "dist/types/src/index.d.ts",
    output: [{ file: "dist/index.d.ts", format: "cjs" }],
    plugins: [dts.default()],
    external: [/\.css$/],
  },
];
```

My index.ts:
```
import './tailwind.css'

export * from './components/ui/index'
```

Can someone please help?

**Comment by SySagar** [comment]
> I solved this in the past couple days by finding the root index.js file that is getting rolled up by rollup, such as where it transforms `./src/index.js` into `./dist/index.js`:
> 
> **./src/index.js** (root of bundle, ie: similar to the main.js file in a Vue application)
> 
> ```
> import './assets/css/index.css';
> ```
> 
> **./assets/css/index.css**
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> .test-fart {
>     background-color: orange;
>     color: brown;
> }
> ```
> 
> **./rollup.config.js**
> 
> ```
> import postcss from 'rollup-plugin-postcss';
> import tailwindcss from 'tailwindcss';
> 
> const tailwindConfig = require('./tailwind.config.js');
> 
> ...
> 
>             plugins: [
>                 postcss({
>                     extensions: ['.css'],
>                     plugins: [tailwindcss(tailwindConfig)],
>                 }),
>             ]
>         },
> ```
> 
> After that you can add your package.json scripts for dev: `rollup -c --watch` and prod: `rollup -c`

Yes this work. But it shoul naturally import the css files rather than manually updating it in build files.

**Comment by rahul-vyas-dev** [comment]
I am facing the same issue.

I am building a npm package using roll-up, tailwind v4.x.x. But building with roll-up and using postcss as a plugin, which only can compile tailwind v3, can not compile if v>3.x. 

After building, I used in my project (nextJs project) which have tailwind v3, it is showing issue: - `../SupportUsButton/dist/style.css:2:993 Syntax error: C:\Users\rahul\PRG\SupportUsButton\dist\style.css @layer base is used but no matching @tailwind base directive is present.`
