### ISSUE TITLE
Issue using @apply with Nuxt.js 

### ISSUE THREAD

**Issue by bangjelkoski** [tailwindcss/tailwindcss#794]
I have upgraded to the newest beta version and there is an issue with compiling css on a Nuxt.js project. 

I have this line in the `nuxt.config.js`: `css: ['~/assets/css/app.scss']`.

Here is the tailwind.config.js file I use: [tailwind.config.js](https://gist.github.com/bangjelkoski/2d26df23b1f7c32333c79f5230502186)

Here is the postcss.config.js I use: [postcss.config.js](https://gist.github.com/bangjelkoski/c01c6567aa4a7fcfb0ad7ce4b2fd73ac)

Here is the app.scss that should be compiled: [app.scss](https://gist.github.com/bangjelkoski/cad2d84b5ce6b2f9da8d595c0a0b4872)

Here is the _buttons.scss where the issue happens:
```css
.btn {
    @apply px-6 py-2 rounded-sm inline-block text-white text-2xs no-underline;
}
```
I get this error: `"@apply" cannot be used with ".px-6" because ".px-6" either cannot be found ... `. 

**This wasnt the case before upgrading, so it must be an issue with the newest release.**

Thanks for your work on this amazing library Adam!

**Comment by adamwathan** [comment]
Not sure what the issue is, can you share the whole project?

Here is a Nuxt project with v1.0.0-beta.3 installed that worked as expected:

https://github.com/adamwathan/tailwind-1-nuxt-test

**Comment by bangjelkoski** [comment]
okay, so I found the issue. Instead of using padding: `theme => theme('spacing');` I was using `padding: theme => theme.spacing;` because the old `defaultConfig.js` was referenced in the upgrade guide when I did the migration.

Sorry for the inconvenience Adam, you can close the issue now.

**Comment by bdrtsky** [comment]
I have soimiliar issue. What is `padding: theme => theme.spacing`? I need to write this manually in config? What config do I need? Upgrade guide is so obscure.

**Comment by bangjelkoski** [comment]
@bdrtsky the `padding: theme => theme.spacing` was used in the config for the 1.0.0 beta1 version, but it changed to `theme => theme('spacing');` in the latter version, which is why I had the issue, so I changed the values where the same issue was and then it worked. You should just follow the newest config values and change to reflect your needs.

**Comment by bdrtsky** [comment]
ok, then what is `theme => theme('spacing');`. I have to writeit in config myself? Why do I needd it if this is default setting.

**Comment by bangjelkoski** [comment]
This is the case when you use your own custom config. I would suggest you copy the default config and then edit the values to fit your needs. Here is the default config for the latest version [defaultConfig.stub.js](https://github.com/tailwindcss/tailwindcss/blob/v1.0.0-beta.4/stubs/defaultConfig.stub.js)

**Comment by adamwathan** [comment]
> ok, then what is theme => theme('spacing');

https://next.tailwindcss.com/docs/theme#referencing-other-values

>  I have to writeit in config myself? Why do I needd it if this is default setting.

If you are upgrading an old config file to the new config file, then yes you have to type the new defaults yourself. We are working on a tool to automatically upgrade people's config files but it's not quite ready.

> Upgrade guide is so obscure.

Can you show me a section that is unclear? I spent probably 30 hours writing it and making sure it walks through every single character you need to type step-by-step, so if you just read it and make the changes as you go it should go fairly smoothly.
