### ISSUE TITLE
[Feature Request] Consider adding/modifying prefix selector option to increase specificity of generated utilities.

### ISSUE THREAD

**Issue by iainhenderson** [tailwindcss/tailwindcss#797]
We add a fair amount of "default" element styling using element and attribute selectors, like so:

```
input[type="text"], input[type="password"], input[type="email"] {
    @apply py-2 px-4;
}
``` 

or

```
table td {
    @apply py-2 px-4;
}
```

The issue with adding default styling like this is that it makes it impossible to override it later with utilities, as two element selectors, or an element plus attribute selector is higher specificity than Tailwinds generated utilities.

I know it's already possible to add !important to all generated utilities, but this can cause a number of problems, especially with JS animation libraries which try to override appearance by adding inline styles without !importants.

Would it be possible to add a config option (or modify the existing prefix option) to let authors specify a selector to increase the specificity of the generated utilities? Example: If someone specified the utility prefix selector as `html body#coolwebsite` all generated utilities would look like:

```
html body#coolwebsite .pl-4 {
    padding-left: 16px;
}

```

This would allow people jack up the specificity of all generated utilities without relying on !important rules which can cause problems with other libraries.

On the downside, I understand that implementing this option could encourage some authors to write nested components and create specificity battles for themselves.

EDIT: I have tried using the existing 'prefix' config option to accomplish this, but Tailwind performs some formatting on the prefix which breaks it for this use case. i.e. Tailwind prefixes a '.' and escapes spaces in the selector.

I think we could make the prefix option work for this use case with some minimal changes, although it could break existing prefix options as authors may have to to add a "." to the start of their prefix options e.g. `prefix: ".tw-"` instead of `prefix: "tw-"`

**Comment by benface** [comment]
I would love to see something like this. In fact, I already do it on all my Tailwind projects with the [postcss-prepend-selector](https://github.com/ledniy/postcss-prepend-selector) plugin, which I constrain to the utilities using the [postcss-partial-process](https://github.com/benface/postcss-partial-process) plugin, which I wrote expressly for this. Here's what it looks like:

#### PostCSS config

```
const tailwindcss = require('tailwindcss');
const partialProcess = require('postcss-partial-process');
const prependSelector = require('postcss-prepend-selector');
```
```
[
  tailwindcss('./tailwind.js'),
  partialProcess({
    plugins: [
      prependSelector({ selector: '#a ' }),
    ],
  }),
]
```

#### CSS

```
@tailwind preflight;

@tailwind components;

/* start postcss-partial-process */

@tailwind utilities;

/* end postcss-partial-process */
```

And then all I have to do is put the `a` ID on the `html` tag, and it works perfectly. You could use a class instead of an ID, of course, but I wanted something that would 100% override ANY component or base style selector.

It's slightly annoying to require `postcss-prepend-selector` and `postcss-partial-process` in every project though, so I would love to see this in the core, even if it might seem a little "hackish". It has two main benefits over the `important` option:

1. `!important` rules override inline styles, which is rarely desirable, especially when working with JS animation libraries like @iainhenderson said.
2. If the prefix is short enough (like I do with `#a`), the resulting CSS is smaller.

**Comment by adamwathan** [comment]
I think this is a valid request but I can't think of a way to add it that doesn't feel sort of sloppy or hacky. 

I'd rather it use a new config key like `utilityScope` or something but having to document that people need to add an ID to their `html` tag or something just feels untidy. Willing to hear out any ideas if anyone has suggestions on how to support this in a way that feels really clean.

**Comment by benface** [comment]
> I'd rather it use a new config key like utilityScope or something but having to document that people need to add an ID to their html tag or something just feels untidy.

I think by calling it scope it makes total sense to have to add an ID or a class to *some element* in the HTML (doesn't have to be the `html` element, it could be placed wherever Tailwind utilities are used to prevent conflicts with other classes when adding Tailwind to an existing project).

**Comment by pxwee5** [comment]
Don't mind adding the id myself to make TW classes have specificity of 1 1 0. This is very much an advanced feature where people have to understand css specificity first in order to justify the use. 

IMO This is so much cleaner compared to !important. Smaller too in size too if we use a short #id.

**Comment by hacknug** [comment]
@pxwee5 no need to worry about how long that string is since compression will make that difference negligible in any way.

**Comment by adamwathan** [comment]
I think I'd like to add this feature for power users but probably just bake it into the `important` option, where if you specify a string instead of true/false, it'll scope the utilities:

```js
module.exports = {
  important: '#app',
}
```

Sort of unintuitive maybe but since the goal is the same it seems like a reasonable place to sneak this feature in. My only concern is that it will break `@apply`, so it might take a bit of work to implement this in a way that keeps that working.

**Comment by leeshadle** [comment]
@adamwathan some sort of scoping would be helpful.

I build a lot of blocks for the new WordPress block editor using tailwindcss.  I need to scope tailwindcss so it only applies to specific blocks, or specific parts of the page, without impacting a WordPress theme's global styling.  

I tried using postcss-nested like so:
```
 [class*="wp-block-custom-class"] {

	@tailwind components;

	@tailwind utilities;

} 
```

It would apply to everything but the responsive tailwindcss utilities:
```
/* applies to all non-responsive utilities */
[class*="wp-block-custom-class"] .duration-500 {
    -webkit-transition-duration: 500ms;
            transition-duration: 500ms
  }

[class*="wp-block-custom-class"] .duration-700 {
    -webkit-transition-duration: 700ms;
            transition-duration: 700ms
  }

[class*="wp-block-custom-class"] .duration-1000 {
    -webkit-transition-duration: 1000ms;
            transition-duration: 1000ms
  }

/* doesn't apply to responsive utilities */
@media (min-width: 640px) {
  .sm\:sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0
  }

  .sm\:not-sr-only {
    position: static;
    width: auto;
    height: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    clip: auto;
    white-space: normal
  }
}
...

```

@benface solution of using 'postcss-prepend-selector' did the trick:

```
// postcss.config.js file
const postcssPrependSelector = require( 'postcss-prepend-selector' )( {
	selector: '[class*="wp-block-custom-class"] '
});
```

Generated css:
```
[class*="wp-block-custom-class"] .duration-500 {
  -webkit-transition-duration: 500ms;
          transition-duration: 500ms
}

[class*="wp-block-custom-class"] .duration-700 {
  -webkit-transition-duration: 700ms;
          transition-duration: 700ms
}

[class*="wp-block-custom-class"] .duration-1000 {
  -webkit-transition-duration: 1000ms;
          transition-duration: 1000ms
}

@media (min-width: 640px) {
  [class*="wp-block-custom-class"] .sm\:sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0
  }

  [class*="wp-block-custom-class"] .sm\:not-sr-only {
    position: static;
    width: auto;
    height: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    clip: auto;
    white-space: normal
  }
}
```

**Comment by hamfz** [comment]
I would also like to see support for something similar, obviously this is more of a PostCSS than Tailwind thing, but could make adoption useful for places trying to use Tailwind to get rid of legacy assets/older stuff. In our case we needed to apply this prepend selector solution around all of the imports, including the base/preflight

**Comment by tsuz** [comment]
Thanks @benface your comment here https://github.com/tailwindlabs/tailwindcss/issues/797#issuecomment-475754646 gave me some directions to work with!

I ended up creating the outmost container and only the elements within the container would use the CSS from the `preflight`, for example, `button` styling. I ended up replacing Tailwindcss with PostCSS and used `postcss-prefix-selector` instead. 


**postcss.config.js**


```

const prefixSelector = require('postcss-prefix-selector');

module.exports = {
    plugins: [
        require('tailwindcss'),
        prefixSelector({
            prefix: '#kaitaku-feedback-ui ',
            exclude: [
                /\[/, // starts with [ (e.g. [role])
            ],

            // Optional transform callback for case-by-case overrides
            transform: function (prefix, selector, prefixedSelector) {
                console.log("Prefix:", prefix, ", selector:", selector, ", prefixedSelector:", prefixSelector)

                // mainly for applying font
                if (selector === 'html') {
                    return prefix + "*"
                }

                // root identifier
                if (selector === '#kaitaku-feedback-ui') {
                    return '#kaitaku-feedback-ui'
                }

                return prefix + selector;
            }
        }),
    ]
}
```

**Comment by bdkoder** [comment]
> I think I'd like to add this feature for power users but probably just bake it into the `important` option, where if you specify a string instead of true/false, it'll scope the utilities:
> 
> ```js
> module.exports = {
>   important: '#app',
> }
> ```
> 
> Sort of unintuitive maybe but since the goal is the same it seems like a reasonable place to sneak this feature in. My only concern is that it will break `@apply`, so it might take a bit of work to implement this in a way that keeps that working.

**Thank you Very Much. It's saved my time.**
