### ISSUE TITLE
Update the simpleConfig.stub.js

### ISSUE THREAD

**Issue by MattStypa** [tailwindcss/tailwindcss#799]
This is just a reminder to update the "useful comments" to actually useful comments.

```js
module.exports = {
  theme: {
    // Some useful comment
  },
  variants: {
    // Some useful comment
  },
  plugins: [
    // Some useful comment
  ]
}
```

**Comment by adamwathan** [comment]
Just going to remove these for now as I don't have any grand ideas of what to include here 😅
