### ISSUE TITLE
Beta Upgrade Guide Suggestion

### ISSUE THREAD

**Issue by tance77** [tailwindcss/tailwindcss#801]
Upgrade Guide currently has

> Replace .pin-{side} with .{top|left|bottom|right|inset}-{side}-{value}

I think this should be

Replace .pin-{side} with .{top|left|bottom|right|inset}-{value}

or

Replace .pin-{side} with .{side}-{value}

I found the original format confusing and I was doing things like top-top-0 instead of top-0

**Comment by adamwathan** [comment]
Ah thanks, just fixed it!
