### ISSUE TITLE
[Feature Request] Module for CSS variable setter classes

### ISSUE THREAD

**Issue by hdodov** [tailwindcss/tailwindcss#806]
My use case is a bunch of boxes that should have their own themes. I have 4 colors and each box is assigned one of them. Some text, borders, and backgrounds inside should use that box's color.

I should obviously use CSS variables, so I've defined a new color in my Tailwind config:
```js
theme: {
  colors: {
    var: 'var(--color)',
    ...
  }
}
```

So now, if I add a class `text-var` or `bg-var`, the element would be styled according to the variable. The only problem now is setting the variable.

I could do:
```sass
.var-color-pink {
  --color: #fabfab;
}
```

and it would work, but it can get quite hard to maintain if I need it to work with a lot of colors. Even worse is the fact that I can't use Tailwind variables inside my CSS file, as [other people have discussed](https://github.com/tailwindcss/discuss/issues/72), so I would have to sync my config and my CSS file.

### So here's where this feature comes in!

With this module, I could specify a `variables` object in my config:

```js
theme: {
  variables: theme => {
    return {
      color: {
        pink: theme('colors.pink'),
        green: theme('colors.green')
      },
      // or to generate classes for all colors:
      // color: theme('colors')
      somevar: {
        base: '50px'
      }
    }
  }
}
```

and it would generate:

```css
.var\:color-pink {
  --color: #fabfab;
}

.var\:color-green {
  --color: #66cc99;
}

.var\:somevar-base {
  --somevar: 50px;
}
```

So now in my markup, I could use everything like that:

```html
<div class="var:color-pink">
  <h1 class="text-black">this is black</h1>
  <span class="text-var">but this is colored</span>

  <hr class="border-var">

  <div class="bg-var">
    <p class="text-white">
      variable colored box with white text
    </p>
  </div>
</div>
```

Whenever I need to use the variable, I add the `var` version of each class. If I need to change the theme of the box, I simply change the `var:color-pink` class of the topmost parent and that's it.

You could do all sorts of things with that! Would be an awesome feature!!!

**Comment by hdodov** [comment]
If this gets implemented, you could do all sorts of clever stuff and easily manage multiple variables. For example, in your config:

```js
theme: {
  colors: {
    white: '#fff'
    pink: '#fabfab',
    green: '#66cc99',
    '-color1': 'var(--color1)',
    '-color2': 'var(--color2)'
  },
  variables: theme => {
    return {
      color1: theme('colors'),
      color2: theme('colors')
    }
  }
}
```

So now, `var:color1-pink` would set the variable and `text--color1` would use it:

```html
<div class="var:color1-pink var:color2-green">
  <p class="text-white">some boring white text</p>
  <p class="text--color1">whoa, that's pink</p>
  <p class="text--color2">whoa, that's green</p>

  <div class="var:color2-pink">
    <p class="text--color2">
      due to inheritance, that's pink too now
    </p>
  </div>
</div>
```

You could juggle variables all over the place and everything would be controlled from the config file!

**Comment by adamwathan** [comment]
This is a cool idea! I think to start it would be best to build this as a third-party plugin and if it's something a lot of people wish was in core then we can explore adding it directly 👍 

Going to close this as "no concrete plans to implement right now" but would definitely be interested in playing with it as a plugin.
