### ISSUE TITLE
Border-color issue In Tailwind 1.0

### ISSUE THREAD

**Issue by mccombs** [tailwindcss/tailwindcss#808]
Looks like there is an issue with Border-color Tailwind 1.0

If I do `@apply border-orange` It returns

``@apply` cannot be used with `.border-orange` because `.border-orange` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.border-orange` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.`

As if it does not default to the 300 orange like it does for text-{color}

However `@apply border-orange-300` OR `@apply border-oranged;` (when a custom color specified) **does** work.

**Comment by tlgreg** [comment]
There is no `border-orange` it shouldn't work for `text-{color}` either, unless you configured for `textColor`.
It was intentional to not have a "default" for colors. The special cases are black, white and transparent for obvious reasons.

**Comment by adamwathan** [comment]
Yep @tlgreg is right, `border-orange` doesn't exist and neither does `text-orange`.

Can see the default set of generated utilities here to be sure:

https://unpkg.com/tailwindcss@1.0.0-beta.3/dist/utilities.css
