### ISSUE TITLE
How to config default hover style?

### ISSUE THREAD

**Issue by vincent-lu** [tailwindcss/tailwindcss#811]
Hi I'm trying to override the default hover style on `<a>` where it applies a 1px bottom border. I know you can define hover variants by using `hover:text-blue-darker` but is there a way to disable the default 1px bottom border from tailwind's config?

Thanks.

**Comment by jeroengerits** [comment]
```
border-transparent
```

**Comment by vincent-lu** [comment]
Thanks @jeroengerits. Is there a way to define without border for hovered links as default style in tailwind's config?

**Comment by jeroengerits** [comment]
you have ```border-0``` or ```no-underline```...  not sure what you are referring to

**Comment by vincent-lu** [comment]
Sorry I'm new to tailwind; what I'm trying to do is to remove the border settings on `a` tag by default.

I'm assuming there is a way to do this by setting it in https://tailwindcss.com/docs/configuration file.

**Comment by vincent-lu** [comment]
Thanks for the help @jeroengerits I figured it out. I was using roots/sage's tailwind and it has a _global.scss file that defined this style I was trying to override.
