### ISSUE TITLE
Feature: support RTL direction 

### ISSUE THREAD

**Issue by ghost** [tailwindcss/tailwindcss#815]

**Comment by Rux77** [comment]
@RonMelkhior have solved this issue in an interesting way:
https://github.com/RonMelkhior/tailwindcss-dir

Shouldn't such a feature be added to the official package, rather leaving to the user land?

**Comment by adamwathan** [comment]
I'm not opposed to adding this to core at all and definitely like the solution in that plugin. I have no experience building RTL websites so I'm probably not the best person to lead or maintain this feature right now though, so I think pointing people to that plugin is the best option right now.

Going to close this as "no concrete plans to implement right now" but can definitely revisit in the future.

**Comment by lijoantony** [comment]
https://www.npmjs.com/package/tailwindcss-rtl
