### ISSUE TITLE
@screen in 1.0b4 not working

### ISSUE THREAD

**Issue by jaddison** [tailwindcss/tailwindcss#816]
Either I'm really tired or I simply don't know how to use the `@screen` function appropriately; my code (`postcss-nested`):
```
.jumbotron {
  /* ... other stuff */
  .body {
    @apply text-2xl;
    @apply mx-auto;
    width: 100%;
    @screen md{
      width: 60%;
    }
  }
}
```

The above does not set the media query up correctly, here is the result in Chrome DevTools:
```
.jumbotron .body {
    font-size: 1.5rem;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    @media (min-width: 768px) {;
    width: 60%;
    }: ;
}
```
Screenshot of same as well:
![Screen Shot 2019-04-01 at 8 24 33 PM](https://user-images.githubusercontent.com/101148/55374113-3158d180-54bc-11e9-83ea-6c194a0dac59.png)

webpack.config.js `module.rules` relevant setting:
```
{
    test: /\.(sa|sc|c)ss$/i,
    use: [
        devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
        {
            loader: 'css-loader',
            options: {
                // 0 => no loaders (default); 1 => postcss-loader; 2 => postcss-loader, sass-loader
                importLoaders: 1
            }
        },
        'postcss-loader'
    ]
}
```
postcss.config.js settings:
```
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-nested'),
    require('postcss-import'),
    require('tailwindcss'),
  ]
}
```

**Note that `@media (min-width: 768px)` works fine.**

**Comment by tlgreg** [comment]
Does this help?
```diff
-     require('postcss-nested'),
+     require('postcss-nested')({ bubble: ['screen'] }),
```

**Comment by jaddison** [comment]
Yes, that helps. Is this by design, that I should need to add this? Or should `postcss-nested` work with `@screen` properly without this kind of intervention?

Thanks!

**Comment by tlgreg** [comment]
It's not an issue, `postcss-nested` only bubles only `@media` and `@support` by default, any custom at-functions you'll need to configure like so.

**Comment by adamwathan** [comment]
Everything will work without the bubble stuff if you tweak your plugin order:

```js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('postcss-nested'),
    require('autoprefixer'),
  ]
}
```

**Comment by jaddison** [comment]
Confirmed - all is well and working. Thanks for helping a newb out!
