### ISSUE TITLE
Idea for multiple sane textSizes defaults

### ISSUE THREAD

**Issue by jeroengerits** [tailwindcss/tailwindcss#828]
Tailwind is a great utility framework and it makes it very easy to change default textSizes globally, however I personally feel its would be a nice addition to include (out of the box) a range of popular defaults as text sizes. 

A website like https://type-scale.com/ shows a bunch of text size schemes that are oftenly used.. 

i can imagine something like this in the config
```
textSizes: perfectFourth
```

which then would translate to the tailwind naming 'text-xl', 'text-base', etc. 

![1](https://user-images.githubusercontent.com/808734/55520365-48462200-567c-11e9-91bf-c4d762b08b01.PNG)

![Capture](https://user-images.githubusercontent.com/808734/55521669-fbfde080-5681-11e9-9019-9c97df6ec0db.PNG)

![Capture2](https://user-images.githubusercontent.com/808734/55521733-43846c80-5682-11e9-8b5b-c5c7c2cb4631.PNG)

**Resources to check**

- https://type-scale.com/
- https://www.modularscale.com/

**Comment by adamwathan** [comment]
Hey @Jeroen-G thanks for the suggestion! For now we are just going to stick with our existing type scale, I have tried using things like modularscale.com in the past and at least for application UIs I haven't liked the results. You could easily use a scale like this in your own project though, and could even create a little package if you wanted to make it easy for others to use.
