### ISSUE TITLE
Can't easily get values from config after 1.0.0

### ISSUE THREAD

**Issue by davecalnan** [tailwindcss/tailwindcss#832]
# Background
Sometimes I like to import my Tailwind config and use the values from it to ensure consistency across the board. One example would be media queries using Tailwind screen sizes when using `styled-components`:
```js
import tailwind from '../../tailwind'
// ...
export default styled(Component)`
// some css...
@media screen and (min-width: ${tailwind.screens.md}) {
  // more css...
}
`
```
# Problem
With the new 1.0 approach to merging the user config with the default config, it's not as simple as single import within the project. The configs have to have their function keys resolved and then be merged.
# Solution
So I made a little package using [`resolveConfig()`](https://github.com/tailwindcss/tailwindcss/blob/next/src/util/resolveConfig.js) under the hood to merge and resolve the user's config with the default config.

You can use it like:
```js
import tailwind from 'tailwind-config'

const { theme, variants, ...etc } = tailwind.config('./path/to/tailwind.config')
/* or */
const { colors, screens, spacing, ...etc } = tailwind.theme({ ...configObject })
```

Here's the package: [davecalnan/tailwind-config](https://github.com/davecalnan/tailwind-config)

# Include this in `tailwindcss`?
This could be added as a first-party feature with some sort of API like:

```js
import { config } from 'tailwindcss'

const { theme, ...etc} = config('./path/to/tailwind.config')
```

Any thoughts? If it seems like a worthwhile addition I'd be happy to make the PR @adamwathan /@reinink. Otherwise I'll just leave it as the `tailwind-config` package as an opt-in for anyone who would like to use it.

**Comment by saintplay** [comment]
This is keeping us from upgrade to version 1.0.

The import method before 1.0

```js
import tailwind from '../../tailwind'
```

was very simple and straightforward.

```js
import { config } from 'tailwindcss'

const { theme, ...etc} = config('./path/to/tailwind.config')
```

I think the path for the config file should be specified only one time

**Comment by davecalnan** [comment]
> ```js
> import { config } from 'tailwindcss'
> 
> const { theme, ...etc} = config('./path/to/tailwind.config')
> ```
> I think the path for the config file should be specified only one time

Just to be clear, the above code sample is a suggestion for how things might work in a *future* version of Tailwind. It won't work if you run it as it doesn't currently exist.

---

If you are using a version of Tailwind >= 1.0.0 and want to access values from the resolved config, you can use the package I mentioned to easily do that.

```
npm install tailwind-config
```

```js
import tailwind from 'tailwind-config'
const config = tailwind.config('../../tailwind')
```

Bear in mind this is a separate package to `tailwindcss`. Full usage guide on the package [documentation](https://github.com/davecalnan/tailwind-config#usage).

Does that help clear things up at all?

**Comment by saintplay** [comment]
Yes, thanks for creating this package

**Comment by brasilikum** [comment]
For use outside of js it would also be useful to me if it would spit out a json.
maybe `tailwind export-config`

**Comment by dobromir-hristov** [comment]
@brasilikum https://github.com/dobromir-hristov/tailwindcss-export-config/ already exports to CSS preprocessors, I could also add a JSON output too. 

I am going to use @davecalnan package, until we have something official to resolve the configs.

**Comment by adamwathan** [comment]
Thinking about this a bit today, one of the things that was annoying in 0.x was that if you import your whole `tailwind.js` file into your JS, you end up with a bunch of stuff in your front end bundle that you might not actually need, like any of your Tailwind plugins for example since they are `require`'d in your config file.

For that reason, it feels like the safest way to reference your Tailwind config in JS is to split your `theme` section into a separate file so you can import it without carrying around any other dependency baggage.

Or alternatively, we could make it possible to register plugins in your Tailwind config without actually using a `require` statement, so that you can import your config elsewhere without those dependencies actually being resolved, sort of like how you can do it in a `postcss.config.js` file — basically just making the file a static object with no dependencies, even if you are pulling in plugins.

Either way we would probably expose our `resolveConfig` function as public API so people could get the final values.

Anyone have any other ideas on the best way to make this possible while not forcing people to bundle build dependencies into the JS they serve to the client?

**Comment by mikemand** [comment]
> For that reason, it feels like the safest way to reference your Tailwind config in JS is to split your theme section into a separate file so you can import it without carrying around any other dependency baggage.

While that would work if you were to copy the entirety of Tailwind's colors and your custom colors to said separate file, what about if you're only using the `extends` part of the config to add your custom colors (or sizes or spaces, etc.)?

**Comment by llaski** [comment]
+1 for exposing the resolveConfig or another function publicly to get the config object. Couple of use cases I'm running into are wanting access to theme values such as colors and screen sizes in React components dealing with charts and css in js where I'm unable to use classes or variants.

**Comment by davecalnan** [comment]
I haven't personally had the need to reference anything in my Tailwind config that wouldn't be in the final resolved config object so I'm not sure what people might be looking for there.

I agree exporting resolveConfig or a helper function would be great. That's what I did in the small package I made ([davecalnan/tailwind-config](https://github.com/davecalnan/tailwind-config)) and I like the api.

Enabling usage like:
```js
import { config } from 'tailwindcss'

const config = config('path/to/config')
/* or */
const config = config({ ...importedConfigObject })
```

Giving you a plain JS object to get your keys from solves all my use cases I've come across, is straightforward to explain, and requires minimal changes to the framework. I'd be happy to make the pull request and make my package irrelevant!

**Comment by adamwathan** [comment]
PR'd a basic implementation of this:

https://github.com/tailwindcss/tailwindcss/pull/877

Likely will add support for a require-less `plugins` key syntax to make it "safe" to import your config in your front end bundle without carrying a bunch of unneeded dependencies but can come after 1.0, not really a big deal.

**Comment by adamwathan** [comment]
Merged that PR so this will be possible in the next beta.

**Comment by saintplay** [comment]
Is this available in v1.0.0-beta.7?

**Comment by mikemand** [comment]
It was available with v1.0.0-beta.6, but I would suggest beta.7 because of the bug extending the margins.

**Comment by thiagorossener** [comment]
Like @adamwathan, I noticed that using the recommended `resolveConfig` was adding ~200kb into my bundled file. 

I just needed the breakpoints used by Tailwind, so what I did was creating a Gulp task to generate a `breakpoints.json` file and then use only that in my JS.

If anyone end up here looking for a way to improve their bundle file size, here is my task:

```
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from './tailwind.config';
import fs from 'fs';

function breakpoints(done) {
  let json = {};

  const fullConfig = resolveConfig(tailwindConfig);

  Object.keys(fullConfig.theme.screens).forEach(key => json[key] = parseInt(fullConfig.theme.screens[key]));

  fs.writeFile(`${paths.src}/breakpoints.json`, JSON.stringify(json), done);
}
```

BTW, I'm using [Gulp 4 with ES6](https://hisk.io/using-gulp-4-with-es6-babel/), so all of this is in a `gulpfile.babel.js`.

**Comment by laygir** [comment]
I am having similar bundle issues due to resolveConfig usage. Is there already a plugin that helps with this situation?  👀 

> Likely will add support for a require-less `plugins` key syntax to make it "safe" to import your config in your front end bundle without carrying a bunch of unneeded dependencies but can come after 1.0, not really a big deal.

**Comment by danimalweb** [comment]
I just removed `resolveConfig ` due to size and I only need the screens part of the object.

Is there an easy way to only parse out the object that you want?
