### ISSUE TITLE
Ability to disable all core plugins (corePlugins: false?)

### ISSUE THREAD

**Issue by benface** [tailwindcss/tailwindcss#833]
As discussed on Discord, it would be useful to be able to disable all core plugins without explicitly listing them all, for instance when using Tailwind in a test suite for a plugin. Adam suggested `corePlugins: false`.

**Comment by ernsheong** [comment]
Looking for this as well! I use Tailwind to generate mini util files for use in Shadow DOM.

**Comment by adamwathan** [comment]
Added for 1.0 👍 Would be open to some sort of whitelisting option as well, feel free to start another issue about that if you like.
