### ISSUE TITLE
Hide element on mobile (sm)

### ISSUE THREAD

**Issue by ahinkle** [tailwindcss/tailwindcss#841]
Hey,

I'm unable to hide an element on mobile `sm`. The element should appear once the it reaches `md` but hidden within `sm`.  I've tried the following:

```
<div class="sm:hidden md:block">
     // my content
</div>
```
Using the classes above, the class shows on mobile but is hidden once we reach `md`.

I feel like I used to be able to do this before -- was the syntax changed?

**Comment by tlgreg** [comment]
Tailwind is mobile first, `sm` is `576px` and above (`640px` in `v1`), if you want to make it hidden below `md`, it should be just `<div class="hidden sm:block">`

**Comment by ahinkle** [comment]
Ah perfect. Thanks!

**Comment by tonysnowboardunderthebridge** [comment]
Hello, 

first time that I post something under a closed issue, hope that I'm reporting in the good way.

below the code that I create for purpose

```
<p class="border border-solid text-center border-black md:border-red-berry">Border</p>
<p class="border border-solid text-center hidden md:block">Display</p>
```

the paragraph related to the change on border color, works perfectly, instead I had problem on the display paragraph. there is something wrong on my code or the display is an edge case?

Regards
Antonio

**Comment by tlgreg** [comment]
The above code does work for me as expected.
What is the intended behavior?

**Comment by tonysnowboardunderthebridge** [comment]
> The above code does work for me as expected.
> What is the intended behavior?
> 
> ps.: In the future, opening a discussion here on github or joining the tailwindcss discord would be better for questions though.

Sorry, my fault. I apologize for the inconvenience.

What should I do, if I will have questions on tailwind? I create a discussion?

**Comment by tlgreg** [comment]
Not that big of a problem but opening a new discussion is better.
Also if you use discord, tailwindcss has a server:
https://tailwindcss.com/discord

**Comment by u007** [comment]
if you wish todo the opposite, only show on xs

```
<div className="visible sm:hidden mt-4"></div>
```

**Comment by rameezmeans** [comment]
this is the right way sir. 

class="block sm:hidden xs:hidden"

**Comment by manishchauhan8429** [comment]
> Hey,
> 
> I'm unable to hide an element on mobile `sm`. The element should appear once the it reaches `md` but hidden within `sm`. I've tried the following:
> 
> ```
> <div class="sm:hidden md:block">
>      // my content
> </div>
> ```
> 
> Using the classes above, the class shows on mobile but is hidden once we reach `md`.
> 
> I feel like I used to be able to do this before -- was the syntax changed?

thanks you

**Comment by beesou777** [comment]
really thanks helped since i am learning tailwind just now

**Comment by DaMayorG** [comment]
thank you @tlgreg I tried this 
<div class="hidden md:block">
     // my content
</div>

and it worked for the button I was trying to hide on small screen but wanted it to be visible on other screens. Thank you
