### ISSUE TITLE
Feature Request: float-end and float-start

### ISSUE THREAD

**Issue by AdelDima** [tailwindcss/tailwindcss#843]
Hello all,

What about if you have `.float-start` and `.float-end` rather than `.float-left` and `.float-right`

and will change depending on the direction, we can apply it on all left/right classes like text-left and clear-left ...

For me that what I'm using on SCSS.

```scss
.float-start {
    @include float-start();
}

.float-end {
    @include float-end();
} 
```
on the configuration file, it may be a good idea to add the direction RTL/LTR or both, both mean that we got two files `styles.css` and `styles-rtl.css`

Thank You!

**Comment by adamwathan** [comment]
Not planning to make this change but definitely something we'd want to support in some way as part of some RTL feature one day.

We would most likely do something based on this approach:

https://github.com/RonMelkhior/tailwindcss-dir
