### ISSUE TITLE
Add aliases for text classes to improve searchability

### ISSUE THREAD

**Issue by rightaway** [tailwindcss/tailwindcss#844]
After using tailwind heavily I've realized that it gets confusing when searching throughout the project for `text-` when trying to customize text or fonts. Searching `text-` shows alignment, sizes, and colors. So there's a lot of extra stuff to sort through when you're trying to go through the whole project looking at some particular item (such as trying to improve colors throughout the project or trying to standardize sizes). In a large project these strings could appear thousands of times which gets quite difficult to manage.

If we could have an alias like `color-` for text color properties related to color then only color classes would appear. Or `size-` for text size properties. If I want to search for colors now I have to search for all possible colors and there are a lot of them.

**Comment by adamwathan** [comment]
Hey thanks for the suggestion! I don't really want to add multiple names for classes — I'd rather there just be one way to do each thing. I also don't want to make any more backwards compatibility breaks right now so going to keep the names as they are. Appreciate your input though!
