### ISSUE TITLE
[1.0.0]  @apply cannot be used with .text-white because .text-white cannot be found

### ISSUE THREAD

**Issue by dotnetCarpenter** [tailwindcss/tailwindcss#863]
I've just updated from tailwindcss 0.7.4 to 1.0.0-beta.5 and followed the [upgrade guide](https://github.com/tailwindcss/tailwindcss/releases/v1.0.0-beta.1#update-tailwind).

I have a simple button component where I use tailwindcss's `@apply` and have removed any styles from ~`tailwind.js`~ `tailwind.config.js` that I'm not changing, but now I get the following error:

>@apply cannot be used with .text-white because .text-white either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that .text-white exists, make sure that any @import statements are being properly processed *before* Tailwind CSS sees your CSS, as @apply can only be used for classes in the same CSS tree.

According to the [docs for beta, `.text-white` is still here](https://next.tailwindcss.com/docs/text-color/#class-reference).

**Is it a documentation issue, a bug or me?**

*button.css*:
```css
.button {
  @apply
    inline-block
    border
    border-solid
    rounded
    py-2
    px-5
    ml-4
    mt-4
    no-underline;
  }
.button--green {
  @apply
    border-green-darker
    text-green-darker;
}
.button--green:hover
{
  @apply
    text-white
    bg-green-darker;
}
.button--grey
{
  @apply
    border-grey-darker
    text-grey-darker;
}
.button--grey:hover
{
  @apply
    text-white
    bg-grey-darker;
}
```

*tailwind.config.js*:
```js
module.exports = {
  theme: {
    colors: {
      'transparent': 'transparent',
      'sk-green': '#5D7F57',
      'sk-green-dark': '#304325',

      'black': '#231F20',

      'green-darker': '#3b8070',
    },
    fontFamily: {
      'source': [
        '"Source Sans Pro"',
        'sans-serif'
      ],
      'open': [
        'Open Sans',
        'sans-serif'
      ],
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '4': '4px',
      '8': '8px',
      '10': '10px',
    },
    minWidth: {
      '0': '0',
      'xxs': '10rem',
      'xs': '20rem',
      'sm': '30rem',
      'md': '40rem',
      'lg': '50rem',
      'xl': '60rem',
      '2xl': '70rem',
      '3xl': '80rem',
      '4xl': '90rem',
      '5xl': '100rem',
      'full': '100%',
    }
  }
}
```

**Comment by benface** [comment]
@dotnetCarpenter Looks like you're missing a `white` color in your `tailwind.config.js` file. Simply add:

```
'white': 'white',
```
or
```
'white': '#fff',
```
somewhere in the `theme.colors` dictionary and it should fix your problem.

**Comment by dotnetCarpenter** [comment]
In `node_modules/tailwindcss/stubs/defaultConfig.stub.js` I can see that `white` is defined.

I was under the impression that my colors got mixed in with the default colors. This appears to be false.

After re-reading:
> The way your configuration is merged with the defaults is designed to be very intuitive and mostly just work, but for the curious:
>
>    prefix is replaced
>    separator is replaced
>    important is replaced
>    **theme is merged one level deep, so if you provide an object for theme.opacity it replaces the default theme.opacity object**
>    variants is merged one level deep, so if you provide an array for variants.opacity it replaces the default variants.opacity object
>    plugins is merged, but the default is an empty array so it's really the same as replacing

> **theme is merged one level deep, so if you provide an object for theme.opacity it replaces the default theme.opacity object**

Should probably be in the beginning of the upgrade guide (in **bold**). :I

@benface Thx!

**Comment by devcircus** [comment]
If you don’t want to overwrite the defaults, add your colors under “theme.extend” instead of just “theme”. I’ve mentioned before that this needs to be covered in a more obvious way. I’m sure it will once the 1.0 docs are released.

**Comment by dotnetCarpenter** [comment]
@devcircus How do you use `extend`?

I just tried to do
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        'transparent': 'transparent',
        'sk-green': '#5D7F57',
        'sk-green-dark': '#304325',

        'black': '#231F20',

        'green-darker': '#3b8070',
      },
    }, 
    ...
```

And I got:

> Syntax Error: SyntaxError                                                                                                                     friendly-errors 19:35:35
>
>(27:3) @apply cannot be used with .border-grey-darker because .border-grey-darker either cannot be found, or  ....

**Comment by devcircus** [comment]
make sure you completely restart your watcher if you're watching your file changes. Thats how it is used.

**Comment by benface** [comment]
Well, also @dotnetCarpenter are you sure you have a `grey-darker` color? In the example you posted, you defined `green-darker` but no `grey-darker`.

**Comment by dotnetCarpenter** [comment]
@devcircus @benface Ah, I see that `grey-darker` is now `gray-800`... That seems like a bug. `gray` is misspelled(!).

```
grep gray node_modules/tailwindcss/stubs/defaultConfig.stub.js 
      gray: {
      default: theme('colors.gray.300', 'currentColor'),
```

**Comment by benface** [comment]
`gray` is the correct American spelling, it was changed for v1.0.

**Comment by dotnetCarpenter** [comment]
@benface same on us Europeans... hehe

**Comment by dotnetCarpenter** [comment]
Hmm... according to [the new docs](https://next.tailwindcss.com/docs/text-color/#class-reference), `.text-gray-700` should work but I get:
```
Syntax Error: SyntaxError                                                                                                                     friendly-errors 20:21:57

(29:5) Unknown word

  27 |   @apply
  28 |     border-gray-700;
> 29 |     text-gray-700;
     |     ^
  30 | }
```

**Comment by benface** [comment]
Remove the `;` after `border-gray-700`?

**Comment by dotnetCarpenter** [comment]
@benface THANKS!
