### ISSUE TITLE
Variant styles not displayed in chrome devtools

### ISSUE THREAD

**Issue by sfeldkamp** [tailwindcss/tailwindcss#864]
A `block` class added to an element does appear in Chrome Devtools under the _Elements_ Tab > _Styles_ Subtab when the element is selected.

A `sm:block` class does _not_ appear.

This can be proved by editing the class name in the _Elements_ main tab and watching the class appear and disappear in the _Styles_ subtab.

I realize this is not something that can be fixed under this project, the purpose for raising this issue is:

1) Document the issue
2) Discuss any work-arounds
3) Discuss whether using a `:` delimiter for variants is desirable and whether there are any other options.

**Comment by CvX** [comment]
That doesn't seem correct:

<img alt="classes in devtools" src="https://user-images.githubusercontent.com/66961/56605439-73c98600-6604-11e9-95cc-3396bed4da91.png" width="230">

Are you sure these classes are actually in your styles? (screen sizes defined in your config, not removed by purgeCSS, etc.)

**Comment by sfeldkamp** [comment]
Sorry, this was a media query issue on my end.
