### ISSUE TITLE
Weird box-shadow bug on Safari for next.tailwindcss.com

### ISSUE THREAD

**Issue by benjaminmodayil** [tailwindcss/tailwindcss#891]
There seems to be a very apparent box-shadow on the next.tailwindcss.com site on Safari:
https://i.imgur.com/sloqaZm.png

**Comment by tlgreg** [comment]
Isn't it the gradient? `transparent` still means `rgba(0, 0, 0, 0)` in some browsers, so it lerps between white and black too. Changing `linear-gradient(white, transparent)` to `linear-gradient(white, rgba(255, 255, 255, 0))` could work.

**Comment by benface** [comment]
[Yes, that's exactly what it is](https://github.com/w3c/csswg-drafts/issues/2722). Safari is the only browser following the current spec.

**Comment by benface** [comment]
> Changing linear-gradient(white, transparent) to linear-gradient(white, rgba(255, 255, 255, 0)) could work.

Yes it would.

**Comment by tlgreg** [comment]
Already fixed w/ https://github.com/tailwindcss/docs/commit/879a94dfcd1d760b68cbd6f00cadcbc182b2daaf
