### ISSUE TITLE
Margin class on one element is affecting other elements

### ISSUE THREAD

**Issue by JamesChevalier** [tailwindcss/tailwindcss#896]
I've created [this Codepen](https://codepen.io/jameschevalier/pen/LoEmJY) to show how adding `mt-16` to the div containing the content of the page (in the hopes of pushing down the content to sit below the sticky nav menu) also causes the nav element to be pushed down the page.

It's possible that I'm just doing something wrong. If that's the case, I apologize - could you correct me?

Thanks for building such a fantastically powered tool. This is impressive.

**Comment by CvX** [comment]
`pin-t` has been replaced with `top-0`. See: https://next.tailwindcss.com/docs/top-right-bottom-left

**Comment by JamesChevalier** [comment]
**Thank you!**
