### ISSUE TITLE
mx-auto/ml-auto/mr-auto not working in 1.0.0-beta.8?

### ISSUE THREAD

**Issue by bploetz** [tailwindcss/tailwindcss#898]
I'm trying to center an image within a div using `margin-left: auto` `margin-right: auto` via Tailwind 1.0.0-beta.8. I've tried both `mx-auto` and `ml-auto` + `mr-auto`, but none of them seem to work in v.1.0.0beta8

```
<img className="lg:block lg:mx-auto lg:max-w-60pct" />
```

[The docs](https://next.tailwindcss.com/docs/margin#margins) seem to suggest the auto variants should be there and don't need to be configured, but they don't seem to work for me.

Am I just doing something wrong? Thanks!

**Comment by adamwathan** [comment]
Can you share a repository or Codepen that reproduces? Happy to help troubleshoot just need to see the HTML and your config file.

**Comment by kevinruscoe** [comment]
`className` should be `class` unless you're using some funky pre/post HTML tools.

**Comment by bploetz** [comment]
This is so weird. The most stripped down version in my app simply doesn't work, but it works fine on codepen pointed at the cdn.

Don't want to waste your time. Will re-open if I can get a reproducible use case.

**Comment by jesperp** [comment]
I know this is old but I was having similar issue and it was due to using a `space-x-*` on the parent container! Hope this helps anyone searching !

**Comment by deepaktammali** [comment]
I'm facing the same issue. How did you resolve it? @jesperp

**Comment by PedroDuarteDev** [comment]
> I'm facing the same issue. How did you resolve it? @jesperp

Hi, i was facing the same problem and i found a solution, try to use the container class on the parent, it should work fine.
