### ISSUE TITLE
colors missing from cdn stylesheets

### ISSUE THREAD

**Issue by StevenWeathers** [tailwindcss/tailwindcss#912]
Been utilizing the cdn provided stylesheets for inflight projects that don't need customization/optimization on styles yet, and as of today the stylesheets have lost their colors (borders, backgrounds, text, you name it).

Tried the jsdelivr and unpkg cdn urls and both are affected.

**Comment by StevenWeathers** [comment]
Seems to be the final 1.0.0 and 1.0.1 versions were pushed, and prior to this the default url was 0.7.4 based.
Switching to fixed version url resolves this for now, but might want to fix cdn stylesheets for 1.x

https://cdn.jsdelivr.net/npm/tailwindcss@0.7.4/dist/tailwind.min.css

**Comment by adamwathan** [comment]
Yeah we released v1 today so any non-versioned CDN links will be out of date. I'll update the CDN links in the old docs.
