### ISSUE TITLE
Add a custom prefix ?

### ISSUE THREAD

**Issue by florenthobein** [tailwindcss/tailwindcss#92]
I like my utility classes prefixed with `.u-`, would be nice if it was possible to configure a prefix for the whole library.

**Comment by psren** [comment]
Hey there,

should be quite simple to add this with an extra postcss-plugin.
Maybe based on annotations?

This way it would be usable without tailwind and in any other postcss environment.

Maybe based on annotations?
You can do that with this [postcss method](http://api.postcss.org/AtRule.html#walkRules)

(I do not belong to the team, this is just my opinion)

**Comment by adamwathan** [comment]
This is now possible in `master` thanks to #186 🙌🏻 Details there!

We'll tag a release with this added early this week.

**Comment by florenthobein** [comment]
Perfect, exactly how imagined it. Thanks !

**Comment by florenthobein** [comment]
An extra request, or more like a topic to discuss: I realise that `@apply` is prefix-dependant, which in my opinion is a serious coupling factor for every library written using tailwind.

I have no idea how you manage the replacement of `@apply` js-wise, but I believe it would be an improvement if we could just write `@apply .an-utility-without-prefix` in the (catastrophic) scenario where our prefix was to change.
