### ISSUE TITLE
No border style property for individual sides

### ISSUE THREAD

**Issue by stevenmunro** [tailwindcss/tailwindcss#920]
tailwindcss v1.0.1

I believe this is a bug. 

Previously, `border-b` would put a solid 1px line at the bottom of my element. Now with v1.0.1 this border doesn't show unless I also include `border-solid`. The problem with this is now I have a border on all four sides of my element.

I am applying `border-b-2 border-gray-600` as per the docs at https://tailwindcss.com/docs/border-width for individual sides - however, this does not show as there isn't a border style property.

**Comment by stevenmunro** [comment]
The workaround is to declare `border-0` as well. For example;

`border-solid border-0 border-b-2 border-gray-500`

Hope this helps someone.

**Comment by CvX** [comment]
Sounds similar to #919.

**Comment by stevenmunro** [comment]
> Sounds similar to #919.

Yep. I also forgot to change from preflight to base.
