### ISSUE TITLE
Using a href with type="button" in Chrome on Mac removed background color

### ISSUE THREAD

**Issue by trentramseyer** [tailwindcss/tailwindcss#923]
Hello,

I have a button similar to this, adding the type="button" to the href removes the background color in Chrome on Mac . Toggling the     -webkit-appearance: button; in the developer tools brings color back. 

` <a href="{{  URL("/appointment") }}?in_state=Y" class="bg-blue no-underline hover:underline hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
                    I agree with the above conditions.
                </a>`

**Comment by adamwathan** [comment]
Hmm what's the reason for using `type="button"` on an `a` tag? As far as I can find that's not a valid attribute for links.

**Comment by trentramseyer** [comment]
Not saying it is useful or valid.  I believe in this instance, a <button> was changed to an "href" and the type wasn't removed, however not sure why that would affect the background color.

**Comment by adamwathan** [comment]
This is happening because of normalize.css:

https://github.com/necolas/normalize.css/blob/master/normalize.css#L196

I wouldn't say it's an issue though because it's invalid to use `type="button"` on an anchor anyways.
