### ISSUE TITLE
[Feature/Question] Does Tailwind support the html tag <details> ?

### ISSUE THREAD

**Issue by tance77** [tailwindcss/tailwindcss#924]
I just recently learned about the HTML element  [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)  

I was hoping to style this list with tailwindcss, but I couldn't find any documentation when I typed details into tailwindcss search bar. 

Does tailwind support the ```<details>``` tag and if it does exist would you be so kind and link me to the documentation on tailwindcss. If it doesn't could we see the ```<details>``` tag have styles like lists for future iterations of tailwind?

#### Example
```html
<details>
<summary>Users</summary>
<div>
    <p>Jessica</p>
    <p>Fred</p>
    <p>Mary</p>
    <p>Doug</p>
</div>
</details>
```

<details>
<summary>Users</summary>
<div><p>Jessica</p><p>Fred</p><p>Mary</p><p>Doug</p></div></details>

**Comment by tlgreg** [comment]
Tailwind inherits normalize's styling of `<details>` and `<summary>` so details is a `block` and summary is `list-item`

**Comment by tance77** [comment]
Correct but I guess my question was more of do we have something that I can use for removing the arrow. 

```list-none``` does not seem to do the job.

The css to do that in chrome is

```details > summary::-webkit-details-marker {
  display: none;
}
```

**Comment by tlgreg** [comment]
`list-none` on the `<summary>` works in Firefox. Unfortunately, webkit/chrome uses the pseudo-element instead.

Should this be added to `list-none` utility? Or maybe reset by default, like other lists?
```css
.list-none {
  list-style-type: none;
}
.list-none::-webkit-details-marker {
  display: none;
}
```

**Comment by adamwathan** [comment]
Not planning to change anything around this any time soon as it would be a breaking change. If you want to reset this we have instructions for [adding your own base styles](https://tailwindcss.com/docs/adding-base-styles) in the docs 👍

**Comment by swanson** [comment]
Ran into this today, added this to my application as a work-around:

```css
/* Fix Safari issue related to <summary> / <detail> arrow */
details > summary.list-none::-webkit-details-marker,
details > summary.list-none::marker {
  display: none;
}
```

There seems to be some Safari versions using `::-webkit-details-marker` and some using `::marker` now.

**Comment by CaptainYarb** [comment]
It's a shame this ticket is closed as it would be highly valuable to a more semantic web to have control over this within tailwind. The workaround is reasonable, but with Tailwind 2's JIT it would seem like a reasonable feature to have added with relatively no cost.

**Comment by lloydjatkinson** [comment]
Wanted to add this would be a great addition to Tailwind 3.x - it would be great for the Typography plugin as well, imagine being able to put a collapsible panel for extra information using only <details> and <summary>.

**Comment by TsarPrince** [comment]
So, tailwind 3.0 is out there, and this feature is still not added -_- Please consider adding it further releases, I just love tailwind and this little touch will make it even more robust.

**Comment by ColmanHumphrey** [comment]
Just in case it helps anyone, as I was slightly struggling earlier: you can customise the symbol, and in fact every part, once you've sorted out removing the marker from webkit (elsewhere, just adding `list-none` to the summary will do it). So assuming you've got one of the above webkit options in your CSS somewhere, e.g.:

```css
details > summary::-webkit-details-marker {
  display: none;
}
```

You can then use `group` with `group-open` for full control:

```html
<details className="group open:ring">
  <summary
    className="text-blue-500 group-open:text-green-500"
  >
    <span className="group-open:hidden mr-4">
      Show Closed
    </span>
    <span className="hidden group-open:inline mr-4">
      Show Open
    </span>
    I'm the summary
  </summary>
  <p>
    Whatever else
  </p>
</details>
```

(use an icon in place of `Show Closed` and `Show Open` etc)

**Comment by raview69** [comment]
> Just in case it helps anyone, as I was slightly struggling earlier: you can customise the symbol, and in fact every part, once you've sorted out removing the marker from webkit (elsewhere, just adding `list-none` to the summary will do it). So assuming you've got one of the above webkit options in your CSS somewhere, e.g.:
> 
> ```css
> details > summary::-webkit-details-marker {
>   display: none;
> }
> ```
> 
> You can then use `group` with `group-open` for full control:
> 
> ```
> <details className="group open:ring">
>   <summary
>     className="text-blue-500 group-open:text-green-500 list-none"
>   >
>     <span className="group-open:hidden mr-4">
>       Show Closed
>     </span>
>     <span className="hidden group-open:inline mr-4">
>       Show Open
>     </span>
>     I'm the summary
>   </summary>
>   <p>
>     Whatever else
>   </p>
> </details>
> ```
> 
> (use an icon in place of `Show Closed` and `Show Open` etc)

thank you that is help me so much

**Comment by qwatts-dev** [comment]
I just encountered this issue, and I was able to solve using Tailwind's [Arbitrary Variants](https://tailwindcss.com/docs/hover-focus-and-other-states#custom-modifiers).

### Using arbitrary variants
Just like [arbitrary values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values) let you use custom values with your utility classes, arbitrary variants let you write custom selector modifiers directly in your HTML.

Arbitrary variants are just format strings that represent the selector, wrapped in square brackets. For example, this arbitrary modifier selects an element only when it is the third child:

```html
<ul role="list">
  {#each items as item}
    <li class="[&:nth-child(3)]:underline">{item}</li>
  {/each}
</ul>
```


### Solution
So, in [this example](https://github.com/tailwindlabs/tailwindcss/issues/924#issuecomment-1251912399), you don't have to add _non Tailwind_ css. You simply add the Arbitrary Variate `[&::-webkit-details-marker]:hidden` to the `<summary>` tag.

So this html:
```html
<details className="group open:ring">
  <summary
    className="text-blue-500 group-open:text-green-500 list-none"
  >
  ...
```

Becomes this:
```html
<details className="group open:ring">
  <summary
    className="text-blue-500 group-open:text-green-500 list-none [&::-webkit-details-marker]:hidden"
  >
  ...
```

**Comment by lloydjatkinson** [comment]
I think you could add `[&::-webkit-details-marker]:hidden` as a custom utility class in `tailwind.config.js`, right?

**Comment by surjithctly** [comment]
+1 for this. Would love to see a fix for this in v4 🙏

**Comment by collimarco** [comment]
@swanson solution is great. I think it should be added as a default to the Tailwind preflight / reset.

**Comment by sergio-agosti** [comment]
At the moment this is what I’m using:

```javascript
// add webkit details marker support to the marker variant
// this can be removed when webkit fully implements marker
addVariant('marker', [
    '&::marker',
    '& *::marker',
    '&::-webkit-details-marker',
    '& *::-webkit-details-marker',
]);
```

This solution allows any style to be applied to the marker, not just “hidden”...

**Comment by i-am-the-slime** [comment]
When you're pasting these excerpts, it would be extremely valuable if you could also post *where* these snippets are supposed to go.

**Comment by sergio-agosti** [comment]
> When you're pasting these excerpts, it would be extremely valuable if you could also post _where_ these snippets are supposed to go.

Of course, I updated my previous comment, hope it makes sense now...
