### ISSUE TITLE
Max-width Scale from v0.72 -> v1.0.1

### ISSUE THREAD

**Issue by terryupton** [tailwindcss/tailwindcss#926]
Hi @adamwathan - so I have been using Tailwind from its infancy and I have always created my own container - in most instances this is done via a single class (.container) and uses @apply to set a max-width. So updating it should be fairly easy. However, in several instances I have also used max-width classes.

Upgrading old projects should be fine as I would keep the original max-width scale.
However, for new projects I wondered if you would consider extending the default max-width scale to include the following?

```
max-width: 80rem;
max-width: 90rem;
max-width: 100rem;
```
The old class names were:
```
.max-w-3xl | max-width: 80rem;
.max-w-4xl | max-width: 90rem;
.max-w-5xl | max-width: 100rem;
```
So perhaps the new ones would be:
```
.max-w-7xl	max-width: 80rem;
.max-w-8xl	max-width: 90rem;
.max-w-9xl	max-width: 100rem;
```

The main one being the 90rem as this equates to 1440px (on a standard 16px scale) which is an ideal max-width resolution for most containers (maxes the desktop size nicely). I always design fluid responsive websites not fixed width at breakpoints so I don't like or use the container plugin approach. 

I appreciate I can naturally set these up as standard in my own config file, but I wondered if others might be in a similar position having used max-4w from versions prior to 1 fairly extensively?

**Comment by adamwathan** [comment]
Hey Terry! We did in fact have a 1440px value at one point while we were coming up with the new values, but ultimately opted to limit the number of values for default file-size considerations (the max width values don't add a lot on their own, but if we are too lax about what values we include everywhere in the framework it adds up.)

Best option for now is to add these values in your own config file, but if the demand is high enough I'm open to discussing expanding the default scale.
