### ISSUE TITLE
How can I add "text-indent" with TailwindCSS

### ISSUE THREAD

**Issue by irioor** [tailwindcss/tailwindcss#928]
Is there any way to add "text-indent" with TailwindCSS ?

**Comment by hacknug** [comment]
You can use one of these two plugins:
- https://www.npmjs.com/package/tailwindcss-text-indent
- https://www.npmjs.com/package/tailwindcss-typography

**Comment by adamwathan** [comment]
Yep those will work, or you can just follow the instructions for adding your own utilities in the documentation:

https://tailwindcss.com/docs/adding-new-utilities

**Comment by MarcelloTheArcane** [comment]
@adamwathan Is there any way to add the default numbers? 

For example widths have the increments 1, 2, 3, 4, 5, 6, 8, 10, ... 56, 64 which correspond to specific `rems`.

I'd like to be able to make a utility for `.indent-1`, `.indent-2`, etc programmatically.

**Comment by adamwathan** [comment]
@MarcelloTheArcane Use this plugin:

https://www.npmjs.com/package/tailwindcss-text-indent

...and configure it like this:

```js
// tailwind.config.js
module.exports = {
  theme: {
    textIndent: theme => theme('spacing'),
    // ...
  },
  // ...
}
```

**Comment by bobgravity1** [comment]
the fact that i need a plugin to indent a paragraph honestly shows how broken web dev is..

**Comment by fuchunhui** [comment]
why plugin or utilities instead of default

**Comment by dospolov** [comment]
can you add 'indent' as default now with JIT mode?

**Comment by proimage** [comment]
> the fact that i need a plugin to indent a paragraph honestly shows how broken web dev is..

Not web dev; Tailwind. ¯\_(ツ)_/¯

**Comment by JessicaSachs** [comment]
FYI, if it's helpful for someone, this is bundled by default into [WindiCSS](https://windicss.org/utilities/typography.html#text-indent) (A Tailwind-compat library, with native JIT... originally made for Vite). I was honestly surprised when `indent-sm` autocompleted in my editor 😅

**Comment by dospolov** [comment]
@adamwathan is there a reason why this CSS style is not provided out of the box?
For me it's pretty basic, but maybe there is a technical complexity

**Comment by bobgravity1** [comment]
how do you do it without tailwind?

**Comment by JessicaSachs** [comment]
> how do you do it without tailwind?
> […](#)

text-indent is just a CSS property. [Here’s a CSS Tricks article on it](https://css-tricks.com/almanac/properties/t/text-indent/).

**Comment by joshxyzhimself** [comment]
@adamwathan, can't this be a built-in feature?

thank you!

**Comment by jpoints** [comment]
I googled this, and ended up here. So I am another one wanting this out of the box. 
I assume it comes down to managing the size of the base build.

**Comment by hacknug** [comment]
It was added to core in #5449 about three weeks ago so I think it'll be included with v3. Core team can probably clarify if any of you have more questions but I'd say be a little more patient and you'll get this in core _soon_ 👍
