### ISSUE TITLE
Add diagonal line-through

### ISSUE THREAD

**Issue by Koc** [tailwindcss/tailwindcss#940]
Would be nice add support of diagonal line-through like https://codepen.io/rjanjic/pen/obdEbv . It useful for ecommerce.

**Comment by adamwathan** [comment]
Cool idea! If this could be done very simply with one line of CSS it would be a better fit for core but since it's actually somewhat complicated and opinionated to pull off, I think it's best left implemented as a custom utility or third-party plugin.
