### ISSUE TITLE
React PostCSS

### ISSUE THREAD

**Issue by jrock2004** [tailwindcss/tailwindcss#945]
So I am trying to use tailwind css and I am noticing that the compiled css file is missing things like `bg-white`. I think I might be doing something wrong as I am not seeing colors when I add the classes. . I am using postcss.

// postcss.config.js
```
const tailwindcss = require ('tailwindcss');

module.exports = {
  plugins: [tailwindcss ('./src/utils/tailwind.js'), require ('autoprefixer')],
};
 
```

// tailwind.js
```
module.exports = {
  theme: {
    colors: {},
    extend: {},
  },
  variants: {},
  plugins: [],
};
```

// tailwind.css
```
 @tailwind preflight;
 @tailwind components;
 @tailwind utilities;
```

// package.json
```
"build:css": "postcss src/styles/tailwind.css -o src/styles/index.css",
"watch:css": "postcss src/styles/tailwind.css -o src/styles/index.css -w",
"start": "yarn run watch:css & react-scripts start",
...

"devDependencies": {
    "autoprefixer": "^9.5.1",
    "postcss-cli": "^6.1.2",
    "tailwindcss": "^1.0.2"
}
```

This worked pre 1.0. Not sure if something changed

**Comment by jrock2004** [comment]
I need to read documentation some more. I did not realize that you generate a bare bone system and you have to add the stuff in you want. Or you can init with `--full`

**Comment by tlgreg** [comment]
You don't have to use the `--full` if you would otherwise prefer merging.
The issue was the line `    colors: {},` in your `tailwind.js`.
Configs are merged, but if you specify a key it overrides the defaults for that base-plugin.
If you want to extend specific plugins' config you should add it under `extend`.
Docs: https://tailwindcss.com/docs/theme#customizing-the-default-theme
```diff
 module.exports = {
   theme: {
-    colors: {},
-    extend: {},
+    extend: {
+      colors: {},
+    },
   },
   variants: {},
   plugins: [],
 };
```

**Comment by jrock2004** [comment]
@tlgreg If I do not run full, I do not get any colors from tailwind at all.

**Comment by devcircus** [comment]
Can you put a sample repo up that reproduces this problem? You definitely don't have to run full.

**Comment by zaknesler** [comment]
@jrock2004 What @tlgreg is saying is that in your `tailwind.js` file, you are overriding the default Tailwind colors. Any additional colors you want to add belong in the `extend` key.

```js
module.exports = {
  theme: {
    colors: {}, // This overrides the default color object, wiping out all colors
    extend: {},
  },
  variants: {},
  plugins: [],
};
```

So you should move the `colors` object into the `extend` object:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        // You may add any additional colors here
      },
    },
  },
  variants: {},
  plugins: [],
};
```

Alternatively, you may choose to override the default colors and define a list of your own. Here is an example in the [documentation](https://tailwindcss.com/docs/customizing-colors/#overview):

```js
module.exports = {
  theme: {
    colors: {
      indigo: '#5c6ac4',
      blue: '#007ace',
      red: '#de3618',
    }
  }
};
```

This will only generate color utilities based on those three colors.

**Comment by jrock2004** [comment]
@zaknesler when I ran npx tailwind init I got his

```
module.exports = {
  theme: {
    colors: {},
    extend: {},
  },
  variants: {},
  plugins: [],
};
```

I did not change that
