### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.hover:bg-grey' is not a valid selector.

### ISSUE THREAD

**Issue by valh1996** [tailwindcss/tailwindcss#956]
Hello,

I don't know why this error appears. Indeed, I have this error in the console when I right-click on some elements, mainly buttons. Here are some mistakes that all seem to be getting closer: 

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.hover:bg-grey' is not a valid selector.
```

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.w-1/3' is not a valid selector.
```

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.md:w-1/2' is not a valid selector.
```

I would like to point out that I do not use QuerySelectorAll() on my side.

![Capture d’écran 2019-06-04 à 21 42 21](https://user-images.githubusercontent.com/20521112/58908746-aee5cb80-8711-11e9-9c22-e0dfdfd9acba.png)

Thank you for your help!

Best regards,
Valentin

**Comment by devcircus** [comment]
You possibly need to escape some of tailwind's unusual characters like "/" and ":". Not sure though as I give specific classes to elements that need to be used in selectors.

**Comment by adamwathan** [comment]
This error is coming from a Chrome extension you have installed that isn't properly escaping CSS classes, I'd try disabling all extensions and verifying that the error goes away then enabling them one at a time to find out which one it is.

**Comment by tlgreg** [comment]
As said, I wouldn't advise selecting by utility classes if you can avoid it.
But yes, it does work if you escape the selector. It's easy for just `:` and `/`, but if you want to make sure for any class-name, you could use `CSS.escae()` ([mdn](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) | [npm](https://www.npmjs.com/package/css.escape)).

**Comment by tlgreg** [comment]
If somebody finds this with their own code: `querySelector` does work with escaped selectors.

Just looking at the ID of the extension seems like this is something built-in into Brave browser.

**Comment by valh1996** [comment]
Problem solved, thank you all for your answers 💯!

**Solution**: I updated Brave to its latest version. And from the settings, I checked the "Hide the Brave Rewards button" box.
