### ISSUE TITLE
Can't use extend to add a smaller setting to screens?

### ISSUE THREAD

**Issue by adamkiss** [tailwindcss/tailwindcss#957]
### Description

If I use extend to add a breakpoint — in my case `xs: '400px'` — the CSS for this breakpoint is added after all the default breakpoints, meaning you now can't use larger screen's utility to override the setting.

### Example

``` html
<p class="xs:text-red lg:text-black">I am red, xs+</p>
```

``` javascript
theme: {
    extend: {
        screens: {xs: '400px'}
    }
}
```

### Solution

Probably the only solution is to add a warning not to use `extend` if you intend to use default and add a smaller media query — I am currently dealing with it by not extending, but simply overriding the screen setting.

**Comment by adamwathan** [comment]
Yeah the order that the screens are defined in is important, so if you want to add a smaller screen your best bet is to do this:

```js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    screens: {
      xs: '400px',
      ...defaultTheme.screens,
    }
  }
}
```

I'll try to remember to add a note to the docs about this. Going to close as not a bug or anything per se, just something we should educate people about in the docs.

**Comment by missmatsuko** [comment]
@adamwathan I'm trying to add a smaller breakpoint using the method you showed, but my 'xs' screen is still coming after 'xl'. 

I think it makes sense for options passed into `screens` to get ordered by their value (width) so the it follows the [mobile-first methodology](https://tailwindcss.com/docs/responsive-design/#mobile-first) of the framework.

**Comment by missmatsuko** [comment]
Also tried just replacing the whole `screens` option like this:
```
      screens: {
        xs: "450px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
```

`xs` styles are still generated after `xl`. Maybe it's because the object property order is not being preserved? But then I'm surprised the default set (sm-xl) seem to always be in the expected order.

**Comment by adamwathan** [comment]
Can you paste your whole config? Make sure you aren't in the `extends` section as that would be adding the new screens in addition to the old ones.

**Comment by missmatsuko** [comment]
Ah sorry, that is what was happening. I didn't notice all the config was in `extend` already because there were already spread operators in some values, too. 😫

**Comment by adibsadeghi1993** [comment]
I defined xs=450px in the screen in the theme but I've got an error it says theme is not defined
