### ISSUE TITLE
Tailwind dont work at all

### ISSUE THREAD

**Issue by Briareos17** [tailwindcss/tailwindcss#966]
I am trying to setup tailwind on my just created laravel project bu after `npm  run dev` resulted `app.css` stay like this:
```css
    @tailwind 'base';
    @tailwind 'components';
    @tailwind 'utilities';
```

my webpack.mix.js are folowing:
```javascript
    const mix = require('laravel-mix')
    const tailwindcss = require('tailwindcss')

    mix
      .js('resources/js/app.js', 'public/js')
      .sass('resources/sass/app.scss', 'public/css')
      .options({
        processCssUrls: false,
        postCss: [ tailwindcss('tailwind.js') ],
      })
```

my tailwind.js are folowing:
```javascript
    module.exports = {
      theme: {},
      variants: {},
      plugins: [],
    }
```

What I am doing wrong?

Laravel mix version 4.

Also I tried to use gulp with postcss bu same result.

**Comment by bbashy** [comment]
You're saying the contents of app.css in `public/css` contains the same as `resources/sass/app.scss`?

I haven't used that method in a while but I use this now: https://laravel-mix.com/extensions/tailwindcss

**Comment by Briareos17** [comment]
> You're saying the contents of app.css in `public/css` contains the same as `resources/sass/app.scss`?
Only tailwind directives, sass compilling as expected

**Comment by bbashy** [comment]
Sounds like something to do with PostCSS then. Not sure, sorry.

**Comment by adamwathan** [comment]
Can you create a GitHub repo that reproduces the problem?

**Comment by Briareos17** [comment]
@adamwathan Please give me few minutes

**Comment by Briareos17** [comment]
@adamwathan Please look this repo: https://github.com/Briareos17/tailwind-debug

**Comment by bbashy** [comment]
clones, npm i, and npm run dev;
```
$ cat dist/app.css
@tailwind "base";

@tailwind "components";

@tailwind "utilities";%
```

**Comment by bbashy** [comment]
Yes, that was me just confirming I had the same. I'll try a few things to make it to work.

**Comment by adamwathan** [comment]
The problem is you are using quotes.

Your file should look like this:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Docs here:

https://tailwindcss.com/docs/installation#2-add-tailwind-to-your-css

**Comment by bbashy** [comment]
Damn. I didn't see that. Too similar to `@import` 😛

**Comment by Briareos17** [comment]
@adamwathan Oh my god, thank you, I was blind!

**Comment by AzizjonNigmatjonov** [comment]
tailwind ml property is not working. Who knows what to do?
