### ISSUE TITLE
Feature Request: CSS Code Splitting

### ISSUE THREAD

**Issue by geekox86** [tailwindcss/tailwindcss#971]
Greetings. Fantastic job and well respected repo.

I would like to open a discussion about CSS code splitting based on actually used classes by JS files. The split CSS files can be named after their corresponding JS files.

This will allow for better performance on initial and later page loading.

It would be also great if this is integrated with Webpack workflow through a separate plugin.

Thank you.

**Comment by geekox86** [comment]
Anyone interested to discuss the feature?

**Comment by adamwathan** [comment]
No plans to implement this in Tailwind itself as I think it's sort of outside the scope of this project. Seems like something better handled by a general-purpose tool for splitting any CSS based on usage in your templates. Thanks for the suggestion!
