### ISSUE TITLE
Compile Tailwind Client/Browser side with PostCSS 

### ISSUE THREAD

**Issue by davidboom95** [tailwindcss/tailwindcss#977]
Hi,

I have a question/problem, there is any way of compiling tailwind css client/browser side? I need to compile and provide css file locally. Inject css to body.

```typescript
import * as postcss from 'postcss'
const tailwind = require('tailwindcss')
const resolveConfig = require('tailwindcss/resolveConfig')

// Simulate css file
const input = "@tailwind base;@tailwind components;@tailwind utilities;"
// Custom config
const tailwindConfig = {...}

// Process tailwind with postcss and custom JSON tailwindConfig. No root tailwind.config.js file.
postcss([tailwind()])
   .process(input, tailwindConfig)
   .then(res=>{
      const cssFile = res.css
     // Do something with css file
    })
```

I got `'fs' module` not found error. There is a way to export and isolate tailwind and postcss functions without 'fs' dependency? As 'fs' only works on node server environments

**Comment by venusvavadiya** [comment]
Hi David, see if this link helps. I think it has do with how PostCSS works not specifically tailwind. 
https://github.com/postcss/postcss/issues/830#issuecomment-228218969

**Comment by tlgreg** [comment]
The error shows because `postcss` was made to be used in a node environment, to use it in the browser you can [browserify](https://github.com/browserify/browserify) it.
`postcss` and `postcss-js` and many plugins can be browserified, as most of what they do is process strings. So it is possible, but some plugins might have issues, unfortunately, tailwindcss itself does.

Tailwind currently can't easily be browserified through automated solutions because of `request.resolve` is used to get the path to normalize. The browserified runtime will throw an error that `resolve` is not a function.

**Comment by hacknug** [comment]
I think @bradlc built something like this for [his VSCode extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss). Not sure this is it but: https://github.com/bradlc/tailwindcss-as-a-service/

**Comment by davidboom95** [comment]
I found a workaround :), deactivate preflight
```js
await postcss([require('tailwindcss')({
          ...this.library.tailwind,
          corePlugins: { preflight: false }
        })])
          .process(input)
          .then(res => {
            console.log(res.css)
          })
```

**Comment by adamwathan** [comment]
Glad you found a workaround, no plans to really change anything to support this directly right now though.

**Comment by mhsdesign** [comment]
To enable jit one needs to mock `fs.readFileSync()`

i just made a plugin (its the extracted simplified core of https://github.com/beyondcode/tailwindcss-jit-cdn)

voila:
https://github.com/mhsdesign/browser-jit-generate-tailwindcss

**Comment by mhsdesign** [comment]
one could argue its kind of an art to mock the right things and get it working:

this projekt uses esbuild to mock fs and other dependencies ;)
https://github.com/remcohaszing/monaco-tailwindcss

or maybe this older revision helps better: 
https://github.com/remcohaszing/monaco-tailwindcss/commit/31792325715e117437ed30b57fb6939695297e4a#diff-ebe72636f47c5acf2b64d93faf024ba8e975f3be04bbe426f51e63df5f254a6aR41

this build script also handles other specific things but 50% is tailwind specific ;) i hope you can find something useful.

**Comment by mhsdesign** [comment]
@rem4ik4ever i just updated my package https://github.com/mhsdesign/browser-jit-generate-tailwindcss

you should be able to use it without Problems ;)

**Comment by mhsdesign** [comment]
@rem4ik4ever i just updated my package https://github.com/mhsdesign/browser-jit-generate-tailwindcss

you should be able to use it without Problems ;)
