### ISSUE TITLE
Bug? Horizontal rules are invisible by default

### ISSUE THREAD

**Issue by AlexVipond** [tailwindcss/tailwindcss#979]
The `border-width` reset in preflight causes `hr` elements to be invisible by default:

https://github.com/tailwindcss/tailwindcss/blob/ca670f5a764d53185a16545f8b51868af1fd47b0/src/plugins/css/preflight.css#L100-L106

Easy fix is to add the `border` class to `hr` in your markup, but maybe it makes more sense to set a 1px border for `hr` in preflight?

Not sure if I like the idea of allowing specific values from tailwind's design system to leak into preflight, but I also am not a huge fan of every `hr` being invisible unless you add the `border` class or override preflight 🤔

**Comment by adamwathan** [comment]
Agree, would accept a PR that just adds this to Preflight:

```css
hr {
  border-width: 1px;
}
```
