### ISSUE TITLE
Webpack watch breaks when @apply'ing a non-existing class.

### ISSUE THREAD

**Issue by 1player** [tailwindcss/tailwindcss#98]
First of all, thanks for this great project, I've been waiting for this since ages!

I don't know if I'm reporting this in the correct place, but my problem is this: if in my component I `@apply` a class that does not exist, I get an error such as:

```
ERROR in ./css/app.css
Module build failed: ModuleBuildError: Module build failed: Syntax Error

(3:3) No .foo class found.
```

and my webpack watch breaks, and does not pick up further changes until I stop and restart webpack.

I think it's because of Tailwind's implementation of `@apply`, which completely break the webpack watcher until the error is fixed and webpack restarted.

Any easy workaround for the time being? It's a bit frustrating to stop and restart webpack everytime I add a typo in my components.

How can I help?

**Comment by 1player** [comment]
Mmmm.. spent more time on this, and it seems this happens only on an `@apply` error in an `@import`ed CSS file. 

If I have a typo in my main css file, rebuild after error works.

I'm using `postcss-easy-import` which is basically `postcss-import` with globs, the problem is probably there. I'll report back.

**Comment by 1player** [comment]
Couldn't make it work with postcss-import. I've resolved by converting all my stylesheets to SASS and using it to concatenate imports, which are then processed by postcss and tailwind.

Here's my webpack rules:
```
 // Preloader to support globbed @import on SASS
      {
        test: /\.s?css$/,
        enforce: "pre",
        loader: "import-glob-loader"
      },
      {
        test: /\.s?css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ["css-loader", "postcss-loader", "sass-loader"]
        })
      }
```

And my main CSS:
```
@tailwind preflight;

@import "./components/*";

@tailwind utilities;

@import "./utilities";
```

**Comment by 1player** [comment]
Pinging #53 since I originally got the idea of using postcss-import from there.

**Comment by sebastiandedeyne** [comment]
I have the same issue that webpack sopts watching... It's not a dealbreaker but kind of annoying every time I need to restart the process.
