### ISSUE TITLE
Custom checkbox/radio

### ISSUE THREAD

**Issue by divdax** [tailwindcss/tailwindcss#981]
Hey guys,

what do you think about a new component for custom checkbox/radio?
I hate the browsers standard look of those form controls... 🙈😄

**Comment by tlgreg** [comment]
The core is mainly for utilities.
A WIP plugin: https://github.com/tailwindcss/custom-forms

**Comment by divdax** [comment]
Thank you @tlgreg! Did not find the custom-form plugin. 🙈

**Comment by adamwathan** [comment]
Good timing as I just released a brand new version of that plugin :)
