### ISSUE TITLE
[Feature Request] Support negative prefix syntax in config for letterSpacing and boxShadow

### ISSUE THREAD

**Issue by AlexVipond** [tailwindcss/tailwindcss#982]
### Background
When I'm using letter spacing utilities, I prefer numerical class names like `tracking-1`, `tracking-2`, etc. instead of `wide`, `wider`, etc. 

I also like to set my negative letter spacing values to `-tracking-1`, `-tracking-2`, etc.—the negative prefix makes it more explicit that I'm shrinking the font's normal letter spacing.

Same goes for box shadows—I prefer `shadow-1`, `shadow-2`, etc., and I dig `-shadow` instead of `shadow-inner`. Also feels cleaner to do something like `-shadow-1`, `-shadow-2`, etc. instead of `shadow-inner-md`, `shadow-inner-lg`, etc.

### Problem

For `zIndex`, `margin`, and `inset`, you can easily create these prefixed classes in your config like so:

```
zIndex: {
  '10': '10', // z-10
  '-10': '-10' // -z-10
}
```

But the negative prefix syntax isn't supported for any other utilities (I edit Tailwind's source code in my projects to get it working).

### Solution

Support negative prefix syntax for `letterSpacing` and `boxShadow`. Looking through the other plugins, it might make sense to add support for `lineHeight` too.

If this is considered a breaking change, it's probably not worth it. Otherwise, I'd be happy to make the pull request.

**Comment by adamwathan** [comment]
Happy to accept a PR for this, it's probably technically a breaking change but it's just as much a bugfix IMO 👍
