### ISSUE TITLE
[Feature proposal] `fractions` config util

### ISSUE THREAD

**Issue by AlexVipond** [tailwindcss/tailwindcss#986]
Tailwind's default config includes a set of fractions for width utilities:

https://github.com/tailwindcss/tailwindcss/blob/ca670f5a764d53185a16545f8b51868af1fd47b0/stubs/defaultConfig.stub.js#L378-L409

I enjoy using these same fractions with `maxWidth`, `height`, and `maxHeight`. I also typically repeat the same entries with a `-screen` suffix to add screen height/width fractions:

```
width: theme => ({
  ...
  '1/2-screen': 'calc(1/2 * 100vw)'
})
```

I propose adding a `fractions` config util—just a simple function that takes a `unit` argument and returns Tailwind's default set of fractions, like so:

```
width: (theme, { fractions }) => {
  auto: 'auto',
  ...theme('spacing'),
  ...fractions('%'),
  ...fractions('vw'),
}

// is equivalent to...

width: (theme, { fractions }) => {
  auto: 'auto',
  px: '1px',
  '0': '0',
  '1': '0.25rem',
  '2': '0.5rem',
  '3': '0.75rem',
  '4': '1rem',
  '5': '1.25rem',
  '6': '1.5rem',
  '8': '2rem',
  '10': '2.5rem',
  '12': '3rem',
  '16': '4rem',
  '20': '5rem',
  '24': '6rem',
  '32': '8rem',
  '40': '10rem',
  '48': '12rem',
  '56': '14rem',
  '64': '16rem',
  '1/2': 'calc(1/2 * 100%)',
  '1/3': 'calc(1/3 * 100%)',
  '2/3': 'calc(2/3 * 100%)',
  '1/4': 'calc(1/4 * 100%)',
  '2/4': 'calc(2/4 * 100%)',
  '3/4': 'calc(3/4 * 100%)',
  '1/5': 'calc(1/5 * 100%)',
  '2/5': 'calc(2/5 * 100%)',
  '3/5': 'calc(3/5 * 100%)',
  '4/5': 'calc(4/5 * 100%)',
  '1/6': 'calc(1/6 * 100%)',
  '2/6': 'calc(2/6 * 100%)',
  '3/6': 'calc(3/6 * 100%)',
  '4/6': 'calc(4/6 * 100%)',
  '5/6': 'calc(5/6 * 100%)',
  '1/12': 'calc(1/12 * 100%)',
  '2/12': 'calc(2/12 * 100%)',
  '3/12': 'calc(3/12 * 100%)',
  '4/12': 'calc(4/12 * 100%)',
  '5/12': 'calc(5/12 * 100%)',
  '6/12': 'calc(6/12 * 100%)',
  '7/12': 'calc(7/12 * 100%)',
  '8/12': 'calc(8/12 * 100%)',
  '9/12': 'calc(9/12 * 100%)',
  '10/12': 'calc(10/12 * 100%)',
  '11/12': 'calc(11/12 * 100%)',
  full: 100%,
  '1/2-screen': 'calc(1/2 * 100vw)',
  '1/3-screen': 'calc(1/3 * 100vw)',
  '2/3-screen': 'calc(2/3 * 100vw)',
  '1/4-screen': 'calc(1/4 * 100vw)',
  '2/4-screen': 'calc(2/4 * 100vw)',
  '3/4-screen': 'calc(3/4 * 100vw)',
  '1/5-screen': 'calc(1/5 * 100vw)',
  '2/5-screen': 'calc(2/5 * 100vw)',
  '3/5-screen': 'calc(3/5 * 100vw)',
  '4/5-screen': 'calc(4/5 * 100vw)',
  '1/6-screen': 'calc(1/6 * 100vw)',
  '2/6-screen': 'calc(2/6 * 100vw)',
  '3/6-screen': 'calc(3/6 * 100vw)',
  '4/6-screen': 'calc(4/6 * 100vw)',
  '5/6-screen': 'calc(5/6 * 100vw)',
  '1/12-screen': 'calc(1/12 * 100vw)',
  '2/12-screen': 'calc(2/12 * 100vw)',
  '3/12-screen': 'calc(3/12 * 100vw)',
  '4/12-screen': 'calc(4/12 * 100vw)',
  '5/12-screen': 'calc(5/12 * 100vw)',
  '6/12-screen': 'calc(6/12 * 100vw)',
  '7/12-screen': 'calc(7/12 * 100vw)',
  '8/12-screen': 'calc(8/12 * 100vw)',
  '9/12-screen': 'calc(9/12 * 100vw)',
  '10/12-screen': 'calc(10/12 * 100vw)',
  '11/12-screen': 'calc(11/12 * 100vw)',
  screen: '100vw',
}
```

Anyone else dig this approach? I have it working locally; it's not a breaking change as long as Tailwind's default config is left untouched.

**Comment by adamwathan** [comment]
Don't really want to add this at the moment, but it's something you could easily extract into a function you reuse in your own projects that you just import into the top of your config 👍🏻

**Comment by brunetton** [comment]
+1 for this !

@AlexVipond do you plan to make a plugin for this ? I'm super interested !

Thanks

**Comment by AlexVipond** [comment]
@brunetton Yep I made it! Adam's original suggestion ended up being the best option—a function imported into the config file made more sense than a plugin of some kind.

Note that Tailwind JIT has mostly made the function obsolete. Instead of configuring fraction classes that you'll very rarely use, it's probably best to use the JIT bracket syntax:

```css
/* JIT class for 6/7 max width */
.max-w-[calc(6/7*100%)]
```

The important thing is to make sure your `calc()` expression doesn't contain any spaces, so that CSS can recognize it as a single discrete class.

If you prefer to configure this kind of stuff though, here's what I built:

https://baleada.dev/docs/theme-utils/functions/fractions

```js
// tailwind.config.js
const { fractions } = require('@baleada/tailwind-theme-utils')

module.exports = {
  theme: {
    height: {
      ...fractions({ unit: 'vh', mode: 'baleada' })
    }
  }
}

// This config would produce classes like:
// .h-1/2
// .h-3/2
// .h-screen-1/2
// .h-screen-3/2
// etc.
```

**Comment by brunetton** [comment]
> @brunetton Yep I made it! Adam's original suggestion ended up being the best option—a function imported into the config file made more sense than a plugin of some kind.
> 
> Note that Tailwind JIT has mostly made the function obsolete. Instead of configuring fraction classes that you'll very rarely use, it's probably best to use the JIT bracket syntax:
> 
> ```css
> /* JIT class for 6/7 max width */
> .max-w-[calc(6/7*100%)]
> ```
> 
> The important thing is to make sure your `calc()` expression doesn't contain any spaces, so that CSS can recognize it as a single discrete class.
> 
> If you prefer to configure this kind of stuff though, here's what I built:
> 
> https://baleada.dev/docs/theme-utils/functions/fractions
> 
> ```js
> // tailwind.config.js
> const { fractions } = require('@baleada/tailwind-theme-utils')
> 
> module.exports = {
>   theme: {
>     height: {
>       ...fractions({ unit: 'vh', mode: 'baleada' })
>     }
>   }
> }
> 
> // This config would produce classes like:
> // .h-1/2
> // .h-3/2
> // .h-screen-1/2
> // .h-screen-3/2
> // etc.
> ```

Thank you a lot ! This is absolutely perfect :)
