### ISSUE TITLE
Tailwindcss messes with Trix

### ISSUE THREAD

**Issue by rgaufman** [tailwindcss/tailwindcss#989]
Hi there,

I'm using https://github.com/basecamp/trix version 1.1.1 and Tailwindcss version 1.0.4. When I try to add the WYSIWYG editor like this:

```html
    <div class="flex flex-wrap">
      <div class="w-full">
        <form>
          <input id="x" value="Editor content goes here" type="hidden" name="content">
          <trix-editor input="x"></trix-editor>
        </form>
      </div>
    </div>
```

It works, but the ordered and unordered lists do not indent or render correctly. How do I prevent tailwindcss from clashing with the expected default styles for lists?

**Comment by rellect** [comment]
This is because tailwind resets some default styles. You can remove '@tailwind base;' from your css and use your own reset.

**Comment by AlexVipond** [comment]
Also, you can keep tailwind's base reset and just override specific pieces of it further down in the cascade.

Or add some css specifically for the editor, e.g. add a `trix-editor` class on a parent element and manually style `.trix-editor ul`, `.trix-editor li`, etc. 

Main thing to remember is that this is all just css at the end of the day—the standard specificity and cascade rules still apply.

**Comment by adamwathan** [comment]
You can disable our preflight styles if they are conflicting with something else you're using:

https://tailwindcss.com/docs/preflight/#disabling-preflight

If you'd like to keep using them, you could create a custom class that tries to undo whatever styles are causing the conflict and wrap the Trix editor with that class, something sort of like this (not test, just the general idea):

```css
.trix ul {
  list-style-type: disc;
  padding-left: 2.5rem;
}

.trix ol {
  list-style-type: decimal;
  padding-left: 2.5rem;
}
```

**Comment by RabeeaAli** [comment]
Just come from the future :) to make the editor works with the default style. 
First, you  have to give the `trix-editor` a class like so:

```
<trix-editor class="trix-editor" input="x"></trix-editor>
```

Then paste these CSS lines in your CSS file

```
.trix-editor {
    @apply w-full;
}

.trix-editor h1 {
    font-size: 1.25rem !important;
    line-height: 1.25rem !important;
    @apply leading-5 font-semibold mb-4;
}

.trix-editor a:not(.no-underline) {
    @apply underline;
}

.trix-editor a:visited {
    color: green;
} 

.trix-editor ul {
    list-style-type: disc;
    padding-left: 1rem;
}

.trix-editor ol {
    list-style-type: decimal;
    padding-left: 1rem;
}

.trix-editor pre {
    display: inline-block;
    width: 100%;
    vertical-align: top;
    font-family: monospace;
    font-size: 1.5em;
    padding: 0.5em;
    white-space: pre;
    background-color: #eee;
    overflow-x: auto;
}

.trix-editor blockquote {
    border: 0 solid #ccc;
    border-left-width: 0px;
    border-left-width: 0.3em;
    margin-left: 0.3em;
    padding-left: 0.6em;
}
```

**Comment by buncis** [comment]
even better since trix have its own custom component
```
<trix-editor></trix-editor>
```
you could just do 
```
@layer base {
  trix-editor {
    @apply w-full;
  }
  
  trix-editor h1 {
    font-size: 1.25rem !important;
    line-height: 1.25rem !important;
    @apply leading-5 font-semibold mb-4;
  }
  
  trix-editor a:not(.no-underline) {
    @apply underline;
  }
  
  trix-editor a:visited {
    color: green;
  } 
  
  trix-editor ul {
    list-style-type: disc;
    padding-left: 1rem;
  }
  
  trix-editor ol {
    list-style-type: decimal;
    padding-left: 1rem;
  }
  
  trix-editor pre {
    display: inline-block;
    width: 100%;
    vertical-align: top;
    font-family: monospace;
    font-size: 1.5em;
    padding: 0.5em;
    white-space: pre;
    background-color: #eee;
    overflow-x: auto;
  }
  
  trix-editor blockquote {
    border: 0 solid #ccc;
    border-left-width: 0px;
    border-left-width: 0.3em;
    margin-left: 0.3em;
    padding-left: 0.6em;
  }
}
```

**Comment by krisnaw** [comment]
If anyone is still experiencing this problem, I managed to resolve it by utilizing Tailwind's prose feature.

`prose lg:prose-sm prose-a:text-blue-600`
