### ISSUE TITLE
@apply !important doesn't work

### ISSUE THREAD

**Issue by KKSzymanowski** [tailwindcss/tailwindcss#993]
From the docs:

>If you'd like to `@apply` an existing class and make it !important, simply add !important to the end of the declaration:
> ```css
> .btn {
>   @apply font-bold py-2 px-4 rounded !important;
> }
> ```

My code:
```css
.swal2-modal {
  @apply rounded-xl !important;
}
```

An error occurs during the SCSS compilation
```
ERROR in ./src/scss/app.scss ([..]/src/scss/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  @apply rounded-xl !important;
        ^
      Invalid CSS after "...pply rounded-xl": expected "}", was "!important;"
      in [..]/src/scss/_swal.scss (line 10, column 10)
 @ ./src/scss/app.scss 2:14-198
```

I suppose this has something to do with using SCSS instead of PostCSS. How can I apply the `!important` modifier to the `@apply` directive in SCSS?

**Comment by adamwathan** [comment]
https://tailwindcss.com/docs/using-with-preprocessors#sass

**Comment by KKSzymanowski** [comment]
Thanks a lot, I looked in the wrong place.

If you want I can make a PR to add a note about this caveat to the `@apply` docs.

**Comment by adamwathan** [comment]
Yeah that's a good idea 👍 Thanks!

**Comment by KKSzymanowski** [comment]
PR created
